-- =================================================================
-- Unlocked seed v3 — AMIGOS (200 entries)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- Requiere migración _012 (categoría 'amigos' en el enum)
-- =================================================================

insert into achievements (slug, title, emoji, category, status) values
  ('cancele-un-plan-inventando-que-estaba-malo', 'Cancelé un plan inventando que estaba malo', '🤥', 'amigos', 'approved'),
  ('mantengo-silenciado-el-grupo-de-whatsapp-de-mis-amigos-del-c', 'Mantengo silenciado el grupo de WhatsApp de mis amigos del cole', '🔕', 'amigos', 'approved'),
  ('lei-el-mensaje-pense-que-responder-y-no-respondi-nunca', 'Leí el mensaje, pensé qué responder y no respondí nunca', '👀', 'amigos', 'approved'),
  ('dije-manana-fijo-sabiendo-que-no-iba-a-ir', 'Dije "mañana fijo" sabiendo que no iba a ir', '📅', 'amigos', 'approved'),
  ('cancele-un-plan-a-20-minutos-de-salir-de-casa', 'Cancelé un plan a 20 minutos de salir de casa', '🏃', 'amigos', 'approved'),
  ('mande-un-bizum-cuatro-meses-despues-de-la-cena', 'Mandé un Bizum cuatro meses después de la cena', '💸', 'amigos', 'approved'),
  ('le-preste-dinero-a-un-amigo-y-nunca-me-lo-devolvio', 'Le presté dinero a un amigo y nunca me lo devolvió', '💰', 'amigos', 'approved'),
  ('copie-y-pegue-el-mismo-felicidades-a-cinco-personas-en-un-di', 'Copié y pegué el mismo "felicidades" a cinco personas en un día', '🎂', 'amigos', 'approved'),
  ('felicite-un-cumple-tres-dias-tarde-y-disimule', 'Felicité un cumple tres días tarde y disimulé', '🎈', 'amigos', 'approved'),
  ('olvide-el-cumpleanos-de-mi-mejor-amigo', 'Olvidé el cumpleaños de mi mejor amigo', '😬', 'amigos', 'approved'),
  ('compre-el-regalo-de-boda-de-camino-a-la-boda', 'Compré el regalo de boda de camino a la boda', '🎁', 'amigos', 'approved'),
  ('llore-borracho-en-una-boda-diciendole-a-mi-amigo-que-le-quie', 'Lloré borracho en una boda diciéndole a mi amigo que le quiero', '🥲', 'amigos', 'approved'),
  ('invente-una-excusa-elaboradisima-para-no-ir-a-una-boda', 'Inventé una excusa elaboradísima para no ir a una boda', '💍', 'amigos', 'approved'),
  ('deje-de-seguir-en-instagram-a-mis-amigos-del-colegio-uno-a-u', 'Dejé de seguir en Instagram a mis amigos del colegio uno a uno', '📵', 'amigos', 'approved'),
  ('silencie-las-stories-de-mis-amigos-pero-sigo-vigilandolas', 'Silencié las stories de mis amigos pero sigo vigilándolas', '👁️', 'amigos', 'approved'),
  ('vi-por-stories-un-plan-al-que-no-me-invitaron', 'Vi por stories un plan al que no me invitaron', '📸', 'amigos', 'approved'),
  ('fingi-no-haber-visto-el-mensaje-cuando-me-pregunto-si-queria', 'Fingí no haber visto el mensaje cuando me preguntó si quería quedar', '🙈', 'amigos', 'approved'),
  ('mande-un-audio-de-cuatro-minutos-al-grupo-y-nadie-lo-escucho', 'Mandé un audio de cuatro minutos al grupo y nadie lo escuchó', '🎙️', 'amigos', 'approved'),
  ('en-mi-grupo-solo-hablamos-a-base-de-memes-desde-2022', 'En mi grupo solo hablamos a base de memes desde 2022', '🐸', 'amigos', 'approved'),
  ('mi-grupo-principal-lleva-tres-meses-sin-un-solo-mensaje', 'Mi grupo principal lleva tres meses sin un solo mensaje', '💀', 'amigos', 'approved'),
  ('ignore-una-llamada-de-un-amigo-aposta-y-le-mande-ahora-no-pu', 'Ignoré una llamada de un amigo aposta y le mandé "ahora no puedo, llamo luego"', '📵', 'amigos', 'approved'),
  ('llego-tarde-a-todos-los-planes-y-todos-lo-saben', 'Llego tarde a todos los planes y todos lo saben', '⏰', 'amigos', 'approved'),
  ('le-dije-a-mi-amigo-que-era-una-hora-antes-para-que-llegase-a', 'Le dije a mi amigo que era una hora antes para que llegase a tiempo', '🕒', 'amigos', 'approved'),
  ('espere-una-hora-solo-en-un-bar-a-un-amigo-que-no-daba-senale', 'Esperé una hora solo en un bar a un amigo que no daba señales', '🍺', 'amigos', 'approved'),
  ('conte-borracho-un-secreto-que-me-habian-pedido-que-no-contar', 'Conté borracho un secreto que me habían pedido que no contara', '🤐', 'amigos', 'approved'),
  ('filtre-un-cotilleo-que-iba-a-cambiarle-la-vida-a-alguien', 'Filtré un cotilleo que iba a cambiarle la vida a alguien', '🗣️', 'amigos', 'approved'),
  ('estuvimos-seis-meses-sin-hablar-por-una-chorrada', 'Estuvimos seis meses sin hablar por una chorrada', '🥶', 'amigos', 'approved'),
  ('perdone-a-una-amiga-simplemente-porque-me-daba-pereza-seguir', 'Perdoné a una amiga simplemente porque me daba pereza seguir enfadado', '🤷', 'amigos', 'approved'),
  ('fingi-reconciliarme-con-un-amigo-y-nunca-volvi-a-quedar-con', 'Fingí reconciliarme con un amigo y nunca volví a quedar con él', '🕊️', 'amigos', 'approved'),
  ('soy-el-tercero-en-mi-grupo-de-tres-y-me-he-dado-cuenta-este', 'Soy el tercero en mi grupo de tres y me he dado cuenta este año', '🥉', 'amigos', 'approved'),
  ('un-amigo-me-reemplazo-por-un-amigo-nuevo-y-aun-no-lo-he-supe', 'Un amigo me reemplazó por un amigo nuevo y aún no lo he superado', '😔', 'amigos', 'approved'),
  ('senti-celos-cuando-mi-mejor-amiga-empezo-a-quedar-con-otra', 'Sentí celos cuando mi mejor amiga empezó a quedar con otra', '👯', 'amigos', 'approved'),
  ('le-caigo-fatal-a-la-pareja-de-mi-mejor-amigo-y-lo-se', 'Le caigo fatal a la pareja de mi mejor amigo y lo sé', '🙅', 'amigos', 'approved'),
  ('le-caen-mal-mis-amigos-a-mi-pareja-y-mis-amigos-lo-notan', 'Le caen mal mis amigos a mi pareja y mis amigos lo notan', '😬', 'amigos', 'approved'),
  ('falte-a-la-cena-de-mis-amigos-por-la-cena-de-los-amigos-de-m', 'Falté a la cena de mis amigos por la cena de los amigos de mi pareja', '🍽️', 'amigos', 'approved'),
  ('tengo-un-amigo-que-cuenta-la-misma-anecdota-cada-vez-que-sal', 'Tengo un amigo que cuenta la misma anécdota cada vez que salimos', '🔁', 'amigos', 'approved'),
  ('me-he-dado-cuenta-de-que-el-plomo-del-grupo-soy-yo', 'Me he dado cuenta de que el plomo del grupo soy yo', '😶', 'amigos', 'approved'),
  ('soy-el-que-se-queja-siempre-del-bar-elegido', 'Soy el que se queja siempre del bar elegido', '😤', 'amigos', 'approved'),
  ('solte-un-analisis-futbolistico-delante-de-gente-que-no-me-ha', 'Solté un análisis futbolístico delante de gente que no me había preguntado', '⚽', 'amigos', 'approved'),
  ('empece-una-frase-con-yo-es-que-soy-de-los-que-en-una-cena', 'Empecé una frase con "yo es que soy de los que" en una cena', '🙄', 'amigos', 'approved'),
  ('monte-una-discusion-politica-en-una-cena-y-todos-se-incomoda', 'Monté una discusión política en una cena y todos se incomodaron', '🗳️', 'amigos', 'approved'),
  ('me-pegue-a-un-plan-al-que-tecnicamente-no-me-habian-invitado', 'Me pegué a un plan al que técnicamente no me habían invitado', '🚪', 'amigos', 'approved'),
  ('apareci-en-una-cena-de-cinco-personas-siendo-el-sexto-sin-av', 'Aparecí en una cena de cinco personas siendo el sexto sin avisar', '🍝', 'amigos', 'approved'),
  ('dormi-en-una-habitacion-de-hotel-sin-pagarla-en-un-viaje-con', 'Dormí en una habitación de hotel sin pagarla en un viaje con amigos', '🛏️', 'amigos', 'approved'),
  ('vacaciones-con-amigos-arruinadas-por-discutir-quien-paga-que', 'Vacaciones con amigos arruinadas por discutir quién paga qué', '🧾', 'amigos', 'approved'),
  ('dormi-cuatro-personas-en-una-cama-doble-en-un-viaje', 'Dormí cuatro personas en una cama doble en un viaje', '🛌', 'amigos', 'approved'),
  ('me-pelee-con-un-amigo-por-la-temperatura-del-aire-acondicion', 'Me peleé con un amigo por la temperatura del aire acondicionado', '🌡️', 'amigos', 'approved'),
  ('me-mude-de-ciudad-y-mi-grupo-de-amigos-dejo-de-existir', 'Me mudé de ciudad y mi grupo de amigos dejó de existir', '📦', 'amigos', 'approved'),
  ('veo-las-stories-de-mi-mejor-amiga-y-eso-es-toda-nuestra-rela', 'Veo las stories de mi mejor amiga y eso es toda nuestra relación ya', '📲', 'amigos', 'approved'),
  ('quedamos-en-llamarnos-cada-semana-y-llevamos-un-ano-sin-habl', 'Quedamos en llamarnos cada semana y llevamos un año sin hablar', '📞', 'amigos', 'approved'),
  ('me-encontre-con-un-excompanero-en-un-bar-y-fingimos-no-verno', 'Me encontré con un excompañero en un bar y fingimos no vernos', '🍻', 'amigos', 'approved'),
  ('me-cruce-con-una-amiga-del-cole-y-nos-hicimos-las-locas', 'Me crucé con una amiga del cole y nos hicimos las locas', '🚶', 'amigos', 'approved'),
  ('cumpli-30-anos-sin-un-grupo-claro-de-amigos', 'Cumplí 30 años sin un grupo claro de amigos', '🕯️', 'amigos', 'approved'),
  ('las-fiestas-del-pueblo-son-el-unico-momento-del-ano-que-teng', 'Las fiestas del pueblo son el único momento del año que tengo grupo', '🎉', 'amigos', 'approved'),
  ('doy-likes-selectivos-a-las-publicaciones-de-mis-amigos-segun', 'Doy likes selectivos a las publicaciones de mis amigos según mi humor', '❤️', 'amigos', 'approved'),
  ('comento-guapooo-en-todas-las-fotos-de-un-amigo-y-en-las-de-o', 'Comento "guapooo" en todas las fotos de un amigo y en las de otro nunca', '💬', 'amigos', 'approved'),
  ('cambie-de-trabajo-y-nunca-mas-volvi-a-hablar-con-mis-amigos', 'Cambié de trabajo y nunca más volví a hablar con mis "amigos" del curro', '👋', 'amigos', 'approved'),
  ('soy-amiga-de-mi-companero-solo-dentro-de-la-oficina', 'Soy amiga de mi compañero solo dentro de la oficina', '💼', 'amigos', 'approved'),
  ('una-amistad-paso-a-ser-solo-seguirnos-en-redes', 'Una amistad pasó a ser solo seguirnos en redes', '📱', 'amigos', 'approved'),
  ('mi-grupo-del-instituto-se-disolvio-oficialmente-y-nadie-lo-d', 'Mi grupo del instituto se disolvió oficialmente y nadie lo dijo', '⚰️', 'amigos', 'approved'),
  ('cena-de-reencuentro-con-amigos-del-cole-rara-y-forzada', 'Cena de reencuentro con amigos del cole rara y forzada', '🍷', 'amigos', 'approved'),
  ('mis-amigos-del-cole-hablan-de-una-vida-que-ya-no-es-la-mia', 'Mis amigos del cole hablan de una vida que ya no es la mía', '🏫', 'amigos', 'approved'),
  ('monte-un-negocio-con-un-amigo-y-perdimos-los-dos-cosas', 'Monté un negocio con un amigo y perdimos los dos cosas', '📉', 'amigos', 'approved'),
  ('le-preste-500-euros-a-un-amigo-y-perdi-amigo-y-dinero', 'Le presté 500 euros a un amigo y perdí amigo y dinero', '💔', 'amigos', 'approved'),
  ('soy-siempre-el-que-adelanta-el-dinero-en-las-cenas', 'Soy siempre el que adelanta el dinero en las cenas', '🤑', 'amigos', 'approved'),
  ('un-amigo-me-pidio-bizum-por-3-euros-de-unas-cervezas', 'Un amigo me pidió Bizum por 3 euros de unas cervezas', '🍺', 'amigos', 'approved'),
  ('soy-oficialmente-el-tacano-del-grupo-y-lo-asumo', 'Soy oficialmente el tacaño del grupo y lo asumo', '🪙', 'amigos', 'approved'),
  ('no-me-invitaron-a-un-plan-y-senti-mas-alivio-que-pena', 'No me invitaron a un plan y sentí más alivio que pena', '😌', 'amigos', 'approved'),
  ('vi-fotos-en-instagram-del-plan-al-que-dije-que-no-podia-ir', 'Vi fotos en Instagram del plan al que dije que no podía ir', '📷', 'amigos', 'approved'),
  ('dije-que-estaba-malo-y-me-quede-toda-la-tarde-en-la-cama-vie', 'Dije que estaba malo y me quedé toda la tarde en la cama viendo series', '🛋️', 'amigos', 'approved'),
  ('invente-una-reunion-de-trabajo-para-no-ir-a-una-cena', 'Inventé una reunión de trabajo para no ir a una cena', '📊', 'amigos', 'approved'),
  ('menti-diciendo-que-tenia-cena-con-la-familia-politica', 'Mentí diciendo que tenía cena con la familia política', '👵', 'amigos', 'approved'),
  ('cancele-con-unos-amigos-para-quedar-con-otros-mas-interesant', 'Cancelé con unos amigos para quedar con otros más interesantes', '🔄', 'amigos', 'approved'),
  ('dije-que-estaba-malo-y-luego-subi-stories-en-una-terraza', 'Dije que estaba malo y luego subí stories en una terraza', '🤧', 'amigos', 'approved'),
  ('ignore-la-invitacion-de-cumple-y-deje-el-evento-en-visto', 'Ignoré la invitación de cumple y dejé el evento en visto', '🎂', 'amigos', 'approved'),
  ('llegue-tarde-con-una-excusa-que-ni-yo-me-creia', 'Llegué tarde con una excusa que ni yo me creía', '🚇', 'amigos', 'approved'),
  ('vi-la-llamada-de-mi-amiga-un-domingo-y-no-devolvi', 'Vi la llamada de mi amiga un domingo y no devolví', '📞', 'amigos', 'approved'),
  ('quede-solo-para-que-mi-amiga-dejara-de-insistir', 'Quedé solo para que mi amiga dejara de insistir', '😶‍🌫️', 'amigos', 'approved'),
  ('llevo-seis-meses-sin-quedar-con-mi-mejor-amiga-y-aun-la-llam', 'Llevo seis meses sin quedar con mi mejor amiga y aún la llamo así', '⌛', 'amigos', 'approved'),
  ('llevamos-un-ano-diciendonos-tenemos-que-quedar-a-tomar-algo', 'Llevamos un año diciéndonos "tenemos que quedar a tomar algo"', '☕', 'amigos', 'approved'),
  ('soy-siempre-yo-el-que-propone-planes-y-un-dia-deje-de-hacerl', 'Soy siempre yo el que propone planes y un día dejé de hacerlo a ver qué pasaba', '🤐', 'amigos', 'approved'),
  ('deje-de-proponer-planes-y-descubri-que-nadie-proponia', 'Dejé de proponer planes y descubrí que nadie proponía', '🦗', 'amigos', 'approved'),
  ('bloquee-las-stories-a-una-amiga-sin-que-ella-lo-supiera', 'Bloqueé las stories a una amiga sin que ella lo supiera', '🚫', 'amigos', 'approved'),
  ('elimine-fotos-con-un-grupo-de-amigos-del-que-ya-no-formo-par', 'Eliminé fotos con un grupo de amigos del que ya no formo parte', '🗑️', 'amigos', 'approved'),
  ('perdi-una-amistad-cuando-me-eche-pareja', 'Perdí una amistad cuando me eché pareja', '💑', 'amigos', 'approved'),
  ('mi-pareja-me-ha-aislado-de-mis-amigos-y-solo-me-doy-cuenta-a', 'Mi pareja me ha aislado de mis amigos y solo me doy cuenta ahora', '🔒', 'amigos', 'approved'),
  ('soy-el-unico-soltero-del-grupo-y-odio-cuando-hablan-de-hipot', 'Soy el único soltero del grupo y odio cuando hablan de hipotecas', '🙄', 'amigos', 'approved'),
  ('un-amigo-fue-padre-y-deje-de-entender-de-que-hablaba', 'Un amigo fue padre y dejé de entender de qué hablaba', '👶', 'amigos', 'approved'),
  ('aguante-una-cena-entera-oyendo-hablar-de-hipotecas-y-guarder', 'Aguanté una cena entera oyendo hablar de hipotecas y guarderías', '🥱', 'amigos', 'approved'),
  ('mis-nuevos-amigos-son-los-amigos-de-mi-pareja', 'Mis nuevos amigos son los amigos de mi pareja', '🤝', 'amigos', 'approved'),
  ('tengo-mas-relacion-con-los-amigos-de-mi-pareja-que-con-los-m', 'Tengo más relación con los amigos de mi pareja que con los míos', '👥', 'amigos', 'approved'),
  ('confirme-asistencia-y-al-final-no-apareci-sin-avisar', 'Confirmé asistencia y al final no aparecí sin avisar', '👻', 'amigos', 'approved'),
  ('no-fui-al-cumple-no-felicite-no-di-senales', 'No fui al cumple, no felicité, no di señales', '🪦', 'amigos', 'approved'),
  ('me-invitaron-a-un-bautizo-y-no-sabia-que-hacer-ahi', 'Me invitaron a un bautizo y no sabía qué hacer ahí', '⛪', 'amigos', 'approved'),
  ('no-fui-al-funeral-del-padre-de-un-amigo-y-aun-me-arrepiento', 'No fui al funeral del padre de un amigo y aún me arrepiento', '🕯️', 'amigos', 'approved'),
  ('no-supe-que-decirle-a-un-amigo-cuando-perdio-a-alguien', 'No supe qué decirle a un amigo cuando perdió a alguien', '🥀', 'amigos', 'approved'),
  ('le-puse-mucho-animo-en-facebook-y-me-senti-fatal', 'Le puse "mucho ánimo" en Facebook y me sentí fatal', '🙏', 'amigos', 'approved'),
  ('mantengo-la-amistad-solo-a-base-de-likes', 'Mantengo la amistad solo a base de likes', '👍', 'amigos', 'approved'),
  ('stalkee-el-tfg-de-un-excompanero-solo-por-curiosidad-morbosa', 'Stalkeé el TFG de un excompañero solo por curiosidad morbosa', '🎓', 'amigos', 'approved'),
  ('stalkeo-cada-nueva-pareja-de-mi-mejor-amiga-durante-una-hora', 'Stalkeo cada nueva pareja de mi mejor amiga durante una hora', '🔍', 'amigos', 'approved'),
  ('hago-las-stories-solo-para-ver-quien-esta-con-quien', 'Hago las stories solo para ver quién está con quién', '👀', 'amigos', 'approved'),
  ('tengo-un-grupo-paralelo-donde-criticamos-al-grupo-principal', 'Tengo un grupo paralelo donde criticamos al grupo principal', '🤫', 'amigos', 'approved'),
  ('estoy-en-un-grupo-de-whatsapp-donde-criticamos-a-una-persona', 'Estoy en un grupo de WhatsApp donde criticamos a una persona del grupo grande', '😈', 'amigos', 'approved'),
  ('saque-a-colacion-un-tema-en-una-cena-para-criticar-a-alguien', 'Saqué a colación un tema en una cena para criticar a alguien que no estaba', '🗯️', 'amigos', 'approved'),
  ('hice-de-mediadora-entre-dos-amigas-que-se-odiaban-y-acabe-pe', 'Hice de mediadora entre dos amigas que se odiaban y acabé peor', '⚔️', 'amigos', 'approved'),
  ('tuve-que-tomar-partido-en-una-pelea-de-amigos-y-elegi-mal', 'Tuve que tomar partido en una pelea de amigos y elegí mal', '🤺', 'amigos', 'approved'),
  ('no-defendi-a-un-amigo-cuando-hablaban-mal-de-el-en-una-cena', 'No defendí a un amigo cuando hablaban mal de él en una cena', '🫥', 'amigos', 'approved'),
  ('rei-una-broma-de-un-amigo-aunque-me-parecio-hiriente', 'Reí una broma de un amigo aunque me pareció hiriente', '😅', 'amigos', 'approved'),
  ('hice-una-broma-que-dolio-a-un-amigo-y-segui-como-si-nada', 'Hice una broma que dolió a un amigo y seguí como si nada', '🙊', 'amigos', 'approved'),
  ('me-pidio-perdon-y-dije-tranqui-no-pasa-nada-pero-si-pasaba', 'Me pidió perdón y dije "tranqui no pasa nada" pero sí pasaba', '😐', 'amigos', 'approved'),
  ('llevo-anos-aguantando-rencor-a-una-amiga-sin-que-lo-sepa', 'Llevo años aguantando rencor a una amiga sin que lo sepa', '🪨', 'amigos', 'approved'),
  ('corte-una-amistad-de-10-anos-con-un-mensaje-de-whatsapp', 'Corté una amistad de 10 años con un mensaje de WhatsApp', '✂️', 'amigos', 'approved'),
  ('acabe-una-amistad-por-desgaste-sin-decir-nada', 'Acabé una amistad por desgaste sin decir nada', '🌫️', 'amigos', 'approved'),
  ('mi-mejor-amigo-del-instituto-es-ahora-literalmente-un-descon', 'Mi mejor amigo del instituto es ahora literalmente un desconocido', '🥲', 'amigos', 'approved'),
  ('vi-una-foto-vieja-con-mi-exmejor-amiga-y-llore', 'Vi una foto vieja con mi exmejor amiga y lloré', '📸', 'amigos', 'approved'),
  ('borre-el-numero-de-un-amigo-en-un-arrebato', 'Borré el número de un amigo en un arrebato', '📵', 'amigos', 'approved'),
  ('bloquee-y-desbloquee-a-un-amigo-en-menos-de-una-hora', 'Bloqueé y desbloqueé a un amigo en menos de una hora', '🔁', 'amigos', 'approved'),
  ('stalkeo-a-un-amigo-con-el-que-ya-no-hablo-cada-dos-por-tres', 'Stalkeo a un amigo con el que ya no hablo cada dos por tres', '🕵️', 'amigos', 'approved'),
  ('tengo-una-cuenta-secundaria-solo-para-ver-perfiles-de-excomp', 'Tengo una cuenta secundaria solo para ver perfiles de excompañeros', '🤳', 'amigos', 'approved'),
  ('vi-una-peli-sobre-amigos-y-me-deprimi-pensando-en-los-mios', 'Vi una peli sobre amigos y me deprimí pensando en los míos', '🎬', 'amigos', 'approved'),
  ('llegue-a-los-30-con-muchas-amistades-superficiales-y-pocas-r', 'Llegué a los 30 con muchas amistades superficiales y pocas reales', '🫤', 'amigos', 'approved'),
  ('pase-un-fin-de-semana-entero-sin-hablar-con-nadie-y-nadie-lo', 'Pasé un fin de semana entero sin hablar con nadie y nadie lo notó', '🛏️', 'amigos', 'approved'),
  ('quedaron-y-se-entere-por-casualidad-por-una-historia', 'Quedaron y se enteré por casualidad por una historia', '🥺', 'amigos', 'approved'),
  ('hicieron-un-grupo-mas-pequeno-dentro-del-grupo-y-no-me-invit', 'Hicieron un grupo más pequeño dentro del grupo y no me invitaron', '🚷', 'amigos', 'approved'),
  ('mi-cumpleanos-fueron-tres-personas-y-me-hice-el-feliz', 'Mi cumpleaños fueron tres personas y me hice el feliz', '🎈', 'amigos', 'approved'),
  ('tuve-que-organizar-mi-propio-cumpleanos-porque-nadie-iba-a-h', 'Tuve que organizar mi propio cumpleaños porque nadie iba a hacerlo', '🎂', 'amigos', 'approved'),
  ('prepare-un-discurso-para-una-cena-de-amigos-y-lo-solte-con-v', 'Preparé un discurso para una cena de amigos y lo solté con vergüenza', '🎤', 'amigos', 'approved'),
  ('me-puse-pesadisimo-en-un-bar-diciendo-a-mis-amigos-cuanto-le', 'Me puse pesadísimo en un bar diciendo a mis amigos cuánto les quería', '🍻', 'amigos', 'approved'),
  ('llore-en-un-bar-con-un-amigo-y-a-la-manana-siguiente-ninguno', 'Lloré en un bar con un amigo y a la mañana siguiente ninguno lo mencionó', '🍷', 'amigos', 'approved'),
  ('le-conte-algo-intimo-a-un-amigo-borracho-y-al-dia-siguiente', 'Le conté algo íntimo a un amigo borracho y al día siguiente quería desaparecer', '😵', 'amigos', 'approved'),
  ('cante-cumpleanos-feliz-a-una-amiga-por-nota-de-voz-desafinan', 'Canté Cumpleaños Feliz a una amiga por nota de voz desafinando', '🎶', 'amigos', 'approved'),
  ('mande-feliz-cumple-sin-emojis-a-una-persona-muy-importante', 'Mandé "feliz cumple :)" sin emojis a una persona muy importante', '🥲', 'amigos', 'approved'),
  ('solo-me-felicitaron-por-el-grupo-de-la-familia-y-no-por-el-d', 'Solo me felicitaron por el grupo de la familia y no por el de los amigos', '😶', 'amigos', 'approved'),
  ('le-pedi-perdon-a-una-amiga-seis-anos-despues-por-algo-que-el', 'Le pedí perdón a una amiga seis años después por algo que ella ya había olvidado', '🕰️', 'amigos', 'approved'),
  ('no-fui-a-la-despedida-de-soltera-y-le-envie-regalo-de-amazon', 'No fui a la despedida de soltera y le envié regalo de Amazon', '👰', 'amigos', 'approved'),
  ('llore-en-la-despedida-del-piso-de-mis-amigas-como-si-no-nos', 'Lloré en la despedida del piso de mis amigas como si no nos fuéramos a ver', '📦', 'amigos', 'approved'),
  ('prometi-ayudar-en-una-mudanza-y-nunca-apareci', 'Prometí ayudar en una mudanza y nunca aparecí', '📦', 'amigos', 'approved'),
  ('dije-que-ayudaba-con-la-mudanza-y-le-di-excusa-esa-misma-man', 'Dije que ayudaba con la mudanza y le di excusa esa misma mañana', '🚚', 'amigos', 'approved'),
  ('mi-mejor-amigo-se-mudo-hace-dos-anos-y-aun-no-he-ido-a-su-ca', 'Mi mejor amigo se mudó hace dos años y aún no he ido a su casa', '🏠', 'amigos', 'approved'),
  ('mi-amiga-lleva-tres-anos-en-otra-ciudad-y-no-la-he-visitado', 'Mi amiga lleva tres años en otra ciudad y no la he visitado', '✈️', 'amigos', 'approved'),
  ('volvio-de-erasmus-y-nuestra-amistad-ya-no-era-igual', 'Volvió de Erasmus y nuestra amistad ya no era igual', '🌍', 'amigos', 'approved'),
  ('mi-grupo-de-erasmus-es-ya-solo-gente-que-no-vere-nunca-mas', 'Mi grupo de Erasmus es ya solo gente que no veré nunca más', '🪦', 'amigos', 'approved'),
  ('solo-nos-recordamos-por-una-foto-vieja-de-erasmus-en-anivers', 'Solo nos recordamos por una foto vieja de Erasmus en aniversario', '🖼️', 'amigos', 'approved'),
  ('mi-grupo-de-la-uni-se-disolvio-cuando-uno-se-hizo-papa', 'Mi grupo de la uni se disolvió cuando uno se hizo papá', '🍼', 'amigos', 'approved'),
  ('he-cambiado-de-grupo-de-amigos-como-tres-veces-en-mi-vida', 'He cambiado de grupo de amigos como tres veces en mi vida', '🔄', 'amigos', 'approved'),
  ('conozco-a-mucha-gente-y-no-se-si-tengo-un-amigo-de-verdad', 'Conozco a mucha gente y no sé si tengo un amigo de verdad', '🫥', 'amigos', 'approved'),
  ('a-los-30-conoci-a-alguien-con-quien-hice-amistad-de-verdad', 'A los 30 conocí a alguien con quien hice amistad de verdad', '🫶', 'amigos', 'approved'),
  ('hice-una-amiga-en-una-clase-de-yoga-a-los-28', 'Hice una amiga en una clase de yoga a los 28', '🧘', 'amigos', 'approved'),
  ('mi-grupo-mas-fuerte-se-formo-pasados-los-25', 'Mi grupo más fuerte se formó pasados los 25', '🌱', 'amigos', 'approved'),
  ('le-preste-una-camiseta-a-un-amigo-y-nunca-volvio', 'Le presté una camiseta a un amigo y nunca volvió', '👕', 'amigos', 'approved'),
  ('preste-un-libro-y-desde-entonces-se-que-no-lo-voy-a-recupera', 'Presté un libro y desde entonces sé que no lo voy a recuperar', '📚', 'amigos', 'approved'),
  ('le-di-un-taper-a-una-amiga-y-han-pasado-dos-anos', 'Le di un táper a una amiga y han pasado dos años', '🥡', 'amigos', 'approved'),
  ('le-preste-la-ps5-a-un-amigo-seis-meses', 'Le presté la PS5 a un amigo seis meses', '🎮', 'amigos', 'approved'),
  ('dije-una-mas-y-a-casa-y-acabe-a-las-7-con-mi-mejor-amigo', 'Dije "una más y a casa" y acabé a las 7 con mi mejor amigo', '🍻', 'amigos', 'approved'),
  ('perdi-las-llaves-del-piso-volviendo-de-fiesta-con-mis-amigos', 'Perdí las llaves del piso volviendo de fiesta con mis amigos', '🔑', 'amigos', 'approved'),
  ('mi-amigo-me-llevo-a-casa-cargado-de-borracho-y-nunca-lo-agra', 'Mi amigo me llevó a casa cargado de borracho y nunca lo agradecí bien', '🤝', 'amigos', 'approved'),
  ('sostuve-el-pelo-a-una-amiga-vomitando-y-nos-hicimos-intimas', 'Sostuve el pelo a una amiga vomitando y nos hicimos íntimas', '🤢', 'amigos', 'approved'),
  ('hice-mejor-amiga-del-bar-en-el-bano-de-una-discoteca', 'Hice mejor amiga del bar en el baño de una discoteca', '💃', 'amigos', 'approved'),
  ('la-mejor-amiga-del-bar-no-volvi-a-verla-en-mi-vida', 'La mejor amiga del bar no volví a verla en mi vida', '🌙', 'amigos', 'approved'),
  ('pague-el-uber-del-amigo-borracho-y-nunca-me-lo-bizumeo', 'Pagué el Uber del amigo borracho y nunca me lo Bizumeó', '🚖', 'amigos', 'approved'),
  ('atendi-una-llamada-de-un-amigo-a-las-3am-llorando-y-le-ayude', 'Atendí una llamada de un amigo a las 3am llorando y le ayudé', '📱', 'amigos', 'approved'),
  ('vi-una-llamada-perdida-a-las-3am-de-un-amigo-y-no-devolvi', 'Vi una llamada perdida a las 3am de un amigo y no devolví', '😴', 'amigos', 'approved'),
  ('aguante-tres-horas-de-whatsapp-a-una-amiga-rota-tras-una-rup', 'Aguanté tres horas de WhatsApp a una amiga rota tras una ruptura', '💔', 'amigos', 'approved'),
  ('conte-el-mismo-drama-mio-a-tres-amigos-distintos', 'Conté el mismo drama mío a tres amigos distintos', '🎭', 'amigos', 'approved'),
  ('fingi-escuchar-a-una-amiga-mientras-pensaba-en-mis-cosas', 'Fingí escuchar a una amiga mientras pensaba en mis cosas', '🫠', 'amigos', 'approved'),
  ('asenti-mucho-rato-sin-entender-de-que-iba-la-conversacion', 'Asentí mucho rato sin entender de qué iba la conversación', '🙂', 'amigos', 'approved'),
  ('mi-amigo-alarga-las-cenas-hasta-las-2am-cuando-yo-solo-queri', 'Mi amigo alarga las cenas hasta las 2am cuando yo solo quería irme', '🥱', 'amigos', 'approved'),
  ('fingi-una-llamada-para-irme-antes-de-una-cena', 'Fingí una llamada para irme antes de una cena', '📞', 'amigos', 'approved'),
  ('me-fui-a-la-francesa-de-una-fiesta-con-amigos', 'Me fui a la francesa de una fiesta con amigos', '🚪', 'amigos', 'approved'),
  ('una-amiga-me-trato-mal-toda-la-noche-y-no-dije-nada', 'Una amiga me trató mal toda la noche y no dije nada', '😶', 'amigos', 'approved'),
  ('en-el-grupo-siempre-acabo-aceptando-el-plan-que-no-quiero', 'En el grupo siempre acabo aceptando el plan que no quiero', '🦴', 'amigos', 'approved'),
  ('dije-que-todo-estaba-bien-y-luego-me-fui-llorando-al-bano', 'Dije que todo estaba bien y luego me fui llorando al baño', '🚻', 'amigos', 'approved'),
  ('mi-mejor-amistad-se-basa-en-trauma-compartido', 'Mi mejor amistad se basa en trauma compartido', '🩹', 'amigos', 'approved'),
  ('mi-amiga-y-yo-nos-contamos-que-pastilla-tomamos', 'Mi amiga y yo nos contamos qué pastilla tomamos', '💊', 'amigos', 'approved'),
  ('llore-viendo-una-foto-vieja-del-grupo-en-la-galeria', 'Lloré viendo una foto vieja del grupo en la galería', '😢', 'amigos', 'approved'),
  ('busque-fotos-antiguas-para-recordar-que-tenia-amigos', 'Busqué fotos antiguas para recordar que tenía amigos', '🖼️', 'amigos', 'approved'),
  ('relei-conversaciones-viejas-con-un-amigo-con-el-que-ya-no-ha', 'Releí conversaciones viejas con un amigo con el que ya no hablo', '💌', 'amigos', 'approved'),
  ('mi-mejor-ano-fue-uno-con-un-grupo-que-ya-no-existe', 'Mi mejor año fue uno con un grupo que ya no existe', '🌅', 'amigos', 'approved'),
  ('cuando-se-echo-pareja-la-perdi-casi-del-todo', 'Cuando se echó pareja la perdí casi del todo', '💔', 'amigos', 'approved'),
  ('quede-con-una-amiga-despues-de-dos-anos-y-fue-una-peli', 'Quedé con una amiga después de dos años y fue una peli', '🎞️', 'amigos', 'approved'),
  ('soy-el-unico-del-grupo-que-sigue-viviendo-en-el-barrio', 'Soy el único del grupo que sigue viviendo en el barrio', '🏘️', 'amigos', 'approved'),
  ('mi-grupo-se-disolvio-cuando-dejamos-el-piso-compartido', 'Mi grupo se disolvió cuando dejamos el piso compartido', '🏚️', 'amigos', 'approved'),
  ('quise-matar-a-mi-mejor-amiga-viviendo-juntas', 'Quise matar a mi mejor amiga viviendo juntas', '🗡️', 'amigos', 'approved'),
  ('estuve-un-mes-sin-hablar-con-mi-companera-de-piso-por-los-pl', 'Estuve un mes sin hablar con mi compañera de piso por los platos', '🍽️', 'amigos', 'approved'),
  ('deje-un-post-it-pasivo-agresivo-a-mi-amiga-compi-de-piso', 'Dejé un post-it pasivo-agresivo a mi amiga compi de piso', '📝', 'amigos', 'approved'),
  ('en-mi-piso-compartido-los-bizum-eran-un-infierno', 'En mi piso compartido los Bizum eran un infierno', '💸', 'amigos', 'approved'),
  ('dormi-en-el-sofa-de-un-amigo-cuatro-meses', 'Dormí en el sofá de un amigo cuatro meses', '🛋️', 'amigos', 'approved'),
  ('acogi-a-un-amigo-en-mi-casa-cuando-rompio-con-su-pareja', 'Acogí a un amigo en mi casa cuando rompió con su pareja', '🛏️', 'amigos', 'approved'),
  ('tuve-la-llave-de-la-casa-de-tres-amigas-y-la-perdi-en-alguna', 'Tuve la llave de la casa de tres amigas y la perdí en alguna fiesta', '🗝️', 'amigos', 'approved'),
  ('junte-a-dos-amigos-como-pareja-y-luego-rompieron-y-todo-fue', 'Junté a dos amigos como pareja y luego rompieron y todo fue raro', '💞', 'amigos', 'approved'),
  ('tuve-un-rollo-con-un-amigo-del-grupo-y-todos-lo-notaron', 'Tuve un rollo con un amigo del grupo y todos lo notaron', '😬', 'amigos', 'approved'),
  ('tuve-un-rollo-con-la-mejor-amiga-de-mi-mejor-amiga-y-nunca-l', 'Tuve un rollo con la mejor amiga de mi mejor amiga y nunca lo conté', '🤐', 'amigos', 'approved'),
  ('tuve-celos-cuando-mi-amiga-se-hizo-intima-de-otra', 'Tuve celos cuando mi amiga se hizo íntima de otra', '😒', 'amigos', 'approved'),
  ('tengo-una-amistad-chico-chica-que-vive-de-tension-sexual-no', 'Tengo una amistad chico-chica que vive de tensión sexual no resuelta', '🌶️', 'amigos', 'approved'),
  ('una-noche-con-un-amigo-arruino-la-amistad-para-siempre', 'Una noche con un amigo arruinó la amistad para siempre', '🕯️', 'amigos', 'approved'),
  ('mi-amiga-se-lio-con-un-amigo-mio-y-se-incomodo-todo', 'Mi amiga se lió con un amigo mío y se incomodó todo', '🌀', 'amigos', 'approved'),
  ('una-pareja-de-amigos-del-grupo-corto-y-nos-dividieron', 'Una pareja de amigos del grupo cortó y nos dividieron', '💔', 'amigos', 'approved'),
  ('tuve-que-elegir-bando-en-la-ruptura-de-dos-amigos-y-elegi-ma', 'Tuve que elegir bando en la ruptura de dos amigos y elegí mal', '⚖️', 'amigos', 'approved'),
  ('vi-una-foto-del-grupo-y-note-que-faltaba-alguien-que-ya-no-e', 'Vi una foto del grupo y noté que faltaba alguien que ya no está', '📸', 'amigos', 'approved'),
  ('en-mi-cumple-alguien-hizo-foto-y-mi-mejor-amigo-no-estaba', 'En mi cumple alguien hizo foto y mi mejor amigo no estaba', '🥲', 'amigos', 'approved'),
  ('no-tengo-una-foto-reciente-con-un-solo-amigo-de-verdad', 'No tengo una foto reciente con un solo amigo de verdad', '🤳', 'amigos', 'approved'),
  ('adelante-la-cuenta-de-la-cena-y-el-que-faltaba-nunca-pago', 'Adelanté la cuenta de la cena y el que faltaba nunca pagó', '🧾', 'amigos', 'approved'),
  ('en-mi-cumple-de-30-vinieron-mas-amigos-de-mi-pareja-que-mios', 'En mi cumple de 30 vinieron más amigos de mi pareja que míos', '🎂', 'amigos', 'approved'),
  ('llamo-a-mi-madre-antes-que-a-un-amigo-cuando-me-pasa-algo-bu', 'Llamo a mi madre antes que a un amigo cuando me pasa algo bueno', '📞', 'amigos', 'approved'),
  ('me-paso-algo-bueno-y-no-se-lo-conte-a-nadie-por-pereza', 'Me pasó algo bueno y no se lo conté a nadie por pereza', '🤐', 'amigos', 'approved'),
  ('tengo-un-mensaje-sin-leer-de-un-amigo-desde-hace-tres-semana', 'Tengo un mensaje sin leer de un amigo desde hace tres semanas', '📬', 'amigos', 'approved'),
  ('respondo-siempre-con-tres-palabras-a-mi-amiga-que-escribe-no', 'Respondo siempre con tres palabras a mi amiga que escribe novelas', '⌨️', 'amigos', 'approved'),
  ('recibo-audios-de-mi-amiga-y-los-oigo-en-x2-sin-atencion', 'Recibo audios de mi amiga y los oigo en x2 sin atención', '🎧', 'amigos', 'approved'),
  ('transcribo-los-audios-de-mi-amiga-porque-me-da-pereza-escuch', 'Transcribo los audios de mi amiga porque me da pereza escucharlos', '📝', 'amigos', 'approved'),
  ('leo-los-mensajes-del-grupo-desde-la-cuenta-de-mi-pareja', 'Leo los mensajes del grupo desde la cuenta de mi pareja', '👥', 'amigos', 'approved'),
  ('mi-pareja-conoce-a-mis-amigos-solo-por-lo-que-cuento-del-gru', 'Mi pareja conoce a mis amigos solo por lo que cuento del grupo', '💬', 'amigos', 'approved'),
  ('despues-de-cada-cena-con-amigos-hago-debrief-con-mi-pareja-u', 'Después de cada cena con amigos hago debrief con mi pareja una hora', '🛋️', 'amigos', 'approved'),
  ('le-conte-a-mi-pareja-un-secreto-que-un-amigo-me-habia-confia', 'Le conté a mi pareja un secreto que un amigo me había confiado', '🗝️', 'amigos', 'approved'),
  ('toda-la-pandilla-cambio-la-foto-de-perfil-al-grupo-en-una-bo', 'Toda la pandilla cambió la foto de perfil al grupo en una boda menos yo', '📷', 'amigos', 'approved'),
  ('mi-grupo-tuvo-una-epoca-en-la-que-todos-teniamos-la-misma-fo', 'Mi grupo tuvo una época en la que todos teníamos la misma foto de perfil', '🖼️', 'amigos', 'approved'),
  ('mi-grupo-me-puso-un-mote-y-no-me-he-atrevido-a-decir-que-lo', 'Mi grupo me puso un mote y no me he atrevido a decir que lo odio', '🏷️', 'amigos', 'approved'),
  ('llevo-veinte-anos-respondiendo-a-un-mote-del-cole', 'Llevo veinte años respondiendo a un mote del cole', '🏷️', 'amigos', 'approved'),
  ('tuve-que-explicarle-una-broma-interna-del-grupo-a-un-nuevo-y', 'Tuve que explicarle una broma interna del grupo a un nuevo y se rompió la magia', '🪄', 'amigos', 'approved'),
  ('mis-amigos-hicieron-una-broma-interna-que-no-pille-y-me-sent', 'Mis amigos hicieron una broma interna que no pillé y me sentí fuera', '🥲', 'amigos', 'approved'),
  ('llegue-tarde-a-una-comida-y-todos-comieron-sin-mi', 'Llegué tarde a una comida y todos comieron sin mí', '🍝', 'amigos', 'approved'),
  ('llegue-la-ultima-a-mi-propio-cumpleanos', 'Llegué la última a mi propio cumpleaños', '🎉', 'amigos', 'approved'),
  ('soy-el-pesado-del-escape-room-cuando-voy-con-amigos', 'Soy el pesado del escape room cuando voy con amigos', '🔓', 'amigos', 'approved'),
  ('hago-trampas-en-juegos-de-mesa-con-amigos-y-lo-niego', 'Hago trampas en juegos de mesa con amigos y lo niego', '🎲', 'amigos', 'approved'),
  ('sali-del-bar-sin-avisar-y-mis-amigos-me-buscaron-una-hora', 'Salí del bar sin avisar y mis amigos me buscaron una hora', '🌃', 'amigos', 'approved'),
  ('perdi-a-mis-amigos-en-un-festival-y-volvi-solo-al-hostel', 'Perdí a mis amigos en un festival y volví solo al hostel', '🎪', 'amigos', 'approved'),
  ('despues-del-festival-con-mis-amigos-nada-volvio-a-ser-igual', 'Después del festival con mis amigos nada volvió a ser igual', '🌈', 'amigos', 'approved'),
  ('me-fui-de-vacas-con-un-grupo-y-nunca-volvere-a-ir', 'Me fui de vacas con un grupo y nunca volveré a ir', '🏖️', 'amigos', 'approved'),
  ('cancele-en-el-grupo-y-silencie-notificaciones-para-no-leer-l', 'Cancelé en el grupo y silencié notificaciones para no leer las quejas', '🔕', 'amigos', 'approved'),
  ('la-amistad-acabo-sin-pelea-solo-se-diluyo', 'La amistad acabó sin pelea, solo se diluyó', '🌫️', 'amigos', 'approved')
on conflict (slug) do nothing;
