-- =================================================================
-- Unlocked seed v2 — Part 2 of 4
-- Aplicar en Supabase Dashboard -> SQL Editor (después de Part 1)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- =================================================================

insert into achievements (slug, title, emoji, category, status) values
  ('estuve-sola-san-valentin', 'He pasado el San Valentín completamente solo', '💝', 'amor', 'approved'),
  ('bloquee-desbloquee-ex', 'He bloqueado y desbloqueado a mi ex tres veces en un mes', '🔒', 'amor', 'approved'),
  ('me-enamore-de-alguien-que-no-me-queria', 'Me enamoré de quien no me quería y me costó más de un año', '⌛', 'amor', 'approved'),
  ('escribi-carta-nunca-mande', 'Escribí una carta a alguien que nunca mandé', '✉️', 'amor', 'approved'),
  ('primera-vez-incomoda', 'Mi primera vez fue radicalmente distinta a lo que esperaba', '🙈', 'amor', 'approved'),
  ('primera-ruptura-apocalipsis', 'Mi primera ruptura me pareció el fin del mundo', '🌍', 'amor', 'approved'),
  ('me-siguen-en-instagram-exes', 'Todos mis exes me siguen en Instagram pero no hablamos', '📸', 'amor', 'approved'),
  ('compre-anticonceptivos-nervioso', 'Compré preservativos en el Mercadona con cara de poker', '🙂', 'amor', 'approved'),
  ('me-gusto-alguien-que-tenia-pareja', 'Me gustó alguien que tenía pareja y tuve que aguantar', '😶', 'amor', 'approved'),
  ('ex-del-mismo-circulo', 'Mi ex y yo seguimos en el mismo grupo de amigos', '😬', 'amor', 'approved'),
  ('tarde-en-superar-ruptura', 'He tardado más en superar una relación que en durar la relación', '⏳', 'amor', 'approved'),
  ('fui-boda-soltero', 'He ido a una boda solo mientras todos iban en pareja', '💒', 'amor', 'approved'),
  ('menti-sobre-ex', 'He mentido sobre cuántas personas he besado', '🤫', 'amor', 'approved'),
  ('me-compararon-con-ex', 'Mi pareja me comparó con su ex sin darse cuenta', '😤', 'amor', 'approved'),
  ('chat-copiado-equivocada', 'He mandado el mensaje que era para mi amigo a la persona de la que hablo', '📲', 'amor', 'approved'),
  ('primer-te-quiero-no-devuelto', 'Dije "te quiero" y la respuesta fue "gracias"', '💬', 'amor', 'approved'),
  ('me-ilusione-de-mas', 'Me ilusioné de más con algo que ni había empezado', '✨', 'amor', 'approved'),
  ('vi-ex-en-san-valentin', 'Vi a mi ex con alguien nuevo el día de San Valentín', '🍷', 'amor', 'approved'),
  ('me-escribio-despues-de-meses', 'Mi ex me escribió después de meses de silencio con un "hola"', '💬', 'amor', 'approved'),
  ('primera-cita-tinder', 'Mi primera cita de Tinder fue un desastre absoluto', '📱', 'amor', 'approved'),
  ('me-dejaron-sin-explicacion', 'Me dejaron sin dar ninguna explicación', '❓', 'amor', 'approved'),
  ('ex-con-amigo-mio', 'Mi ex acabó con un amigo mío', '🫂', 'amor', 'approved'),
  ('enamore-personaje-serie', 'Me enamoré de un personaje de serie', '📺', 'amor', 'approved'),
  ('vi-exes-de-ex', 'He stalkeado a los exes de mi ex', '🔍', 'amor', 'approved'),
  ('me-dejaron-por-alguien-mejor', 'Me dejaron con la frase "mereces algo mejor"', '💔', 'amor', 'approved'),
  ('declare-con-testigos', 'Me declaré a alguien con gente mirando y dijo que no', '😬', 'amor', 'approved'),
  ('relacion-larga-distancia', 'Mantuve una relación a distancia más tiempo del razonable', '🗺️', 'amor', 'approved'),
  ('dependi-del-movil', 'He tenido el móvil en la mano esperando una respuesta durante horas', '📱', 'amor', 'approved'),
  ('vi-ex-en-festival', 'Me crucé con mi ex en un festival sin aviso previo', '🎪', 'amor', 'approved'),
  ('llore-en-aeropuerto', 'He llorado en un aeropuerto despidiendo a alguien que me importaba', '✈️', 'amor', 'approved'),
  ('me-gusto-persona-imposible', 'Me gustó alguien que nunca podría gustarme en circunstancias normales', '🌪️', 'amor', 'approved'),
  ('termine-algo-que-no-empezo', 'Terminé algo que técnicamente nunca había empezado', '🎭', 'amor', 'approved'),
  ('guarde-objeto-ex', 'Guardé una cosa de mi ex durante demasiado tiempo', '📦', 'amor', 'approved'),
  ('me-acoste-llorando', 'Me he dormido llorando de noche más veces de las que querría admitir', '🌙', 'amor', 'approved'),
  ('le-di-segunda-oportunidad', 'Le di una segunda oportunidad que no merecía', '🔄', 'amor', 'approved'),
  ('me-enamore-en-vacaciones', 'Me enamoré de alguien en vacaciones que nunca volvería a ver', '🌅', 'amor', 'approved'),
  ('me-entere-de-infidelidad-en-instagram', 'Me enteré de que me ponían los cuernos por Instagram', '📸', 'amor', 'approved'),
  ('escribi-su-nombre-sin-querer', 'Escribí el nombre de mi ex sin querer en un documento de trabajo', '💻', 'amor', 'approved'),
  ('llame-mama-jefe', 'He llamado "mamá" a mi jefe sin querer', '👔', 'trabajo', 'approved'),
  ('vomite-cena-empresa', 'He vomitado en la cena de empresa', '🤮', 'trabajo', 'approved'),
  ('llore-bano-oficina', 'He llorado en el baño de la oficina', '🚽', 'trabajo', 'approved'),
  ('dormi-reunion-teams', 'Me he dormido en una reunión de Teams', '💻', 'trabajo', 'approved'),
  ('busque-curro-en-curro', 'He empezado a buscar curro 5 minutos después de entrar', '🔍', 'trabajo', 'approved'),
  ('correo-no-llego', 'He fingido que el correo no me llegó', '📧', 'trabajo', 'approved'),
  ('semana-cama-teletrabajo', 'He vivido una semana entera de teletrabajo desde la cama', '🛏️', 'trabajo', 'approved'),
  ('jefe-no-sabe-mi-nombre', 'He tenido un jefe que no sabía mi nombre tras un año', '👋', 'trabajo', 'approved'),
  ('trabaje-domingo-nada', 'He trabajado un domingo por nada', '📅', 'trabajo', 'approved'),
  ('culpa-al-outlook', 'He echado la culpa al Outlook', '🐌', 'trabajo', 'approved'),
  ('camara-apagada-todo-el-dia', 'He tenido la cámara apagada en todas las reuniones', '📷', 'trabajo', 'approved'),
  ('primer-sueldo-desaparecio', 'Mi primer sueldo desapareció en tres días', '💸', 'trabajo', 'approved'),
  ('comi-triste-mio-de-pie', 'He comido en mi mesa de oficina sin levantarme en todo el día', '🥪', 'trabajo', 'approved'),
  ('mande-cv-empresa-en-la-que-trabajo', 'Mandé mi CV a una empresa y era la empresa donde trabajo', '🤦', 'trabajo', 'approved'),
  ('me-quede-dormido-presentacion', 'Me quedé dormido en mi propia presentación de empresa', '📊', 'trabajo', 'approved'),
  ('hice-horas-extra-sin-paga', 'He hecho horas extra gratis durante meses y no me las compensaron', '⏰', 'trabajo', 'approved'),
  ('menti-entrevista', 'He mentido en una entrevista de trabajo sobre experiencia', '📝', 'trabajo', 'approved'),
  ('me-confundi-de-sala-reunion', 'Entré a la sala de reuniones equivocada y me senté antes de darme cuenta', '🚪', 'trabajo', 'approved'),
  ('companero-come-olor-fuerte', 'He aguantado a un compañero que calienta comida con olor fuerte cada día', '🐟', 'trabajo', 'approved'),
  ('primer-dia-no-encontre-bano', 'El primer día de trabajo no encontré el baño y no pregunté', '🚽', 'trabajo', 'approved'),
  ('firme-sin-leer', 'He firmado un contrato sin leerlo entero', '📃', 'trabajo', 'approved'),
  ('dimiti-sin-otro-trabajo', 'He dimitido sin tener otro trabajo', '✌️', 'trabajo', 'approved'),
  ('tuve-jefe-peor', 'He tenido el peor jefe de mi vida y no le dije nada', '😤', 'trabajo', 'approved'),
  ('me-olvide-reunion-importante', 'Se me olvidó una reunión importante', '📅', 'trabajo', 'approved'),
  ('me-dormi-con-emails-abiertos', 'Me quedé dormido con los emails abiertos en el portátil', '💤', 'trabajo', 'approved'),
  ('trabaje-con-fiebre', 'He ido a trabajar con fiebre para no gastar días de baja', '🤒', 'trabajo', 'approved'),
  ('me-pillaron-en-redes-en-hora-trabajo', 'Me pillaron en redes sociales en horario de trabajo', '📱', 'trabajo', 'approved'),
  ('me-echaron-primer-curro', 'Me echaron de mi primer trabajo', '📦', 'trabajo', 'approved'),
  ('practique-firma-nuevo-nombre', 'He practicado mi firma cuando empecé a trabajar', '✒️', 'trabajo', 'approved'),
  ('llegue-tarde-el-primer-dia', 'Llegué tarde el primer día de trabajo', '⏱️', 'trabajo', 'approved'),
  ('me-equivoque-de-destinatario-email', 'Mandé un email confidencial al destinatario equivocado', '📧', 'trabajo', 'approved'),
  ('cobre-menos-que-esperaba', 'La primera nómina fue menos de lo que esperaba', '💰', 'trabajo', 'approved'),
  ('companero-habla-mucho', 'He tenido el compañero que habla contigo cuando estás con auriculares', '🎧', 'trabajo', 'approved'),
  ('me-arrepenti-de-dimision', 'He pedido no procesar mi dimisión a las 48 horas', '🔄', 'trabajo', 'approved'),
  ('copie-a-companero', 'He copiado el trabajo de un compañero discretamente', '🤫', 'trabajo', 'approved'),
  ('reunion-que-era-email', 'He asistido a una reunión de una hora que era un email', '📧', 'trabajo', 'approved'),
  ('llegue-tarde-excusa-metro', 'He llegado tarde al trabajo y he culpado al transporte público', '🚇', 'trabajo', 'approved'),
  ('puse-fondo-falso-teletrabajo', 'He puesto fondo falso en videollamada para que no vieran mi cuarto', '🖥️', 'trabajo', 'approved'),
  ('hice-la-lista-de-curros-futuros', 'He buscado casas en otras ciudades mientras estaba en el trabajo', '🏠', 'trabajo', 'approved'),
  ('no-encontre-aparcamiento-llegue-tarde', 'Llegué tarde porque "no había aparcamiento"', '🅿️', 'trabajo', 'approved'),
  ('perdi-hilo-reunion-larga', 'Perdí el hilo de una reunión de dos horas y asentí a todo', '👍', 'trabajo', 'approved'),
  ('comi-con-jefe-incomodo', 'He comido con mi jefe a solas sin saber de qué hablar', '🍽️', 'trabajo', 'approved'),
  ('guarde-cosas-en-el-cajon-varios-meses', 'He guardado papeles en el cajón sin organizarlos durante meses', '🗂️', 'trabajo', 'approved'),
  ('me-dormi-en-el-tren-de-vuelta', 'Me dormí en el tren de vuelta del trabajo y me pasé tres paradas', '🚆', 'trabajo', 'approved'),
  ('trabaje-en-algo-inutil', 'He trabajado semanas en algo que cancelaron sin aviso', '🗑️', 'trabajo', 'approved'),
  ('me-olvide-el-portatil', 'Olvidé el portátil en casa el día más importante del mes', '💻', 'trabajo', 'approved'),
  ('me-ascendieron-sin-sueldo', 'Me ascendieron de título pero no de sueldo', '📈', 'trabajo', 'approved'),
  ('pregunte-algo-ya-explicado', 'Pregunté algo en una reunión que ya se había explicado', '🙋', 'trabajo', 'approved'),
  ('llegue-mucho-antes-por-nervios', 'Llegué al nuevo trabajo 45 minutos antes el primer día', '⏰', 'trabajo', 'approved'),
  ('me-dormi-en-formacion', 'Me dormí en una formación obligatoria de empresa', '😴', 'trabajo', 'approved'),
  ('tuve-que-saludar-sin-recordar-nombre', 'Presenté a un compañero sin recordar su nombre', '😅', 'trabajo', 'approved'),
  ('trabaje-navidad', 'He trabajado el 25 de diciembre', '🎄', 'trabajo', 'approved'),
  ('cometi-error-grande-calle', 'Cometí un error grande y no se lo dije a nadie durante una semana', '🤐', 'trabajo', 'approved'),
  ('me-cambiaron-de-proyecto-sin-avisar', 'Me cambiaron de proyecto sin avisarme el lunes por la mañana', '🔀', 'trabajo', 'approved'),
  ('copie-plantilla-correo', 'He mandado un correo con el nombre del cliente anterior sin cambiarlo', '📧', 'trabajo', 'approved'),
  ('me-bloquearon-reunion-a-la-hora-de-comer', 'Me bloquearon la hora de comer con una reunión semanal', '🍴', 'trabajo', 'approved'),
  ('fui-despedida-empresa-de-alguien', 'Fui a la cena de despedida de alguien que no me caía bien', '🥂', 'trabajo', 'approved'),
  ('tuve-jefe-que-se-atribuyo-mi-trabajo', 'Mi jefe presentó mi trabajo como suyo', '📊', 'trabajo', 'approved'),
  ('hice-el-trabajo-de-otro', 'He hecho el trabajo de un compañero sin reconocimiento', '🔧', 'trabajo', 'approved'),
  ('use-la-impresora-en-mal-momento', 'La impresora me falló justo antes de una entrega importante', '🖨️', 'trabajo', 'approved'),
  ('me-equivoque-de-sala-el-primer-dia', 'El primer día de trabajo fui a la sala equivocada para la reunión de bienvenida', '🚪', 'trabajo', 'approved'),
  ('acepte-trabajo-con-sueldo-bajo', 'Acepté un trabajo con sueldo bajo porque tenía miedo de rechazarlo', '💶', 'trabajo', 'approved'),
  ('cai-rompi-cabeza', 'Me caí y me rompí la cabeza', '🤕', 'salud', 'approved'),
  ('lumbalgia-cordones', 'Me dio una lumbalgia atando los cordones', '🪢', 'salud', 'approved'),
  ('hueso-aceituna', 'Me he tragado un hueso de aceituna', '🫒', 'salud', 'approved'),
  ('escayola-despacito', 'Me han escayolado un pie por bailar Despacito', '💃', 'salud', 'approved'),
  ('urgencias-lentilla', 'He ido a urgencias por una lentilla atascada', '👁️', 'salud', 'approved'),
  ('queme-lengua-cafe', 'Me he quemado la lengua con cada café desde 2018', '☕', 'salud', 'approved'),
  ('piojos-adulto', 'He pillado piojos de adulto', '🦟', 'salud', 'approved'),
  ('patatus-factura', 'Me dio un patatús al ver una factura', '💀', 'salud', 'approved'),
  ('lego-nocturno', 'He pisado un Lego descalzo en plena noche', '🧱', 'salud', 'approved'),
  ('palillo-encia', 'Me clavé un palillo en la encía celebrando algo', '🥢', 'salud', 'approved'),
  ('me-torci-tobillo-plano', 'Me torcí el tobillo en terreno completamente llano', '🦶', 'salud', 'approved'),
  ('queme-con-planchado', 'Me quemé planchando sin camisa', '👕', 'salud', 'approved'),
  ('corte-con-tijeras-de-ensalada', 'Me corté con las tijeras de abrir una bolsa de ensalada', '🥗', 'salud', 'approved'),
  ('me-desmaye-analisis', 'Me desmayé haciéndome un análisis de sangre', '💉', 'salud', 'approved'),
  ('alergia-sin-saber', 'Descubrí una alergia en el peor momento posible', '🤧', 'salud', 'approved'),
  ('me-golpee-dedo-puerta', 'Me pillé el dedo con la puerta del coche', '🚗', 'salud', 'approved'),
  ('me-cai-bicicleta-adulto', 'Me caí de la bicicleta de adulto en la calle', '🚲', 'salud', 'approved'),
  ('me-clave-esquirla', 'Me clavé una astilla en el pie y fui al médico', '🌲', 'salud', 'approved'),
  ('gastroenteritis-viaje', 'Pillé gastroenteritis en un viaje importante', '🤢', 'salud', 'approved'),
  ('dormi-mal-semana', 'He dormido mal una semana entera sin saber por qué', '😴', 'salud', 'approved'),
  ('me-golpee-con-armario', 'Me di en la espinilla con el armario abierto en la oscuridad', '🌑', 'salud', 'approved'),
  ('queme-con-sarten', 'Me quemé con la sartén haciendo el primer huevo frito de mi vida', '🍳', 'salud', 'approved'),
  ('me-cai-cama', 'Me caí de la cama durmiendo', '🛌', 'salud', 'approved'),
  ('me-indigeste-sin-exceso', 'Me indigesté con algo que como cada semana', '🍝', 'salud', 'approved'),
  ('me-pille-el-pelo-secador', 'Me pillé el pelo en el secador', '💨', 'salud', 'approved'),
  ('me-golpee-la-cabeza-maletero', 'Me di en la cabeza con el maletero del coche', '🚗', 'salud', 'approved'),
  ('resfrio-verano', 'Me resfriÉ en pleno verano', '☀️', 'salud', 'approved'),
  ('me-pele-nariz-sol', 'Se me peló la nariz del sol aunque me puse crema', '🌞', 'salud', 'approved'),
  ('dolor-espalda-sofa', 'Me lesioné la espalda en el sofá viendo Netflix', '📺', 'salud', 'approved'),
  ('calambre-piscina', 'Me dio un calambre en la piscina y tuve que salir con ayuda', '🏊', 'salud', 'approved'),
  ('me-golpee-en-el-ojo', 'Me golpeé el ojo sin saber con qué', '👁️', 'salud', 'approved'),
  ('reaccion-alergia-maquillaje', 'Me salió urticaria con un producto nuevo el día de algo importante', '🧴', 'salud', 'approved'),
  ('calambres-por-frio', 'Tuve calambres en las piernas en mitad de la noche', '🦵', 'salud', 'approved'),
  ('me-clave-aguja-cosiendo', 'Me clavé una aguja cosiendo un botón', '🧵', 'salud', 'approved'),
  ('me-arranque-piel-en-invierno', 'Se me cuartearon los labios tanto que sangraron en una reunión', '🥶', 'salud', 'approved'),
  ('me-golpee-arco-pie', 'Me di en el dedo gordo del pie contra la pata de la mesa', '🛋️', 'salud', 'approved'),
  ('me-bebi-agua-tragante', 'Me atragané con agua sola', '💧', 'salud', 'approved'),
  ('me-queme-pelo', 'Me quemé el pelo con una vela encendida', '🕯️', 'salud', 'approved'),
  ('lumbago-estornudo', 'Me lesioné la espalda estornudando', '🤧', 'salud', 'approved'),
  ('no-dormi-por-cafeina', 'No dormí por haberme tomado un café a las 6 de la tarde', '☕', 'salud', 'approved'),
  ('alergia-sol', 'Descubrí que soy alérgico al sol en la playa', '☀️', 'salud', 'approved'),
  ('me-di-con-cristal', 'Me di contra un cristal limpio en un establecimiento', '🪟', 'salud', 'approved'),
  ('cai-escalera-casa', 'Me caí por la escalera de mi propia casa', '🏠', 'salud', 'approved'),
  ('me-corte-afeitando-cara', 'Me corté afeitando el día que tenía algo importante', '🪒', 'salud', 'approved'),
  ('queme-lengua-pizza', 'Me quemé el paladar con la pizza sin esperar', '🍕', 'salud', 'approved'),
  ('me-intoxique-con-mejillones', 'Me intoxiqué con mejillones en el bar de siempre', '🦪', 'salud', 'approved'),
  ('dolor-cuello-dormir-mal', 'Me desperté con tortícolis sin haber hecho nada raro', '😩', 'salud', 'approved'),
  ('me-disloque-una-articulacion', 'Me disloqué un dedo haciendo algo cotidiano', '🤌', 'salud', 'approved'),
  ('me-pico-avispa', 'Me picó una avispa en el momento más improcedente', '🐝', 'salud', 'approved'),
  ('me-meti-agua-en-nariz', 'Me metí agua en la nariz en la piscina de adulto', '🏊', 'salud', 'approved'),
  ('me-raspe-las-rodillas', 'Me raspé las rodillas cayéndome en la calle', '🩹', 'salud', 'approved'),
  ('me-corto-el-papel', 'Me cortó el papel y tuve que tirar de curita', '📄', 'salud', 'approved'),
  ('me-entraron-ganas-urgentes', 'Tuve que buscar un baño urgente en una ciudad desconocida', '🚽', 'salud', 'approved'),
  ('me-maree-barco', 'Me mareé en un barco con calma chicha', '⛵', 'salud', 'approved'),
  ('me-di-en-la-frente', 'Me di en la frente con la puerta del armario abierta', '🚪', 'salud', 'approved'),
  ('olvide-pastillas', 'He olvidado tomar las pastillas durante una semana', '💊', 'salud', 'approved'),
  ('me-cai-escalon-entrada', 'Me caí en el escalón de la entrada de un bar', '🍺', 'salud', 'approved'),
  ('me-lastime-ducha', 'Me hice daño en la ducha sin hacer nada fuera de lo normal', '🚿', 'salud', 'approved'),
  ('me-golpee-con-mueble-oscuridad', 'Me golpeé con todos los muebles posibles yendo al baño de noche', '🌙', 'salud', 'approved'),
  ('me-atragante-sin-motivo', 'Me atragané comiendo tranquilamente en casa solo', '🤦', 'salud', 'approved'),
  ('me-clave-agujas-manualidades', 'Me clavé una aguja haciendo manualidades que nunca terminé', '🧶', 'salud', 'approved'),
  ('vi-ballena', 'He visto una ballena', '🐳', 'viajes', 'approved'),
  ('deportado-sello', 'Me deportaron por un sello mal puesto en el pasaporte', '📕', 'viajes', 'approved'),
  ('malaria-tailandia', 'Pillé la malaria en Tailandia', '🦟', 'viajes', 'approved'),
  ('perdi-maleta', 'He perdido la maleta en un viaje de 3 días', '✈️', 'viajes', 'approved'),
  ('dormi-barajas', 'He dormido en el suelo de Barajas', '💤', 'viajes', 'approved'),
  ('200-euros-bus', 'Me cobraron 200 € por ir mal de bus', '🚌', 'viajes', 'approved'),
  ('regatear-bazar', 'He intentado regatear en un bazar y me han ganado', '💰', 'viajes', 'approved'),
  ('diarrea-erasmus', 'Me dio diarrea en un viaje de Erasmus', '🧻', 'viajes', 'approved'),
  ('llore-ver-mar', 'He llorado al ver el mar tras 2 años sin verlo', '🌊', 'viajes', 'approved'),
  ('mal-pulpo-galicia', 'Me puse malo de comer pulpo en Galicia', '🐙', 'viajes', 'approved'),
  ('perdi-avion', 'He perdido un avión', '✈️', 'viajes', 'approved'),
  ('pasaporte-caducado', 'Llegué al aeropuerto con el pasaporte caducado', '🛂', 'viajes', 'approved'),
  ('vuelo-cancelado-sin-aviso', 'Me cancelaron el vuelo sin aviso el mismo día', '🛫', 'viajes', 'approved'),
  ('hostal-6-camas', 'Compartí habitación de hostal con desconocidos que roncaban', '😤', 'viajes', 'approved'),
  ('turista-mi-ciudad', 'He hecho de guía en mi propia ciudad sin haber visto nada', '🗺️', 'viajes', 'approved'),
  ('error-airbnb', 'He llegado a un Airbnb que no era como en las fotos', '🏚️', 'viajes', 'approved'),
  ('blablacar-raro', 'He compartido BlaBlaCar con alguien que no paró de hablar en 3 horas', '🚗', 'viajes', 'approved'),
  ('olvide-cargador-hotel', 'Olvidé el cargador en el hotel y lo descubrí en el aeropuerto', '🔌', 'viajes', 'approved'),
  ('me-queme-primer-dia', 'Me quemé en el primer día de playa del año', '🔆', 'viajes', 'approved'),
  ('no-hable-el-idioma', 'Viví una semana en un país sin hablar nada del idioma', '🗣️', 'viajes', 'approved'),
  ('perdi-excursion-grupo', 'Me perdí del grupo en una excursión organizada', '🧭', 'viajes', 'approved'),
  ('me-estafaron-taxi', 'Me estafaron en un taxi en el extranjero', '🚕', 'viajes', 'approved'),
  ('comi-algo-raro', 'Comí algo raro en un mercado de un país desconocido', '🍢', 'viajes', 'approved'),
  ('me-perdi-sin-datos', 'Me perdí en una ciudad extranjera sin datos en el móvil', '📵', 'viajes', 'approved'),
  ('me-multaron-metro-extranjero', 'Me multaron en el metro de otro país por no validar', '🚇', 'viajes', 'approved'),
  ('llegue-hotel-a-las-4am', 'Llegué al hotel a las 4 AM y me habían dado la habitación a otro', '🏨', 'viajes', 'approved'),
  ('reserve-vuelta-mal', 'Reservé el vuelo de vuelta un día antes de lo que debía', '📅', 'viajes', 'approved'),
  ('subi-montana-zapatillas', 'Subí una montaña con zapatillas de deporte', '⛰️', 'viajes', 'approved'),
  ('hice-turismo-solo', 'He viajado solo por primera vez', '🧳', 'viajes', 'approved'),
  ('me-perdi-el-vuelo-conexion', 'Perdí la conexión por unos minutos', '🛬', 'viajes', 'approved'),
  ('me-queje-del-hotel-en-redes', 'Puse una reseña de hotel con fotos en el momento de enfado', '⭐', 'viajes', 'approved'),
  ('blablacar-conductor-puso-su-musica', 'El conductor de BlaBlaCar puso su playlist entera sin preguntar', '🎵', 'viajes', 'approved'),
  ('llegue-cierre', 'Llegué al monumento al cierre y no entré', '🏛️', 'viajes', 'approved'),
  ('perdi-monedero-ciudad-ajena', 'Perdí el monedero en una ciudad que no era la mía', '👛', 'viajes', 'approved'),
  ('borracho-en-barco', 'Me mareé en un crucero sin haberme movido del bar', '🛳️', 'viajes', 'approved'),
  ('mezcle-idiomas', 'He hablado en una mezcla de tres idiomas sin querer en el extranjero', '🌐', 'viajes', 'approved'),
  ('me-queme-haciendo-cola', 'Me quemé en la cola de un parque temático', '🎢', 'viajes', 'approved'),
  ('viaje-sin-ropa-interior', 'Hice un viaje de 5 días sin llevar suficiente ropa interior', '🧦', 'viajes', 'approved'),
  ('compre-souvenirs-horribles', 'He comprado souvenirs que nunca he regalado', '🗿', 'viajes', 'approved'),
  ('llegue-distinto-aeropuerto', 'El vuelo llegó a un aeropuerto distinto al esperado', '✈️', 'viajes', 'approved'),
  ('despertador-hotel-no-sono', 'El despertador del hotel no sonó y perdí el tren', '⏰', 'viajes', 'approved'),
  ('comi-lo-mismo-toda-una-semana', 'Comí en el mismo restaurante todos los días del viaje porque era lo único fiable', '🍽️', 'viajes', 'approved'),
  ('me-ataque-foto-turista', 'Me hice 200 fotos en un día y no salgo en ninguna decente', '📷', 'viajes', 'approved'),
  ('me-quede-sin-bateria-en-viaje', 'Se me fue la batería del móvil el primer día', '🔋', 'viajes', 'approved'),
  ('primer-viaje-solo-al-extranjero', 'Viajé solo al extranjero por primera vez con 19 años', '🌍', 'viajes', 'approved'),
  ('me-robaron-cartera-metro', 'Me robaron la cartera en el metro de una ciudad europea', '💼', 'viajes', 'approved'),
  ('perdi-ropa-lavanderia-hostal', 'Perdí una prenda en la lavandería del hostal', '🧺', 'viajes', 'approved'),
  ('hice-el-camino-de-santiago', 'He hecho el Camino de Santiago', '🥾', 'viajes', 'approved'),
  ('dormi-avion-boca-abierta', 'Me dormí en el avión boca abierta y me grabaron', '😴', 'viajes', 'approved'),
  ('me-perdi-vuelta-hotel', 'Me perdí volviendo al hotel desde el restaurante', '🍴', 'viajes', 'approved'),
  ('fui-con-amigos-llegue-solo', 'Fui de viaje con amigos y llegué solo al hotel', '🏨', 'viajes', 'approved'),
  ('me-quede-dormido-tren-internacional', 'Me pasé de parada en un tren internacional', '🚄', 'viajes', 'approved'),
  ('comi-sin-saber-precio', 'Comí en un restaurante sin ver la carta de precios', '💸', 'viajes', 'approved'),
  ('no-encontre-alojamiento', 'Busqué alojamiento de noche llegando a una ciudad sin reserva', '🌙', 'viajes', 'approved'),
  ('me-equivoque-de-autobus', 'Me subí al autobús equivocado y tardé en darme cuenta', '🚌', 'viajes', 'approved'),
  ('llegue-sin-efectivo-extranjero', 'Llegué a un país donde no aceptaban tarjeta y no llevaba efectivo', '💳', 'viajes', 'approved'),
  ('primer-viaje-erasmus', 'Hice mi primer viaje de Erasmus solo con una mochila', '🎒', 'viajes', 'approved'),
  ('vi-amanecer-en-un-sitio-especial', 'Vi un amanecer en un sitio que no olvidaré nunca', '🌄', 'viajes', 'approved'),
  ('dormi-aeropuerto-segunda-vez', 'He dormido en un aeropuerto más de una vez en mi vida', '🛫', 'viajes', 'approved'),
  ('me-confundi-de-tren', 'Me subí al tren que iba en dirección contraria', '🚉', 'viajes', 'approved'),
  ('fui-destino-que-odiaba', 'Fui a un destino obligado y resultó ser lo mejor del año', '🌟', 'viajes', 'approved'),
  ('cura-tabaco-7am', 'He visto a un cura comprando tabaco a las 7 AM', '🚬', 'random', 'approved'),
  ('escarabajo-crudo', 'Me he comido un escarabajo crudo', '🪲', 'random', 'approved'),
  ('aprendi-punto', 'He aprendido a hacer punto en una tarde', '🧶', 'random', 'approved'),
  ('hable-solo-vecino', 'He hablado solo en voz alta y me ha pillado un vecino', '🗣️', 'random', 'approved'),
  ('ticket-mercadona-6meses', 'He guardado el ticket de Mercadona 6 meses', '🧾', 'random', 'approved'),
  ('karaoke-sin-sabersela', 'He cantado en el karaoke una canción que no me sé', '🎤', 'random', 'approved'),
  ('gane-bingo-verguenza', 'Gané en un bingo y me dio vergüenza gritar', '🎰', 'random', 'approved'),
  ('follando-parque', 'He visto a alguien follando en un parque', '🌳', 'random', 'approved'),
  ('bateria-consola-bolsillo', 'He estado dos semanas con la batería de la consola en mi bolsillo', '🎮', 'random', 'approved'),
  ('compre-en-wallapop', 'He comprado algo en Wallapop que nunca usé', '📦', 'random', 'approved'),
  ('vendi-en-wallapop', 'He vendido en Wallapop algo que compré la semana anterior', '🔄', 'random', 'approved'),
  ('me-quede-en-casa-mirar-pared', 'Me he quedado mirando la pared diez minutos sin pensar en nada', '🧱', 'random', 'approved'),
  ('perdi-apuesta-estupida', 'Perdí una apuesta estúpida y tuve que cumplirla', '🎲', 'random', 'approved'),
  ('cante-en-ducha-sin-saber', 'He cantado en la ducha y me lo han grabado', '🎵', 'random', 'approved'),
  ('compre-libro-no-lei', 'He comprado un libro que no leí', '📚', 'random', 'approved'),
  ('deje-planta-morir', 'Se me ha muerto una planta', '🪴', 'random', 'approved'),
  ('gaste-en-app', 'He gastado dinero real en una aplicación sin querer', '📱', 'random', 'approved'),
  ('me-apunte-gym-no-fui', 'Me apunté al gimnasio y fui tres veces en total', '🏋️', 'random', 'approved'),
  ('me-apunte-curso-no-termine', 'Empecé un curso online y lo dejé en el módulo 2', '💻', 'random', 'approved'),
  ('vi-serie-24h', 'He visto una serie entera en un fin de semana', '📺', 'random', 'approved'),
  ('pedi-extra-no-cobre', 'He pedido algo extra en una cafetería y no lo he cobrado', '☕', 'random', 'approved')
on conflict (slug) do nothing;
