-- =================================================================
-- Unlocked seed v3 — RELACIONES (200 entries)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- Requiere migración _012 (categoría 'relaciones' en el enum)
-- =================================================================

insert into achievements (slug, title, emoji, description, category, status) values
  ('relaciones-stalkee-ex-insta-3am', 'Stalkeé el Instagram de mi ex a las 3 de la mañana en modo incógnito', '🔍', 'Hice scroll hasta 2019 sin pestañear.', 'relaciones', 'approved'),
  ('relaciones-like-foto-2018-ex', 'Le di like sin querer a una foto de mi ex de 2018', '💀', NULL, 'relaciones', 'approved'),
  ('relaciones-swipe-derecha-companero-trabajo', 'Le di swipe a la derecha a un compañero de trabajo en Tinder', '🫠', 'Ahora compartimos almuerzo cada día.', 'relaciones', 'approved'),
  ('relaciones-match-con-mi-jefe', 'Hice match con mi jefe en Tinder', '😱', NULL, 'relaciones', 'approved'),
  ('relaciones-vi-perfil-ex-bumble', 'Vi el perfil de mi ex en Bumble y cerré la app del susto', '📱', NULL, 'relaciones', 'approved'),
  ('relaciones-cancele-cita-ultimo-minuto', 'Cancelé una cita de Tinder a 10 minutos de quedar sin excusa real', '📵', 'Le dije que tenía gastroenteritis.', 'relaciones', 'approved'),
  ('relaciones-llegue-borracho-primera-cita', 'Llegué borracho a la primera cita y la lié parda', '🍷', NULL, 'relaciones', 'approved'),
  ('relaciones-vomite-primera-cita', 'Vomité en la primera cita y aún así hubo segunda', '🤮', 'Le hizo gracia, no preguntéis.', 'relaciones', 'approved'),
  ('relaciones-confundi-nombre-cita', 'Llamé a mi cita por el nombre de mi ex', '😬', NULL, 'relaciones', 'approved'),
  ('relaciones-cite-misma-noche-dos', 'Cité a dos personas la misma noche en bares distintos', '🏃', 'No me pillaron de milagro.', 'relaciones', 'approved'),
  ('relaciones-ghosting-tres-meses', 'Le hice ghosting a alguien después de tres meses', '👻', NULL, 'relaciones', 'approved'),
  ('relaciones-recibi-ghosting-7-meses', 'Recibí ghosting de alguien con quien llevaba siete meses', '🪦', 'Aún espero el visto bueno.', 'relaciones', 'approved'),
  ('relaciones-respondi-mensaje-mes-tarde', 'Respondí un mensaje de Hinge un mes después como si nada', '⏳', NULL, 'relaciones', 'approved'),
  ('relaciones-breadcrumbing-pro', 'Hice breadcrumbing a alguien durante medio año', '🍞', 'Le mandaba un meme cada quincena.', 'relaciones', 'approved'),
  ('relaciones-frase-estoy-liado', 'Dije estoy muy liado para no quedar y vio que estaba en Twitter', '📲', NULL, 'relaciones', 'approved'),
  ('relaciones-quede-con-ex-otra-vez', 'Quedé con mi ex jurando que solo era un café', '☕', 'Acabamos en su casa, sorpresa.', 'relaciones', 'approved'),
  ('relaciones-folle-con-ex-aniversario', 'Follé con mi ex en lo que habría sido nuestro aniversario', '💔', NULL, 'relaciones', 'approved'),
  ('relaciones-vi-stories-ex-cinco-veces', 'Vi las Stories de mi ex cinco veces el mismo día', '👀', 'Sé que salgo en su top de espectadores.', 'relaciones', 'approved'),
  ('relaciones-cuenta-falsa-stalkear-ex', 'Me hice una cuenta falsa solo para stalkear a mi ex', '🥸', NULL, 'relaciones', 'approved'),
  ('relaciones-screenshot-ex-amigas', 'Mandé screenshots de mi ex al grupo de amigas para análisis forense', '📸', 'Análisis forense de un emoji, qué tristeza.', 'relaciones', 'approved'),
  ('relaciones-stalkear-nueva-pareja-ex', 'Stalkeé hasta el LinkedIn de la nueva pareja de mi ex', '💼', NULL, 'relaciones', 'approved'),
  ('relaciones-mire-movil-pareja-dormida', 'Miré el móvil de mi pareja mientras dormía', '🔓', 'No encontré nada y me sentí peor.', 'relaciones', 'approved'),
  ('relaciones-celos-amigo-trabajo', 'Tuve celos del amigo del trabajo de mi pareja', '😤', NULL, 'relaciones', 'approved'),
  ('relaciones-revise-likes-instagram', 'Revisé a quién daba likes mi pareja en Instagram', '🕵️', 'Encontré una ex y casi exploté.', 'relaciones', 'approved'),
  ('relaciones-pregunte-quien-es-esa', 'Pregunté quién es esa de la foto y monté un drama de hora y media', '🎭', NULL, 'relaciones', 'approved'),
  ('relaciones-relacion-distancia-3-meses', 'Mantuve una relación a distancia tres meses sin vernos', '✈️', 'Acabamos rompiendo por audio.', 'relaciones', 'approved'),
  ('relaciones-videollamada-7-horas', 'Hice una videollamada de siete horas con mi pareja a distancia', '📹', NULL, 'relaciones', 'approved'),
  ('relaciones-deje-hablarle-distancia', 'Dejé de hablarle a mi pareja a distancia sin avisar', '🌐', 'Volví a la semana como si nada.', 'relaciones', 'approved'),
  ('relaciones-situationship-un-ano', 'Estuve un año en una situationship sin etiquetar nada', '🤷', NULL, 'relaciones', 'approved'),
  ('relaciones-frase-estamos-viendo', 'Solté el clásico estamos viendo qué pasa', '🌫️', 'Llevábamos siete meses viéndolo.', 'relaciones', 'approved'),
  ('relaciones-presente-amigos-mi-amigo', 'Presenté a mi situationship a mis amigos como mi amigo', '🥲', NULL, 'relaciones', 'approved'),
  ('relaciones-amigo-derecho-meses', 'Tuve un amigo con derecho a roce durante medio año', '🛌', 'Acabó como acaban estas cosas.', 'relaciones', 'approved'),
  ('relaciones-deje-hablar-friends-benefits', 'Dejé de hablarme con un amigo después de follar una vez', '🚪', NULL, 'relaciones', 'approved'),
  ('relaciones-conversacion-ruptura-restaurante', 'Tuve la conversación de ruptura en un restaurante lleno de gente', '🍝', 'Y pagué la cena igual.', 'relaciones', 'approved'),
  ('relaciones-llore-una-hora-bano', 'Lloré una hora seguida en el baño después de cortar', '😭', NULL, 'relaciones', 'approved'),
  ('relaciones-bloquee-todas-redes-ex', 'Bloqueé a mi ex en todas las redes en menos de cinco minutos', '🚫', 'WhatsApp, Insta, Spotify, todo.', 'relaciones', 'approved'),
  ('relaciones-desbloquee-tres-dias-despues', 'Desbloqueé a mi ex tres días después porque pude', '🔁', NULL, 'relaciones', 'approved'),
  ('relaciones-corte-por-whatsapp', 'Corté con mi pareja por WhatsApp después de dos años', '💬', 'Ni una llamada, qué fuerte.', 'relaciones', 'approved'),
  ('relaciones-recibi-corte-audio', 'Me cortaron por un audio de WhatsApp de doce minutos', '🎙️', NULL, 'relaciones', 'approved'),
  ('relaciones-pareja-larga-no-follamos', 'Llevo con mi pareja años y ya no follamos casi nunca', '🛌', 'Pero somos felices, ojo.', 'relaciones', 'approved'),
  ('relaciones-dormimos-espaldas', 'Mi pareja y yo dormimos mirando a lados opuestos cada noche', '🛏️', NULL, 'relaciones', 'approved'),
  ('relaciones-cenamos-mirando-movil', 'Cenamos cada noche con mi pareja mirando el móvil', '📱', 'Conexión emocional sólida.', 'relaciones', 'approved'),
  ('relaciones-rutina-domingo-sofa', 'Llevamos cinco años haciendo el mismo plan de domingo', '🛋️', NULL, 'relaciones', 'approved'),
  ('relaciones-rebote-mes-ruptura', 'Tuve un rebote a las dos semanas de cortar', '🏀', 'Duró exactamente lo que tenía que durar.', 'relaciones', 'approved'),
  ('relaciones-dije-te-quiero-tres-citas', 'Dije te quiero en la tercera cita y se asustó', '💘', NULL, 'relaciones', 'approved'),
  ('relaciones-pelea-conocer-padres', 'Tuve una pelea con mi pareja delante de sus padres la primera vez', '👵', 'Adiós a la primera impresión.', 'relaciones', 'approved'),
  ('relaciones-suegra-pregunta-boda', 'Mi suegra me preguntó cuándo nos casamos a la segunda comida', '💒', NULL, 'relaciones', 'approved'),
  ('relaciones-pelea-whatsapp-visto', 'Monté una bronca porque mi pareja me dejó en visto cuatro horas', '👁️', 'Spoiler: estaba currando.', 'relaciones', 'approved'),
  ('relaciones-pelea-cenar-jueves', 'Discutimos media hora porque no decidíamos dónde cenar', '🍽️', NULL, 'relaciones', 'approved'),
  ('relaciones-pelea-futbol-aniversario', 'Mi pareja vio un partido de fútbol el día de nuestro aniversario', '⚽', 'Sigo sin perdonarlo del todo.', 'relaciones', 'approved'),
  ('relaciones-olvide-aniversario', 'Olvidé nuestro aniversario y me enteré por su Story', '📅', NULL, 'relaciones', 'approved'),
  ('relaciones-regalo-cubitera-cumple', 'Le regalé a mi pareja una cubitera por su cumpleaños', '🧊', 'Aún se acuerda dos años después.', 'relaciones', 'approved'),
  ('relaciones-comparo-aniversarios-insta', 'Comparé mi aniversario con los de Instagram y me deprimí', '📸', NULL, 'relaciones', 'approved'),
  ('relaciones-piso-pareja-pelea-bano', 'Vivo con mi pareja y nos peleamos por el orden del baño', '🚽', 'La toalla mojada en la cama, otra vez.', 'relaciones', 'approved'),
  ('relaciones-pelea-quien-saca-basura', 'Tuvimos una pelea épica por quién saca la basura', '🗑️', 'Llevamos un Excel ahora.', 'relaciones', 'approved'),
  ('relaciones-bloquee-desbloquee-ex-10', 'Bloqueé y desbloqueé a mi ex diez veces en una semana', '🔄', NULL, 'relaciones', 'approved'),
  ('relaciones-crush-mirar-clase', 'Tuve un crush en clase y solo le miré durante un cuatrimestre entero', '👁️', NULL, 'relaciones', 'approved'),
  ('relaciones-mensaje-crush-sin-leer-mes', 'Mi crush me dejó un mensaje sin leer durante un mes', '💌', 'Y aún así seguía con esperanzas.', 'relaciones', 'approved'),
  ('relaciones-puse-cuernos-borracho', 'Puse los cuernos en una boda con la prima del novio', '👰', NULL, 'relaciones', 'approved'),
  ('relaciones-recibi-cuernos-mejor-amigo', 'Me pusieron los cuernos con mi mejor amigo', '🗡️', 'Perdí dos personas en una noche.', 'relaciones', 'approved'),
  ('relaciones-sospeche-cuernos-tres-meses', 'Sospeché que me ponían los cuernos durante tres meses', '🤔', NULL, 'relaciones', 'approved'),
  ('relaciones-frase-pesima-ligar-bar', 'Solté una frase de ligar tan mala que se rió en mi cara', '🍻', 'Le dije Tu padre es ladrón, qué horror.', 'relaciones', 'approved'),
  ('relaciones-pedi-bizum-primera-cita', 'Pedí Bizum a mi cita por la mitad de la cuenta', '💸', 'No hubo segunda cita, sorpresa.', 'relaciones', 'approved'),
  ('relaciones-mensaje-borracho-ex-3am', 'Mandé un mensaje a mi ex a las 3am estando borracho perdido', '🌙', NULL, 'relaciones', 'approved'),
  ('relaciones-folle-no-debia-borracho', 'Follé con quien NO debía estando borracho', '🙈', 'Sigo evitando ese bar a día de hoy.', 'relaciones', 'approved'),
  ('relaciones-desperte-desconocido-cama', 'Me desperté en la cama de un desconocido sin saber ni el nombre', '🛌', NULL, 'relaciones', 'approved'),
  ('relaciones-escape-puntillas-amanecer', 'Salí de su casa de puntillas al amanecer sin despedirme', '🚪', 'Casi me llevo sus llaves por error.', 'relaciones', 'approved'),
  ('relaciones-ducha-sin-preguntar', 'Me duché en casa de alguien que acababa de conocer', '🚿', NULL, 'relaciones', 'approved'),
  ('relaciones-dm-instagram-ligar', 'Ligué por DMs de Instagram y acabamos saliendo año y medio', '📩', 'Funciona más de lo que parece.', 'relaciones', 'approved'),
  ('relaciones-tirar-ficha-linkedin', 'Tiré ficha por LinkedIn y se lo tomó como spam profesional', '💼', NULL, 'relaciones', 'approved'),
  ('relaciones-ligue-en-gimnasio', 'Ligué con alguien en el gimnasio y ahora le evito como a la peste', '🏋️', NULL, 'relaciones', 'approved'),
  ('relaciones-dije-no-pedida-mano', 'Dije no a una pedida de mano en un restaurante lleno', '💍', 'Las miradas, joder, las miradas.', 'relaciones', 'approved'),
  ('relaciones-anillo-improvisado-bolsa', 'Improvisé un anillo con la anilla de una lata para pedirle matrimonio', '🥫', NULL, 'relaciones', 'approved'),
  ('relaciones-vi-compromiso-ex-instagram', 'Vi el compromiso de mi ex en Instagram el mismo día que lo subió', '💔', 'Lloré viendo el carrusel.', 'relaciones', 'approved'),
  ('relaciones-fingir-cae-bien-suegra', 'Fingí que me caía bien mi suegra durante cuatro Navidades seguidas', '🎄', NULL, 'relaciones', 'approved'),
  ('relaciones-cunada-me-odia', 'Mi cuñada me odia desde la primera comida y nadie sabe por qué', '😠', NULL, 'relaciones', 'approved'),
  ('relaciones-suegro-me-llama-otro-nombre', 'Mi suegro lleva llamándome por otro nombre cinco años', '👴', 'Ya ni le corrijo, joder.', 'relaciones', 'approved'),
  ('relaciones-match-con-mi-prima', 'Hice match con la prima de mi mejor amigo en Tinder', '😅', NULL, 'relaciones', 'approved'),
  ('relaciones-swipe-amigo-pareja', 'Vi a la pareja de mi amigo en Tinder swipeando activamente', '🚨', 'Y tuve que decidir si decirlo.', 'relaciones', 'approved'),
  ('relaciones-modo-incognito-roto', 'Me cogieron stalkeando porque le di like sin querer a algo de 2017', '😵', NULL, 'relaciones', 'approved'),
  ('relaciones-cocine-paella-mal-cita', 'Cociné paella para impresionar y salió un arroz quemado', '🥘', 'Pidió pizza y aún sigue conmigo.', 'relaciones', 'approved'),
  ('relaciones-prepare-spotify-cita', 'Preparé una playlist específica para una cita y sonó la del gym', '🎶', 'Sonó reggaetón en pleno momento.', 'relaciones', 'approved'),
  ('relaciones-pille-leyendo-mensajes', 'Pillé a mi pareja leyendo mis mensajes con mi mejor amiga', '📖', NULL, 'relaciones', 'approved'),
  ('relaciones-creo-cuenta-fake-test', 'Creé una cuenta falsa para testear la fidelidad de mi pareja', '🎭', 'Pasó el test y aún me siento culpable.', 'relaciones', 'approved'),
  ('relaciones-segui-pareja-discoteca', 'Seguí a mi pareja a una discoteca para ver con quién iba', '🪩', NULL, 'relaciones', 'approved'),
  ('relaciones-amor-platonico-instituto', 'Aún sigo el Instagram de mi amor platónico del instituto', '🎓', NULL, 'relaciones', 'approved'),
  ('relaciones-stalkee-nueva-pareja-pinterest', 'Stalkeé hasta el Pinterest de la nueva pareja de mi ex', '🪡', 'Tiene un tablero de bodas, joder.', 'relaciones', 'approved'),
  ('relaciones-screenshot-mandado-persona', 'Mandé el screenshot de la persona a la propia persona', '📸', NULL, 'relaciones', 'approved'),
  ('relaciones-cite-bar-de-mi-ex', 'Llevé a una cita al bar donde curra mi ex sin saberlo', '🍺', 'La cara de mi ex no tenía precio.', 'relaciones', 'approved'),
  ('relaciones-pague-todo-cita-tinder', 'Pagué la cuenta entera en una cita y no me devolvió ni gracias', '💳', 'Aprendizaje caro, literal.', 'relaciones', 'approved'),
  ('relaciones-no-me-devolvio-bizum', 'No me devolvió nunca el Bizum de la primera cita', '💸', NULL, 'relaciones', 'approved'),
  ('relaciones-tinder-aeropuerto-vuelo', 'Hice match en Tinder en un aeropuerto y nunca le vi en mi vida', '✈️', 'Estaba a tres metros, lo juro.', 'relaciones', 'approved'),
  ('relaciones-cite-cinco-personas-misma-semana', 'Cité a cinco personas distintas en la misma semana', '📆', 'Acabé sin ganas de quedar con nadie.', 'relaciones', 'approved'),
  ('relaciones-dije-frase-no-eres-tu', 'Solté el clásico no eres tú soy yo y me lo creí', '🎬', 'Era él, lo era todo el rato.', 'relaciones', 'approved'),
  ('relaciones-recibi-no-eres-tu', 'Me dijeron no eres tú soy yo y me hundí dos meses', '🪦', NULL, 'relaciones', 'approved'),
  ('relaciones-ruptura-en-aeropuerto', 'Corté con mi pareja en un aeropuerto antes de embarcar', '✈️', 'El vuelo se me hizo eterno.', 'relaciones', 'approved'),
  ('relaciones-ruptura-cumpleanos', 'Me cortaron el día de mi cumpleaños', '🎂', NULL, 'relaciones', 'approved'),
  ('relaciones-ruptura-navidades', 'Cortamos en Nochebuena y comí con mi familia llorando', '🎄', 'Mi madre fingió que no notaba nada.', 'relaciones', 'approved'),
  ('relaciones-llore-supermercado-ruptura', 'Lloré en el pasillo de cereales del Mercadona por una ruptura', '🥣', 'Una señora me dio un abrazo, gracias.', 'relaciones', 'approved'),
  ('relaciones-borre-fotos-pareja-instagram', 'Borré todas las fotos con mi pareja de Instagram en una sola sesión', '🗑️', 'Veintidós fotos, se quedó vacío.', 'relaciones', 'approved'),
  ('relaciones-quemar-cartas-pareja', 'Quemé cartas de mi ex en una bandeja del horno', '🔥', 'Casi se me quema la cocina entera.', 'relaciones', 'approved'),
  ('relaciones-recoger-cosas-piso-ex', 'Tuve que volver a recoger mis cosas al piso de mi ex y fue horror', '📦', 'Lloramos los dos en la puerta.', 'relaciones', 'approved'),
  ('relaciones-pareja-amiga-pelea-amistad', 'Salí con la ex de un amigo y perdimos la amistad', '🤝', 'No mereció la pena, lo confirmo.', 'relaciones', 'approved'),
  ('relaciones-pelea-fiesta-amigo', 'Tuve una pelea con mi pareja en la fiesta de un amigo', '🥳', NULL, 'relaciones', 'approved'),
  ('relaciones-fingir-bien-amigos-pareja', 'Fingí toda la cena que me caían bien los amigos de mi pareja', '🍷', 'Me dolía la cara de sonreír.', 'relaciones', 'approved'),
  ('relaciones-grupo-whatsapp-parejas-cringe', 'Estoy en un grupo de WhatsApp de parejas y me da vergüenza brutal', '👥', NULL, 'relaciones', 'approved'),
  ('relaciones-pelea-pago-cuenta-cena', 'Discutimos quién pagaba la cena delante del camarero diez minutos', '🧾', 'El camarero quería morirse.', 'relaciones', 'approved'),
  ('relaciones-pille-amigo-tinder-pareja', 'Pillé a la pareja de mi amigo en Tinder y no supe qué hacer', '😶', 'Sigue dándome vueltas, joder.', 'relaciones', 'approved'),
  ('relaciones-mensaje-equivocado-mi-padre', 'Mandé un mensaje subido de tono a mi padre por error', '🆘', NULL, 'relaciones', 'approved'),
  ('relaciones-grupo-amigos-analizar-ex', 'Creé un grupo de WhatsApp solo para analizar mensajes de mi ex', '🔬', 'Lo seguimos usando dos años después.', 'relaciones', 'approved'),
  ('relaciones-foto-pareja-fondo-pantalla', 'Puse a mi pareja de fondo de pantalla y cortamos a la semana', '🖼️', NULL, 'relaciones', 'approved'),
  ('relaciones-tatuaje-iniciales-pareja', 'Me tatué las iniciales de mi pareja y luego rompimos', '🖋️', 'Ahora son las de mi gata, listo.', 'relaciones', 'approved'),
  ('relaciones-conoci-pareja-tinder-aniversario', 'Llevo cinco años con la pareja que conocí en Tinder y nadie nos cree', '💞', NULL, 'relaciones', 'approved'),
  ('relaciones-cite-en-funeral', 'Conocí a alguien en un funeral y acabamos saliendo medio año', '🕯️', 'Lo más raro de mi historial.', 'relaciones', 'approved'),
  ('relaciones-cite-en-boda-amigo', 'Lié con la prima de la novia en la boda de mi mejor amigo', '👰', NULL, 'relaciones', 'approved'),
  ('relaciones-baile-lento-no-conozco', 'Bailé un lento con un desconocido en una boda', '💃', 'Su madre me dio el teléfono después.', 'relaciones', 'approved'),
  ('relaciones-pareja-gym-evito', 'Conocí a alguien en el gym y ahora cambio de horario para no verle', '🏋️‍♀️', NULL, 'relaciones', 'approved'),
  ('relaciones-stalkee-spotify-pareja', 'Stalkeé el Spotify de mi pareja para ver qué escucha cuando llora', '🎧', 'Era reggaetón triste, no preguntéis.', 'relaciones', 'approved'),
  ('relaciones-quito-cuenta-cuando-corte', 'Le quité mi cuenta de Netflix al día siguiente de cortar', '✂️', NULL, 'relaciones', 'approved'),
  ('relaciones-perdi-clave-streaming-ex', 'Perdí la clave de Spotify Family que pagaba mi ex', '🎵', 'Me llevó dos meses asumir HBO solo.', 'relaciones', 'approved'),
  ('relaciones-mensaje-dejame-en-paz', 'Le mandé un déjame en paz a mi ex y le respondí dos horas después', '📵', NULL, 'relaciones', 'approved'),
  ('relaciones-grupos-amigos-bandos-ruptura', 'Mi grupo de amigos se dividió en bandos cuando rompí con mi pareja', '⚔️', 'Aún no nos hablamos algunos.', 'relaciones', 'approved'),
  ('relaciones-amiga-empezo-salir-ex', 'Mi amiga empezó a salir con mi ex y la perdí', '😔', NULL, 'relaciones', 'approved'),
  ('relaciones-comente-foto-pareja-amigo', 'Comenté una foto de la pareja de un amigo con un emoji raro', '🥵', 'Mi amigo me mira con sospecha desde entonces.', 'relaciones', 'approved'),
  ('relaciones-bloquear-numero-padres-pareja', 'Bloqueé el número de los padres de mi pareja por error', '📞', 'Tardé tres meses en darme cuenta.', 'relaciones', 'approved'),
  ('relaciones-llamar-pareja-otro-nombre-sexo', 'Llamé a mi pareja por otro nombre en pleno momento íntimo', '🗣️', NULL, 'relaciones', 'approved'),
  ('relaciones-prematuro-decir-te-quiero', 'Pasé del te quiero al ya no en la misma noche', '⌛', 'Y juro que lo decía en serio las dos veces.', 'relaciones', 'approved'),
  ('relaciones-pareja-no-cancion-favorita', 'Mi pareja de tres años no sabe cuál es mi canción favorita', '🎼', NULL, 'relaciones', 'approved'),
  ('relaciones-perfil-tinder-mismo-edificio', 'Hice match con alguien que vivía en mi mismo edificio sin saberlo', '🏢', 'Nos cruzamos en el ascensor al día siguiente.', 'relaciones', 'approved'),
  ('relaciones-deje-toxicos-ex-meses', 'Volví con mi pareja tóxica tres veces seguidas', '🔁', NULL, 'relaciones', 'approved'),
  ('relaciones-amiga-deja-pareja-por-fin', 'Mi amiga me llevaba años diciendo deja a tu pareja y por fin lo hice', '💪', 'Tarde pero llegué, joder.', 'relaciones', 'approved'),
  ('relaciones-tire-copas-cita-pijo', 'Tiré dos copas en una cita en un bar pijo de Madrid', '🍷', NULL, 'relaciones', 'approved'),
  ('relaciones-tartamudear-cita-nervios', 'Tartamudeé tanto en una primera cita que pareció que no hablaba español', '😵‍💫', 'Le dio penita y aceptó la segunda.', 'relaciones', 'approved'),
  ('relaciones-perdi-llaves-casa-pareja', 'Perdí las llaves de la casa de mi pareja la primera vez que dormí allí', '🔑', NULL, 'relaciones', 'approved'),
  ('relaciones-mama-encontro-mi-tinder', 'Mi madre me encontró Tinder abierto en mi tablet', '🤱', 'Tuvimos LA conversación.', 'relaciones', 'approved'),
  ('relaciones-amigos-saben-mas-pareja', 'Mi grupo de amigos sabe más detalles de mi relación que mi pareja', '🫣', NULL, 'relaciones', 'approved'),
  ('relaciones-conte-pareja-detalles-cama', 'Conté detalles íntimos de mi pareja en el grupo del trabajo', '🙊', 'Nunca más, lo prometo.', 'relaciones', 'approved'),
  ('relaciones-llore-cancion-tres-anos', 'Lloré con una canción tres años después de cortar con mi ex', '🎶', NULL, 'relaciones', 'approved'),
  ('relaciones-evito-restaurante-favorito', 'Llevo años sin volver al restaurante favorito de mi ex y yo', '🍝', 'Y era buenísimo, joder.', 'relaciones', 'approved'),
  ('relaciones-borrar-fotos-galeria-800', 'Borré todas las fotos con mi ex y descubrí que tenía 800', '🖼️', NULL, 'relaciones', 'approved'),
  ('relaciones-cuenta-fake-amiga-prestada', 'Mi amiga me presta su cuenta fake para stalkear a mi ex', '🤝', 'Es nuestro acuerdo sagrado.', 'relaciones', 'approved'),
  ('relaciones-pague-tarot-vuelve-ex', 'Pagué tarot online para preguntar si mi ex iba a volver', '🔮', 'Dijo que no y aún seguí preguntando.', 'relaciones', 'approved'),
  ('relaciones-tinder-vacaciones-distancia', 'Bajé Tinder de vacaciones y hice match a 800 km de mi pareja', '🏖️', NULL, 'relaciones', 'approved'),
  ('relaciones-ligue-camarero-vacaciones', 'Ligué con el camarero del hotel toda la semana de vacaciones', '🍹', NULL, 'relaciones', 'approved'),
  ('relaciones-volver-vacaciones-cortar', 'Volví de vacaciones decidida a cortar y aún tardé seis meses', '🧳', 'Cobardía pura.', 'relaciones', 'approved'),
  ('relaciones-pareja-friendzoneo-amigo', 'Mi pareja friendzoneó a mi mejor amigo antes de conocerme', '🤡', 'Las cenas son interesantes ahora.', 'relaciones', 'approved'),
  ('relaciones-camarero-recuerda-citas', 'El camarero del bar de citas se acuerda de mí y de TODAS', '👋', 'Me sonríe con compasión.', 'relaciones', 'approved'),
  ('relaciones-confeti-aniversario-explote', 'Compré confeti para el aniversario y le exploté en la cara a mi pareja', '🎊', NULL, 'relaciones', 'approved'),
  ('relaciones-flores-primera-cita-mal', 'Llevé flores a una primera cita y le dio repelús', '💐', 'Pasaba de mí desde el minuto cero.', 'relaciones', 'approved'),
  ('relaciones-recibi-flores-trabajo-jure', 'Me llegaron flores al trabajo y juré que nunca más', '🌹', NULL, 'relaciones', 'approved'),
  ('relaciones-suegra-controla-comer', 'Mi suegra me dice cuánto debo comer en cada comida familiar', '🍽️', 'Y aún así repito plato a propósito.', 'relaciones', 'approved'),
  ('relaciones-padres-pregunta-cuando-nietos', 'Mis padres llevan dos años preguntándome por los nietos', '👶', NULL, 'relaciones', 'approved'),
  ('relaciones-pareja-toxicos-amigos-aguanta', 'Mi pareja conoció a mis amigos tóxicos y aún así sigue conmigo', '😅', 'Es un milagro.', 'relaciones', 'approved'),
  ('relaciones-conoci-pareja-funeral-abuela', 'Conocí a mi pareja en el funeral de mi abuela', '🥀', NULL, 'relaciones', 'approved'),
  ('relaciones-amigo-cuernos-mentir-pareja', 'Mi amigo me confesó cuernos a su pareja y le seguí mintiendo', '🤐', 'Acabé pillándome yo en el secreto.', 'relaciones', 'approved'),
  ('relaciones-acepte-cita-aburrimiento', 'Acepté una cita por aburrimiento un domingo por la tarde', '😪', NULL, 'relaciones', 'approved'),
  ('relaciones-cita-resaca-domingo', 'Acepté una cita con resaca y me arrepentí en la primera caña', '🍻', 'No volví a aceptar nada un domingo.', 'relaciones', 'approved'),
  ('relaciones-mensaje-buenos-dias-cinco-anos', 'Mando buenos días a mi pareja desde hace cinco años sin fallar uno', '🌅', NULL, 'relaciones', 'approved'),
  ('relaciones-excel-tareas-domesticas', 'Llevamos un Excel de tareas de casa y nos peleamos cada lunes', '📊', 'No funciona pero lo mantenemos.', 'relaciones', 'approved'),
  ('relaciones-celos-videojuegos-pareja', 'Tengo celos del videojuego que juega mi pareja por las noches', '🎮', NULL, 'relaciones', 'approved'),
  ('relaciones-celos-perro-pareja', 'Le tengo celos al perro de mi pareja, en serio', '🐶', 'Le hace más mimos que a mí.', 'relaciones', 'approved'),
  ('relaciones-pareja-mejor-amiga-cumple', 'Mi pareja olvidó mi cumple pero felicitó a su mejor amiga', '🎉', NULL, 'relaciones', 'approved'),
  ('relaciones-perfil-tinder-mascota', 'Mi perfil de Tinder tiene más fotos de mi gato que mías', '🐱', NULL, 'relaciones', 'approved'),
  ('relaciones-foto-pareja-mes-mas', 'Subí una foto en pareja, cortamos, y la dejé un mes más', '📷', 'Por orgullo, qué triste.', 'relaciones', 'approved'),
  ('relaciones-poliamor-prueba-explote', 'Probé el poliamor con mi pareja y exploté a la segunda semana', '💔', NULL, 'relaciones', 'approved'),
  ('relaciones-amigos-coco-ghosting-partidazo', 'Mis amigos me comieron el coco y le hice ghosting al partidazo', '🧠', 'Y resulta que era un partidazo, joder.', 'relaciones', 'approved'),
  ('relaciones-erasmus-cuatro-meses-vuelo', 'Tuve relación de Erasmus que duró cuatro meses y un vuelo', '🛩️', NULL, 'relaciones', 'approved'),
  ('relaciones-pareja-erasmus-no-volvio', 'Mi pareja de Erasmus se fue y nunca volvió a contestar', '✈️', 'Lo entiendo y me jode al mismo tiempo.', 'relaciones', 'approved'),
  ('relaciones-piso-firmado-corte', 'Firmamos un piso juntos y cortamos antes de mudarnos', '🏠', NULL, 'relaciones', 'approved'),
  ('relaciones-vivir-juntos-roto-medio-ano', 'Vivimos juntos seis meses y rompimos en el séptimo', '📦', 'El piso aún huele a su champú.', 'relaciones', 'approved'),
  ('relaciones-recibi-corte-fin-curro', 'Me cortaron por mensaje a las 8 antes de entrar al curro', '⏰', 'Trabajé llorando una jornada entera.', 'relaciones', 'approved'),
  ('relaciones-deja-vu-misma-mesa-camarero', 'Acabé en una primera cita en la misma mesa donde estuve con mi ex', '🪑', 'Misma silla, mismo camarero, todo.', 'relaciones', 'approved'),
  ('relaciones-amigos-preguntan-por-ex', 'Cortamos y mis amigos me preguntaron primero por mi ex', '😤', 'Aún no se lo perdono del todo.', 'relaciones', 'approved'),
  ('relaciones-pareja-no-baila-bodas', 'Mi pareja no baila NUNCA en las bodas y tengo que mendigar', '💃', NULL, 'relaciones', 'approved'),
  ('relaciones-pareja-elige-peli-mala', 'Mi pareja elige siempre la peli en el cine y siempre es mala', '🎥', 'Pero no me oirás quejarme jamás.', 'relaciones', 'approved'),
  ('relaciones-pelea-marca-mantequilla', 'Discutimos por la marca de mantequilla del Mercadona', '🧈', 'Tres mensajes de paz después.', 'relaciones', 'approved'),
  ('relaciones-pelea-cargador-movil', 'Llevamos cinco años peleando por el cargador del móvil', '🔌', NULL, 'relaciones', 'approved'),
  ('relaciones-amigos-comunes-acabamos-ano', 'Conocí a alguien por amigos comunes y acabamos juntos un año', '🤝', 'Las cosas más simples salen bien.', 'relaciones', 'approved'),
  ('relaciones-no-nos-seguimos-instagram', 'Mi pareja y yo llevamos años saliendo y no nos seguimos en Instagram', '🔒', NULL, 'relaciones', 'approved'),
  ('relaciones-piedrecita-ventana-rompi-cristal', 'Tiré piedrecitas a la ventana de mi crush y rompí el cristal', '🪟', NULL, 'relaciones', 'approved'),
  ('relaciones-pase-casa-ex-tres-veces', 'Pasé andando por la casa de mi ex tres veces el día que rompí', '🚶', 'Mis pies tienen vida propia.', 'relaciones', 'approved'),
  ('relaciones-borre-app-conoci-pareja', 'Borré la app justo después de conocer a mi pareja y nunca volví', '🗑️', NULL, 'relaciones', 'approved'),
  ('relaciones-conocido-trabajo-tinder-locos', 'Hice match con alguien del trabajo y nos hicimos los locos', '🤐', 'Fingimos que nunca pasó.', 'relaciones', 'approved'),
  ('relaciones-celos-uno-trabajo-pareja', 'Tengo celos de UNA persona del trabajo de mi pareja desde hace dos años', '🟥', NULL, 'relaciones', 'approved'),
  ('relaciones-pareja-secreto-dos-meses', 'Estuve saliendo con alguien dos meses sin decírselo a mis amigos', '🤫', 'Por supersticiones, no preguntéis.', 'relaciones', 'approved'),
  ('relaciones-cita-perfil-falso-no-existe', 'Quedé en una cita y la persona del perfil ni existía', '🪤', NULL, 'relaciones', 'approved'),
  ('relaciones-cuenta-cada-uno-aniversario', 'Pagamos cada uno nuestra cuenta en un restaurante de aniversario', '🧾', 'No nos hablamos hasta el postre.', 'relaciones', 'approved'),
  ('relaciones-borrador-cortar-dos-meses', 'Mantuve borrador del mensaje de cortar dos meses antes de mandarlo', '📝', NULL, 'relaciones', 'approved'),
  ('relaciones-pense-broma-quiero-cortar', 'Pensé que era una broma cuando me dijo quiero cortar', '🃏', 'No lo era, joder, no lo era.', 'relaciones', 'approved'),
  ('relaciones-vodafone-cancelar-promo', 'Lloré en la tienda de Vodafone cancelando una promo familiar con mi ex', '📱', NULL, 'relaciones', 'approved'),
  ('relaciones-tinder-recomienda-conocidos', 'Tinder me recomienda a mi propio primo y a tres del curro', '🫥', 'Cierro la app cada vez que pasa.', 'relaciones', 'approved'),
  ('relaciones-suegros-borracho-perdido', 'Conocí a mis suegros borracho perdido en su salón', '🍷', 'Aún cuentan la anécdota cada Navidad.', 'relaciones', 'approved'),
  ('relaciones-cita-sin-ducharme-noto', 'Llegué a una primera cita sin ducharme y se notó', '😶‍🌫️', 'Lo lamenté el resto del año.', 'relaciones', 'approved'),
  ('relaciones-mismo-outfit-tres-citas', 'Llevé el mismo outfit a tres primeras citas seguidas', '👔', NULL, 'relaciones', 'approved'),
  ('relaciones-camarero-aplaude-corte', 'Corté en un restaurante y un camarero me aplaudió de fondo', '👏', 'Le di propina extra por el apoyo moral.', 'relaciones', 'approved'),
  ('relaciones-celos-mejor-amiga-pareja', 'Tengo celos de la mejor amiga de mi pareja desde hace siglos', '👯', NULL, 'relaciones', 'approved'),
  ('relaciones-bar-amigos-banderas-rojas', 'Llevé a mi pareja al bar de mis amigos y todos sospecharon', '🚩', 'Tenían razón, joder, tenían razón.', 'relaciones', 'approved'),
  ('relaciones-pareja-no-conoce-mi-trabajo', 'Mi pareja no sabe en qué trabajo después de dos años', '💼', NULL, 'relaciones', 'approved'),
  ('relaciones-conoci-comunion-12-anos', 'Conocí a mi pareja en una comunión cuando tenía 12 años', '⛪', 'Reaparecimos por Tinder a los 28.', 'relaciones', 'approved'),
  ('relaciones-corte-buzon-voz-amigos', 'Corté con mi pareja por buzón de voz porque no me lo cogía', '📞', 'Lo escuchó con dos amigos al lado.', 'relaciones', 'approved')
on conflict (slug) do nothing;
