-- =================================================================
-- Unlocked seed v3 — TRABAJO (200 entries)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- =================================================================

insert into achievements (slug, title, emoji, category, status) values
  ('le-di-a-responder-a-todos-en-un-correo-que-no-debia', 'Le di a "Responder a todos" en un correo que no debía', '📧', 'trabajo', 'approved'),
  ('encendi-la-camara-en-teams-y-estaba-en-pijama', 'Encendí la cámara en Teams y estaba en pijama', '😱', 'trabajo', 'approved'),
  ('me-robaron-el-tuper-del-frigorifico-de-la-oficina', 'Me robaron el túper del frigorífico de la oficina', '🍱', 'trabajo', 'approved'),
  ('hable-pestes-del-jefe-sin-saber-que-tenia-el-micro-abierto', 'Hablé pestes del jefe sin saber que tenía el micro abierto', '🎤', 'trabajo', 'approved'),
  ('compre-uno-de-esos-cacharros-que-mueven-el-raton-solo', 'Compré uno de esos cacharros que mueven el ratón solo', '🖱️', 'trabajo', 'approved'),
  ('llore-en-el-bano-de-la-oficina-entre-reuniones', 'Lloré en el baño de la oficina entre reuniones', '🚽', 'trabajo', 'approved'),
  ('me-dormi-en-una-reunion-de-teams-con-la-camara-puesta', 'Me dormí en una reunión de Teams con la cámara puesta', '😴', 'trabajo', 'approved'),
  ('mande-un-correo-diciendo-adjunto-sin-adjuntar-nada', 'Mandé un correo diciendo "adjunto" sin adjuntar nada', '📎', 'trabajo', 'approved'),
  ('mande-un-audio-cachondo-al-canal-de-la-empresa', 'Mandé un audio cachondo al canal de la empresa', '😅', 'trabajo', 'approved'),
  ('me-ha-salido-el-verde-de-slack-a-las-3-de-la-manana', 'Me ha salido el verde de Slack a las 3 de la mañana', '🟢', 'trabajo', 'approved'),
  ('mi-jefe-lleva-2-anos-llamandome-por-otro-nombre', 'Mi jefe lleva 2 años llamándome por otro nombre', '🙃', 'trabajo', 'approved'),
  ('estuve-dos-semanas-sin-saber-donde-estaba-el-bano', 'Estuve dos semanas sin saber dónde estaba el baño', '🚻', 'trabajo', 'approved'),
  ('mi-primer-dia-y-el-portatil-no-encendia', 'Mi primer día y el portátil no encendía', '💻', 'trabajo', 'approved'),
  ('ensaye-el-discurso-de-dimision-40-veces-frente-al-espejo', 'Ensayé el discurso de dimisión 40 veces frente al espejo', '🪞', 'trabajo', 'approved'),
  ('me-echaron-un-viernes-a-las-1755', 'Me echaron un viernes a las 17:55', '📦', 'trabajo', 'approved'),
  ('puse-excel-avanzado-en-el-cv-y-solo-se-sumar', 'Puse "Excel avanzado" en el CV y solo sé sumar', '📊', 'trabajo', 'approved'),
  ('sali-de-una-entrevista-y-me-eche-a-llorar-en-el-coche', 'Salí de una entrevista y me eché a llorar en el coche', '😢', 'trabajo', 'approved'),
  ('me-ascendieron-pero-sin-subida-de-sueldo', 'Me ascendieron pero sin subida de sueldo', '🎖️', 'trabajo', 'approved'),
  ('he-visto-el-ascenso-de-un-ex-companero-y-se-me-ha-caido-el-a', 'He visto el ascenso de un ex compañero y se me ha caído el alma', '💼', 'trabajo', 'approved'),
  ('el-domingo-a-las-19h-me-entra-una-ansiedad-que-no-veas', 'El domingo a las 19h me entra una ansiedad que no veas', '😰', 'trabajo', 'approved'),
  ('he-hecho-una-reunion-por-zoom-desde-la-playa', 'He hecho una reunión por Zoom desde la playa', '🏖️', 'trabajo', 'approved'),
  ('he-currado-en-remoto-sin-salir-de-la-cama-en-todo-el-dia', 'He currado en remoto sin salir de la cama en todo el día', '🛏️', 'trabajo', 'approved'),
  ('llevo-8-meses-en-remoto-y-nadie-sabe-que-cara-tengo', 'Llevo 8 meses en remoto y nadie sabe qué cara tengo', '🫥', 'trabajo', 'approved'),
  ('tengo-200-pestanas-abiertas-y-no-me-atrevo-a-cerrarlas', 'Tengo 200 pestañas abiertas y no me atrevo a cerrarlas', '🌐', 'trabajo', 'approved'),
  ('vomite-en-la-cena-de-empresa', 'Vomité en la cena de empresa', '🤮', 'trabajo', 'approved'),
  ('dije-lo-que-pensaba-del-jefe-en-la-cena-de-navidad', 'Dije lo que pensaba del jefe en la cena de Navidad', '🍷', 'trabajo', 'approved'),
  ('subi-un-post-a-linkedin-que-aun-me-da-verguenza', 'Subí un post a LinkedIn que aún me da vergüenza', '📱', 'trabajo', 'approved'),
  ('llegue-a-una-reunion-con-cliente-con-una-mancha-de-cafe-enor', 'Llegué a una reunión con cliente con una mancha de café enorme', '☕', 'trabajo', 'approved'),
  ('llegue-en-chandal-el-dia-que-todos-iban-de-traje', 'Llegué en chándal el día que todos iban de traje', '👕', 'trabajo', 'approved'),
  ('calente-pescado-en-el-microondas-comunal', 'Calenté pescado en el microondas comunal', '🐟', 'trabajo', 'approved'),
  ('he-comido-solo-mirando-el-movil-3-anos-seguidos', 'He comido solo mirando el móvil 3 años seguidos', '📱', 'trabajo', 'approved'),
  ('mande-al-becario-a-por-cafes-y-se-equivoco-con-todos', 'Mandé al becario a por cafés y se equivocó con todos', '☕', 'trabajo', 'approved'),
  ('mi-jefe-presento-como-suyo-el-trabajo-que-hice-yo', 'Mi jefe presentó como suyo el trabajo que hice yo', '😤', 'trabajo', 'approved'),
  ('no-me-mencionaron-en-el-correo-del-proyecto-que-lleve-yo', 'No me mencionaron en el correo del proyecto que llevé yo', '📨', 'trabajo', 'approved'),
  ('descubri-que-mi-companero-cobra-600-mas-que-yo', 'Descubrí que mi compañero cobra 600 más que yo', '💸', 'trabajo', 'approved'),
  ('el-primer-dia-de-vuelta-de-vacaciones-me-odio-a-mi-mismo', 'El primer día de vuelta de vacaciones me odio a mí mismo', '🌴', 'trabajo', 'approved'),
  ('rrhh-me-cito-para-hablar-y-casi-me-da-algo', 'RRHH me citó "para hablar" y casi me da algo', '📅', 'trabajo', 'approved'),
  ('puse-en-copia-al-jefe-en-un-correo-donde-le-criticaba', 'Puse en copia al jefe en un correo donde le criticaba', '😬', 'trabajo', 'approved'),
  ('mande-un-correo-super-importante-con-el-asunto-vacio', 'Mandé un correo súper importante con el asunto vacío', '✉️', 'trabajo', 'approved'),
  ('reenvie-sin-querer-una-cadena-de-mensajes-privados-al-client', 'Reenvié sin querer una cadena de mensajes privados al cliente', '📤', 'trabajo', 'approved'),
  ('entre-20-minutos-tarde-a-la-reunion-porque-iba-la-vpn', 'Entré 20 minutos tarde a la reunión "porque iba la VPN"', '⏰', 'trabajo', 'approved'),
  ('me-deje-el-micro-abierto-mientras-meaba-en-una-reunion', 'Me dejé el micro abierto mientras meaba en una reunión', '🚽', 'trabajo', 'approved'),
  ('se-me-cayo-el-fondo-virtual-y-se-vio-mi-cuarto-destrozado', 'Se me cayó el fondo virtual y se vio mi cuarto destrozado', '🛏️', 'trabajo', 'approved'),
  ('mi-perro-se-puso-a-ladrar-a-mitad-de-presentacion', 'Mi perro se puso a ladrar a mitad de presentación', '🐕', 'trabajo', 'approved'),
  ('mi-madre-entro-al-cuarto-en-mitad-de-una-reunion-gritando', 'Mi madre entró al cuarto en mitad de una reunión gritando', '🚪', 'trabajo', 'approved'),
  ('camisa-arriba-pantalon-de-pijama-abajo-en-todas-las-reunione', 'Camisa arriba, pantalón de pijama abajo en todas las reuniones', '👔', 'trabajo', 'approved'),
  ('llevo-2-anos-en-mi-puesto-y-aun-no-se-que-hago-exactamente', 'Llevo 2 años en mi puesto y aún no sé qué hago exactamente', '🤷', 'trabajo', 'approved'),
  ('mi-jefe-me-manda-buscar-cosas-que-el-podria-googlear', 'Mi jefe me manda buscar cosas que él podría googlear', '🔍', 'trabajo', 'approved'),
  ('mi-jefe-me-pregunta-cada-hora-como-va', 'Mi jefe me pregunta cada hora cómo va', '⏱️', 'trabajo', 'approved'),
  ('mi-jefe-me-deja-en-visto-durante-dias', 'Mi jefe me deja en visto durante días', '👁️', 'trabajo', 'approved'),
  ('el-que-se-trae-cocido-madrileno-en-tupper-a-la-oficina', 'El que se trae cocido madrileño en tupper a la oficina', '🥘', 'trabajo', 'approved'),
  ('llevo-4-anos-sentado-al-lado-de-alguien-que-no-me-ha-hablado', 'Llevo 4 años sentado al lado de alguien que no me ha hablado', '🤐', 'trabajo', 'approved'),
  ('dia-1-y-no-sabia-donde-sentarme-me-quede-de-pie-media-hora', 'Día 1 y no sabía dónde sentarme, me quedé de pie media hora', '🪑', 'trabajo', 'approved'),
  ('me-pille-sin-papel-en-el-bano-de-la-oficina', 'Me pillé sin papel en el baño de la oficina', '🧻', 'trabajo', 'approved'),
  ('coincidi-en-el-ascensor-con-el-director-y-no-dije-nada', 'Coincidí en el ascensor con el director y no dije nada', '🛗', 'trabajo', 'approved'),
  ('mande-el-cv-con-el-nombre-de-otra-empresa-en-el-asunto', 'Mandé el CV con el nombre de otra empresa en el asunto', '📄', 'trabajo', 'approved'),
  ('puse-c1-en-ingles-y-solo-se-how-are-you', 'Puse C1 en inglés y solo sé "How are you"', '🇬🇧', 'trabajo', 'approved'),
  ('cai-muy-bien-en-la-entrevista-al-que-no-tenia-voto', 'Caí muy bien en la entrevista al que no tenía voto', '🤝', 'trabajo', 'approved'),
  ('dije-que-mi-mayor-defecto-era-ser-perfeccionista', 'Dije que mi mayor defecto era ser perfeccionista', '😬', 'trabajo', 'approved'),
  ('presente-unas-slides-que-no-habia-abierto-ni-una-vez', 'Presenté unas slides que no había abierto ni una vez', '🎤', 'trabajo', 'approved'),
  ('hice-un-power-point-en-la-pausa-de-cafe-antes-de-presentarlo', 'Hice un Power Point en la pausa de café antes de presentarlo', '📊', 'trabajo', 'approved'),
  ('me-cargaron-con-todo-porque-nunca-digo-que-no', 'Me cargaron con todo porque nunca digo que no', '😩', 'trabajo', 'approved'),
  ('he-trabajado-un-domingo-y-nadie-me-lo-agradecio', 'He trabajado un domingo y nadie me lo agradeció', '📆', 'trabajo', 'approved'),
  ('en-mis-vacaciones-mire-el-correo-cada-hora', 'En mis vacaciones miré el correo cada hora', '📧', 'trabajo', 'approved'),
  ('cancele-el-medico-para-asistir-a-una-reunion-que-se-cancelo', 'Cancelé el médico para asistir a una reunión que se canceló', '🏥', 'trabajo', 'approved'),
  ('he-comido-un-bocadillo-en-la-mesa-mientras-curraba', 'He comido un bocadillo en la mesa mientras curraba', '🥪', 'trabajo', 'approved'),
  ('me-tome-el-decimo-cafe-del-dia-y-me-temblaba-todo', 'Me tomé el décimo café del día y me temblaba todo', '☕', 'trabajo', 'approved'),
  ('dimiti-y-a-los-6-meses-me-llamaron-y-volvi', 'Dimití y a los 6 meses me llamaron y volví', '🔄', 'trabajo', 'approved'),
  ('vaya-justo-cuando-hay-mas-curro-me-dijo-al-pedir-vacaciones', 'Vaya, justo cuando hay más curro me dijo al pedir vacaciones', '😒', 'trabajo', 'approved'),
  ('pase-mi-cumpleanos-currando-hasta-las-21h', 'Pasé mi cumpleaños currando hasta las 21h', '🎂', 'trabajo', 'approved'),
  ('conecte-con-mi-ex-en-linkedin-por-aburrimiento', 'Conecté con mi ex en LinkedIn por aburrimiento', '💔', 'trabajo', 'approved'),
  ('me-rechazaron-con-un-seguiremos-en-contacto-y-nunca-mas', 'Me rechazaron con un seguiremos en contacto y nunca más', '👻', 'trabajo', 'approved'),
  ('aplique-a-100-ofertas-en-una-semana-y-solo-respondieron-2', 'Apliqué a 100 ofertas en una semana y solo respondieron 2', '📋', 'trabajo', 'approved'),
  ('hice-una-prueba-tecnica-de-8-horas-y-luego-me-ghostearon', 'Hice una prueba técnica de 8 horas y luego me ghostearon', '👻', 'trabajo', 'approved'),
  ('me-rechazaron-porque-no-encajaba-con-la-cultura', 'Me rechazaron porque no encajaba con la cultura', '🤷', 'trabajo', 'approved'),
  ('llore-un-domingo-solo-de-pensar-en-el-lunes', 'Lloré un domingo solo de pensar en el lunes', '😭', 'trabajo', 'approved'),
  ('pase-3-noches-sin-dormir-por-una-entrega-que-nadie-miro', 'Pasé 3 noches sin dormir por una entrega que nadie miró', '🌙', 'trabajo', 'approved'),
  ('tengo-un-post-it-con-renuncia-pegado-en-el-cajon', 'Tengo un post-it con RENUNCIA pegado en el cajón', '📝', 'trabajo', 'approved'),
  ('busco-trabajo-desde-el-ordenador-del-trabajo', 'Busco trabajo desde el ordenador del trabajo', '🔎', 'trabajo', 'approved'),
  ('pedi-baja-con-un-dolor-de-espalda-inventado', 'Pedí baja con un dolor de espalda inventado', '🤒', 'trabajo', 'approved'),
  ('he-currado-con-resaca-brutal-sin-que-se-notase-creo', 'He currado con resaca brutal sin que se notase, creo', '🥴', 'trabajo', 'approved'),
  ('llamada-perdida-del-jefe-un-domingo-y-casi-me-da-algo', 'Llamada perdida del jefe un domingo y casi me da algo', '📞', 'trabajo', 'approved'),
  ('no-conteste-al-jefe-un-domingo-y-me-senti-muy-adulto', 'No contesté al jefe un domingo y me sentí muy adulto', '💪', 'trabajo', 'approved'),
  ('estoy-en-un-grupo-de-whatsapp-del-curro-y-nunca-he-hablado', 'Estoy en un grupo de WhatsApp del curro y nunca he hablado', '🤐', 'trabajo', 'approved'),
  ('tengo-silenciado-el-grupo-del-curro-hasta-el-ano-2099', 'Tengo silenciado el grupo del curro hasta el año 2099', '🔕', 'trabajo', 'approved'),
  ('he-programado-correos-a-las-22h-para-que-parezca-que-curro-t', 'He programado correos a las 22h para que parezca que curro tarde', '🕙', 'trabajo', 'approved'),
  ('alttab-compulsivo-cada-vez-que-pasa-el-jefe', 'Alt+tab compulsivo cada vez que pasa el jefe', '🖥️', 'trabajo', 'approved'),
  ('he-pasado-un-dia-entero-sin-hacer-absolutamente-nada', 'He pasado un día entero sin hacer absolutamente nada', '🦥', 'trabajo', 'approved'),
  ('me-pregunto-algo-el-jefe-en-una-reunion-y-dije-lo-primero', 'Me preguntó algo el jefe en una reunión y dije lo primero', '🎲', 'trabajo', 'approved'),
  ('llevo-6-meses-en-una-cadena-de-correos-que-ya-no-entiendo', 'Llevo 6 meses en una cadena de correos que ya no entiendo', '🔗', 'trabajo', 'approved'),
  ('mande-un-correo-al-cliente-con-una-falta-enorme-en-el-asunto', 'Mandé un correo al cliente con una falta enorme en el asunto', '📝', 'trabajo', 'approved'),
  ('empece-un-correo-con-estimado-cuando-ya-nos-tuteabamos', 'Empecé un correo con Estimado cuando ya nos tuteábamos', '✉️', 'trabajo', 'approved'),
  ('mande-un-meme-de-mierda-al-canal-general-por-error', 'Mandé un meme de mierda al canal general por error', '💩', 'trabajo', 'approved'),
  ('hice-screenshot-de-un-mensaje-de-slack-y-lo-pegue-en-el-mism', 'Hice screenshot de un mensaje de Slack y lo pegué en el mismo Slack', '📸', 'trabajo', 'approved'),
  ('le-escribi-te-amo-al-grupo-de-la-empresa-pensando-que-era-mi', 'Le escribí te amo al grupo de la empresa pensando que era mi pareja', '💌', 'trabajo', 'approved'),
  ('llame-mama-a-mi-jefa-por-error', 'Llamé mamá a mi jefa por error', '🤦', 'trabajo', 'approved'),
  ('el-becario-sabe-mas-que-yo-y-lo-disimulo-como-puedo', 'El becario sabe más que yo y lo disimulo como puedo', '🤓', 'trabajo', 'approved'),
  ('llego-un-junior-y-me-hizo-sentir-un-dinosaurio', 'Llegó un junior y me hizo sentir un dinosaurio', '🦖', 'trabajo', 'approved'),
  ('me-pusieron-a-hacer-un-curso-obligatorio-y-solo-le-di-a-sigu', 'Me pusieron a hacer un curso obligatorio y solo le di a siguiente', '📚', 'trabajo', 'approved'),
  ('le-di-a-siguiente-50-veces-y-me-dieron-un-certificado', 'Le di a siguiente 50 veces y me dieron un certificado', '🏅', 'trabajo', 'approved'),
  ('llevo-un-mes-esperando-que-it-responda-mi-ticket', 'Llevo un mes esperando que IT responda mi ticket', '🎫', 'trabajo', 'approved'),
  ('it-me-dijo-apaga-y-enciende-y-funciono-que-rabia', 'IT me dijo apaga y enciende y funcionó, qué rabia', '🔌', 'trabajo', 'approved'),
  ('word-se-cerro-sin-guardar-y-perdi-4-horas-de-curro', 'Word se cerró sin guardar y perdí 4 horas de curro', '😭', 'trabajo', 'approved'),
  ('borre-sin-querer-el-excel-compartido-del-equipo', 'Borré sin querer el Excel compartido del equipo', '😱', 'trabajo', 'approved'),
  ('llevo-3-horas-peleandome-con-un-vlookup-que-no-me-sale', 'Llevo 3 horas peleándome con un VLOOKUP que no me sale', '📊', 'trabajo', 'approved'),
  ('he-googleado-como-hacer-una-suma-en-excel-con-28-anos', 'He googleado cómo hacer una suma en Excel con 28 años', '🔍', 'trabajo', 'approved'),
  ('le-contesto-al-jefe-con-cosas-que-me-genera-chatgpt', 'Le contesto al jefe con cosas que me genera ChatGPT', '🤖', 'trabajo', 'approved'),
  ('la-ia-me-hace-el-trabajo-y-me-sobran-6-horas-al-dia', 'La IA me hace el trabajo y me sobran 6 horas al día', '🤖', 'trabajo', 'approved'),
  ('dije-que-habia-leido-el-pdf-de-80-paginas-sin-abrirlo', 'Dije que había leído el PDF de 80 páginas sin abrirlo', '📄', 'trabajo', 'approved'),
  ('pregunte-algo-en-reunion-y-ya-estaba-contestado', 'Pregunté algo en reunión y ya estaba contestado', '🙋', 'trabajo', 'approved'),
  ('me-he-quedado-mudo-en-una-reunion-y-nadie-ha-notado-mi-prese', 'Me he quedado mudo en una reunión y nadie ha notado mi presencia', '🤐', 'trabajo', 'approved'),
  ('asenti-en-una-reunion-sin-entender-ni-una-palabra', 'Asentí en una reunión sin entender ni una palabra', '🙂', 'trabajo', 'approved'),
  ('me-he-tragado-una-reunion-de-2h-que-era-un-correo', 'Me he tragado una reunión de 2h que era un correo', '😑', 'trabajo', 'approved'),
  ('tuve-una-reunion-para-preparar-otra-reunion', 'Tuve una reunión para preparar otra reunión', '🔁', 'trabajo', 'approved'),
  ('tengo-el-calendario-tan-lleno-que-no-me-da-tiempo-a-comer', 'Tengo el calendario tan lleno que no me da tiempo a comer', '📅', 'trabajo', 'approved'),
  ('acepte-dos-reuniones-a-la-vez-y-me-hice-el-desconectado', 'Acepté dos reuniones a la vez y me hice el desconectado', '📞', 'trabajo', 'approved'),
  ('llevo-todo-el-ano-esperando-el-bonus-y-han-sido-200', 'Llevo todo el año esperando el bonus y han sido 200€', '💸', 'trabajo', 'approved'),
  ('la-subida-no-llego-ni-a-cubrirme-el-ipc', 'La subida no llegó ni a cubrirme el IPC', '📉', 'trabajo', 'approved'),
  ('pedi-aumento-y-me-dijeron-el-ano-que-viene-como-siempre', 'Pedí aumento y me dijeron el año que viene, como siempre', '😅', 'trabajo', 'approved'),
  ('abri-la-nomina-y-se-me-cayo-el-alma-a-los-pies', 'Abrí la nómina y se me cayó el alma a los pies', '💰', 'trabajo', 'approved'),
  ('tengo-dos-curros-remotos-a-la-vez-y-no-se-enteran', 'Tengo dos curros remotos a la vez y no se enteran', '🥷', 'trabajo', 'approved'),
  ('el-cliente-lleva-3-meses-sin-pagarme-la-factura', 'El cliente lleva 3 meses sin pagarme la factura', '🧾', 'trabajo', 'approved'),
  ('pago-la-cuota-de-autonomo-y-me-echo-a-llorar', 'Pago la cuota de autónomo y me echo a llorar', '😭', 'trabajo', 'approved'),
  ('me-equivoque-con-un-modelo-y-hacienda-me-trajo-de-cabeza', 'Me equivoqué con un modelo y Hacienda me trajo de cabeza', '🏛️', 'trabajo', 'approved'),
  ('mi-companero-me-manda-correos-pasivo-agresivos-en-cc-al-jefe', 'Mi compañero me manda correos pasivo-agresivos en CC al jefe', '😡', 'trabajo', 'approved'),
  ('reunion-sin-agenda-y-se-ha-alargado-90-minutos', 'Reunión sin agenda y se ha alargado 90 minutos', '🤯', 'trabajo', 'approved'),
  ('sali-con-cara-de-psicopata-en-la-foto-corporativa-de-la-web', 'Salí con cara de psicópata en la foto corporativa de la web', '📸', 'trabajo', 'approved'),
  ('llevo-5-anos-con-la-misma-foto-de-linkedin-que-no-me-parezco', 'Llevo 5 años con la misma foto de LinkedIn que no me parezco', '🖼️', 'trabajo', 'approved'),
  ('en-una-dinamica-de-grupo-no-abri-la-boca-y-no-me-cogieron', 'En una dinámica de grupo no abrí la boca y no me cogieron', '🤐', 'trabajo', 'approved'),
  ('siempre-me-toca-a-mi-ser-el-que-toma-actas', 'Siempre me toca a mí ser el que toma actas', '✍️', 'trabajo', 'approved'),
  ('organizo-siempre-los-cumples-y-nadie-organiza-el-mio', 'Organizo siempre los cumples y nadie organiza el mío', '🎂', 'trabajo', 'approved'),
  ('me-toco-el-amigo-invisible-y-me-regalaron-un-boli-del-banco', 'Me tocó el amigo invisible y me regalaron un boli del banco', '🎁', 'trabajo', 'approved'),
  ('nos-llevaron-a-paintball-y-acabe-con-moratones', 'Nos llevaron a paintball y acabé con moratones', '🎯', 'trabajo', 'approved'),
  ('tuvimos-que-decir-una-virtud-del-companero-y-mori-por-dentro', 'Tuvimos que decir una virtud del compañero y morí por dentro', '🙃', 'trabajo', 'approved'),
  ('me-hicieron-hacer-un-role-play-en-una-formacion-verguenza-ma', 'Me hicieron hacer un role play en una formación, vergüenza máxima', '🎭', 'trabajo', 'approved'),
  ('me-toco-decir-un-dato-curioso-sobre-mi-en-el-onboarding', 'Me tocó decir un dato curioso sobre mí en el onboarding', '🧊', 'trabajo', 'approved'),
  ('el-cliente-lo-cambio-todo-el-dia-antes-de-la-entrega', 'El cliente lo cambió todo el día antes de la entrega', '🔄', 'trabajo', 'approved'),
  ('el-cliente-me-dijo-tu-sabes-lo-que-necesito', 'El cliente me dijo tú sabes lo que necesito', '🤡', 'trabajo', 'approved'),
  ('cliente-me-llamo-un-sabado-a-las-23h-y-respondi', 'Cliente me llamó un sábado a las 23h y respondí', '☎️', 'trabajo', 'approved'),
  ('presentacion-importante-y-el-proyector-no-funcionaba', 'Presentación importante y el proyector no funcionaba', '📽️', 'trabajo', 'approved'),
  ('se-me-quedo-tildado-el-clicker-en-mitad-de-la-presentacion', 'Se me quedó tildado el clicker en mitad de la presentación', '🖱️', 'trabajo', 'approved'),
  ('nos-mudaron-de-oficina-y-ahora-tardo-1h-mas-al-dia', 'Nos mudaron de oficina y ahora tardo 1h más al día', '🏢', 'trabajo', 'approved'),
  ('nos-hicieron-volver-presencial-5-dias-y-me-quiero-morir', 'Nos hicieron volver presencial 5 días y me quiero morir', '🏬', 'trabajo', 'approved'),
  ('cojo-metro-a-las-8-de-la-manana-y-soy-una-sardina', 'Cojo metro a las 8 de la mañana y soy una sardina', '🚇', 'trabajo', 'approved'),
  ('en-la-oficina-hacen-18-grados-y-curro-con-manta', 'En la oficina hacen 18 grados y curro con manta', '🥶', 'trabajo', 'approved'),
  ('en-invierno-la-oficina-esta-a-14-grados-y-nadie-hace-nada', 'En invierno la oficina está a 14 grados y nadie hace nada', '🥶', 'trabajo', 'approved'),
  ('llevo-6-meses-con-la-silla-rota-y-rrhh-dice-ya-veremos', 'Llevo 6 meses con la silla rota y RRHH dice ya veremos', '🪑', 'trabajo', 'approved'),
  ('mi-alfombrilla-esta-mas-sucia-que-las-escaleras-del-metro', 'Mi alfombrilla está más sucia que las escaleras del metro', '🐀', 'trabajo', 'approved'),
  ('me-dieron-una-sudadera-con-el-logo-y-la-uso-para-dormir', 'Me dieron una sudadera con el logo y la uso para dormir', '👕', 'trabajo', 'approved'),
  ('vi-el-mensaje-del-jefe-y-dije-que-no-me-habia-llegado', 'Vi el mensaje del jefe y dije que no me había llegado', '👻', 'trabajo', 'approved'),
  ('he-ido-al-banco-y-a-hacer-la-compra-entre-reuniones', 'He ido al banco y a hacer la compra entre reuniones', '🛒', 'trabajo', 'approved'),
  ('he-pasado-toda-la-manana-en-la-cocina-hablando-con-companero', 'He pasado toda la mañana en la cocina hablando con compañeros', '☕', 'trabajo', 'approved'),
  ('fingi-una-tos-para-no-ir-a-la-oficina', 'Fingí una tos para no ir a la oficina', '🤧', 'trabajo', 'approved'),
  ('invente-una-cita-medica-para-salir-antes', 'Inventé una cita médica para salir antes', '🏥', 'trabajo', 'approved'),
  ('dije-que-mi-pareja-tenia-una-emergencia-para-salir-antes', 'Dije que mi pareja tenía una emergencia para salir antes', '💔', 'trabajo', 'approved'),
  ('invente-un-funeral-para-coger-un-dia-libre', 'Inventé un funeral para coger un día libre', '⚰️', 'trabajo', 'approved'),
  ('me-quede-en-blanco-delante-de-un-cliente-importante', 'Me quedé en blanco delante de un cliente importante', '🧊', 'trabajo', 'approved'),
  ('llame-al-cliente-por-el-nombre-del-cliente-anterior', 'Llamé al cliente por el nombre del cliente anterior', '😬', 'trabajo', 'approved'),
  ('le-deje-en-visto-al-cliente-3-dias-y-aun-no-he-contestado', 'Le dejé en visto al cliente 3 días y aún no he contestado', '👁️', 'trabajo', 'approved'),
  ('dije-que-iba-al-80-y-aun-no-habia-empezado', 'Dije que iba al 80% y aún no había empezado', '😅', 'trabajo', 'approved'),
  ('empece-el-proyecto-el-dia-antes-de-la-entrega', 'Empecé el proyecto el día antes de la entrega', '⏰', 'trabajo', 'approved'),
  ('he-pedido-prorroga-5-veces-de-la-misma-tarea', 'He pedido prórroga 5 veces de la misma tarea', '🐌', 'trabajo', 'approved'),
  ('para-final-del-dia-significa-que-voy-a-currar-hasta-las-23h', 'Para final del día significa que voy a currar hasta las 23h', '🌙', 'trabajo', 'approved'),
  ('es-algo-rapido-y-me-ha-llevado-3-dias', 'Es algo rápido y me ha llevado 3 días', '🐢', 'trabajo', 'approved'),
  ('me-pidieron-una-cosita-y-acabe-haciendo-todo-el-proyecto', 'Me pidieron una cosita y acabé haciendo todo el proyecto', '🌱', 'trabajo', 'approved'),
  ('estime-un-proyecto-en-1-semana-y-duro-4', 'Estimé un proyecto en 1 semana y duró 4', '📈', 'trabajo', 'approved'),
  ('no-comi-en-todo-el-dia-por-una-entrega-y-nadie-lo-noto', 'No comí en todo el día por una entrega y nadie lo notó', '🥖', 'trabajo', 'approved'),
  ('mi-jefe-me-llamo-en-mitad-de-una-cena-con-amigos-y-respondi', 'Mi jefe me llamó en mitad de una cena con amigos y respondí', '🍽️', 'trabajo', 'approved'),
  ('reviso-el-correo-en-la-cama-antes-de-dormir-todos-los-dias', 'Reviso el correo en la cama antes de dormir todos los días', '🛏️', 'trabajo', 'approved'),
  ('sone-con-mi-jefe-y-me-desperte-llorando', 'Soñé con mi jefe y me desperté llorando', '😱', 'trabajo', 'approved'),
  ('tuve-un-ataque-de-ansiedad-delante-del-ordenador', 'Tuve un ataque de ansiedad delante del ordenador', '😰', 'trabajo', 'approved'),
  ('voy-al-psicologo-solo-por-el-trabajo', 'Voy al psicólogo solo por el trabajo', '🛋️', 'trabajo', 'approved'),
  ('estuve-de-baja-por-ansiedad-2-meses', 'Estuve de baja por ansiedad 2 meses', '🍃', 'trabajo', 'approved'),
  ('voy-al-gym-a-las-22h-porque-es-lo-unico-que-controlo-del-dia', 'Voy al gym a las 22h porque es lo único que controlo del día', '💪', 'trabajo', 'approved'),
  ('me-bebo-una-copa-de-vino-todas-las-noches-despues-de-currar', 'Me bebo una copa de vino todas las noches después de currar', '🍷', 'trabajo', 'approved'),
  ('los-domingos-por-la-tarde-me-deprimo-solo-de-pensar', 'Los domingos por la tarde me deprimo solo de pensar', '🌧️', 'trabajo', 'approved'),
  ('sueno-con-dimitir-todos-los-dias-pero-no-me-atrevo', 'Sueño con dimitir todos los días pero no me atrevo', '🚪', 'trabajo', 'approved'),
  ('reviso-la-cuenta-el-dia-30-cada-hora-a-ver-si-entra-el-sueld', 'Reviso la cuenta el día 30 cada hora a ver si entra el sueldo', '🏦', 'trabajo', 'approved'),
  ('el-sueldo-me-dura-4-dias-y-luego-cuenta-atras', 'El sueldo me dura 4 días y luego cuenta atrás', '💸', 'trabajo', 'approved'),
  ('pedi-un-adelanto-y-casi-me-da-algo-de-la-verguenza', 'Pedí un adelanto y casi me da algo de la vergüenza', '😳', 'trabajo', 'approved'),
  ('la-empresa-quebro-y-me-entere-por-linkedin', 'La empresa quebró y me enteré por LinkedIn', '🚨', 'trabajo', 'approved'),
  ('pase-un-ere-y-aun-tengo-pesadillas', 'Pasé un ERE y aún tengo pesadillas', '😵', 'trabajo', 'approved'),
  ('no-me-renovaron-el-contrato-y-me-entere-el-ultimo-dia', 'No me renovaron el contrato y me enteré el último día', '📝', 'trabajo', 'approved'),
  ('cobre-paro-y-me-daba-verguenza-decirlo', 'Cobré paro y me daba vergüenza decirlo', '🫥', 'trabajo', 'approved'),
  ('tuve-que-volver-a-casa-de-mis-padres-con-30-anos-por-el-curr', 'Tuve que volver a casa de mis padres con 30 años por el curro', '🏠', 'trabajo', 'approved'),
  ('tengo-dos-curros-y-aun-asi-no-llego-a-fin-de-mes', 'Tengo dos curros y aún así no llego a fin de mes', '😩', 'trabajo', 'approved'),
  ('acabe-la-carrera-y-al-final-estoy-de-camarero', 'Acabé la carrera y al final estoy de camarero', '🍽️', 'trabajo', 'approved'),
  ('llevo-2-anos-fingiendo-que-se-usar-la-impresora', 'Llevo 2 años fingiendo que sé usar la impresora', '🖨️', 'trabajo', 'approved'),
  ('atasque-la-impresora-y-me-fui-sin-avisar', 'Atasqué la impresora y me fui sin avisar', '🖨️', 'trabajo', 'approved'),
  ('le-preste-el-cargador-a-alguien-y-nunca-lo-recupere', 'Le presté el cargador a alguien y nunca lo recuperé', '🔌', 'trabajo', 'approved'),
  ('me-roban-la-grapadora-cada-semana', 'Me roban la grapadora cada semana', '📎', 'trabajo', 'approved'),
  ('tuve-que-comprar-regalo-para-el-jefe-y-no-sabia-que', 'Tuve que comprar regalo para el jefe y no sabía qué', '🎁', 'trabajo', 'approved'),
  ('tuve-que-cantar-el-cumpleanos-feliz-en-la-oficina-y-mori', 'Tuve que cantar el cumpleaños feliz en la oficina y morí', '🎂', 'trabajo', 'approved'),
  ('pille-al-jefe-llorando-en-su-despacho-y-no-supe-que-hacer', 'Pillé al jefe llorando en su despacho y no supe qué hacer', '😶', 'trabajo', 'approved'),
  ('vi-a-dos-companeras-gritarse-y-me-hice-el-invisible', 'Vi a dos compañeras gritarse y me hice el invisible', '🙈', 'trabajo', 'approved'),
  ('llevo-un-mes-con-el-rumor-de-que-cierran-y-nadie-dice-nada', 'Llevo un mes con el rumor de que cierran y nadie dice nada', '🤫', 'trabajo', 'approved'),
  ('llevo-anos-buscando-el-curro-perfecto-y-entiendo-que-no-exis', 'Llevo años buscando el curro perfecto y entiendo que no existe', '🦄', 'trabajo', 'approved'),
  ('cuando-preguntan-en-familia-digo-muy-contento-con-el-curro', 'Cuando preguntan en familia digo muy contento con el curro', '🎭', 'trabajo', 'approved'),
  ('me-preguntan-que-tal-el-finde-y-no-tengo-nada-que-contar', 'Me preguntan qué tal el finde y no tengo nada que contar', '🫥', 'trabajo', 'approved'),
  ('soy-siempre-el-ultimo-en-irme-y-nadie-me-lo-agradece', 'Soy siempre el último en irme y nadie me lo agradece', '🌙', 'trabajo', 'approved')
on conflict (slug) do nothing;
