-- =================================================================
-- Unlocked seed v3 — VIAJES (200 entries)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- =================================================================

insert into achievements (slug, title, emoji, category, status) values
  ('me-perdi-el-vuelo-de-conexion-por-mirar-las-tiendas-del-aero', 'Me perdí el vuelo de conexión por mirar las tiendas del aeropuerto', '🛒', 'viajes', 'approved'),
  ('me-pelee-con-mi-pareja-en-el-aeropuerto-antes-de-un-viaje-ro', 'Me peleé con mi pareja en el aeropuerto antes de un viaje romántico', '😤', 'viajes', 'approved'),
  ('me-puse-a-llorar-en-la-puerta-de-embarque-sin-saber-muy-bien', 'Me puse a llorar en la puerta de embarque sin saber muy bien por qué', '😭', 'viajes', 'approved'),
  ('cogi-un-ryanair-a-las-6am-habiendo-dormido-en-el-suelo-de-ba', 'Cogí un Ryanair a las 6am habiendo dormido en el suelo de Barajas', '🛌', 'viajes', 'approved'),
  ('me-quede-en-tierra-por-overbooking-y-me-dieron-un-vale-para', 'Me quedé en tierra por overbooking y me dieron un vale para el McDonalds', '🍔', 'viajes', 'approved'),
  ('me-toco-el-bebe-llorando-al-lado-en-un-vuelo-de-8-horas', 'Me tocó el bebé llorando al lado en un vuelo de 8 horas', '👶', 'viajes', 'approved'),
  ('el-bebe-que-lloraba-en-el-avion-esta-vez-era-el-mio', 'El bebé que lloraba en el avión esta vez era el mío', '🍼', 'viajes', 'approved'),
  ('vomite-en-la-bolsita-del-avion-en-pleno-aterrizaje', 'Vomité en la bolsita del avión en pleno aterrizaje', '🤢', 'viajes', 'approved'),
  ('me-dormi-en-el-avion-y-me-desperte-con-la-gente-mirandome-po', 'Me dormí en el avión y me desperté con la gente mirándome por roncar', '😴', 'viajes', 'approved'),
  ('pite-en-el-control-y-no-sabia-que-tenia-en-el-bolsillo', 'Pité en el control y no sabía qué tenía en el bolsillo', '🚨', 'viajes', 'approved'),
  ('me-hicieron-tirar-las-cremas-en-seguridad-y-eran-las-caras', 'Me hicieron tirar las cremas en seguridad y eran las caras', '🧴', 'viajes', 'approved'),
  ('llegue-al-aeropuerto-y-descubri-que-mi-pasaporte-estaba-cadu', 'Llegué al aeropuerto y descubrí que mi pasaporte estaba caducado', '📕', 'viajes', 'approved'),
  ('llegue-al-aeropuerto-sin-pasaporte-y-volvi-a-por-el-en-taxi', 'Llegué al aeropuerto sin pasaporte y volví a por él en taxi', '🏠', 'viajes', 'approved'),
  ('me-hicieron-pesar-la-mochila-en-ryanair-y-me-cobraron-50-eur', 'Me hicieron pesar la mochila en Ryanair y me cobraron 50 euros', '⚖️', 'viajes', 'approved'),
  ('cambiaron-la-puerta-de-embarque-y-cruce-el-aeropuerto-a-espr', 'Cambiaron la puerta de embarque y crucé el aeropuerto a esprint', '🏃', 'viajes', 'approved'),
  ('me-cancelaron-el-vuelo-y-pase-4-horas-en-la-cola-del-mostrad', 'Me cancelaron el vuelo y pasé 4 horas en la cola del mostrador', '😩', 'viajes', 'approved'),
  ('me-dormi-en-la-puerta-de-embarque-y-me-desperte-solo-en-la-s', 'Me dormí en la puerta de embarque y me desperté solo en la sala', '🛏️', 'viajes', 'approved'),
  ('me-toco-el-asiento-del-medio-entre-dos-senores-que-no-callar', 'Me tocó el asiento del medio entre dos señores que no callaron en 3 horas', '😐', 'viajes', 'approved'),
  ('mi-bolso-no-entro-en-el-medidor-y-lo-meti-a-presion-con-la-r', 'Mi bolso no entró en el medidor y lo metí a presión con la rodilla', '🎒', 'viajes', 'approved'),
  ('me-pillaron-en-aduana-llevando-un-trozo-de-jamon-en-la-malet', 'Me pillaron en aduana llevando un trozo de jamón en la maleta', '🐷', 'viajes', 'approved'),
  ('me-sellaron-mal-el-pasaporte-y-casi-no-entro-al-pais', 'Me sellaron mal el pasaporte y casi no entro al país', '🛂', 'viajes', 'approved'),
  ('me-equivoque-de-cola-en-el-control-de-pasaportes-y-me-toco-1', 'Me equivoqué de cola en el control de pasaportes y me tocó 1 hora extra', '🚶', 'viajes', 'approved'),
  ('perdieron-mi-maleta-y-llego-3-dias-despues-con-todo-dentro-m', 'Perdieron mi maleta y llegó 3 días después con todo dentro mojado', '🧳', 'viajes', 'approved'),
  ('recogi-la-maleta-en-la-cinta-y-estaba-rota-con-todo-asomando', 'Recogí la maleta en la cinta y estaba rota con todo asomando', '💔', 'viajes', 'approved'),
  ('cogi-la-maleta-de-otra-persona-y-me-di-cuenta-en-el-hotel', 'Cogí la maleta de otra persona y me di cuenta en el hotel', '🙃', 'viajes', 'approved'),
  ('perdi-el-ultimo-aerobus-a-las-1am-y-dormi-en-una-silla-del-a', 'Perdí el último Aerobus a las 1am y dormí en una silla del aeropuerto', '🚌', 'viajes', 'approved'),
  ('me-toco-un-blablacar-de-6-horas-con-un-conductor-que-no-abri', 'Me tocó un BlaBlaCar de 6 horas con un conductor que no abrió la boca', '🚗', 'viajes', 'approved'),
  ('sufri-700km-de-reggaeton-al-maximo-en-un-blablacar', 'Sufrí 700km de reggaeton al máximo en un BlaBlaCar', '🔊', 'viajes', 'approved'),
  ('cogi-el-tren-equivocado-y-apareci-en-una-ciudad-que-ni-iba-a', 'Cogí el tren equivocado y aparecí en una ciudad que ni iba a visitar', '🚆', 'viajes', 'approved'),
  ('hice-un-bus-nocturno-con-el-asiento-roto-que-no-se-reclinaba', 'Hice un bus nocturno con el asiento roto que no se reclinaba', '😵', 'viajes', 'approved'),
  ('me-subi-al-metro-en-otro-pais-sin-saber-como-se-compraba-el', 'Me subí al metro en otro país sin saber cómo se compraba el billete', '🎫', 'viajes', 'approved'),
  ('me-pillaron-sin-validar-el-billete-del-metro-y-me-clavaron-6', 'Me pillaron sin validar el billete del metro y me clavaron 60 euros', '💸', 'viajes', 'approved'),
  ('me-dieron-la-vuelta-larga-en-taxi-desde-el-aeropuerto-y-me-c', 'Me dieron la vuelta larga en taxi desde el aeropuerto y me cobraron triple', '🚕', 'viajes', 'approved'),
  ('me-subi-al-uber-equivocado-y-no-me-di-cuenta-en-5-minutos', 'Me subí al Uber equivocado y no me di cuenta en 5 minutos', '🤦', 'viajes', 'approved'),
  ('me-di-cuenta-a-mitad-de-trayecto-que-el-conductor-olia-a-alc', 'Me di cuenta a mitad de trayecto que el conductor olía a alcohol', '🍺', 'viajes', 'approved'),
  ('llegue-a-un-airbnb-que-en-las-fotos-era-espectacular-y-era-u', 'Llegué a un Airbnb que en las fotos era espectacular y era una covacha', '📸', 'viajes', 'approved'),
  ('el-anfitrion-del-airbnb-me-hizo-un-tour-de-1-hora-por-la-cas', 'El anfitrión del Airbnb me hizo un tour de 1 hora por la casa', '🗝️', 'viajes', 'approved'),
  ('reserve-airbnb-entero-y-resulto-que-el-anfitrion-vivia-en-la', 'Reservé Airbnb entero y resultó que el anfitrión vivía en la casa', '👀', 'viajes', 'approved'),
  ('en-el-hostal-el-de-la-litera-de-arriba-roncaba-como-un-oso', 'En el hostal el de la litera de arriba roncaba como un oso', '😤', 'viajes', 'approved'),
  ('a-las-3am-alguien-encendio-la-luz-del-hostal-para-hacer-la-m', 'A las 3am alguien encendió la luz del hostal para hacer la maleta', '🔦', 'viajes', 'approved'),
  ('en-el-hostal-estaban-follando-en-la-litera-de-al-lado-y-yo-f', 'En el hostal estaban follando en la litera de al lado y yo fingiendo dormir', '🙉', 'viajes', 'approved'),
  ('el-hotel-del-centro-no-tenia-agua-caliente-y-yo-banandome-en', 'El hotel del centro no tenía agua caliente y yo bañándome en hielo', '🥶', 'viajes', 'approved'),
  ('encontre-un-bicho-en-la-cama-del-hotel-a-la-1-de-la-manana', 'Encontré un bicho en la cama del hotel a la 1 de la mañana', '🪳', 'viajes', 'approved'),
  ('el-vecino-de-hotel-puso-la-tele-a-las-7am-y-no-habia-forma-d', 'El vecino de hotel puso la tele a las 7am y no había forma de dormir', '📺', 'viajes', 'approved'),
  ('llegue-al-airbnb-a-las-11-de-la-noche-y-no-habia-papel-higie', 'Llegué al Airbnb a las 11 de la noche y no había papel higiénico', '🧻', 'viajes', 'approved'),
  ('llegue-al-alojamiento-tarde-y-la-recepcion-estaba-cerrada-ha', 'Llegué al alojamiento tarde y la recepción estaba cerrada hasta las 8am', '🔒', 'viajes', 'approved'),
  ('no-encontre-la-llave-en-el-buzon-del-airbnb-y-dormi-en-el-po', 'No encontré la llave en el buzón del Airbnb y dormí en el portal', '🔑', 'viajes', 'approved'),
  ('se-me-mojo-la-tienda-entera-la-primera-noche-de-camping', 'Se me mojó la tienda entera la primera noche de camping', '⛺', 'viajes', 'approved'),
  ('acampe-con-un-saco-que-no-daba-calor-y-me-mori-de-frio', 'Acampé con un saco que no daba calor y me morí de frío', '🥶', 'viajes', 'approved'),
  ('me-perdi-en-el-bosque-siguiendo-google-maps-por-un-sendero-q', 'Me perdí en el bosque siguiendo Google Maps por un sendero que no existía', '🌲', 'viajes', 'approved'),
  ('hice-una-ruta-de-15km-con-zapatillas-urbanas-y-se-me-deshici', 'Hice una ruta de 15km con zapatillas urbanas y se me deshicieron', '👟', 'viajes', 'approved'),
  ('sali-a-hacer-una-ruta-sin-agua-y-casi-me-desmayo-a-mitad', 'Salí a hacer una ruta sin agua y casi me desmayo a mitad', '💧', 'viajes', 'approved'),
  ('llegue-a-la-cumbre-y-se-me-apago-el-movil-justo-antes-de-la', 'Llegué a la cumbre y se me apagó el móvil justo antes de la foto', '🔋', 'viajes', 'approved'),
  ('me-torci-el-tobillo-el-primer-dia-y-me-pase-las-vacaciones-c', 'Me torcí el tobillo el primer día y me pasé las vacaciones cojeando', '🩹', 'viajes', 'approved'),
  ('me-queme-tanto-al-sol-que-no-podia-ni-ponerme-la-camiseta', 'Me quemé tanto al sol que no podía ni ponerme la camiseta', '🔥', 'viajes', 'approved'),
  ('volvi-de-la-playa-con-la-marca-de-la-camiseta-de-tirantes-pa', 'Volví de la playa con la marca de la camiseta de tirantes para 3 meses', '🌞', 'viajes', 'approved'),
  ('pise-un-erizo-en-la-playa-y-pase-el-resto-del-viaje-cojeando', 'Pisé un erizo en la playa y pasé el resto del viaje cojeando', '🦔', 'viajes', 'approved'),
  ('me-pico-una-medusa-el-primer-dia-y-se-acabo-el-plan-playa', 'Me picó una medusa el primer día y se acabó el plan playa', '🪼', 'viajes', 'approved'),
  ('pille-una-diarrea-de-viaje-que-no-quiero-ni-recordar', 'Pillé una diarrea de viaje que no quiero ni recordar', '🤮', 'viajes', 'approved'),
  ('comi-marisco-en-un-puesto-cualquiera-y-pase-la-noche-en-el-b', 'Comí marisco en un puesto cualquiera y pasé la noche en el baño', '🦐', 'viajes', 'approved'),
  ('vomite-en-un-tuk-tuk-por-la-mezcla-de-calor-comida-y-conducc', 'Vomité en un tuk-tuk por la mezcla de calor, comida y conducción', '🛺', 'viajes', 'approved'),
  ('pille-un-resfriado-bestia-por-el-aire-acondicionado-del-hote', 'Pillé un resfriado bestia por el aire acondicionado del hotel', '🤧', 'viajes', 'approved'),
  ('con-el-jet-lag-me-hice-una-tortilla-francesa-a-las-3-de-la-m', 'Con el jet lag me hice una tortilla francesa a las 3 de la mañana', '🍳', 'viajes', 'approved'),
  ('pague-100-euros-por-una-cena-que-pensaba-que-costaba-30', 'Pagué 100 euros por una cena que pensaba que costaba 30', '💶', 'viajes', 'approved'),
  ('pedi-en-otro-idioma-y-me-trajeron-algo-que-ni-reconoci', 'Pedí en otro idioma y me trajeron algo que ni reconocí', '🍽️', 'viajes', 'approved'),
  ('cai-en-una-trampa-para-turistas-y-me-cobraron-el-cubierto-a', 'Caí en una trampa para turistas y me cobraron el cubierto a 8 euros', '🪤', 'viajes', 'approved'),
  ('no-sabia-cuanta-propina-dejar-y-deje-el-doble-por-miedo', 'No sabía cuánta propina dejar y dejé el doble por miedo', '💵', 'viajes', 'approved'),
  ('despues-de-5-dias-de-probar-comida-local-termine-en-un-mcdon', 'Después de 5 días de probar comida local terminé en un McDonalds en Roma', '🍟', 'viajes', 'approved'),
  ('cene-un-sandwich-de-gasolinera-de-un-pais-que-no-entendia-na', 'Cené un sandwich de gasolinera de un país que no entendía nada', '⛽', 'viajes', 'approved'),
  ('pase-40-minutos-en-un-supermercado-intentando-comprar-cosas', 'Pasé 40 minutos en un supermercado intentando comprar cosas básicas', '🛒', 'viajes', 'approved'),
  ('pedi-un-cafe-con-leche-en-italia-a-las-5-de-la-tarde-y-me-mi', 'Pedí un café con leche en Italia a las 5 de la tarde y me miraron mal', '☕', 'viajes', 'approved'),
  ('me-cobraron-12-libras-por-una-pinta-en-londres-y-disimule', 'Me cobraron 12 libras por una pinta en Londres y disimulé', '🍺', 'viajes', 'approved'),
  ('pedi-una-cerveza-en-baviera-y-me-trajeron-un-litro-que-no-me', 'Pedí una cerveza en Baviera y me trajeron un litro que no me acabé', '🍺', 'viajes', 'approved'),
  ('dije-que-aguantaba-el-picante-en-mexico-y-casi-lloro', 'Dije que aguantaba el picante en México y casi lloro', '🌶️', 'viajes', 'approved'),
  ('en-el-sushi-de-cinta-no-entendi-los-precios-y-pague-80-euros', 'En el sushi de cinta no entendí los precios y pagué 80 euros', '🍣', 'viajes', 'approved'),
  ('pedi-el-vino-de-la-carta-sin-mirar-precio-y-costaba-200-euro', 'Pedí el vino de la carta sin mirar precio y costaba 200 euros', '🍷', 'viajes', 'approved'),
  ('llegue-al-destino-sin-haber-cambiado-moneda-y-todo-cerrado', 'Llegué al destino sin haber cambiado moneda y todo cerrado', '💱', 'viajes', 'approved'),
  ('el-cajero-del-extranjero-me-clavo-15-euros-de-comision-por-s', 'El cajero del extranjero me clavó 15 euros de comisión por sacar 100', '🏧', 'viajes', 'approved'),
  ('mi-banco-bloqueo-la-tarjeta-por-sospechar-fraude-justo-en-el', 'Mi banco bloqueó la tarjeta por sospechar fraude justo en el viaje', '🚫', 'viajes', 'approved'),
  ('la-revolut-no-me-funciono-y-tuve-que-pagar-todo-con-la-tarje', 'La Revolut no me funcionó y tuve que pagar todo con la tarjeta cara', '💳', 'viajes', 'approved'),
  ('perdi-la-cartera-en-la-estacion-de-tren-y-no-volvi-a-verla', 'Perdí la cartera en la estación de tren y no volví a verla', '👛', 'viajes', 'approved'),
  ('me-robaron-la-mochila-en-un-bar-mientras-pedia-la-segunda-ce', 'Me robaron la mochila en un bar mientras pedía la segunda cerveza', '🎒', 'viajes', 'approved'),
  ('un-carterista-me-saco-el-movil-del-bolsillo-en-el-metro-y-no', 'Un carterista me sacó el móvil del bolsillo en el metro y no me enteré', '🥷', 'viajes', 'approved'),
  ('me-hicieron-la-estafa-de-la-pulsera-en-plena-calle-y-pague', 'Me hicieron la estafa de la pulsera en plena calle y pagué', '🤡', 'viajes', 'approved'),
  ('pague-100-euros-por-una-bici-de-alquiler-que-se-rompio-en-el', 'Pagué 100 euros por una bici de alquiler que se rompió en el primer km', '🚲', 'viajes', 'approved'),
  ('mi-primera-noche-de-erasmus-la-pase-llorando-en-la-habitacio', 'Mi primera noche de Erasmus la pasé llorando en la habitación', '😢', 'viajes', 'approved'),
  ('fui-a-mi-primera-clase-de-erasmus-y-no-entendi-ni-una-palabr', 'Fui a mi primera clase de Erasmus y no entendí ni una palabra', '📚', 'viajes', 'approved'),
  ('en-el-erasmus-me-alimente-de-pasta-con-tomate-durante-un-mes', 'En el Erasmus me alimenté de pasta con tomate durante un mes entero', '🍝', 'viajes', 'approved'),
  ('en-mi-piso-de-erasmus-la-cocina-parecia-una-zona-de-guerra-c', 'En mi piso de Erasmus la cocina parecía una zona de guerra cada mañana', '🍳', 'viajes', 'approved'),
  ('sali-de-fiesta-en-erasmus-perdi-las-llaves-y-dormi-en-el-rel', 'Salí de fiesta en Erasmus, perdí las llaves y dormí en el rellano', '🔐', 'viajes', 'approved'),
  ('llore-en-el-vuelo-de-vuelta-del-erasmus-mirando-por-la-venta', 'Lloré en el vuelo de vuelta del Erasmus mirando por la ventanilla', '🛫', 'viajes', 'approved'),
  ('hice-un-mes-de-mochilero-con-tres-camisetas-que-ya-no-olian', 'Hice un mes de mochilero con tres camisetas que ya no olían a nada bueno', '👕', 'viajes', 'approved'),
  ('me-lie-con-alguien-en-el-hostal-y-al-dia-siguiente-cogimos-v', 'Me lié con alguien en el hostal y al día siguiente cogimos vuelos distintos', '💋', 'viajes', 'approved'),
  ('conoci-a-alguien-en-un-hostal-y-seguimos-hablando-4-anos-des', 'Conocí a alguien en un hostal y seguimos hablando 4 años después', '🌍', 'viajes', 'approved'),
  ('cene-yo-solo-en-la-cocina-del-hostel-mientras-todos-hacian-p', 'Cené yo solo en la cocina del hostel mientras todos hacían planes', '🍽️', 'viajes', 'approved'),
  ('mi-pareja-y-yo-nos-peleamos-por-el-mapa-y-dejamos-de-hablarn', 'Mi pareja y yo nos peleamos por el mapa y dejamos de hablarnos un día entero', '🗺️', 'viajes', 'approved'),
  ('en-vacaciones-queriamos-cosas-opuestas-y-acabamos-cada-uno-p', 'En vacaciones queríamos cosas opuestas y acabamos cada uno por su lado', '↔️', 'viajes', 'approved'),
  ('viaje-con-un-grupo-de-amigos-y-descubri-que-uno-era-un-plomo', 'Viajé con un grupo de amigos y descubrí que uno era un plomo brutal', '😬', 'viajes', 'approved'),
  ('en-el-grupo-el-tipico-que-llevaba-un-excel-con-todos-los-gas', 'En el grupo el típico que llevaba un Excel con todos los gastos en céntimos', '📊', 'viajes', 'approved'),
  ('en-el-viaje-con-amigos-siempre-habia-uno-que-se-escapaba-a-p', 'En el viaje con amigos siempre había uno que se escapaba a pagar', '🙄', 'viajes', 'approved'),
  ('me-coincidio-mi-cumpleanos-en-pleno-viaje-y-nadie-se-acordo', 'Me coincidió mi cumpleaños en pleno viaje y nadie se acordó hasta la noche', '🎂', 'viajes', 'approved'),
  ('en-la-luna-de-miel-nos-peleamos-al-bajar-del-avion', 'En la luna de miel nos peleamos al bajar del avión', '💔', 'viajes', 'approved'),
  ('viaje-con-mis-padres-a-roma-y-acabe-buscando-excusas-para-es', 'Viajé con mis padres a Roma y acabé buscando excusas para escapar 2 horas', '👴', 'viajes', 'approved'),
  ('el-domingo-de-vuelta-del-viaje-pense-en-pedir-la-baja-para-n', 'El domingo de vuelta del viaje pensé en pedir la baja para no ir el lunes', '😩', 'viajes', 'approved'),
  ('se-cancelo-el-vuelo-y-dormi-8h-en-una-silla-rigida-del-aerop', 'Se canceló el vuelo y dormí 8h en una silla rígida del aeropuerto', '🪑', 'viajes', 'approved'),
  ('pase-la-noche-en-el-aeropuerto-cenando-un-burger-king-a-las', 'Pasé la noche en el aeropuerto cenando un Burger King a las 4am', '🍔', 'viajes', 'approved'),
  ('llegue-2-horas-antes-al-aeropuerto-y-aun-asi-casi-pierdo-el', 'Llegué 2 horas antes al aeropuerto y aún así casi pierdo el vuelo', '⏰', 'viajes', 'approved'),
  ('imprimi-la-tarjeta-de-embarque-en-blanco-y-negro-y-casi-me-h', 'Imprimí la tarjeta de embarque en blanco y negro y casi me hacen pagar', '🖨️', 'viajes', 'approved'),
  ('pague-extra-por-ventanilla-y-me-pase-el-vuelo-durmiendo-con', 'Pagué extra por ventanilla y me pasé el vuelo durmiendo con la persiana bajada', '🪟', 'viajes', 'approved'),
  ('cogi-pasillo-y-la-del-medio-se-mareo-toda-encima', 'Cogí pasillo y la del medio se mareó toda encima', '🤢', 'viajes', 'approved'),
  ('pedi-el-menu-especial-del-avion-y-vino-una-cosa-imposible-de', 'Pedí el menú especial del avión y vino una cosa imposible de comer', '🥗', 'viajes', 'approved'),
  ('la-azafata-me-tiro-el-cafe-encima-y-me-pase-el-vuelo-con-el', 'La azafata me tiró el café encima y me pasé el vuelo con el pantalón mojado', '☕', 'viajes', 'approved'),
  ('estuve-en-cola-del-bano-del-avion-30-minutos-y-me-lo-aguante', 'Estuve en cola del baño del avión 30 minutos y me lo aguanté hasta aterrizar', '🚽', 'viajes', 'approved'),
  ('me-puse-a-llorar-viendo-una-peli-en-el-avion-rodeado-de-gent', 'Me puse a llorar viendo una peli en el avión rodeado de gente', '🎬', 'viajes', 'approved'),
  ('aplaudi-cuando-aterrizo-el-avion-y-me-di-cuenta-tarde-de-la', 'Aplaudí cuando aterrizó el avión y me di cuenta tarde de la vergüenza', '👏', 'viajes', 'approved'),
  ('en-una-turbulencia-fuerte-me-puse-a-rezar-sin-ser-creyente', 'En una turbulencia fuerte me puse a rezar sin ser creyente', '🙏', 'viajes', 'approved'),
  ('me-maree-tanto-en-un-coche-que-tuve-que-parar-y-vomitar-en-l', 'Me mareé tanto en un coche que tuve que parar y vomitar en la cuneta', '🚗', 'viajes', 'approved'),
  ('me-maree-en-un-autobus-de-montana-y-vomite-unas-lentejas-que', 'Me mareé en un autobús de montaña y vomité unas lentejas que ni recordaba', '🚌', 'viajes', 'approved'),
  ('en-el-ferry-me-pase-toda-la-travesia-tumbado-en-el-suelo-del', 'En el ferry me pasé toda la travesía tumbado en el suelo del baño', '⛴️', 'viajes', 'approved'),
  ('conduje-en-un-pais-con-el-volante-al-otro-lado-y-casi-me-mat', 'Conduje en un país con el volante al otro lado y casi me mato en una rotonda', '🚗', 'viajes', 'approved'),
  ('eche-gasolina-equivocada-en-un-coche-de-alquiler-en-otro-pai', 'Eché gasolina equivocada en un coche de alquiler en otro país', '⛽', 'viajes', 'approved'),
  ('me-llego-una-multa-del-coche-de-alquiler-4-meses-despues-por', 'Me llegó una multa del coche de alquiler 4 meses después por correo', '📮', 'viajes', 'approved'),
  ('me-llevaron-el-coche-con-la-grua-en-el-primer-dia-de-vacacio', 'Me llevaron el coche con la grúa en el primer día de vacaciones', '🚧', 'viajes', 'approved'),
  ('me-cobraron-80-euros-de-parking-porque-no-entendi-como-se-pa', 'Me cobraron 80 euros de parking porque no entendí cómo se pagaba', '🅿️', 'viajes', 'approved'),
  ('llegue-al-monumento-estrella-del-viaje-y-estaba-cerrado-los', 'Llegué al monumento estrella del viaje y estaba cerrado los lunes', '🏛️', 'viajes', 'approved'),
  ('hice-3-horas-de-cola-para-un-museo-que-me-aburrio-en-20-minu', 'Hice 3 horas de cola para un museo que me aburrió en 20 minutos', '🖼️', 'viajes', 'approved'),
  ('pase-una-tarde-entera-en-un-museo-y-solo-recuerdo-el-dolor-d', 'Pasé una tarde entera en un museo y solo recuerdo el dolor de pies', '🦶', 'viajes', 'approved'),
  ('hice-la-foto-sujetando-la-torre-de-pisa-y-me-sigo-arrepintie', 'Hice la foto sujetando la Torre de Pisa y me sigo arrepintiendo', '📸', 'viajes', 'approved'),
  ('pague-entrada-para-una-atraccion-solo-para-el-insta-y-no-ent', 'Pagué entrada para una atracción solo para el Insta y no entré', '📲', 'viajes', 'approved'),
  ('pase-2-horas-montando-una-foto-de-instagram-en-la-playa', 'Pasé 2 horas montando una foto de Instagram en la playa', '📷', 'viajes', 'approved'),
  ('volvi-con-50-imanes-de-la-nevera-y-no-se-ni-donde-compre-la', 'Volví con 50 imanes de la nevera y no sé ni dónde compré la mitad', '🧲', 'viajes', 'approved'),
  ('me-compre-un-souvenir-de-ceramica-y-llego-a-casa-hecho-anico', 'Me compré un souvenir de cerámica y llegó a casa hecho añicos', '🏺', 'viajes', 'approved'),
  ('me-compre-la-camiseta-de-i-love-ny-y-no-me-la-he-puesto-nunc', 'Me compré la camiseta de I Love NY y no me la he puesto nunca', '👕', 'viajes', 'approved'),
  ('volvi-con-una-bolsa-de-souvenirs-tan-pesada-que-me-cobraron', 'Volví con una bolsa de souvenirs tan pesada que me cobraron en la cabina', '🛍️', 'viajes', 'approved'),
  ('me-duche-en-el-hostel-y-me-senti-mas-solo-que-en-toda-mi-vid', 'Me duché en el hostel y me sentí más solo que en toda mi vida', '🚿', 'viajes', 'approved'),
  ('pedi-mesa-para-uno-en-un-restaurante-caro-y-disfrute-como-nu', 'Pedí mesa para uno en un restaurante caro y disfruté como nunca', '🍴', 'viajes', 'approved'),
  ('hice-match-en-tinder-en-otro-pais-y-quede-con-un-desconocido', 'Hice match en Tinder en otro país y quedé con un desconocido', '💕', 'viajes', 'approved'),
  ('quede-con-alguien-de-grindr-en-otro-pais-y-luego-me-arrepent', 'Quedé con alguien de Grindr en otro país y luego me arrepentí en su salón', '🚪', 'viajes', 'approved'),
  ('me-lie-con-alguien-en-el-viaje-y-al-volver-llore-en-el-avion', 'Me lié con alguien en el viaje y al volver lloré en el avión 3 horas', '✈️', 'viajes', 'approved'),
  ('llame-a-mis-padres-llorando-desde-otro-pais-por-una-tonteria', 'Llamé a mis padres llorando desde otro país por una tontería', '📞', 'viajes', 'approved'),
  ('me-llego-una-factura-de-100-euros-de-roaming-sin-haber-hecho', 'Me llegó una factura de 100 euros de roaming sin haber hecho nada', '📡', 'viajes', 'approved'),
  ('el-hotel-decia-wifi-gratis-y-era-de-pago-a-15-euros-la-hora', 'El hotel decía wifi gratis y era de pago a 15 euros la hora', '📶', 'viajes', 'approved'),
  ('intente-ver-netflix-en-otro-pais-y-la-vpn-no-me-funcionaba', 'Intenté ver Netflix en otro país y la VPN no me funcionaba', '🎥', 'viajes', 'approved'),
  ('llegue-al-hotel-con-el-cargador-equivocado-para-el-tipo-de-e', 'Llegué al hotel con el cargador equivocado para el tipo de enchufe', '🔌', 'viajes', 'approved'),
  ('compre-un-adaptador-de-enchufe-en-el-aeropuerto-a-25-euros', 'Compré un adaptador de enchufe en el aeropuerto a 25 euros', '🔌', 'viajes', 'approved'),
  ('se-me-apago-el-movil-en-una-ciudad-nueva-y-no-sabia-volver-a', 'Se me apagó el móvil en una ciudad nueva y no sabía volver al hotel', '🔋', 'viajes', 'approved'),
  ('en-un-taxi-no-me-acordaba-del-nombre-del-hotel-y-di-vueltas', 'En un taxi no me acordaba del nombre del hotel y di vueltas 30 minutos', '🤔', 'viajes', 'approved'),
  ('use-un-mapa-de-papel-del-hostal-y-aun-asi-me-perdi', 'Usé un mapa de papel del hostal y aún así me perdí', '🗺️', 'viajes', 'approved'),
  ('pague-un-tour-por-adelantado-y-al-final-no-me-apetecia-y-no', 'Pagué un tour por adelantado y al final no me apetecía y no fui', '😴', 'viajes', 'approved'),
  ('cai-en-un-tour-donde-el-guia-no-callo-en-3-horas-y-solo-quer', 'Caí en un tour donde el guía no calló en 3 horas y solo quería sentarme', '🎙️', 'viajes', 'approved'),
  ('en-un-free-tour-me-senti-obligado-a-poner-20-euros-de-propin', 'En un free tour me sentí obligado a poner 20 euros de propina', '💵', 'viajes', 'approved'),
  ('me-quede-dormido-en-un-bus-turistico-y-pase-dos-veces-por-lo', 'Me quedé dormido en un bus turístico y pasé dos veces por lo mismo', '🚌', 'viajes', 'approved'),
  ('se-me-cayeron-las-gafas-haciendo-snorkel-y-se-las-llevo-el-m', 'Se me cayeron las gafas haciendo snorkel y se las llevó el mar', '👓', 'viajes', 'approved'),
  ('en-mi-primera-inmersion-de-buceo-me-dio-un-ataque-de-panico', 'En mi primera inmersión de buceo me dio un ataque de pánico', '🤿', 'viajes', 'approved'),
  ('cogi-un-paddle-surf-y-me-aleje-tanto-que-no-sabia-como-volve', 'Cogí un paddle surf y me alejé tanto que no sabía cómo volver', '🏄', 'viajes', 'approved'),
  ('volque-el-kayak-con-el-movil-dentro-y-se-acabo-el-viaje', 'Volqué el kayak con el móvil dentro y se acabó el viaje', '🛶', 'viajes', 'approved'),
  ('me-monte-en-un-camello-en-marruecos-y-me-cai-en-el-primer-pa', 'Me monté en un camello en Marruecos y me caí en el primer paso', '🐪', 'viajes', 'approved'),
  ('monte-un-elefante-en-tailandia-y-volvi-con-cargo-de-concienc', 'Monté un elefante en Tailandia y volví con cargo de conciencia', '🐘', 'viajes', 'approved'),
  ('un-perro-me-mordio-en-otro-pais-y-tuve-que-ir-a-urgencias-po', 'Un perro me mordió en otro país y tuve que ir a urgencias por la rabia', '🐕', 'viajes', 'approved'),
  ('volvi-del-viaje-con-las-piernas-hechas-un-campo-de-mosquitos', 'Volví del viaje con las piernas hechas un campo de mosquitos', '🦟', 'viajes', 'approved'),
  ('pille-piojos-en-un-hostal-y-me-entere-2-semanas-despues', 'Pillé piojos en un hostal y me enteré 2 semanas después', '🐛', 'viajes', 'approved'),
  ('pille-sarna-en-un-hostal-del-sudeste-asiatico-y-no-se-lo-des', 'Pillé sarna en un hostal del Sudeste Asiático y no se lo deseo a nadie', '🦠', 'viajes', 'approved'),
  ('me-dieron-a-probar-orina-de-vaca-en-india-por-una-broma-de-u', 'Me dieron a probar orina de vaca en India por una broma de un local', '🐄', 'viajes', 'approved'),
  ('use-un-bano-comun-en-asia-y-aun-sueno-con-esa-experiencia', 'Usé un baño común en Asia y aún sueño con esa experiencia', '🚽', 'viajes', 'approved'),
  ('me-quede-sin-papel-en-un-bano-publico-de-un-pais-que-solo-us', 'Me quedé sin papel en un baño público de un país que solo usaba manguera', '🚿', 'viajes', 'approved'),
  ('pase-la-noche-en-el-desierto-y-la-arena-se-me-metio-hasta-en', 'Pasé la noche en el desierto y la arena se me metió hasta en los ojos', '🏜️', 'viajes', 'approved'),
  ('pense-que-el-desierto-era-calor-y-casi-me-congelo-por-la-noc', 'Pensé que el desierto era calor y casi me congelo por la noche', '🥶', 'viajes', 'approved'),
  ('llegue-a-cusco-y-casi-me-desmayo-por-el-mal-de-altura', 'Llegué a Cusco y casi me desmayo por el mal de altura', '⛰️', 'viajes', 'approved'),
  ('llegue-a-machu-picchu-y-estaba-todo-cubierto-de-niebla', 'Llegué a Machu Picchu y estaba todo cubierto de niebla', '🌫️', 'viajes', 'approved'),
  ('vi-las-cataratas-y-volvi-completamente-empapado-al-hotel', 'Vi las cataratas y volví completamente empapado al hotel', '💦', 'viajes', 'approved'),
  ('pague-un-viaje-a-laponia-para-ver-auroras-y-no-vi-ni-una', 'Pagué un viaje a Laponia para ver auroras y no vi ni una', '🌌', 'viajes', 'approved'),
  ('vi-la-torre-eiffel-en-persona-y-me-decepciono-un-poco', 'Vi la Torre Eiffel en persona y me decepcionó un poco', '🗼', 'viajes', 'approved'),
  ('llegue-a-la-mona-lisa-y-era-mucho-mas-pequena-de-lo-que-pens', 'Llegué a la Mona Lisa y era mucho más pequeña de lo que pensaba', '🖼️', 'viajes', 'approved'),
  ('me-robaron-en-las-ramblas-siendo-turista-en-mi-propio-pais', 'Me robaron en Las Ramblas siendo turista en mi propio país', '🥴', 'viajes', 'approved'),
  ('me-perdi-en-san-isidro-siendo-de-madrid-de-toda-la-vida', 'Me perdí en San Isidro siendo de Madrid de toda la vida', '🥲', 'viajes', 'approved'),
  ('perdi-al-grupo-en-ibiza-a-las-4am-y-apareci-al-dia-siguiente', 'Perdí al grupo en Ibiza a las 4am y aparecí al día siguiente', '🌅', 'viajes', 'approved'),
  ('acabe-en-una-calle-de-benidorm-cantando-con-guiris-borrachos', 'Acabé en una calle de Benidorm cantando con guiris borrachos', '🎤', 'viajes', 'approved'),
  ('fui-a-un-festival-de-verano-y-llovio-los-4-dias-seguidos', 'Fui a un festival de verano y llovió los 4 días seguidos', '🌧️', 'viajes', 'approved'),
  ('perdi-la-cartera-en-un-festival-y-aun-asi-segui-bailando', 'Perdí la cartera en un festival y aún así seguí bailando', '🪩', 'viajes', 'approved'),
  ('se-me-volo-la-tienda-del-camping-en-un-festival-con-mis-cosa', 'Se me voló la tienda del camping en un festival con mis cosas dentro', '🌬️', 'viajes', 'approved'),
  ('volvi-de-un-festival-con-0-fotos-de-mi-y-200-de-mis-amigos', 'Volví de un festival con 0 fotos de mí y 200 de mis amigos', '📸', 'viajes', 'approved'),
  ('hice-un-finde-en-otra-ciudad-sin-dormir-practicamente-nada', 'Hice un finde en otra ciudad sin dormir prácticamente nada', '👁️', 'viajes', 'approved'),
  ('hice-un-puente-improvisado-y-volvi-con-la-mochila-mas-pesada', 'Hice un puente improvisado y volví con la mochila más pesada que cuando me fui', '🎒', 'viajes', 'approved'),
  ('en-vacaciones-conteste-un-mail-del-curro-y-me-arrepenti-inme', 'En vacaciones contesté un mail del curro y me arrepentí inmediatamente', '💻', 'viajes', 'approved'),
  ('mi-jefe-me-llamo-estando-en-la-playa-y-disimule-que-estaba-e', 'Mi jefe me llamó estando en la playa y disimulé que estaba en casa', '🤳', 'viajes', 'approved'),
  ('hice-la-tipica-foto-de-pies-en-la-piscina-y-luego-me-dio-ver', 'Hice la típica foto de pies en la piscina y luego me dio vergüenza subirla', '🦶', 'viajes', 'approved'),
  ('me-lie-con-alguien-en-un-resort-todo-incluido-y-nunca-lo-con', 'Me lié con alguien en un resort todo incluido y nunca lo conté en casa', '🏖️', 'viajes', 'approved'),
  ('aproveche-tanto-la-pulsera-del-todo-incluido-que-vomite-el-s', 'Aproveché tanto la pulsera del todo incluido que vomité el segundo día', '🍹', 'viajes', 'approved'),
  ('hice-un-crucero-y-los-3-primeros-dias-estuve-mareado-en-la-c', 'Hice un crucero y los 3 primeros días estuve mareado en la cama', '🚢', 'viajes', 'approved'),
  ('en-un-crucero-comi-en-el-buffet-4-veces-al-dia-y-subi-5-kilo', 'En un crucero comí en el buffet 4 veces al día y subí 5 kilos', '🍽️', 'viajes', 'approved'),
  ('hice-un-tren-nocturno-y-mi-compartimiento-olia-a-pies-durant', 'Hice un tren nocturno y mi compartimiento olía a pies durante 10 horas', '🚆', 'viajes', 'approved'),
  ('me-hice-un-interrail-y-llegue-a-estar-2-dias-sin-ducharme', 'Me hice un Interrail y llegué a estar 2 días sin ducharme', '🛁', 'viajes', 'approved'),
  ('en-un-interrail-perdi-un-tren-por-30-segundos-y-se-me-fue-to', 'En un Interrail perdí un tren por 30 segundos y se me fue toda la ruta', '⏳', 'viajes', 'approved'),
  ('en-el-aeropuerto-cambiamos-de-destino-y-compramos-otro-vuelo', 'En el aeropuerto cambiamos de destino y compramos otro vuelo en el momento', '🎲', 'viajes', 'approved'),
  ('en-roma-comi-pasta-los-3-dias-y-aun-asi-pedi-mas-para-llevar', 'En Roma comí pasta los 3 días y aún así pedí más para llevar', '🍝', 'viajes', 'approved'),
  ('me-perdi-en-shibuya-siguiendo-un-mapa-que-no-entendia', 'Me perdí en Shibuya siguiendo un mapa que no entendía', '🗾', 'viajes', 'approved'),
  ('en-seul-entre-a-un-norebang-yo-solo-y-cante-como-si-nadie-me', 'En Seúl entré a un norebang yo solo y canté como si nadie me oyera', '🎤', 'viajes', 'approved'),
  ('comi-pizza-sentado-en-el-bordillo-en-nueva-york-como-en-las', 'Comí pizza sentado en el bordillo en Nueva York como en las películas', '🍕', 'viajes', 'approved'),
  ('llore-delante-del-castillo-de-disney-teniendo-28-anos', 'Lloré delante del castillo de Disney teniendo 28 años', '🏰', 'viajes', 'approved'),
  ('hice-3-horas-de-cola-para-una-atraccion-que-duro-90-segundos', 'Hice 3 horas de cola para una atracción que duró 90 segundos', '🎢', 'viajes', 'approved'),
  ('me-pase-en-un-coffeeshop-de-amsterdam-y-dormi-en-un-parque', 'Me pasé en un coffeeshop de Amsterdam y dormí en un parque', '🌳', 'viajes', 'approved'),
  ('en-praga-me-bebi-mas-litros-de-cerveza-que-de-agua-en-una-se', 'En Praga me bebí más litros de cerveza que de agua en una semana', '🍺', 'viajes', 'approved'),
  ('fui-a-los-banos-termales-de-budapest-con-la-peor-resaca-de-m', 'Fui a los baños termales de Budapest con la peor resaca de mi vida', '♨️', 'viajes', 'approved'),
  ('estuve-12-horas-seguidas-en-una-discoteca-de-berlin-y-casi-m', 'Estuve 12 horas seguidas en una discoteca de Berlín y casi muero al sol', '🪩', 'viajes', 'approved'),
  ('hice-80-fotos-del-tranvia-de-lisboa-y-subi-solo-una', 'Hice 80 fotos del tranvía de Lisboa y subí solo una', '🚋', 'viajes', 'approved'),
  ('un-camarero-parisino-me-trato-fatal-y-me-fui-sin-tomarme-la', 'Un camarero parisino me trató fatal y me fui sin tomarme la copa', '🥖', 'viajes', 'approved'),
  ('volvi-de-australia-con-tal-jet-lag-que-tarde-semanas-en-recu', 'Volví de Australia con tal jet lag que tardé semanas en recuperarme', '🦘', 'viajes', 'approved'),
  ('volvi-de-bali-diciendo-que-era-otra-persona-y-dure-3-dias-as', 'Volví de Bali diciendo que era otra persona y duré 3 días así', '🧘', 'viajes', 'approved'),
  ('hice-4-amigos-intimos-en-tailandia-y-no-he-vuelto-a-hablar-c', 'Hice 4 amigos íntimos en Tailandia y no he vuelto a hablar con ninguno', '🤝', 'viajes', 'approved'),
  ('alquile-una-moto-en-vietnam-y-me-cai-antes-de-salir-del-park', 'Alquilé una moto en Vietnam y me caí antes de salir del parking', '🛵', 'viajes', 'approved'),
  ('el-grupo-de-whatsapp-del-viaje-murio-a-los-3-dias-de-volver', 'El grupo de WhatsApp del viaje murió a los 3 días de volver', '💀', 'viajes', 'approved'),
  ('tengo-fotos-de-un-viaje-en-el-movil-sin-organizar-desde-hace', 'Tengo fotos de un viaje en el móvil sin organizar desde hace 2 años', '🖼️', 'viajes', 'approved'),
  ('compre-un-album-de-fotos-para-imprimir-el-viaje-y-sigue-vaci', 'Compré un álbum de fotos para imprimir el viaje y sigue vacío', '📔', 'viajes', 'approved'),
  ('volvi-de-viaje-y-al-dia-siguiente-fui-a-currar-como-si-no-hu', 'Volví de viaje y al día siguiente fui a currar como si no hubiera pasado nada', '🥲', 'viajes', 'approved'),
  ('el-domingo-de-vuelta-del-viaje-me-sente-en-el-sofa-a-mirar-l', 'El domingo de vuelta del viaje me senté en el sofá a mirar la pared', '🛋️', 'viajes', 'approved'),
  ('volvi-obsesionado-con-un-restaurante-y-se-lo-conte-a-todo-el', 'Volví obsesionado con un restaurante y se lo conté a todo el que se dejó', '🍽️', 'viajes', 'approved'),
  ('compre-una-guia-de-viaje-en-papel-y-no-la-abri-ni-una-vez', 'Compré una guía de viaje en papel y no la abrí ni una vez', '📖', 'viajes', 'approved'),
  ('segui-una-guia-vieja-y-los-sitios-ya-no-existian', 'Seguí una guía vieja y los sitios ya no existían', '🕰️', 'viajes', 'approved'),
  ('hice-una-lista-de-cosas-para-ver-y-no-marque-ni-la-mitad', 'Hice una lista de cosas para ver y no marqué ni la mitad', '📝', 'viajes', 'approved'),
  ('no-prepare-el-viaje-y-acabe-pagando-todo-el-doble-por-improv', 'No preparé el viaje y acabé pagando todo el doble por improvisar', '🎲', 'viajes', 'approved'),
  ('volvi-del-viaje-pesando-2-kilos-mas-y-me-costo-un-mes-quitar', 'Volví del viaje pesando 2 kilos más y me costó un mes quitármelos', '⚖️', 'viajes', 'approved'),
  ('jure-no-hacer-fotos-turisticas-y-volvi-con-700-identicas-a-l', 'Juré no hacer fotos turísticas y volví con 700 idénticas a las del resto', '📸', 'viajes', 'approved'),
  ('pague-un-tour-de-grupo-y-me-pase-el-dia-evitando-hablar-con', 'Pagué un tour de grupo y me pasé el día evitando hablar con nadie', '🤐', 'viajes', 'approved'),
  ('hice-un-presupuesto-y-al-final-me-gaste-el-doble', 'Hice un presupuesto y al final me gasté el doble', '💸', 'viajes', 'approved'),
  ('me-pase-un-mes-pagando-con-tarjeta-de-credito-un-viaje-de-fi', 'Me pasé un mes pagando con tarjeta de crédito un viaje de fin de semana', '💳', 'viajes', 'approved'),
  ('volvi-del-viaje-con-la-cuenta-a-cero-y-aun-quedaban-10-dias', 'Volví del viaje con la cuenta a cero y aún quedaban 10 días de mes', '💀', 'viajes', 'approved'),
  ('jure-no-viajar-mas-en-6-meses-y-a-los-3-ya-estaba-mirando-vu', 'Juré no viajar más en 6 meses y a los 3 ya estaba mirando vuelos', '✈️', 'viajes', 'approved'),
  ('pase-un-domingo-entero-buscando-vuelos-a-cualquier-sitio-sin', 'Pasé un domingo entero buscando vuelos a cualquier sitio sin un plan', '🌍', 'viajes', 'approved'),
  ('vi-un-error-fare-brutal-y-dude-tanto-que-cuando-fui-a-compra', 'Vi un error fare brutal y dudé tanto que cuando fui a comprarlo se acabó', '😩', 'viajes', 'approved'),
  ('mis-amigos-cancelaron-a-ultima-hora-y-me-fui-de-viaje-yo-sol', 'Mis amigos cancelaron a última hora y me fui de viaje yo solo', '🧍', 'viajes', 'approved'),
  ('hice-mi-primer-viaje-solo-y-me-cambio-un-poco-la-cabeza', 'Hice mi primer viaje solo y me cambió un poco la cabeza', '🌅', 'viajes', 'approved'),
  ('cene-yo-solo-en-la-barra-de-un-bar-leyendo-un-libro-como-un', 'Cené yo solo en la barra de un bar leyendo un libro como un señor', '📖', 'viajes', 'approved'),
  ('en-un-viaje-le-mande-un-mensaje-borracho-a-mi-ex-y-al-dia-si', 'En un viaje le mandé un mensaje borracho a mi ex y al día siguiente quería morir', '📱', 'viajes', 'approved'),
  ('me-pase-el-viaje-montando-stories-de-instagram-en-vez-de-mir', 'Me pasé el viaje montando stories de Instagram en vez de mirar las cosas', '📲', 'viajes', 'approved'),
  ('llovio-toda-la-semana-del-viaje-y-me-lo-pase-en-el-hotel-vie', 'Llovió toda la semana del viaje y me lo pasé en el hotel viendo Netflix', '🌧️', 'viajes', 'approved'),
  ('en-un-viaje-de-trabajo-me-escape-del-grupo-de-la-empresa-par', 'En un viaje de trabajo me escapé del grupo de la empresa para tomarme algo solo', '🍻', 'viajes', 'approved'),
  ('tuve-que-ir-con-corbata-a-una-presentacion-en-otro-pais-y-ol', 'Tuve que ir con corbata a una presentación en otro país y olvidé la camisa', '👔', 'viajes', 'approved'),
  ('hice-una-videollamada-de-trabajo-desde-un-hotel-en-pijama-y', 'Hice una videollamada de trabajo desde un hotel en pijama y bañador', '📹', 'viajes', 'approved'),
  ('vole-en-una-compania-low-cost-y-el-asiento-estaba-literalmen', 'Volé en una compañía low cost y el asiento estaba literalmente roto', '🛫', 'viajes', 'approved'),
  ('espere-45-minutos-en-la-cinta-de-equipajes-y-mi-maleta-no-sa', 'Esperé 45 minutos en la cinta de equipajes y mi maleta no salió', '🧳', 'viajes', 'approved'),
  ('hice-2-horas-de-cola-para-recoger-el-coche-de-alquiler', 'Hice 2 horas de cola para recoger el coche de alquiler', '⏳', 'viajes', 'approved'),
  ('me-cobraron-una-raya-del-coche-de-alquiler-que-ya-estaba-ant', 'Me cobraron una raya del coche de alquiler que ya estaba antes', '🖍️', 'viajes', 'approved'),
  ('el-deposito-del-coche-de-alquiler-tardo-3-meses-en-volver-a', 'El depósito del coche de alquiler tardó 3 meses en volver a mi cuenta', '⏱️', 'viajes', 'approved'),
  ('mi-dni-estaba-caducado-y-descubrirlo-en-el-aeropuerto-fue-un', 'Mi DNI estaba caducado y descubrirlo en el aeropuerto fue una odisea', '🪪', 'viajes', 'approved'),
  ('firme-un-papel-para-un-deporte-extremo-sin-entender-nada-y-l', 'Firmé un papel para un deporte extremo sin entender nada y lo hice igual', '🪂', 'viajes', 'approved'),
  ('salte-en-paracaidas-y-grite-y-llore-en-el-cielo-como-un-nino', 'Salté en paracaídas y grité y lloré en el cielo como un niño', '😱', 'viajes', 'approved'),
  ('me-hice-100-km-para-hacer-puenting-y-al-borde-no-pude-saltar', 'Me hice 100 km para hacer puenting y al borde no pude saltar', '🪢', 'viajes', 'approved'),
  ('mi-primer-dia-de-esqui-acabe-bajando-una-pista-azul-de-culo', 'Mi primer día de esquí acabé bajando una pista azul de culo', '🎿', 'viajes', 'approved'),
  ('me-fracture-la-muneca-el-primer-dia-probando-snowboard', 'Me fracturé la muñeca el primer día probando snowboard', '🏂', 'viajes', 'approved'),
  ('me-cai-del-trineo-de-perros-en-laponia-y-me-arrastraron-5-me', 'Me caí del trineo de perros en Laponia y me arrastraron 5 metros', '🐕', 'viajes', 'approved'),
  ('pague-por-dormir-en-un-iglu-y-no-pegue-ojo-del-frio-que-pase', 'Pagué por dormir en un iglú y no pegué ojo del frío que pasé', '🥶', 'viajes', 'approved'),
  ('reserve-un-glamping-y-era-un-camping-normal-con-luces-de-fer', 'Reservé un glamping y era un camping normal con luces de feria', '🏕️', 'viajes', 'approved'),
  ('dormi-en-una-yurta-y-un-bicho-paso-por-encima-de-mi-cara', 'Dormí en una yurta y un bicho pasó por encima de mi cara', '🐛', 'viajes', 'approved'),
  ('hice-3-vuelos-seguidos-y-llegue-al-destino-sin-saber-que-dia', 'Hice 3 vuelos seguidos y llegué al destino sin saber qué día era', '🌍', 'viajes', 'approved'),
  ('llegue-a-mi-destino-el-dia-de-mi-cumpleanos-y-nadie-me-felic', 'Llegué a mi destino el día de mi cumpleaños y nadie me felicitó', '🎂', 'viajes', 'approved'),
  ('perdi-un-vuelo-por-una-resaca-brutal-del-dia-anterior', 'Perdí un vuelo por una resaca brutal del día anterior', '🥴', 'viajes', 'approved'),
  ('corri-por-el-aeropuerto-como-en-las-peliculas-y-aun-asi-lleg', 'Corrí por el aeropuerto como en las películas y aún así llegué tarde', '🏃', 'viajes', 'approved'),
  ('en-un-viaje-me-toco-el-mismo-asiento-de-ida-y-de-vuelta-sin', 'En un viaje me tocó el mismo asiento de ida y de vuelta sin elegirlo', '🪑', 'viajes', 'approved'),
  ('conoci-a-mi-pareja-actual-en-un-viaje-y-todavia-no-me-lo-cre', 'Conocí a mi pareja actual en un viaje y todavía no me lo creo', '❤️', 'viajes', 'approved'),
  ('a-los-30-descubri-que-ya-no-me-gusta-volar-y-me-da-ansiedad', 'A los 30 descubrí que ya no me gusta volar y me da ansiedad', '😰', 'viajes', 'approved'),
  ('tome-pastillas-para-dormir-en-un-vuelo-y-desperte-con-la-car', 'Tomé pastillas para dormir en un vuelo y desperté con la cara babeada', '💊', 'viajes', 'approved'),
  ('compre-billetes-baratos-saltandome-el-primer-tramo-y-casi-me', 'Compré billetes baratos saltándome el primer tramo y casi me cancelan el resto', '🎟️', 'viajes', 'approved'),
  ('perdi-la-llave-del-hotel-y-tuve-que-despertar-a-recepcion-a', 'Perdí la llave del hotel y tuve que despertar a recepción a las 5am', '🔑', 'viajes', 'approved'),
  ('me-quede-encerrado-en-el-bano-de-un-restaurante-en-otro-idio', 'Me quedé encerrado en el baño de un restaurante en otro idioma', '🚪', 'viajes', 'approved'),
  ('perdi-el-ultimo-bus-al-aeropuerto-y-un-taxi-me-cobro-el-viaj', 'Perdí el último bus al aeropuerto y un taxi me cobró el viaje a precio de oro', '🚖', 'viajes', 'approved'),
  ('me-llego-un-email-importante-de-la-aerolinea-a-spam-y-casi-p', 'Me llegó un email importante de la aerolínea a spam y casi pierdo el vuelo', '📧', 'viajes', 'approved'),
  ('reserve-un-hotel-sin-aire-acondicionado-en-pleno-julio-en-el', 'Reservé un hotel sin aire acondicionado en pleno julio en el sur', '🥵', 'viajes', 'approved'),
  ('no-entendi-lo-que-pedia-la-camarera-y-le-dije-que-si-a-todo', 'No entendí lo que pedía la camarera y le dije que sí a todo', '🙃', 'viajes', 'approved'),
  ('pague-15-euros-por-una-ducha-en-el-aeropuerto-y-volvi-a-sent', 'Pagué 15 euros por una ducha en el aeropuerto y volví a sentirme persona', '🚿', 'viajes', 'approved'),
  ('pague-una-sala-vip-del-aeropuerto-y-se-acabo-la-comida-5-min', 'Pagué una sala VIP del aeropuerto y se acabó la comida 5 minutos antes', '😩', 'viajes', 'approved'),
  ('compre-una-sim-en-otro-pais-y-no-me-funciono-hasta-el-ultimo', 'Compré una SIM en otro país y no me funcionó hasta el último día', '📶', 'viajes', 'approved'),
  ('me-cambiaron-el-vuelo-cancelado-a-otra-aerolinea-peor-y-sin', 'Me cambiaron el vuelo cancelado a otra aerolínea peor y sin avisar', '🤬', 'viajes', 'approved'),
  ('llegue-corriendo-a-la-puerta-de-embarque-cuando-estaban-cerr', 'Llegué corriendo a la puerta de embarque cuando estaban cerrando', '😮‍💨', 'viajes', 'approved'),
  ('no-imprimi-el-billete-de-ryanair-y-me-cobraron-60-euros-en-m', 'No imprimí el billete de Ryanair y me cobraron 60 euros en mostrador', '🧾', 'viajes', 'approved'),
  ('estando-de-viaje-pense-en-serio-si-volvia-o-me-quedaba-a-viv', 'Estando de viaje pensé en serio si volvía o me quedaba a vivir allí', '🌅', 'viajes', 'approved')
on conflict (slug) do nothing;
