-- =================================================================
-- Unlocked seed v3 — VIAJES (200 entries)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- =================================================================

insert into achievements (slug, title, emoji, description, category, status) values
  ('viajes-perdi-vuelo-mirando-tiendas', 'Me perdí el vuelo de conexión por mirar las tiendas del aeropuerto', '🛒', NULL, 'viajes', 'approved'),
  ('viajes-pelea-pareja-aeropuerto', 'Me peleé con mi pareja en el aeropuerto antes de un viaje romántico', '😤', 'Empezamos fuerte.', 'viajes', 'approved'),
  ('viajes-llorar-puerta-embarque', 'Me puse a llorar en la puerta de embarque sin saber muy bien por qué', '😭', NULL, 'viajes', 'approved'),
  ('viajes-ryanair-3am-barajas', 'Cogí un Ryanair a las 6am habiendo dormido en el suelo de Barajas', '🛌', 'El asiento 17C ya nunca sera lo mismo.', 'viajes', 'approved'),
  ('viajes-overbooking-me-quede-en-tierra', 'Me quedé en tierra por overbooking y me dieron un vale para el McDonalds', '🍔', NULL, 'viajes', 'approved'),
  ('viajes-bebe-llorando-al-lado', 'Me tocó el bebé llorando al lado en un vuelo de 8 horas', '👶', NULL, 'viajes', 'approved'),
  ('viajes-bebe-mio-llorando', 'El bebé que lloraba en el avión esta vez era el mío', '🍼', 'Una mirada de 200 personas.', 'viajes', 'approved'),
  ('viajes-vomite-mareo-avion', 'Vomité en la bolsita del avión en pleno aterrizaje', '🤢', NULL, 'viajes', 'approved'),
  ('viajes-ronquidos-vuelo', 'Me dormí en el avión y me desperté con la gente mirándome por roncar', '😴', NULL, 'viajes', 'approved'),
  ('viajes-control-seguridad-pite', 'Pité en el control y no sabía qué tenía en el bolsillo', '🚨', NULL, 'viajes', 'approved'),
  ('viajes-cremas-100ml-tiradas', 'Me hicieron tirar las cremas en seguridad y eran las caras', '🧴', 'Adios 60 euros de serum.', 'viajes', 'approved'),
  ('viajes-pasaporte-caducado-aeropuerto', 'Llegué al aeropuerto y descubrí que mi pasaporte estaba caducado', '📕', NULL, 'viajes', 'approved'),
  ('viajes-pasaporte-en-casa', 'Llegué al aeropuerto sin pasaporte y volví a por él en taxi', '🏠', NULL, 'viajes', 'approved'),
  ('viajes-equipaje-de-mano-overweight', 'Me hicieron pesar la mochila en Ryanair y me cobraron 50 euros', '⚖️', NULL, 'viajes', 'approved'),
  ('viajes-puerta-cambiada-corriendo', 'Cambiaron la puerta de embarque y crucé el aeropuerto a esprint', '🏃', NULL, 'viajes', 'approved'),
  ('viajes-cancelado-cola-mostrador', 'Me cancelaron el vuelo y pasé 4 horas en la cola del mostrador', '😩', NULL, 'viajes', 'approved'),
  ('viajes-dormi-puerta-embarque', 'Me dormí en la puerta de embarque y me desperté solo en la sala', '🛏️', 'Casi pierdo el vuelo por una siesta.', 'viajes', 'approved'),
  ('viajes-asiento-medio-tres-horas', 'Me tocó el asiento del medio entre dos señores que no callaron en 3 horas', '😐', NULL, 'viajes', 'approved'),
  ('viajes-no-cabe-bolso-medidor', 'Mi bolso no entró en el medidor y lo metí a presión con la rodilla', '🎒', NULL, 'viajes', 'approved'),
  ('viajes-pip-aduana-cinta', 'Me pillaron en aduana llevando un trozo de jamón en la maleta', '🐷', 'Lo declaré pero igual lo confiscaron.', 'viajes', 'approved'),
  ('viajes-sello-mal-pasaporte', 'Me sellaron mal el pasaporte y casi no entro al país', '🛂', NULL, 'viajes', 'approved'),
  ('viajes-cola-no-eu-1h', 'Me equivoqué de cola en el control de pasaportes y me tocó 1 hora extra', '🚶', NULL, 'viajes', 'approved'),
  ('viajes-perdi-maleta-llego-3-dias', 'Perdieron mi maleta y llegó 3 días después con todo dentro mojado', '🧳', NULL, 'viajes', 'approved'),
  ('viajes-maleta-rota-cinta', 'Recogí la maleta en la cinta y estaba rota con todo asomando', '💔', NULL, 'viajes', 'approved'),
  ('viajes-recogi-maleta-equivocada', 'Cogí la maleta de otra persona y me di cuenta en el hotel', '🙃', NULL, 'viajes', 'approved'),
  ('viajes-aerobus-ultima-hora', 'Perdí el último Aerobus a las 1am y dormí en una silla del aeropuerto', '🚌', NULL, 'viajes', 'approved'),
  ('viajes-blablacar-conductor-callado', 'Me tocó un BlaBlaCar de 6 horas con un conductor que no abrió la boca', '🚗', NULL, 'viajes', 'approved'),
  ('viajes-blablacar-musica-reggaeton', 'Sufrí 700km de reggaeton al máximo en un BlaBlaCar', '🔊', NULL, 'viajes', 'approved'),
  ('viajes-tren-equivocado-andalucia', 'Cogí el tren equivocado y aparecí en una ciudad que ni iba a visitar', '🚆', NULL, 'viajes', 'approved'),
  ('viajes-bus-noche-asiento-roto', 'Hice un bus nocturno con el asiento roto que no se reclinaba', '😵', '12 horas sentado a 90 grados.', 'viajes', 'approved'),
  ('viajes-metro-extranjero-sin-billete', 'Me subí al metro en otro país sin saber cómo se compraba el billete', '🎫', NULL, 'viajes', 'approved'),
  ('viajes-multa-metro-sin-validar', 'Me pillaron sin validar el billete del metro y me clavaron 60 euros', '💸', NULL, 'viajes', 'approved'),
  ('viajes-taxi-largo-aeropuerto', 'Me dieron la vuelta larga en taxi desde el aeropuerto y me cobraron triple', '🚕', NULL, 'viajes', 'approved'),
  ('viajes-uber-equivocado-subi', 'Me subí al Uber equivocado y no me di cuenta en 5 minutos', '🤦', NULL, 'viajes', 'approved'),
  ('viajes-pinche-conductor-borracho', 'Me di cuenta a mitad de trayecto que el conductor olía a alcohol', '🍺', NULL, 'viajes', 'approved'),
  ('viajes-airbnb-fotos-mentian', 'Llegué a un Airbnb que en las fotos era espectacular y era una covacha', '📸', NULL, 'viajes', 'approved'),
  ('viajes-airbnb-anfitrion-tour', 'El anfitrión del Airbnb me hizo un tour de 1 hora por la casa', '🗝️', 'Solo quería ducharme.', 'viajes', 'approved'),
  ('viajes-airbnb-anfitrion-vivia', 'Reservé Airbnb entero y resultó que el anfitrión vivía en la casa', '👀', NULL, 'viajes', 'approved'),
  ('viajes-hostal-ronquidos-litera', 'En el hostal el de la litera de arriba roncaba como un oso', '😤', NULL, 'viajes', 'approved'),
  ('viajes-hostal-luz-movil-3am', 'A las 3am alguien encendió la luz del hostal para hacer la maleta', '🔦', NULL, 'viajes', 'approved'),
  ('viajes-hostal-folla-litera-arriba', 'En el hostal estaban follando en la litera de al lado y yo fingiendo dormir', '🙉', NULL, 'viajes', 'approved'),
  ('viajes-hotel-sin-agua-caliente', 'El hotel del centro no tenía agua caliente y yo bañándome en hielo', '🥶', NULL, 'viajes', 'approved'),
  ('viajes-hotel-bicho-cama', 'Encontré un bicho en la cama del hotel a la 1 de la mañana', '🪳', NULL, 'viajes', 'approved'),
  ('viajes-vecino-hotel-tv-fuerte', 'El vecino de hotel puso la tele a las 7am y no había forma de dormir', '📺', NULL, 'viajes', 'approved'),
  ('viajes-airbnb-sin-papel-higienico', 'Llegué al Airbnb a las 11 de la noche y no había papel higiénico', '🧻', NULL, 'viajes', 'approved'),
  ('viajes-checkin-tarde-cerrado', 'Llegué al alojamiento tarde y la recepción estaba cerrada hasta las 8am', '🔒', NULL, 'viajes', 'approved'),
  ('viajes-no-encontre-llave-buzon', 'No encontré la llave en el buzón del Airbnb y dormí en el portal', '🔑', NULL, 'viajes', 'approved'),
  ('viajes-camping-tienda-mojada', 'Se me mojó la tienda entera la primera noche de camping', '⛺', NULL, 'viajes', 'approved'),
  ('viajes-camping-saco-roto', 'Acampé con un saco que no daba calor y me morí de frío', '🥶', NULL, 'viajes', 'approved'),
  ('viajes-perdi-bosque-google-maps', 'Me perdí en el bosque siguiendo Google Maps por un sendero que no existía', '🌲', NULL, 'viajes', 'approved'),
  ('viajes-hike-zapatillas-malas', 'Hice una ruta de 15km con zapatillas urbanas y se me deshicieron', '👟', NULL, 'viajes', 'approved'),
  ('viajes-hike-sin-agua', 'Salí a hacer una ruta sin agua y casi me desmayo a mitad', '💧', NULL, 'viajes', 'approved'),
  ('viajes-foto-cumbre-bateria', 'Llegué a la cumbre y se me apagó el móvil justo antes de la foto', '🔋', NULL, 'viajes', 'approved'),
  ('viajes-tobillo-roto-vacaciones', 'Me torcí el tobillo el primer día y me pasé las vacaciones cojeando', '🩹', NULL, 'viajes', 'approved'),
  ('viajes-quemadura-sol-bestia', 'Me quemé tanto al sol que no podía ni ponerme la camiseta', '🔥', 'Rojo langosta.', 'viajes', 'approved'),
  ('viajes-quemadura-marca-camiseta', 'Volví de la playa con la marca de la camiseta de tirantes para 3 meses', '🌞', NULL, 'viajes', 'approved'),
  ('viajes-piedra-pie-playa', 'Pisé un erizo en la playa y pasé el resto del viaje cojeando', '🦔', NULL, 'viajes', 'approved'),
  ('viajes-medusa-picadura', 'Me picó una medusa el primer día y se acabó el plan playa', '🪼', NULL, 'viajes', 'approved'),
  ('viajes-diarrea-no-hablar', 'Pillé una diarrea de viaje que no quiero ni recordar', '🤮', NULL, 'viajes', 'approved'),
  ('viajes-intoxicacion-marisco', 'Comí marisco en un puesto cualquiera y pasé la noche en el baño', '🦐', NULL, 'viajes', 'approved'),
  ('viajes-vomite-tuk-tuk', 'Vomité en un tuk-tuk por la mezcla de calor, comida y conducción', '🛺', NULL, 'viajes', 'approved'),
  ('viajes-resfriado-aire-acondicionado', 'Pillé un resfriado bestia por el aire acondicionado del hotel', '🤧', NULL, 'viajes', 'approved'),
  ('viajes-jet-lag-3am-tortilla', 'Con el jet lag me hice una tortilla francesa a las 3 de la mañana', '🍳', NULL, 'viajes', 'approved'),
  ('viajes-pague-100-cena-equivoque', 'Pagué 100 euros por una cena que pensaba que costaba 30', '💶', 'No leí bien la carta.', 'viajes', 'approved'),
  ('viajes-pedi-mal-idioma', 'Pedí en otro idioma y me trajeron algo que ni reconocí', '🍽️', NULL, 'viajes', 'approved'),
  ('viajes-restaurante-turista-trampa', 'Caí en una trampa para turistas y me cobraron el cubierto a 8 euros', '🪤', NULL, 'viajes', 'approved'),
  ('viajes-tip-no-sabia-poner', 'No sabía cuánta propina dejar y dejé el doble por miedo', '💵', NULL, 'viajes', 'approved'),
  ('viajes-mcdonalds-en-roma', 'Después de 5 días de probar comida local terminé en un McDonalds en Roma', '🍟', NULL, 'viajes', 'approved'),
  ('viajes-comida-gasolinera-extranjero', 'Cené un sandwich de gasolinera de un país que no entendía nada', '⛽', NULL, 'viajes', 'approved'),
  ('viajes-supermercado-extranjero-cole', 'Pasé 40 minutos en un supermercado intentando comprar cosas básicas', '🛒', NULL, 'viajes', 'approved'),
  ('viajes-cafe-no-cafe-italia', 'Pedí un café con leche en Italia a las 5 de la tarde y me miraron mal', '☕', NULL, 'viajes', 'approved'),
  ('viajes-pinta-londres-12-libras', 'Me cobraron 12 libras por una pinta en Londres y disimulé', '🍺', NULL, 'viajes', 'approved'),
  ('viajes-cerveza-gigante-baviera', 'Pedí una cerveza en Baviera y me trajeron un litro que no me acabé', '🍺', NULL, 'viajes', 'approved'),
  ('viajes-no-spice-mexico', 'Dije que aguantaba el picante en México y casi lloro', '🌶️', NULL, 'viajes', 'approved'),
  ('viajes-sushi-conveyor-pague-mas', 'En el sushi de cinta no entendí los precios y pagué 80 euros', '🍣', NULL, 'viajes', 'approved'),
  ('viajes-vino-cena-200', 'Pedí el vino de la carta sin mirar precio y costaba 200 euros', '🍷', NULL, 'viajes', 'approved'),
  ('viajes-no-cambio-moneda', 'Llegué al destino sin haber cambiado moneda y todo cerrado', '💱', NULL, 'viajes', 'approved'),
  ('viajes-comision-cajero-15', 'El cajero del extranjero me clavó 15 euros de comisión por sacar 100', '🏧', NULL, 'viajes', 'approved'),
  ('viajes-tarjeta-bloqueada-fraude', 'Mi banco bloqueó la tarjeta por sospechar fraude justo en el viaje', '🚫', NULL, 'viajes', 'approved'),
  ('viajes-revolut-no-funciono', 'La Revolut no me funcionó y tuve que pagar todo con la tarjeta cara', '💳', NULL, 'viajes', 'approved'),
  ('viajes-perdi-cartera-estacion', 'Perdí la cartera en la estación de tren y no volví a verla', '👛', NULL, 'viajes', 'approved'),
  ('viajes-robaron-mochila-bar', 'Me robaron la mochila en un bar mientras pedía la segunda cerveza', '🎒', NULL, 'viajes', 'approved'),
  ('viajes-carterista-metro-paris', 'Un carterista me sacó el móvil del bolsillo en el metro y no me enteré', '🥷', NULL, 'viajes', 'approved'),
  ('viajes-estafa-gorrilla-rosario', 'Me hicieron la estafa de la pulsera en plena calle y pagué', '🤡', NULL, 'viajes', 'approved'),
  ('viajes-pago-100-bici-rota', 'Pagué 100 euros por una bici de alquiler que se rompió en el primer km', '🚲', NULL, 'viajes', 'approved'),
  ('viajes-erasmus-primera-noche-llore', 'Mi primera noche de Erasmus la pasé llorando en la habitación', '😢', NULL, 'viajes', 'approved'),
  ('viajes-erasmus-no-entendi-clase', 'Fui a mi primera clase de Erasmus y no entendí ni una palabra', '📚', NULL, 'viajes', 'approved'),
  ('viajes-erasmus-pasta-todos-dias', 'En el Erasmus me alimenté de pasta con tomate durante un mes entero', '🍝', NULL, 'viajes', 'approved'),
  ('viajes-erasmus-cocina-piso-mafia', 'En mi piso de Erasmus la cocina parecía una zona de guerra cada mañana', '🍳', NULL, 'viajes', 'approved'),
  ('viajes-erasmus-fiesta-perdi-llaves', 'Salí de fiesta en Erasmus, perdí las llaves y dormí en el rellano', '🔐', NULL, 'viajes', 'approved'),
  ('viajes-erasmus-vuelo-vuelta-llore', 'Lloré en el vuelo de vuelta del Erasmus mirando por la ventanilla', '🛫', NULL, 'viajes', 'approved'),
  ('viajes-mochilero-mes-misma-camiseta', 'Hice un mes de mochilero con tres camisetas que ya no olían a nada bueno', '👕', NULL, 'viajes', 'approved'),
  ('viajes-conoci-pareja-hostal', 'Me lié con alguien en el hostal y al día siguiente cogimos vuelos distintos', '💋', NULL, 'viajes', 'approved'),
  ('viajes-amigo-hostal-meses', 'Conocí a alguien en un hostal y seguimos hablando 4 años después', '🌍', NULL, 'viajes', 'approved'),
  ('viajes-cena-hostel-llorando-solo', 'Cené yo solo en la cocina del hostel mientras todos hacían planes', '🍽️', NULL, 'viajes', 'approved'),
  ('viajes-pareja-pelea-mapa', 'Mi pareja y yo nos peleamos por el mapa y dejamos de hablarnos un día entero', '🗺️', NULL, 'viajes', 'approved'),
  ('viajes-pareja-distintos-planes', 'En vacaciones queríamos cosas opuestas y acabamos cada uno por su lado', '↔️', NULL, 'viajes', 'approved'),
  ('viajes-grupo-amigos-plomo', 'Viajé con un grupo de amigos y descubrí que uno era un plomo brutal', '😬', NULL, 'viajes', 'approved'),
  ('viajes-grupo-cuentas-excel', 'En el grupo el típico que llevaba un Excel con todos los gastos en céntimos', '📊', NULL, 'viajes', 'approved'),
  ('viajes-grupo-uno-no-paga', 'En el viaje con amigos siempre había uno que se escapaba a pagar', '🙄', NULL, 'viajes', 'approved'),
  ('viajes-cumple-de-otro-viaje', 'Me coincidió mi cumpleaños en pleno viaje y nadie se acordó hasta la noche', '🎂', NULL, 'viajes', 'approved'),
  ('viajes-luna-miel-pelea-llegada', 'En la luna de miel nos peleamos al bajar del avión', '💔', NULL, 'viajes', 'approved'),
  ('viajes-padres-mismo-pueblo', 'Viajé con mis padres a Roma y acabé buscando excusas para escapar 2 horas', '👴', NULL, 'viajes', 'approved'),
  ('viajes-domingo-tarde-vuelta-trabajo', 'El domingo de vuelta del viaje pensé en pedir la baja para no ir el lunes', '😩', NULL, 'viajes', 'approved'),
  ('viajes-tarde-flight-club-cancelado', 'Se canceló el vuelo y dormí 8h en una silla rígida del aeropuerto', '🪑', NULL, 'viajes', 'approved'),
  ('viajes-noche-aeropuerto-fast-food', 'Pasé la noche en el aeropuerto cenando un Burger King a las 4am', '🍔', NULL, 'viajes', 'approved'),
  ('viajes-llegue-2h-antes-tarde', 'Llegué 2 horas antes al aeropuerto y aún así casi pierdo el vuelo', '⏰', NULL, 'viajes', 'approved'),
  ('viajes-impresora-tarjeta-embarque', 'Imprimí la tarjeta de embarque en blanco y negro y casi me hacen pagar', '🖨️', NULL, 'viajes', 'approved'),
  ('viajes-asiento-ventanilla-no-mire', 'Pagué extra por ventanilla y me pasé el vuelo durmiendo con la persiana bajada', '🪟', NULL, 'viajes', 'approved'),
  ('viajes-asiento-pasillo-nina-mareo', 'Cogí pasillo y la del medio se mareó toda encima', '🤢', NULL, 'viajes', 'approved'),
  ('viajes-aerolinea-comida-asco', 'Pedí el menú especial del avión y vino una cosa imposible de comer', '🥗', NULL, 'viajes', 'approved'),
  ('viajes-azafata-derramo-cafe', 'La azafata me tiró el café encima y me pasé el vuelo con el pantalón mojado', '☕', NULL, 'viajes', 'approved'),
  ('viajes-bano-avion-cola-30min', 'Estuve en cola del baño del avión 30 minutos y me lo aguanté hasta aterrizar', '🚽', NULL, 'viajes', 'approved'),
  ('viajes-pelicula-avion-llore', 'Me puse a llorar viendo una peli en el avión rodeado de gente', '🎬', NULL, 'viajes', 'approved'),
  ('viajes-aterrizaje-aplausos', 'Aplaudí cuando aterrizó el avión y me di cuenta tarde de la vergüenza', '👏', NULL, 'viajes', 'approved'),
  ('viajes-turbulencia-rezo', 'En una turbulencia fuerte me puse a rezar sin ser creyente', '🙏', NULL, 'viajes', 'approved'),
  ('viajes-mareo-coche-ventanilla', 'Me mareé tanto en un coche que tuve que parar y vomitar en la cuneta', '🚗', NULL, 'viajes', 'approved'),
  ('viajes-curva-pais-lentejas', 'Me mareé en un autobús de montaña y vomité unas lentejas que ni recordaba', '🚌', NULL, 'viajes', 'approved'),
  ('viajes-ferry-mareo-cama', 'En el ferry me pasé toda la travesía tumbado en el suelo del baño', '⛴️', NULL, 'viajes', 'approved'),
  ('viajes-conduzco-otro-pais-volante', 'Conduje en un país con el volante al otro lado y casi me mato en una rotonda', '🚗', NULL, 'viajes', 'approved'),
  ('viajes-gasolinera-extranjero-mal', 'Eché gasolina equivocada en un coche de alquiler en otro país', '⛽', NULL, 'viajes', 'approved'),
  ('viajes-multa-coche-alquiler', 'Me llegó una multa del coche de alquiler 4 meses después por correo', '📮', NULL, 'viajes', 'approved'),
  ('viajes-coche-aparcado-grua', 'Me llevaron el coche con la grúa en el primer día de vacaciones', '🚧', NULL, 'viajes', 'approved'),
  ('viajes-parking-pago-no-sabia', 'Me cobraron 80 euros de parking porque no entendí cómo se pagaba', '🅿️', NULL, 'viajes', 'approved'),
  ('viajes-monumento-cerrado-lunes', 'Llegué al monumento estrella del viaje y estaba cerrado los lunes', '🏛️', NULL, 'viajes', 'approved'),
  ('viajes-cola-museo-3h', 'Hice 3 horas de cola para un museo que me aburrió en 20 minutos', '🖼️', NULL, 'viajes', 'approved'),
  ('viajes-toda-tarde-museo-pies', 'Pasé una tarde entera en un museo y solo recuerdo el dolor de pies', '🦶', NULL, 'viajes', 'approved'),
  ('viajes-foto-torre-pisa-tipica', 'Hice la foto sujetando la Torre de Pisa y me sigo arrepintiendo', '📸', NULL, 'viajes', 'approved'),
  ('viajes-skip-monumento-postureo', 'Pagué entrada para una atracción solo para el Insta y no entré', '📲', NULL, 'viajes', 'approved'),
  ('viajes-instagram-postureo-2h', 'Pasé 2 horas montando una foto de Instagram en la playa', '📷', NULL, 'viajes', 'approved'),
  ('viajes-souvenir-iman-50', 'Volví con 50 imanes de la nevera y no sé ni dónde compré la mitad', '🧲', NULL, 'viajes', 'approved'),
  ('viajes-souvenir-roto-maleta', 'Me compré un souvenir de cerámica y llegó a casa hecho añicos', '🏺', NULL, 'viajes', 'approved'),
  ('viajes-camiseta-i-love-no-pongo', 'Me compré la camiseta de I Love NY y no me la he puesto nunca', '👕', NULL, 'viajes', 'approved'),
  ('viajes-bolsa-pesada-cabina', 'Volví con una bolsa de souvenirs tan pesada que me cobraron en la cabina', '🛍️', NULL, 'viajes', 'approved'),
  ('viajes-ducha-hostel-soledad', 'Me duché en el hostel y me sentí más solo que en toda mi vida', '🚿', NULL, 'viajes', 'approved'),
  ('viajes-mesa-1-restaurante', 'Pedí mesa para uno en un restaurante caro y disfruté como nunca', '🍴', NULL, 'viajes', 'approved'),
  ('viajes-tinder-extranjero-cita', 'Hice match en Tinder en otro país y quedé con un desconocido', '💕', NULL, 'viajes', 'approved'),
  ('viajes-grindr-otro-pais-cuarto', 'Quedé con alguien de Grindr en otro país y luego me arrepentí en su salón', '🚪', NULL, 'viajes', 'approved'),
  ('viajes-conoci-extranjero-llore-volver', 'Me lié con alguien en el viaje y al volver lloré en el avión 3 horas', '✈️', NULL, 'viajes', 'approved'),
  ('viajes-llamada-padres-extranjero', 'Llamé a mis padres llorando desde otro país por una tontería', '📞', NULL, 'viajes', 'approved'),
  ('viajes-roaming-100-euros', 'Me llegó una factura de 100 euros de roaming sin haber hecho nada', '📡', NULL, 'viajes', 'approved'),
  ('viajes-no-wifi-hotel-anuncio', 'El hotel decía wifi gratis y era de pago a 15 euros la hora', '📶', NULL, 'viajes', 'approved'),
  ('viajes-vpn-no-funciono', 'Intenté ver Netflix en otro país y la VPN no me funcionaba', '🎥', NULL, 'viajes', 'approved'),
  ('viajes-cargador-no-vale-enchufe', 'Llegué al hotel con el cargador equivocado para el tipo de enchufe', '🔌', NULL, 'viajes', 'approved'),
  ('viajes-adaptador-comprado-aero', 'Compré un adaptador de enchufe en el aeropuerto a 25 euros', '🔌', NULL, 'viajes', 'approved'),
  ('viajes-sin-bateria-mapas-perdido', 'Se me apagó el móvil en una ciudad nueva y no sabía volver al hotel', '🔋', NULL, 'viajes', 'approved'),
  ('viajes-nombre-hotel-no-recuerdo', 'En un taxi no me acordaba del nombre del hotel y di vueltas 30 minutos', '🤔', NULL, 'viajes', 'approved'),
  ('viajes-mapa-papel-hostal', 'Usé un mapa de papel del hostal y aún así me perdí', '🗺️', NULL, 'viajes', 'approved'),
  ('viajes-prepay-tour-dia-no-fue', 'Pagué un tour por adelantado y al final no me apetecía y no fui', '😴', NULL, 'viajes', 'approved'),
  ('viajes-tour-guia-hablar-3h', 'Caí en un tour donde el guía no calló en 3 horas y solo quería sentarme', '🎙️', NULL, 'viajes', 'approved'),
  ('viajes-free-tour-propina-incomoda', 'En un free tour me sentí obligado a poner 20 euros de propina', '💵', NULL, 'viajes', 'approved'),
  ('viajes-hop-on-bus-dormi', 'Me quedé dormido en un bus turístico y pasé dos veces por lo mismo', '🚌', NULL, 'viajes', 'approved'),
  ('viajes-snorkel-perdi-gafas', 'Se me cayeron las gafas haciendo snorkel y se las llevó el mar', '👓', NULL, 'viajes', 'approved'),
  ('viajes-buceo-panico-bajo-agua', 'En mi primera inmersión de buceo me dio un ataque de pánico', '🤿', NULL, 'viajes', 'approved'),
  ('viajes-paddle-no-supe-volver', 'Cogí un paddle surf y me alejé tanto que no sabía cómo volver', '🏄', NULL, 'viajes', 'approved'),
  ('viajes-kayak-volcado-todo-mojado', 'Volqué el kayak con el móvil dentro y se acabó el viaje', '🛶', NULL, 'viajes', 'approved'),
  ('viajes-camello-monto-vergonzoso', 'Me monté en un camello en Marruecos y me caí en el primer paso', '🐪', NULL, 'viajes', 'approved'),
  ('viajes-elefante-tailandia-pena', 'Monté un elefante en Tailandia y volví con cargo de conciencia', '🐘', NULL, 'viajes', 'approved'),
  ('viajes-perro-extranjero-mordi', 'Un perro me mordió en otro país y tuve que ir a urgencias por la rabia', '🐕', NULL, 'viajes', 'approved'),
  ('viajes-mosquitos-mil-piernas', 'Volví del viaje con las piernas hechas un campo de mosquitos', '🦟', NULL, 'viajes', 'approved'),
  ('viajes-piojos-hostal', 'Pillé piojos en un hostal y me enteré 2 semanas después', '🐛', NULL, 'viajes', 'approved'),
  ('viajes-sarna-hostel-asia', 'Pillé sarna en un hostal del Sudeste Asiático y no se lo deseo a nadie', '🦠', NULL, 'viajes', 'approved'),
  ('viajes-orina-vaca-india', 'Me dieron a probar orina de vaca en India por una broma de un local', '🐄', NULL, 'viajes', 'approved'),
  ('viajes-banyo-comun-asia', 'Usé un baño común en Asia y aún sueño con esa experiencia', '🚽', NULL, 'viajes', 'approved'),
  ('viajes-no-papel-toalita', 'Me quedé sin papel en un baño público de un país que solo usaba manguera', '🚿', NULL, 'viajes', 'approved'),
  ('viajes-sahara-arena-ojos', 'Pasé la noche en el desierto y la arena se me metió hasta en los ojos', '🏜️', NULL, 'viajes', 'approved'),
  ('viajes-frio-sahara-noche', 'Pensé que el desierto era calor y casi me congelo por la noche', '🥶', NULL, 'viajes', 'approved'),
  ('viajes-cusco-altura-mareado', 'Llegué a Cusco y casi me desmayo por el mal de altura', '⛰️', NULL, 'viajes', 'approved'),
  ('viajes-machu-foto-niebla', 'Llegué a Machu Picchu y estaba todo cubierto de niebla', '🌫️', NULL, 'viajes', 'approved'),
  ('viajes-iguazu-empapado', 'Vi las cataratas y volví completamente empapado al hotel', '💦', NULL, 'viajes', 'approved'),
  ('viajes-aurora-boreal-no-vi', 'Pagué un viaje a Laponia para ver auroras y no vi ni una', '🌌', NULL, 'viajes', 'approved'),
  ('viajes-eiffel-no-impresiona', 'Vi la Torre Eiffel en persona y me decepcionó un poco', '🗼', NULL, 'viajes', 'approved'),
  ('viajes-mona-lisa-mas-pequena', 'Llegué a la Mona Lisa y era mucho más pequeña de lo que pensaba', '🖼️', NULL, 'viajes', 'approved'),
  ('viajes-ramble-bcn-pickpocket', 'Me robaron en Las Ramblas siendo turista en mi propio país', '🥴', NULL, 'viajes', 'approved'),
  ('viajes-madrid-feria-perdido', 'Me perdí en San Isidro siendo de Madrid de toda la vida', '🥲', NULL, 'viajes', 'approved'),
  ('viajes-ibiza-perdi-grupo', 'Perdí al grupo en Ibiza a las 4am y aparecí al día siguiente', '🌅', NULL, 'viajes', 'approved'),
  ('viajes-benidorm-britanicos-borracho', 'Acabé en una calle de Benidorm cantando con guiris borrachos', '🎤', NULL, 'viajes', 'approved'),
  ('viajes-festival-llueve-todo', 'Fui a un festival de verano y llovió los 4 días seguidos', '🌧️', NULL, 'viajes', 'approved'),
  ('viajes-festival-perdi-cartera', 'Perdí la cartera en un festival y aún así seguí bailando', '🪩', NULL, 'viajes', 'approved'),
  ('viajes-festival-tienda-volada', 'Se me voló la tienda del camping en un festival con mis cosas dentro', '🌬️', NULL, 'viajes', 'approved'),
  ('viajes-coachella-foto-amigos-ig', 'Volví de un festival con 0 fotos de mí y 200 de mis amigos', '📸', NULL, 'viajes', 'approved'),
  ('viajes-fin-de-semana-sin-dormir', 'Hice un finde en otra ciudad sin dormir prácticamente nada', '👁️', NULL, 'viajes', 'approved'),
  ('viajes-puente-mochila-llegue', 'Hice un puente improvisado y volví con la mochila más pesada que cuando me fui', '🎒', NULL, 'viajes', 'approved'),
  ('viajes-vacaciones-trabajo-mail', 'En vacaciones contesté un mail del curro y me arrepentí inmediatamente', '💻', NULL, 'viajes', 'approved'),
  ('viajes-jefe-llamo-playa', 'Mi jefe me llamó estando en la playa y disimulé que estaba en casa', '🤳', NULL, 'viajes', 'approved'),
  ('viajes-foto-postureo-pies-piscina', 'Hice la típica foto de pies en la piscina y luego me dio vergüenza subirla', '🦶', NULL, 'viajes', 'approved'),
  ('viajes-amor-resort-todo-incluido', 'Me lié con alguien en un resort todo incluido y nunca lo conté en casa', '🏖️', NULL, 'viajes', 'approved'),
  ('viajes-resort-bracelet-bebi-todo', 'Aproveché tanto la pulsera del todo incluido que vomité el segundo día', '🍹', NULL, 'viajes', 'approved'),
  ('viajes-crucero-mareado-tres-dias', 'Hice un crucero y los 3 primeros días estuve mareado en la cama', '🚢', NULL, 'viajes', 'approved'),
  ('viajes-crucero-buffet-comi-x4', 'En un crucero comí en el buffet 4 veces al día y subí 5 kilos', '🍽️', NULL, 'viajes', 'approved'),
  ('viajes-tren-nocturno-companero', 'Hice un tren nocturno y mi compartimiento olía a pies durante 10 horas', '🚆', NULL, 'viajes', 'approved'),
  ('viajes-interrail-ducha-2-dias', 'Me hice un Interrail y llegué a estar 2 días sin ducharme', '🛁', NULL, 'viajes', 'approved'),
  ('viajes-interrail-tren-perdido', 'En un Interrail perdí un tren por 30 segundos y se me fue toda la ruta', '⏳', NULL, 'viajes', 'approved'),
  ('viajes-cambio-de-planes-aeropuerto', 'En el aeropuerto cambiamos de destino y compramos otro vuelo en el momento', '🎲', NULL, 'viajes', 'approved'),
  ('viajes-roma-tres-dias-pasta', 'En Roma comí pasta los 3 días y aún así pedí más para llevar', '🍝', NULL, 'viajes', 'approved'),
  ('viajes-tokyo-perdido-shibuya', 'Me perdí en Shibuya siguiendo un mapa que no entendía', '🗾', NULL, 'viajes', 'approved'),
  ('viajes-seul-norebang-cante', 'En Seúl entré a un norebang yo solo y canté como si nadie me oyera', '🎤', NULL, 'viajes', 'approved'),
  ('viajes-nyc-pizza-suelo', 'Comí pizza sentado en el bordillo en Nueva York como en las películas', '🍕', NULL, 'viajes', 'approved'),
  ('viajes-disney-llore-castillo', 'Lloré delante del castillo de Disney teniendo 28 años', '🏰', NULL, 'viajes', 'approved'),
  ('viajes-disney-cola-3h-atraccion', 'Hice 3 horas de cola para una atracción que duró 90 segundos', '🎢', NULL, 'viajes', 'approved'),
  ('viajes-amsterdam-coffeeshop-pano', 'Me pasé en un coffeeshop de Amsterdam y dormí en un parque', '🌳', NULL, 'viajes', 'approved'),
  ('viajes-praga-cerveza-litros', 'En Praga me bebí más litros de cerveza que de agua en una semana', '🍺', NULL, 'viajes', 'approved'),
  ('viajes-budapest-bano-termal-resaca', 'Fui a los baños termales de Budapest con la peor resaca de mi vida', '♨️', NULL, 'viajes', 'approved'),
  ('viajes-berlin-tecno-12h', 'Estuve 12 horas seguidas en una discoteca de Berlín y casi muero al sol', '🪩', NULL, 'viajes', 'approved'),
  ('viajes-lisboa-tranvia-foto-mil', 'Hice 80 fotos del tranvía de Lisboa y subí solo una', '🚋', NULL, 'viajes', 'approved'),
  ('viajes-paris-camarero-mal', 'Un camarero parisino me trató fatal y me fui sin tomarme la copa', '🥖', NULL, 'viajes', 'approved'),
  ('viajes-sidney-jet-lag-ojeras', 'Volví de Australia con tal jet lag que tardé semanas en recuperarme', '🦘', NULL, 'viajes', 'approved'),
  ('viajes-bali-mochilero-zen-instagram', 'Volví de Bali diciendo que era otra persona y duré 3 días así', '🧘', NULL, 'viajes', 'approved'),
  ('viajes-tailandia-amistades-nunca-mas', 'Hice 4 amigos íntimos en Tailandia y no he vuelto a hablar con ninguno', '🤝', NULL, 'viajes', 'approved'),
  ('viajes-vietnam-moto-caida', 'Alquilé una moto en Vietnam y me caí antes de salir del parking', '🛵', NULL, 'viajes', 'approved'),
  ('viajes-grupo-chat-viaje-muerto', 'El grupo de WhatsApp del viaje murió a los 3 días de volver', '💀', NULL, 'viajes', 'approved'),
  ('viajes-fotos-no-revele-2-anos', 'Tengo fotos de un viaje en el móvil sin organizar desde hace 2 años', '🖼️', NULL, 'viajes', 'approved'),
  ('viajes-album-fisico-no-empece', 'Compré un álbum de fotos para imprimir el viaje y sigue vacío', '📔', NULL, 'viajes', 'approved'),
  ('viajes-vuelta-trabajo-no-aterrice', 'Volví de viaje y al día siguiente fui a currar como si no hubiera pasado nada', '🥲', NULL, 'viajes', 'approved'),
  ('viajes-saudades-vuelta-domingo', 'El domingo de vuelta del viaje me senté en el sofá a mirar la pared', '🛋️', NULL, 'viajes', 'approved'),
  ('viajes-recomendar-restaurante-nadie', 'Volví obsesionado con un restaurante y se lo conté a todo el que se dejó', '🍽️', NULL, 'viajes', 'approved'),
  ('viajes-comprar-apuntar-no-lei', 'Compré una guía de viaje en papel y no la abrí ni una vez', '📖', NULL, 'viajes', 'approved'),
  ('viajes-lonely-planet-2010-no-actualizado', 'Seguí una guía vieja y los sitios ya no existían', '🕰️', NULL, 'viajes', 'approved'),
  ('viajes-checklist-no-cumpli-nada', 'Hice una lista de cosas para ver y no marqué ni la mitad', '📝', NULL, 'viajes', 'approved'),
  ('viajes-nada-prepare-todo-improvisado', 'No preparé el viaje y acabé pagando todo el doble por improvisar', '🎲', NULL, 'viajes', 'approved'),
  ('viajes-volver-pesar-2-kilos', 'Volví del viaje pesando 2 kilos más y me costó un mes quitármelos', '⚖️', NULL, 'viajes', 'approved'),
  ('viajes-anti-postureo-yo-tambien', 'Juré no hacer fotos turísticas y volví con 700 idénticas a las del resto', '📸', NULL, 'viajes', 'approved'),
  ('viajes-grupo-tour-evite-todos', 'Pagué un tour de grupo y me pasé el día evitando hablar con nadie', '🤐', NULL, 'viajes', 'approved'),
  ('viajes-presupuesto-doble-final', 'Hice un presupuesto y al final me gasté el doble', '💸', NULL, 'viajes', 'approved'),
  ('viajes-tarjeta-credito-meses-deuda', 'Me pasé un mes pagando con tarjeta de crédito un viaje de fin de semana', '💳', NULL, 'viajes', 'approved'),
  ('viajes-vuelta-cero-euros-cuenta', 'Volví del viaje con la cuenta a cero y aún quedaban 10 días de mes', '💀', NULL, 'viajes', 'approved'),
  ('viajes-promete-no-mas-viajes-3-meses', 'Juré no viajar más en 6 meses y a los 3 ya estaba mirando vuelos', '✈️', NULL, 'viajes', 'approved'),
  ('viajes-skyscanner-cualquier-destino', 'Pasé un domingo entero buscando vuelos a cualquier sitio sin un plan', '🌍', NULL, 'viajes', 'approved'),
  ('viajes-error-fare-no-compre', 'Vi un error fare brutal y dudé tanto que cuando fui a comprarlo se acabó', '😩', NULL, 'viajes', 'approved'),
  ('viajes-amigos-cancelan-ultima', 'Mis amigos cancelaron a última hora y me fui de viaje yo solo', '🧍', 'Lo mejor que pude hacer.', 'viajes', 'approved'),
  ('viajes-viaje-solo-primera-vez', 'Hice mi primer viaje solo y me cambió un poco la cabeza', '🌅', NULL, 'viajes', 'approved'),
  ('viajes-viaje-solo-cena-bar', 'Cené yo solo en la barra de un bar leyendo un libro como un señor', '📖', NULL, 'viajes', 'approved'),
  ('viajes-mensaje-ex-borracho-viaje', 'En un viaje le mandé un mensaje borracho a mi ex y al día siguiente quería morir', '📱', NULL, 'viajes', 'approved'),
  ('viajes-instagram-stories-horas', 'Me pasé el viaje montando stories de Instagram en vez de mirar las cosas', '📲', NULL, 'viajes', 'approved'),
  ('viajes-no-salio-tiempo-quedarme', 'Llovió toda la semana del viaje y me lo pasé en el hotel viendo Netflix', '🌧️', NULL, 'viajes', 'approved'),
  ('viajes-viaje-trabajo-perdido-empresa', 'En un viaje de trabajo me escapé del grupo de la empresa para tomarme algo solo', '🍻', NULL, 'viajes', 'approved'),
  ('viajes-presentacion-otro-pais-corbata', 'Tuve que ir con corbata a una presentación en otro país y olvidé la camisa', '👔', NULL, 'viajes', 'approved'),
  ('viajes-reunion-hotel-pijama', 'Hice una videollamada de trabajo desde un hotel en pijama y bañador', '📹', NULL, 'viajes', 'approved'),
  ('viajes-vuelo-compania-baja-asiento', 'Volé en una compañía low cost y el asiento estaba literalmente roto', '🛫', NULL, 'viajes', 'approved'),
  ('viajes-cinta-equipajes-30-min', 'Esperé 45 minutos en la cinta de equipajes y mi maleta no salió', '🧳', NULL, 'viajes', 'approved'),
  ('viajes-recogida-coche-cola-eterna', 'Hice 2 horas de cola para recoger el coche de alquiler', '⏳', NULL, 'viajes', 'approved'),
  ('viajes-coche-alquiler-ralla-no-mia', 'Me cobraron una raya del coche de alquiler que ya estaba antes', '🖍️', NULL, 'viajes', 'approved'),
  ('viajes-deposito-bloqueado-3-meses', 'El depósito del coche de alquiler tardó 3 meses en volver a mi cuenta', '⏱️', NULL, 'viajes', 'approved'),
  ('viajes-no-renove-tarjeta-vuelo', 'Mi DNI estaba caducado y descubrirlo en el aeropuerto fue una odisea', '🪪', NULL, 'viajes', 'approved'),
  ('viajes-deporte-extremo-firme-papel', 'Firmé un papel para un deporte extremo sin entender nada y lo hice igual', '🪂', NULL, 'viajes', 'approved'),
  ('viajes-paracaidas-grite-llore', 'Salté en paracaídas y grité y lloré en el cielo como un niño', '😱', NULL, 'viajes', 'approved'),
  ('viajes-puenting-no-pude-saltar', 'Me hice 100 km para hacer puenting y al borde no pude saltar', '🪢', NULL, 'viajes', 'approved'),
  ('viajes-ski-primera-vez-azul', 'Mi primer día de esquí acabé bajando una pista azul de culo', '🎿', NULL, 'viajes', 'approved'),
  ('viajes-snowboard-rotura-mueneca', 'Me fracturé la muñeca el primer día probando snowboard', '🏂', NULL, 'viajes', 'approved'),
  ('viajes-perro-trineo-caida', 'Me caí del trineo de perros en Laponia y me arrastraron 5 metros', '🐕', NULL, 'viajes', 'approved'),
  ('viajes-iglu-frio-no-dormi', 'Pagué por dormir en un iglú y no pegué ojo del frío que pasé', '🥶', NULL, 'viajes', 'approved'),
  ('viajes-glamping-no-glamuroso', 'Reservé un glamping y era un camping normal con luces de feria', '🏕️', NULL, 'viajes', 'approved'),
  ('viajes-yurta-mongolia-bicho', 'Dormí en una yurta y un bicho pasó por encima de mi cara', '🐛', NULL, 'viajes', 'approved'),
  ('viajes-tres-vuelos-jet-lag', 'Hice 3 vuelos seguidos y llegué al destino sin saber qué día era', '🌍', NULL, 'viajes', 'approved'),
  ('viajes-llegue-cumpleanos-viaje', 'Llegué a mi destino el día de mi cumpleaños y nadie me felicitó', '🎂', NULL, 'viajes', 'approved'),
  ('viajes-perdi-vuelo-resaca', 'Perdí un vuelo por una resaca brutal del día anterior', '🥴', NULL, 'viajes', 'approved'),
  ('viajes-corre-aeropuerto-pelicula', 'Corrí por el aeropuerto como en las películas y aún así llegué tarde', '🏃', NULL, 'viajes', 'approved'),
  ('viajes-mismo-asiento-ida-vuelta', 'En un viaje me tocó el mismo asiento de ida y de vuelta sin elegirlo', '🪑', 'El universo riéndose.', 'viajes', 'approved'),
  ('viajes-conoci-pareja-actual-viaje', 'Conocí a mi pareja actual en un viaje y todavía no me lo creo', '❤️', NULL, 'viajes', 'approved'),
  ('viajes-ya-no-aguanto-volar', 'A los 30 descubrí que ya no me gusta volar y me da ansiedad', '😰', NULL, 'viajes', 'approved'),
  ('viajes-vuelo-medicacion-dormir', 'Tomé pastillas para dormir en un vuelo y desperté con la cara babeada', '💊', NULL, 'viajes', 'approved'),
  ('viajes-tres-vuelos-saltar-uno', 'Compré billetes baratos saltándome el primer tramo y casi me cancelan el resto', '🎟️', NULL, 'viajes', 'approved'),
  ('viajes-volver-hotel-llaves-perdi', 'Perdí la llave del hotel y tuve que despertar a recepción a las 5am', '🔑', NULL, 'viajes', 'approved'),
  ('viajes-encerrado-bano-restaurante', 'Me quedé encerrado en el baño de un restaurante en otro idioma', '🚪', NULL, 'viajes', 'approved'),
  ('viajes-perdi-ultimo-bus-aeropuerto', 'Perdí el último bus al aeropuerto y un taxi me cobró el viaje a precio de oro', '🚖', NULL, 'viajes', 'approved'),
  ('viajes-correo-aerolinea-spam-vuelo', 'Me llegó un email importante de la aerolínea a spam y casi pierdo el vuelo', '📧', NULL, 'viajes', 'approved'),
  ('viajes-hotel-no-aire-acond-julio', 'Reservé un hotel sin aire acondicionado en pleno julio en el sur', '🥵', NULL, 'viajes', 'approved'),
  ('viajes-camarera-no-entendio-pedi-mas', 'No entendí lo que pedía la camarera y le dije que sí a todo', '🙃', NULL, 'viajes', 'approved'),
  ('viajes-aeropuerto-ducha-pague-15', 'Pagué 15 euros por una ducha en el aeropuerto y volví a sentirme persona', '🚿', NULL, 'viajes', 'approved'),
  ('viajes-lounge-puerta-no-entre', 'Pagué una sala VIP del aeropuerto y se acabó la comida 5 minutos antes', '😩', NULL, 'viajes', 'approved'),
  ('viajes-comprar-tarjeta-sim-no-funciono', 'Compré una SIM en otro país y no me funcionó hasta el último día', '📶', NULL, 'viajes', 'approved'),
  ('viajes-vuelo-cancelado-otra-aerolinea', 'Me cambiaron el vuelo cancelado a otra aerolínea peor y sin avisar', '🤬', NULL, 'viajes', 'approved'),
  ('viajes-casi-pierdo-conexion-llegar', 'Llegué corriendo a la puerta de embarque cuando estaban cerrando', '😮‍💨', NULL, 'viajes', 'approved'),
  ('viajes-no-imprimo-billete-multa', 'No imprimí el billete de Ryanair y me cobraron 60 euros en mostrador', '🧾', 'La clásica.', 'viajes', 'approved'),
  ('viajes-me-quedo-aqui-no-vuelvo', 'Estando de viaje pensé en serio si volvía o me quedaba a vivir allí', '🌅', NULL, 'viajes', 'approved')
on conflict (slug) do nothing;
