-- =================================================================
-- Unlocked seed v3 — RELACIONES (200 entries)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- Requiere migración _012 (categoría 'relaciones' en el enum)
-- =================================================================

insert into achievements (slug, title, emoji, description, category, status) values
  ('stalkee-el-instagram-de-mi-ex-a-las-3-de-la-manana-en-modo-i', 'Stalkeé el Instagram de mi ex a las 3 de la mañana en modo incógnito', '🔍', 'Hice scroll hasta 2019 sin pestañear.', 'relaciones', 'approved'),
  ('le-di-like-sin-querer-a-una-foto-de-mi-ex-de-2018', 'Le di like sin querer a una foto de mi ex de 2018', '💀', NULL, 'relaciones', 'approved'),
  ('le-di-swipe-a-la-derecha-a-un-companero-de-trabajo-en-tinder', 'Le di swipe a la derecha a un compañero de trabajo en Tinder', '🫠', 'Ahora compartimos almuerzo cada día.', 'relaciones', 'approved'),
  ('hice-match-con-mi-jefe-en-tinder', 'Hice match con mi jefe en Tinder', '😱', NULL, 'relaciones', 'approved'),
  ('vi-el-perfil-de-mi-ex-en-bumble-y-cerre-la-app-del-susto', 'Vi el perfil de mi ex en Bumble y cerré la app del susto', '📱', NULL, 'relaciones', 'approved'),
  ('cancele-una-cita-de-tinder-a-10-minutos-de-quedar-sin-excusa', 'Cancelé una cita de Tinder a 10 minutos de quedar sin excusa real', '📵', 'Le dije que tenía gastroenteritis.', 'relaciones', 'approved'),
  ('llegue-borracho-a-la-primera-cita-y-la-lie-parda', 'Llegué borracho a la primera cita y la lié parda', '🍷', NULL, 'relaciones', 'approved'),
  ('vomite-en-la-primera-cita-y-aun-asi-hubo-segunda', 'Vomité en la primera cita y aún así hubo segunda', '🤮', 'Le hizo gracia, no preguntéis.', 'relaciones', 'approved'),
  ('llame-a-mi-cita-por-el-nombre-de-mi-ex', 'Llamé a mi cita por el nombre de mi ex', '😬', NULL, 'relaciones', 'approved'),
  ('cite-a-dos-personas-la-misma-noche-en-bares-distintos', 'Cité a dos personas la misma noche en bares distintos', '🏃', 'No me pillaron de milagro.', 'relaciones', 'approved'),
  ('le-hice-ghosting-a-alguien-despues-de-tres-meses', 'Le hice ghosting a alguien después de tres meses', '👻', NULL, 'relaciones', 'approved'),
  ('recibi-ghosting-de-alguien-con-quien-llevaba-siete-meses', 'Recibí ghosting de alguien con quien llevaba siete meses', '🪦', 'Aún espero el visto bueno.', 'relaciones', 'approved'),
  ('respondi-un-mensaje-de-hinge-un-mes-despues-como-si-nada', 'Respondí un mensaje de Hinge un mes después como si nada', '⏳', NULL, 'relaciones', 'approved'),
  ('hice-breadcrumbing-a-alguien-durante-medio-ano', 'Hice breadcrumbing a alguien durante medio año', '🍞', 'Le mandaba un meme cada quincena.', 'relaciones', 'approved'),
  ('dije-estoy-muy-liado-para-no-quedar-y-vio-que-estaba-en-twit', 'Dije estoy muy liado para no quedar y vio que estaba en Twitter', '📲', NULL, 'relaciones', 'approved'),
  ('quede-con-mi-ex-jurando-que-solo-era-un-cafe', 'Quedé con mi ex jurando que solo era un café', '☕', 'Acabamos en su casa, sorpresa.', 'relaciones', 'approved'),
  ('folle-con-mi-ex-en-lo-que-habria-sido-nuestro-aniversario', 'Follé con mi ex en lo que habría sido nuestro aniversario', '💔', NULL, 'relaciones', 'approved'),
  ('vi-las-stories-de-mi-ex-cinco-veces-el-mismo-dia', 'Vi las Stories de mi ex cinco veces el mismo día', '👀', 'Sé que salgo en su top de espectadores.', 'relaciones', 'approved'),
  ('me-hice-una-cuenta-falsa-solo-para-stalkear-a-mi-ex', 'Me hice una cuenta falsa solo para stalkear a mi ex', '🥸', NULL, 'relaciones', 'approved'),
  ('mande-screenshots-de-mi-ex-al-grupo-de-amigas-para-analisis', 'Mandé screenshots de mi ex al grupo de amigas para análisis forense', '📸', 'Análisis forense de un emoji, qué tristeza.', 'relaciones', 'approved'),
  ('stalkee-hasta-el-linkedin-de-la-nueva-pareja-de-mi-ex', 'Stalkeé hasta el LinkedIn de la nueva pareja de mi ex', '💼', NULL, 'relaciones', 'approved'),
  ('mire-el-movil-de-mi-pareja-mientras-dormia', 'Miré el móvil de mi pareja mientras dormía', '🔓', 'No encontré nada y me sentí peor.', 'relaciones', 'approved'),
  ('tuve-celos-del-amigo-del-trabajo-de-mi-pareja', 'Tuve celos del amigo del trabajo de mi pareja', '😤', NULL, 'relaciones', 'approved'),
  ('revise-a-quien-daba-likes-mi-pareja-en-instagram', 'Revisé a quién daba likes mi pareja en Instagram', '🕵️', 'Encontré una ex y casi exploté.', 'relaciones', 'approved'),
  ('pregunte-quien-es-esa-de-la-foto-y-monte-un-drama-de-hora-y', 'Pregunté quién es esa de la foto y monté un drama de hora y media', '🎭', NULL, 'relaciones', 'approved'),
  ('mantuve-una-relacion-a-distancia-tres-meses-sin-vernos', 'Mantuve una relación a distancia tres meses sin vernos', '✈️', 'Acabamos rompiendo por audio.', 'relaciones', 'approved'),
  ('hice-una-videollamada-de-siete-horas-con-mi-pareja-a-distanc', 'Hice una videollamada de siete horas con mi pareja a distancia', '📹', NULL, 'relaciones', 'approved'),
  ('deje-de-hablarle-a-mi-pareja-a-distancia-sin-avisar', 'Dejé de hablarle a mi pareja a distancia sin avisar', '🌐', 'Volví a la semana como si nada.', 'relaciones', 'approved'),
  ('estuve-un-ano-en-una-situationship-sin-etiquetar-nada', 'Estuve un año en una situationship sin etiquetar nada', '🤷', NULL, 'relaciones', 'approved'),
  ('solte-el-clasico-estamos-viendo-que-pasa', 'Solté el clásico estamos viendo qué pasa', '🌫️', 'Llevábamos siete meses viéndolo.', 'relaciones', 'approved'),
  ('presente-a-mi-situationship-a-mis-amigos-como-mi-amigo', 'Presenté a mi situationship a mis amigos como mi amigo', '🥲', NULL, 'relaciones', 'approved'),
  ('tuve-un-amigo-con-derecho-a-roce-durante-medio-ano', 'Tuve un amigo con derecho a roce durante medio año', '🛌', 'Acabó como acaban estas cosas.', 'relaciones', 'approved'),
  ('deje-de-hablarme-con-un-amigo-despues-de-follar-una-vez', 'Dejé de hablarme con un amigo después de follar una vez', '🚪', NULL, 'relaciones', 'approved'),
  ('tuve-la-conversacion-de-ruptura-en-un-restaurante-lleno-de-g', 'Tuve la conversación de ruptura en un restaurante lleno de gente', '🍝', 'Y pagué la cena igual.', 'relaciones', 'approved'),
  ('llore-una-hora-seguida-en-el-bano-despues-de-cortar', 'Lloré una hora seguida en el baño después de cortar', '😭', NULL, 'relaciones', 'approved'),
  ('bloquee-a-mi-ex-en-todas-las-redes-en-menos-de-cinco-minutos', 'Bloqueé a mi ex en todas las redes en menos de cinco minutos', '🚫', 'WhatsApp, Insta, Spotify, todo.', 'relaciones', 'approved'),
  ('desbloquee-a-mi-ex-tres-dias-despues-porque-pude', 'Desbloqueé a mi ex tres días después porque pude', '🔁', NULL, 'relaciones', 'approved'),
  ('corte-con-mi-pareja-por-whatsapp-despues-de-dos-anos', 'Corté con mi pareja por WhatsApp después de dos años', '💬', 'Ni una llamada, qué fuerte.', 'relaciones', 'approved'),
  ('me-cortaron-por-un-audio-de-whatsapp-de-doce-minutos', 'Me cortaron por un audio de WhatsApp de doce minutos', '🎙️', NULL, 'relaciones', 'approved'),
  ('llevo-con-mi-pareja-anos-y-ya-no-follamos-casi-nunca', 'Llevo con mi pareja años y ya no follamos casi nunca', '🛌', 'Pero somos felices, ojo.', 'relaciones', 'approved'),
  ('mi-pareja-y-yo-dormimos-mirando-a-lados-opuestos-cada-noche', 'Mi pareja y yo dormimos mirando a lados opuestos cada noche', '🛏️', NULL, 'relaciones', 'approved'),
  ('cenamos-cada-noche-con-mi-pareja-mirando-el-movil', 'Cenamos cada noche con mi pareja mirando el móvil', '📱', 'Conexión emocional sólida.', 'relaciones', 'approved'),
  ('llevamos-cinco-anos-haciendo-el-mismo-plan-de-domingo', 'Llevamos cinco años haciendo el mismo plan de domingo', '🛋️', NULL, 'relaciones', 'approved'),
  ('tuve-un-rebote-a-las-dos-semanas-de-cortar', 'Tuve un rebote a las dos semanas de cortar', '🏀', 'Duró exactamente lo que tenía que durar.', 'relaciones', 'approved'),
  ('dije-te-quiero-en-la-tercera-cita-y-se-asusto', 'Dije te quiero en la tercera cita y se asustó', '💘', NULL, 'relaciones', 'approved'),
  ('tuve-una-pelea-con-mi-pareja-delante-de-sus-padres-la-primer', 'Tuve una pelea con mi pareja delante de sus padres la primera vez', '👵', 'Adiós a la primera impresión.', 'relaciones', 'approved'),
  ('mi-suegra-me-pregunto-cuando-nos-casamos-a-la-segunda-comida', 'Mi suegra me preguntó cuándo nos casamos a la segunda comida', '💒', NULL, 'relaciones', 'approved'),
  ('monte-una-bronca-porque-mi-pareja-me-dejo-en-visto-cuatro-ho', 'Monté una bronca porque mi pareja me dejó en visto cuatro horas', '👁️', 'Spoiler: estaba currando.', 'relaciones', 'approved'),
  ('discutimos-media-hora-porque-no-decidiamos-donde-cenar', 'Discutimos media hora porque no decidíamos dónde cenar', '🍽️', NULL, 'relaciones', 'approved'),
  ('mi-pareja-vio-un-partido-de-futbol-el-dia-de-nuestro-anivers', 'Mi pareja vio un partido de fútbol el día de nuestro aniversario', '⚽', 'Sigo sin perdonarlo del todo.', 'relaciones', 'approved'),
  ('olvide-nuestro-aniversario-y-me-entere-por-su-story', 'Olvidé nuestro aniversario y me enteré por su Story', '📅', NULL, 'relaciones', 'approved'),
  ('le-regale-a-mi-pareja-una-cubitera-por-su-cumpleanos', 'Le regalé a mi pareja una cubitera por su cumpleaños', '🧊', 'Aún se acuerda dos años después.', 'relaciones', 'approved'),
  ('compare-mi-aniversario-con-los-de-instagram-y-me-deprimi', 'Comparé mi aniversario con los de Instagram y me deprimí', '📸', NULL, 'relaciones', 'approved'),
  ('vivo-con-mi-pareja-y-nos-peleamos-por-el-orden-del-bano', 'Vivo con mi pareja y nos peleamos por el orden del baño', '🚽', 'La toalla mojada en la cama, otra vez.', 'relaciones', 'approved'),
  ('tuvimos-una-pelea-epica-por-quien-saca-la-basura', 'Tuvimos una pelea épica por quién saca la basura', '🗑️', 'Llevamos un Excel ahora.', 'relaciones', 'approved'),
  ('bloquee-y-desbloquee-a-mi-ex-diez-veces-en-una-semana', 'Bloqueé y desbloqueé a mi ex diez veces en una semana', '🔄', NULL, 'relaciones', 'approved'),
  ('tuve-un-crush-en-clase-y-solo-le-mire-durante-un-cuatrimestr', 'Tuve un crush en clase y solo le miré durante un cuatrimestre entero', '👁️', NULL, 'relaciones', 'approved'),
  ('mi-crush-me-dejo-un-mensaje-sin-leer-durante-un-mes', 'Mi crush me dejó un mensaje sin leer durante un mes', '💌', 'Y aún así seguía con esperanzas.', 'relaciones', 'approved'),
  ('puse-los-cuernos-en-una-boda-con-la-prima-del-novio', 'Puse los cuernos en una boda con la prima del novio', '👰', NULL, 'relaciones', 'approved'),
  ('me-pusieron-los-cuernos-con-mi-mejor-amigo', 'Me pusieron los cuernos con mi mejor amigo', '🗡️', 'Perdí dos personas en una noche.', 'relaciones', 'approved'),
  ('sospeche-que-me-ponian-los-cuernos-durante-tres-meses', 'Sospeché que me ponían los cuernos durante tres meses', '🤔', NULL, 'relaciones', 'approved'),
  ('solte-una-frase-de-ligar-tan-mala-que-se-rio-en-mi-cara', 'Solté una frase de ligar tan mala que se rió en mi cara', '🍻', 'Le dije Tu padre es ladrón, qué horror.', 'relaciones', 'approved'),
  ('pedi-bizum-a-mi-cita-por-la-mitad-de-la-cuenta', 'Pedí Bizum a mi cita por la mitad de la cuenta', '💸', 'No hubo segunda cita, sorpresa.', 'relaciones', 'approved'),
  ('mande-un-mensaje-a-mi-ex-a-las-3am-estando-borracho-perdido', 'Mandé un mensaje a mi ex a las 3am estando borracho perdido', '🌙', NULL, 'relaciones', 'approved'),
  ('folle-con-quien-no-debia-estando-borracho', 'Follé con quien NO debía estando borracho', '🙈', 'Sigo evitando ese bar a día de hoy.', 'relaciones', 'approved'),
  ('me-desperte-en-la-cama-de-un-desconocido-sin-saber-ni-el-nom', 'Me desperté en la cama de un desconocido sin saber ni el nombre', '🛌', NULL, 'relaciones', 'approved'),
  ('sali-de-su-casa-de-puntillas-al-amanecer-sin-despedirme', 'Salí de su casa de puntillas al amanecer sin despedirme', '🚪', 'Casi me llevo sus llaves por error.', 'relaciones', 'approved'),
  ('me-duche-en-casa-de-alguien-que-acababa-de-conocer', 'Me duché en casa de alguien que acababa de conocer', '🚿', NULL, 'relaciones', 'approved'),
  ('ligue-por-dms-de-instagram-y-acabamos-saliendo-ano-y-medio', 'Ligué por DMs de Instagram y acabamos saliendo año y medio', '📩', 'Funciona más de lo que parece.', 'relaciones', 'approved'),
  ('tire-ficha-por-linkedin-y-se-lo-tomo-como-spam-profesional', 'Tiré ficha por LinkedIn y se lo tomó como spam profesional', '💼', NULL, 'relaciones', 'approved'),
  ('ligue-con-alguien-en-el-gimnasio-y-ahora-le-evito-como-a-la', 'Ligué con alguien en el gimnasio y ahora le evito como a la peste', '🏋️', NULL, 'relaciones', 'approved'),
  ('dije-no-a-una-pedida-de-mano-en-un-restaurante-lleno', 'Dije no a una pedida de mano en un restaurante lleno', '💍', 'Las miradas, joder, las miradas.', 'relaciones', 'approved'),
  ('improvise-un-anillo-con-la-anilla-de-una-lata-para-pedirle-m', 'Improvisé un anillo con la anilla de una lata para pedirle matrimonio', '🥫', NULL, 'relaciones', 'approved'),
  ('vi-el-compromiso-de-mi-ex-en-instagram-el-mismo-dia-que-lo-s', 'Vi el compromiso de mi ex en Instagram el mismo día que lo subió', '💔', 'Lloré viendo el carrusel.', 'relaciones', 'approved'),
  ('fingi-que-me-caia-bien-mi-suegra-durante-cuatro-navidades-se', 'Fingí que me caía bien mi suegra durante cuatro Navidades seguidas', '🎄', NULL, 'relaciones', 'approved'),
  ('mi-cunada-me-odia-desde-la-primera-comida-y-nadie-sabe-por-q', 'Mi cuñada me odia desde la primera comida y nadie sabe por qué', '😠', NULL, 'relaciones', 'approved'),
  ('mi-suegro-lleva-llamandome-por-otro-nombre-cinco-anos', 'Mi suegro lleva llamándome por otro nombre cinco años', '👴', 'Ya ni le corrijo, joder.', 'relaciones', 'approved'),
  ('hice-match-con-la-prima-de-mi-mejor-amigo-en-tinder', 'Hice match con la prima de mi mejor amigo en Tinder', '😅', NULL, 'relaciones', 'approved'),
  ('vi-a-la-pareja-de-mi-amigo-en-tinder-swipeando-activamente', 'Vi a la pareja de mi amigo en Tinder swipeando activamente', '🚨', 'Y tuve que decidir si decirlo.', 'relaciones', 'approved'),
  ('me-cogieron-stalkeando-porque-le-di-like-sin-querer-a-algo-d', 'Me cogieron stalkeando porque le di like sin querer a algo de 2017', '😵', NULL, 'relaciones', 'approved'),
  ('cocine-paella-para-impresionar-y-salio-un-arroz-quemado', 'Cociné paella para impresionar y salió un arroz quemado', '🥘', 'Pidió pizza y aún sigue conmigo.', 'relaciones', 'approved'),
  ('prepare-una-playlist-especifica-para-una-cita-y-sono-la-del', 'Preparé una playlist específica para una cita y sonó la del gym', '🎶', 'Sonó reggaetón en pleno momento.', 'relaciones', 'approved'),
  ('pille-a-mi-pareja-leyendo-mis-mensajes-con-mi-mejor-amiga', 'Pillé a mi pareja leyendo mis mensajes con mi mejor amiga', '📖', NULL, 'relaciones', 'approved'),
  ('cree-una-cuenta-falsa-para-testear-la-fidelidad-de-mi-pareja', 'Creé una cuenta falsa para testear la fidelidad de mi pareja', '🎭', 'Pasó el test y aún me siento culpable.', 'relaciones', 'approved'),
  ('segui-a-mi-pareja-a-una-discoteca-para-ver-con-quien-iba', 'Seguí a mi pareja a una discoteca para ver con quién iba', '🪩', NULL, 'relaciones', 'approved'),
  ('aun-sigo-el-instagram-de-mi-amor-platonico-del-instituto', 'Aún sigo el Instagram de mi amor platónico del instituto', '🎓', NULL, 'relaciones', 'approved'),
  ('stalkee-hasta-el-pinterest-de-la-nueva-pareja-de-mi-ex', 'Stalkeé hasta el Pinterest de la nueva pareja de mi ex', '🪡', 'Tiene un tablero de bodas, joder.', 'relaciones', 'approved'),
  ('mande-el-screenshot-de-la-persona-a-la-propia-persona', 'Mandé el screenshot de la persona a la propia persona', '📸', NULL, 'relaciones', 'approved'),
  ('lleve-a-una-cita-al-bar-donde-curra-mi-ex-sin-saberlo', 'Llevé a una cita al bar donde curra mi ex sin saberlo', '🍺', 'La cara de mi ex no tenía precio.', 'relaciones', 'approved'),
  ('pague-la-cuenta-entera-en-una-cita-y-no-me-devolvio-ni-graci', 'Pagué la cuenta entera en una cita y no me devolvió ni gracias', '💳', 'Aprendizaje caro, literal.', 'relaciones', 'approved'),
  ('no-me-devolvio-nunca-el-bizum-de-la-primera-cita', 'No me devolvió nunca el Bizum de la primera cita', '💸', NULL, 'relaciones', 'approved'),
  ('hice-match-en-tinder-en-un-aeropuerto-y-nunca-le-vi-en-mi-vi', 'Hice match en Tinder en un aeropuerto y nunca le vi en mi vida', '✈️', 'Estaba a tres metros, lo juro.', 'relaciones', 'approved'),
  ('cite-a-cinco-personas-distintas-en-la-misma-semana', 'Cité a cinco personas distintas en la misma semana', '📆', 'Acabé sin ganas de quedar con nadie.', 'relaciones', 'approved'),
  ('solte-el-clasico-no-eres-tu-soy-yo-y-me-lo-crei', 'Solté el clásico no eres tú soy yo y me lo creí', '🎬', 'Era él, lo era todo el rato.', 'relaciones', 'approved'),
  ('me-dijeron-no-eres-tu-soy-yo-y-me-hundi-dos-meses', 'Me dijeron no eres tú soy yo y me hundí dos meses', '🪦', NULL, 'relaciones', 'approved'),
  ('corte-con-mi-pareja-en-un-aeropuerto-antes-de-embarcar', 'Corté con mi pareja en un aeropuerto antes de embarcar', '✈️', 'El vuelo se me hizo eterno.', 'relaciones', 'approved'),
  ('me-cortaron-el-dia-de-mi-cumpleanos', 'Me cortaron el día de mi cumpleaños', '🎂', NULL, 'relaciones', 'approved'),
  ('cortamos-en-nochebuena-y-comi-con-mi-familia-llorando', 'Cortamos en Nochebuena y comí con mi familia llorando', '🎄', 'Mi madre fingió que no notaba nada.', 'relaciones', 'approved'),
  ('llore-en-el-pasillo-de-cereales-del-mercadona-por-una-ruptur', 'Lloré en el pasillo de cereales del Mercadona por una ruptura', '🥣', 'Una señora me dio un abrazo, gracias.', 'relaciones', 'approved'),
  ('borre-todas-las-fotos-con-mi-pareja-de-instagram-en-una-sola', 'Borré todas las fotos con mi pareja de Instagram en una sola sesión', '🗑️', 'Veintidós fotos, se quedó vacío.', 'relaciones', 'approved'),
  ('queme-cartas-de-mi-ex-en-una-bandeja-del-horno', 'Quemé cartas de mi ex en una bandeja del horno', '🔥', 'Casi se me quema la cocina entera.', 'relaciones', 'approved'),
  ('tuve-que-volver-a-recoger-mis-cosas-al-piso-de-mi-ex-y-fue-h', 'Tuve que volver a recoger mis cosas al piso de mi ex y fue horror', '📦', 'Lloramos los dos en la puerta.', 'relaciones', 'approved'),
  ('sali-con-la-ex-de-un-amigo-y-perdimos-la-amistad', 'Salí con la ex de un amigo y perdimos la amistad', '🤝', 'No mereció la pena, lo confirmo.', 'relaciones', 'approved'),
  ('tuve-una-pelea-con-mi-pareja-en-la-fiesta-de-un-amigo', 'Tuve una pelea con mi pareja en la fiesta de un amigo', '🥳', NULL, 'relaciones', 'approved'),
  ('fingi-toda-la-cena-que-me-caian-bien-los-amigos-de-mi-pareja', 'Fingí toda la cena que me caían bien los amigos de mi pareja', '🍷', 'Me dolía la cara de sonreír.', 'relaciones', 'approved'),
  ('estoy-en-un-grupo-de-whatsapp-de-parejas-y-me-da-verguenza-b', 'Estoy en un grupo de WhatsApp de parejas y me da vergüenza brutal', '👥', NULL, 'relaciones', 'approved'),
  ('discutimos-quien-pagaba-la-cena-delante-del-camarero-diez-mi', 'Discutimos quién pagaba la cena delante del camarero diez minutos', '🧾', 'El camarero quería morirse.', 'relaciones', 'approved'),
  ('pille-a-la-pareja-de-mi-amigo-en-tinder-y-no-supe-que-hacer', 'Pillé a la pareja de mi amigo en Tinder y no supe qué hacer', '😶', 'Sigue dándome vueltas, joder.', 'relaciones', 'approved'),
  ('mande-un-mensaje-subido-de-tono-a-mi-padre-por-error', 'Mandé un mensaje subido de tono a mi padre por error', '🆘', NULL, 'relaciones', 'approved'),
  ('cree-un-grupo-de-whatsapp-solo-para-analizar-mensajes-de-mi', 'Creé un grupo de WhatsApp solo para analizar mensajes de mi ex', '🔬', 'Lo seguimos usando dos años después.', 'relaciones', 'approved'),
  ('puse-a-mi-pareja-de-fondo-de-pantalla-y-cortamos-a-la-semana', 'Puse a mi pareja de fondo de pantalla y cortamos a la semana', '🖼️', NULL, 'relaciones', 'approved'),
  ('me-tatue-las-iniciales-de-mi-pareja-y-luego-rompimos', 'Me tatué las iniciales de mi pareja y luego rompimos', '🖋️', 'Ahora son las de mi gata, listo.', 'relaciones', 'approved'),
  ('llevo-cinco-anos-con-la-pareja-que-conoci-en-tinder-y-nadie', 'Llevo cinco años con la pareja que conocí en Tinder y nadie nos cree', '💞', NULL, 'relaciones', 'approved'),
  ('conoci-a-alguien-en-un-funeral-y-acabamos-saliendo-medio-ano', 'Conocí a alguien en un funeral y acabamos saliendo medio año', '🕯️', 'Lo más raro de mi historial.', 'relaciones', 'approved'),
  ('lie-con-la-prima-de-la-novia-en-la-boda-de-mi-mejor-amigo', 'Lié con la prima de la novia en la boda de mi mejor amigo', '👰', NULL, 'relaciones', 'approved'),
  ('baile-un-lento-con-un-desconocido-en-una-boda', 'Bailé un lento con un desconocido en una boda', '💃', 'Su madre me dio el teléfono después.', 'relaciones', 'approved'),
  ('conoci-a-alguien-en-el-gym-y-ahora-cambio-de-horario-para-no', 'Conocí a alguien en el gym y ahora cambio de horario para no verle', '🏋️‍♀️', NULL, 'relaciones', 'approved'),
  ('stalkee-el-spotify-de-mi-pareja-para-ver-que-escucha-cuando', 'Stalkeé el Spotify de mi pareja para ver qué escucha cuando llora', '🎧', 'Era reggaetón triste, no preguntéis.', 'relaciones', 'approved'),
  ('le-quite-mi-cuenta-de-netflix-al-dia-siguiente-de-cortar', 'Le quité mi cuenta de Netflix al día siguiente de cortar', '✂️', NULL, 'relaciones', 'approved'),
  ('perdi-la-clave-de-spotify-family-que-pagaba-mi-ex', 'Perdí la clave de Spotify Family que pagaba mi ex', '🎵', 'Me llevó dos meses asumir HBO solo.', 'relaciones', 'approved'),
  ('le-mande-un-dejame-en-paz-a-mi-ex-y-le-respondi-dos-horas-de', 'Le mandé un déjame en paz a mi ex y le respondí dos horas después', '📵', NULL, 'relaciones', 'approved'),
  ('mi-grupo-de-amigos-se-dividio-en-bandos-cuando-rompi-con-mi', 'Mi grupo de amigos se dividió en bandos cuando rompí con mi pareja', '⚔️', 'Aún no nos hablamos algunos.', 'relaciones', 'approved'),
  ('mi-amiga-empezo-a-salir-con-mi-ex-y-la-perdi', 'Mi amiga empezó a salir con mi ex y la perdí', '😔', NULL, 'relaciones', 'approved'),
  ('comente-una-foto-de-la-pareja-de-un-amigo-con-un-emoji-raro', 'Comenté una foto de la pareja de un amigo con un emoji raro', '🥵', 'Mi amigo me mira con sospecha desde entonces.', 'relaciones', 'approved'),
  ('bloquee-el-numero-de-los-padres-de-mi-pareja-por-error', 'Bloqueé el número de los padres de mi pareja por error', '📞', 'Tardé tres meses en darme cuenta.', 'relaciones', 'approved'),
  ('llame-a-mi-pareja-por-otro-nombre-en-pleno-momento-intimo', 'Llamé a mi pareja por otro nombre en pleno momento íntimo', '🗣️', NULL, 'relaciones', 'approved'),
  ('pase-del-te-quiero-al-ya-no-en-la-misma-noche', 'Pasé del te quiero al ya no en la misma noche', '⌛', 'Y juro que lo decía en serio las dos veces.', 'relaciones', 'approved'),
  ('mi-pareja-de-tres-anos-no-sabe-cual-es-mi-cancion-favorita', 'Mi pareja de tres años no sabe cuál es mi canción favorita', '🎼', NULL, 'relaciones', 'approved'),
  ('hice-match-con-alguien-que-vivia-en-mi-mismo-edificio-sin-sa', 'Hice match con alguien que vivía en mi mismo edificio sin saberlo', '🏢', 'Nos cruzamos en el ascensor al día siguiente.', 'relaciones', 'approved'),
  ('volvi-con-mi-pareja-toxica-tres-veces-seguidas', 'Volví con mi pareja tóxica tres veces seguidas', '🔁', NULL, 'relaciones', 'approved'),
  ('mi-amiga-me-llevaba-anos-diciendo-deja-a-tu-pareja-y-por-fin', 'Mi amiga me llevaba años diciendo deja a tu pareja y por fin lo hice', '💪', 'Tarde pero llegué, joder.', 'relaciones', 'approved'),
  ('tire-dos-copas-en-una-cita-en-un-bar-pijo-de-madrid', 'Tiré dos copas en una cita en un bar pijo de Madrid', '🍷', NULL, 'relaciones', 'approved'),
  ('tartamudee-tanto-en-una-primera-cita-que-parecio-que-no-habl', 'Tartamudeé tanto en una primera cita que pareció que no hablaba español', '😵‍💫', 'Le dio penita y aceptó la segunda.', 'relaciones', 'approved'),
  ('perdi-las-llaves-de-la-casa-de-mi-pareja-la-primera-vez-que', 'Perdí las llaves de la casa de mi pareja la primera vez que dormí allí', '🔑', NULL, 'relaciones', 'approved'),
  ('mi-madre-me-encontro-tinder-abierto-en-mi-tablet', 'Mi madre me encontró Tinder abierto en mi tablet', '🤱', 'Tuvimos LA conversación.', 'relaciones', 'approved'),
  ('mi-grupo-de-amigos-sabe-mas-detalles-de-mi-relacion-que-mi-p', 'Mi grupo de amigos sabe más detalles de mi relación que mi pareja', '🫣', NULL, 'relaciones', 'approved'),
  ('conte-detalles-intimos-de-mi-pareja-en-el-grupo-del-trabajo', 'Conté detalles íntimos de mi pareja en el grupo del trabajo', '🙊', 'Nunca más, lo prometo.', 'relaciones', 'approved'),
  ('llore-con-una-cancion-tres-anos-despues-de-cortar-con-mi-ex', 'Lloré con una canción tres años después de cortar con mi ex', '🎶', NULL, 'relaciones', 'approved'),
  ('llevo-anos-sin-volver-al-restaurante-favorito-de-mi-ex-y-yo', 'Llevo años sin volver al restaurante favorito de mi ex y yo', '🍝', 'Y era buenísimo, joder.', 'relaciones', 'approved'),
  ('borre-todas-las-fotos-con-mi-ex-y-descubri-que-tenia-800', 'Borré todas las fotos con mi ex y descubrí que tenía 800', '🖼️', NULL, 'relaciones', 'approved'),
  ('mi-amiga-me-presta-su-cuenta-fake-para-stalkear-a-mi-ex', 'Mi amiga me presta su cuenta fake para stalkear a mi ex', '🤝', 'Es nuestro acuerdo sagrado.', 'relaciones', 'approved'),
  ('pague-tarot-online-para-preguntar-si-mi-ex-iba-a-volver', 'Pagué tarot online para preguntar si mi ex iba a volver', '🔮', 'Dijo que no y aún seguí preguntando.', 'relaciones', 'approved'),
  ('baje-tinder-de-vacaciones-y-hice-match-a-800-km-de-mi-pareja', 'Bajé Tinder de vacaciones y hice match a 800 km de mi pareja', '🏖️', NULL, 'relaciones', 'approved'),
  ('ligue-con-el-camarero-del-hotel-toda-la-semana-de-vacaciones', 'Ligué con el camarero del hotel toda la semana de vacaciones', '🍹', NULL, 'relaciones', 'approved'),
  ('volvi-de-vacaciones-decidida-a-cortar-y-aun-tarde-seis-meses', 'Volví de vacaciones decidida a cortar y aún tardé seis meses', '🧳', 'Cobardía pura.', 'relaciones', 'approved'),
  ('mi-pareja-friendzoneo-a-mi-mejor-amigo-antes-de-conocerme', 'Mi pareja friendzoneó a mi mejor amigo antes de conocerme', '🤡', 'Las cenas son interesantes ahora.', 'relaciones', 'approved'),
  ('el-camarero-del-bar-de-citas-se-acuerda-de-mi-y-de-todas', 'El camarero del bar de citas se acuerda de mí y de TODAS', '👋', 'Me sonríe con compasión.', 'relaciones', 'approved'),
  ('compre-confeti-para-el-aniversario-y-le-explote-en-la-cara-a', 'Compré confeti para el aniversario y le exploté en la cara a mi pareja', '🎊', NULL, 'relaciones', 'approved'),
  ('lleve-flores-a-una-primera-cita-y-le-dio-repelus', 'Llevé flores a una primera cita y le dio repelús', '💐', 'Pasaba de mí desde el minuto cero.', 'relaciones', 'approved'),
  ('me-llegaron-flores-al-trabajo-y-jure-que-nunca-mas', 'Me llegaron flores al trabajo y juré que nunca más', '🌹', NULL, 'relaciones', 'approved'),
  ('mi-suegra-me-dice-cuanto-debo-comer-en-cada-comida-familiar', 'Mi suegra me dice cuánto debo comer en cada comida familiar', '🍽️', 'Y aún así repito plato a propósito.', 'relaciones', 'approved'),
  ('mis-padres-llevan-dos-anos-preguntandome-por-los-nietos', 'Mis padres llevan dos años preguntándome por los nietos', '👶', NULL, 'relaciones', 'approved'),
  ('mi-pareja-conocio-a-mis-amigos-toxicos-y-aun-asi-sigue-conmi', 'Mi pareja conoció a mis amigos tóxicos y aún así sigue conmigo', '😅', 'Es un milagro.', 'relaciones', 'approved'),
  ('conoci-a-mi-pareja-en-el-funeral-de-mi-abuela', 'Conocí a mi pareja en el funeral de mi abuela', '🥀', NULL, 'relaciones', 'approved'),
  ('mi-amigo-me-confeso-cuernos-a-su-pareja-y-le-segui-mintiendo', 'Mi amigo me confesó cuernos a su pareja y le seguí mintiendo', '🤐', 'Acabé pillándome yo en el secreto.', 'relaciones', 'approved'),
  ('acepte-una-cita-por-aburrimiento-un-domingo-por-la-tarde', 'Acepté una cita por aburrimiento un domingo por la tarde', '😪', NULL, 'relaciones', 'approved'),
  ('acepte-una-cita-con-resaca-y-me-arrepenti-en-la-primera-cana', 'Acepté una cita con resaca y me arrepentí en la primera caña', '🍻', 'No volví a aceptar nada un domingo.', 'relaciones', 'approved'),
  ('mando-buenos-dias-a-mi-pareja-desde-hace-cinco-anos-sin-fall', 'Mando buenos días a mi pareja desde hace cinco años sin fallar uno', '🌅', NULL, 'relaciones', 'approved'),
  ('llevamos-un-excel-de-tareas-de-casa-y-nos-peleamos-cada-lune', 'Llevamos un Excel de tareas de casa y nos peleamos cada lunes', '📊', 'No funciona pero lo mantenemos.', 'relaciones', 'approved'),
  ('tengo-celos-del-videojuego-que-juega-mi-pareja-por-las-noche', 'Tengo celos del videojuego que juega mi pareja por las noches', '🎮', NULL, 'relaciones', 'approved'),
  ('le-tengo-celos-al-perro-de-mi-pareja-en-serio', 'Le tengo celos al perro de mi pareja, en serio', '🐶', 'Le hace más mimos que a mí.', 'relaciones', 'approved'),
  ('mi-pareja-olvido-mi-cumple-pero-felicito-a-su-mejor-amiga', 'Mi pareja olvidó mi cumple pero felicitó a su mejor amiga', '🎉', NULL, 'relaciones', 'approved'),
  ('mi-perfil-de-tinder-tiene-mas-fotos-de-mi-gato-que-mias', 'Mi perfil de Tinder tiene más fotos de mi gato que mías', '🐱', NULL, 'relaciones', 'approved'),
  ('subi-una-foto-en-pareja-cortamos-y-la-deje-un-mes-mas', 'Subí una foto en pareja, cortamos, y la dejé un mes más', '📷', 'Por orgullo, qué triste.', 'relaciones', 'approved'),
  ('probe-el-poliamor-con-mi-pareja-y-explote-a-la-segunda-seman', 'Probé el poliamor con mi pareja y exploté a la segunda semana', '💔', NULL, 'relaciones', 'approved'),
  ('mis-amigos-me-comieron-el-coco-y-le-hice-ghosting-al-partida', 'Mis amigos me comieron el coco y le hice ghosting al partidazo', '🧠', 'Y resulta que era un partidazo, joder.', 'relaciones', 'approved'),
  ('tuve-relacion-de-erasmus-que-duro-cuatro-meses-y-un-vuelo', 'Tuve relación de Erasmus que duró cuatro meses y un vuelo', '🛩️', NULL, 'relaciones', 'approved'),
  ('mi-pareja-de-erasmus-se-fue-y-nunca-volvio-a-contestar', 'Mi pareja de Erasmus se fue y nunca volvió a contestar', '✈️', 'Lo entiendo y me jode al mismo tiempo.', 'relaciones', 'approved'),
  ('firmamos-un-piso-juntos-y-cortamos-antes-de-mudarnos', 'Firmamos un piso juntos y cortamos antes de mudarnos', '🏠', NULL, 'relaciones', 'approved'),
  ('vivimos-juntos-seis-meses-y-rompimos-en-el-septimo', 'Vivimos juntos seis meses y rompimos en el séptimo', '📦', 'El piso aún huele a su champú.', 'relaciones', 'approved'),
  ('me-cortaron-por-mensaje-a-las-8-antes-de-entrar-al-curro', 'Me cortaron por mensaje a las 8 antes de entrar al curro', '⏰', 'Trabajé llorando una jornada entera.', 'relaciones', 'approved'),
  ('acabe-en-una-primera-cita-en-la-misma-mesa-donde-estuve-con', 'Acabé en una primera cita en la misma mesa donde estuve con mi ex', '🪑', 'Misma silla, mismo camarero, todo.', 'relaciones', 'approved'),
  ('cortamos-y-mis-amigos-me-preguntaron-primero-por-mi-ex', 'Cortamos y mis amigos me preguntaron primero por mi ex', '😤', 'Aún no se lo perdono del todo.', 'relaciones', 'approved'),
  ('mi-pareja-no-baila-nunca-en-las-bodas-y-tengo-que-mendigar', 'Mi pareja no baila NUNCA en las bodas y tengo que mendigar', '💃', NULL, 'relaciones', 'approved'),
  ('mi-pareja-elige-siempre-la-peli-en-el-cine-y-siempre-es-mala', 'Mi pareja elige siempre la peli en el cine y siempre es mala', '🎥', 'Pero no me oirás quejarme jamás.', 'relaciones', 'approved'),
  ('discutimos-por-la-marca-de-mantequilla-del-mercadona', 'Discutimos por la marca de mantequilla del Mercadona', '🧈', 'Tres mensajes de paz después.', 'relaciones', 'approved'),
  ('llevamos-cinco-anos-peleando-por-el-cargador-del-movil', 'Llevamos cinco años peleando por el cargador del móvil', '🔌', NULL, 'relaciones', 'approved'),
  ('conoci-a-alguien-por-amigos-comunes-y-acabamos-juntos-un-ano', 'Conocí a alguien por amigos comunes y acabamos juntos un año', '🤝', 'Las cosas más simples salen bien.', 'relaciones', 'approved'),
  ('mi-pareja-y-yo-llevamos-anos-saliendo-y-no-nos-seguimos-en-i', 'Mi pareja y yo llevamos años saliendo y no nos seguimos en Instagram', '🔒', NULL, 'relaciones', 'approved'),
  ('tire-piedrecitas-a-la-ventana-de-mi-crush-y-rompi-el-cristal', 'Tiré piedrecitas a la ventana de mi crush y rompí el cristal', '🪟', NULL, 'relaciones', 'approved'),
  ('pase-andando-por-la-casa-de-mi-ex-tres-veces-el-dia-que-romp', 'Pasé andando por la casa de mi ex tres veces el día que rompí', '🚶', 'Mis pies tienen vida propia.', 'relaciones', 'approved'),
  ('borre-la-app-justo-despues-de-conocer-a-mi-pareja-y-nunca-vo', 'Borré la app justo después de conocer a mi pareja y nunca volví', '🗑️', NULL, 'relaciones', 'approved'),
  ('hice-match-con-alguien-del-trabajo-y-nos-hicimos-los-locos', 'Hice match con alguien del trabajo y nos hicimos los locos', '🤐', 'Fingimos que nunca pasó.', 'relaciones', 'approved'),
  ('tengo-celos-de-una-persona-del-trabajo-de-mi-pareja-desde-ha', 'Tengo celos de UNA persona del trabajo de mi pareja desde hace dos años', '🟥', NULL, 'relaciones', 'approved'),
  ('estuve-saliendo-con-alguien-dos-meses-sin-decirselo-a-mis-am', 'Estuve saliendo con alguien dos meses sin decírselo a mis amigos', '🤫', 'Por supersticiones, no preguntéis.', 'relaciones', 'approved'),
  ('quede-en-una-cita-y-la-persona-del-perfil-ni-existia', 'Quedé en una cita y la persona del perfil ni existía', '🪤', NULL, 'relaciones', 'approved'),
  ('pagamos-cada-uno-nuestra-cuenta-en-un-restaurante-de-anivers', 'Pagamos cada uno nuestra cuenta en un restaurante de aniversario', '🧾', 'No nos hablamos hasta el postre.', 'relaciones', 'approved'),
  ('mantuve-borrador-del-mensaje-de-cortar-dos-meses-antes-de-ma', 'Mantuve borrador del mensaje de cortar dos meses antes de mandarlo', '📝', NULL, 'relaciones', 'approved'),
  ('pense-que-era-una-broma-cuando-me-dijo-quiero-cortar', 'Pensé que era una broma cuando me dijo quiero cortar', '🃏', 'No lo era, joder, no lo era.', 'relaciones', 'approved'),
  ('llore-en-la-tienda-de-vodafone-cancelando-una-promo-familiar', 'Lloré en la tienda de Vodafone cancelando una promo familiar con mi ex', '📱', NULL, 'relaciones', 'approved'),
  ('tinder-me-recomienda-a-mi-propio-primo-y-a-tres-del-curro', 'Tinder me recomienda a mi propio primo y a tres del curro', '🫥', 'Cierro la app cada vez que pasa.', 'relaciones', 'approved'),
  ('conoci-a-mis-suegros-borracho-perdido-en-su-salon', 'Conocí a mis suegros borracho perdido en su salón', '🍷', 'Aún cuentan la anécdota cada Navidad.', 'relaciones', 'approved'),
  ('llegue-a-una-primera-cita-sin-ducharme-y-se-noto', 'Llegué a una primera cita sin ducharme y se notó', '😶‍🌫️', 'Lo lamenté el resto del año.', 'relaciones', 'approved'),
  ('lleve-el-mismo-outfit-a-tres-primeras-citas-seguidas', 'Llevé el mismo outfit a tres primeras citas seguidas', '👔', NULL, 'relaciones', 'approved'),
  ('corte-en-un-restaurante-y-un-camarero-me-aplaudio-de-fondo', 'Corté en un restaurante y un camarero me aplaudió de fondo', '👏', 'Le di propina extra por el apoyo moral.', 'relaciones', 'approved'),
  ('tengo-celos-de-la-mejor-amiga-de-mi-pareja-desde-hace-siglos', 'Tengo celos de la mejor amiga de mi pareja desde hace siglos', '👯', NULL, 'relaciones', 'approved'),
  ('lleve-a-mi-pareja-al-bar-de-mis-amigos-y-todos-sospecharon', 'Llevé a mi pareja al bar de mis amigos y todos sospecharon', '🚩', 'Tenían razón, joder, tenían razón.', 'relaciones', 'approved'),
  ('mi-pareja-no-sabe-en-que-trabajo-despues-de-dos-anos', 'Mi pareja no sabe en qué trabajo después de dos años', '💼', NULL, 'relaciones', 'approved'),
  ('conoci-a-mi-pareja-en-una-comunion-cuando-tenia-12-anos', 'Conocí a mi pareja en una comunión cuando tenía 12 años', '⛪', 'Reaparecimos por Tinder a los 28.', 'relaciones', 'approved'),
  ('corte-con-mi-pareja-por-buzon-de-voz-porque-no-me-lo-cogia', 'Corté con mi pareja por buzón de voz porque no me lo cogía', '📞', 'Lo escuchó con dos amigos al lado.', 'relaciones', 'approved')
on conflict (slug) do nothing;
