-- =================================================================
-- Unlocked seed v3 — AMIGOS (200 entries)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- Requiere migración _012 (categoría 'amigos' en el enum)
-- =================================================================

insert into achievements (slug, title, emoji, description, category, status) values
  ('amigos-cancele-plan-fake-malo', 'Cancelé un plan inventando que estaba malo', '🤥', 'Llevaba dos semanas posponiendolo.', 'amigos', 'approved'),
  ('amigos-mute-grupo-cole', 'Mantengo silenciado el grupo de WhatsApp de mis amigos del cole', '🔕', NULL, 'amigos', 'approved'),
  ('amigos-leido-no-respondido', 'Leí el mensaje, pensé qué responder y no respondí nunca', '👀', 'Tres dias y subiendo.', 'amigos', 'approved'),
  ('amigos-manana-si-fijo', 'Dije "mañana fijo" sabiendo que no iba a ir', '📅', NULL, 'amigos', 'approved'),
  ('amigos-cancele-ultima-hora', 'Cancelé un plan a 20 minutos de salir de casa', '🏃', 'Ya estaba vestido y todo.', 'amigos', 'approved'),
  ('amigos-bizum-meses-despues', 'Mandé un Bizum cuatro meses después de la cena', '💸', NULL, 'amigos', 'approved'),
  ('amigos-bizum-nunca-llego', 'Le presté dinero a un amigo y nunca me lo devolvió', '💰', 'Tampoco lo voy a pedir ya.', 'amigos', 'approved'),
  ('amigos-felicite-copy-paste', 'Copié y pegué el mismo "felicidades" a cinco personas en un día', '🎂', NULL, 'amigos', 'approved'),
  ('amigos-felicite-tarde-cumple', 'Felicité un cumple tres días tarde y disimulé', '🎈', 'Le eché la culpa al WhatsApp.', 'amigos', 'approved'),
  ('amigos-olvide-cumple-mejor-amigo', 'Olvidé el cumpleaños de mi mejor amigo', '😬', NULL, 'amigos', 'approved'),
  ('amigos-regalo-comprado-camino', 'Compré el regalo de boda de camino a la boda', '🎁', NULL, 'amigos', 'approved'),
  ('amigos-llore-borracho-boda', 'Lloré borracho en una boda diciéndole a mi amigo que le quiero', '🥲', 'Al dia siguiente fingi que no me acordaba.', 'amigos', 'approved'),
  ('amigos-excusa-no-ir-boda', 'Inventé una excusa elaboradísima para no ir a una boda', '💍', NULL, 'amigos', 'approved'),
  ('amigos-deje-seguir-cole', 'Dejé de seguir en Instagram a mis amigos del colegio uno a uno', '📵', NULL, 'amigos', 'approved'),
  ('amigos-stories-mute', 'Silencié las stories de mis amigos pero sigo vigilándolas', '👁️', 'Por si me los cruzo y tengo que disimular.', 'amigos', 'approved'),
  ('amigos-vi-stories-plan-no-invitado', 'Vi por stories un plan al que no me invitaron', '📸', NULL, 'amigos', 'approved'),
  ('amigos-finji-no-vi-mensaje', 'Fingí no haber visto el mensaje cuando me preguntó si quería quedar', '🙈', NULL, 'amigos', 'approved'),
  ('amigos-mande-audio-cuatro-min', 'Mandé un audio de cuatro minutos al grupo y nadie lo escuchó', '🎙️', NULL, 'amigos', 'approved'),
  ('amigos-grupo-solo-memes', 'En mi grupo solo hablamos a base de memes desde 2022', '🐸', NULL, 'amigos', 'approved'),
  ('amigos-grupo-muerto-meses', 'Mi grupo principal lleva tres meses sin un solo mensaje', '💀', 'Y nadie se atreve a romper el hielo.', 'amigos', 'approved'),
  ('amigos-ignore-llamada-aposta', 'Ignoré una llamada de un amigo aposta y le mandé "ahora no puedo, llamo luego"', '📵', NULL, 'amigos', 'approved'),
  ('amigos-llego-tarde-siempre', 'Llego tarde a todos los planes y todos lo saben', '⏰', 'Por eso me dicen una hora antes.', 'amigos', 'approved'),
  ('amigos-le-dije-hora-antes', 'Le dije a mi amigo que era una hora antes para que llegase a tiempo', '🕒', NULL, 'amigos', 'approved'),
  ('amigos-espere-una-hora-bar', 'Esperé una hora solo en un bar a un amigo que no daba señales', '🍺', NULL, 'amigos', 'approved'),
  ('amigos-conte-secreto-borracho', 'Conté borracho un secreto que me habían pedido que no contara', '🤐', NULL, 'amigos', 'approved'),
  ('amigos-filtre-cotilleo', 'Filtré un cotilleo que iba a cambiarle la vida a alguien', '🗣️', 'Lo justifiqué con "es que tenia que contarselo a alguien".', 'amigos', 'approved'),
  ('amigos-no-hablamos-seis-meses', 'Estuvimos seis meses sin hablar por una chorrada', '🥶', NULL, 'amigos', 'approved'),
  ('amigos-perdone-por-cansancio', 'Perdoné a una amiga simplemente porque me daba pereza seguir enfadado', '🤷', NULL, 'amigos', 'approved'),
  ('amigos-falsa-reconciliacion', 'Fingí reconciliarme con un amigo y nunca volví a quedar con él', '🕊️', NULL, 'amigos', 'approved'),
  ('amigos-tercero-discordia', 'Soy el tercero en mi grupo de tres y me he dado cuenta este año', '🥉', 'Ellos dos tienen su mundo aparte.', 'amigos', 'approved'),
  ('amigos-amigo-nuevo-desplazo', 'Un amigo me reemplazó por un amigo nuevo y aún no lo he superado', '😔', NULL, 'amigos', 'approved'),
  ('amigos-celos-amistad-nueva', 'Sentí celos cuando mi mejor amiga empezó a quedar con otra', '👯', NULL, 'amigos', 'approved'),
  ('amigos-amigo-pareja-cae-fatal', 'Le caigo fatal a la pareja de mi mejor amigo y lo sé', '🙅', NULL, 'amigos', 'approved'),
  ('amigos-pareja-amigo-mal-rollo', 'Le caen mal mis amigos a mi pareja y mis amigos lo notan', '😬', 'Vivo en una guerra fria perpetua.', 'amigos', 'approved'),
  ('amigos-traicione-equipo-amigos', 'Falté a la cena de mis amigos por la cena de los amigos de mi pareja', '🍽️', NULL, 'amigos', 'approved'),
  ('amigos-plomo-cuenta-anecdota', 'Tengo un amigo que cuenta la misma anécdota cada vez que salimos', '🔁', 'Y todos fingimos que es la primera vez.', 'amigos', 'approved'),
  ('amigos-yo-soy-el-plomo', 'Me he dado cuenta de que el plomo del grupo soy yo', '😶', NULL, 'amigos', 'approved'),
  ('amigos-quejica-grupo', 'Soy el que se queja siempre del bar elegido', '😤', NULL, 'amigos', 'approved'),
  ('amigos-cunadeo-futbol', 'Solté un análisis futbolístico delante de gente que no me había preguntado', '⚽', NULL, 'amigos', 'approved'),
  ('amigos-yo-es-que-soy-de-los-que', 'Empecé una frase con "yo es que soy de los que" en una cena', '🙄', NULL, 'amigos', 'approved'),
  ('amigos-discusion-politica-cena', 'Monté una discusión política en una cena y todos se incomodaron', '🗳️', NULL, 'amigos', 'approved'),
  ('amigos-pegado-plan-no-invitado', 'Me pegué a un plan al que técnicamente no me habían invitado', '🚪', NULL, 'amigos', 'approved'),
  ('amigos-pegado-cena-extra', 'Aparecí en una cena de cinco personas siendo el sexto sin avisar', '🍝', NULL, 'amigos', 'approved'),
  ('amigos-dormi-hotel-sin-pagar', 'Dormí en una habitación de hotel sin pagarla en un viaje con amigos', '🛏️', 'Lo agradeci pero no lo dije.', 'amigos', 'approved'),
  ('amigos-pelea-cuentas-vacaciones', 'Vacaciones con amigos arruinadas por discutir quién paga qué', '🧾', NULL, 'amigos', 'approved'),
  ('amigos-cuatro-cama-doble', 'Dormí cuatro personas en una cama doble en un viaje', '🛌', NULL, 'amigos', 'approved'),
  ('amigos-pelea-airbnb', 'Me peleé con un amigo por la temperatura del aire acondicionado', '🌡️', NULL, 'amigos', 'approved'),
  ('amigos-mudanza-amistad-acaba', 'Me mudé de ciudad y mi grupo de amigos dejó de existir', '📦', NULL, 'amigos', 'approved'),
  ('amigos-stories-unica-conexion', 'Veo las stories de mi mejor amiga y eso es toda nuestra relación ya', '📲', NULL, 'amigos', 'approved'),
  ('amigos-llamar-aniversario-no', 'Quedamos en llamarnos cada semana y llevamos un año sin hablar', '📞', NULL, 'amigos', 'approved'),
  ('amigos-encuentro-bar-fingir', 'Me encontré con un excompañero en un bar y fingimos no vernos', '🍻', NULL, 'amigos', 'approved'),
  ('amigos-cruce-calle-fingir', 'Me crucé con una amiga del cole y nos hicimos las locas', '🚶', NULL, 'amigos', 'approved'),
  ('amigos-cumple-30-sin-grupo', 'Cumplí 30 años sin un grupo claro de amigos', '🕯️', NULL, 'amigos', 'approved'),
  ('amigos-solo-en-fiestas-pueblo', 'Las fiestas del pueblo son el único momento del año que tengo grupo', '🎉', NULL, 'amigos', 'approved'),
  ('amigos-likes-selectivos', 'Doy likes selectivos a las publicaciones de mis amigos según mi humor', '❤️', NULL, 'amigos', 'approved'),
  ('amigos-comentario-fijo-fotos', 'Comento "guapooo" en todas las fotos de un amigo y en las de otro nunca', '💬', NULL, 'amigos', 'approved'),
  ('amigos-ghost-ex-trabajo', 'Cambié de trabajo y nunca más volví a hablar con mis "amigos" del curro', '👋', NULL, 'amigos', 'approved'),
  ('amigos-trabajo-no-fuera', 'Soy amiga de mi compañero solo dentro de la oficina', '💼', NULL, 'amigos', 'approved'),
  ('amigos-conocido-no-amigo', 'Una amistad pasó a ser solo seguirnos en redes', '📱', NULL, 'amigos', 'approved'),
  ('amigos-grupo-cole-disuelto', 'Mi grupo del instituto se disolvió oficialmente y nadie lo dijo', '⚰️', NULL, 'amigos', 'approved'),
  ('amigos-cena-reencuentro-rara', 'Cena de reencuentro con amigos del cole rara y forzada', '🍷', 'Pedi la cuenta a la hora.', 'amigos', 'approved'),
  ('amigos-cole-otra-vida', 'Mis amigos del cole hablan de una vida que ya no es la mía', '🏫', NULL, 'amigos', 'approved'),
  ('amigos-monte-negocio-amigo', 'Monté un negocio con un amigo y perdimos los dos cosas', '📉', NULL, 'amigos', 'approved'),
  ('amigos-presto-dinero-amistad', 'Le presté 500 euros a un amigo y perdí amigo y dinero', '💔', NULL, 'amigos', 'approved'),
  ('amigos-pago-cena-siempre', 'Soy siempre el que adelanta el dinero en las cenas', '🤑', NULL, 'amigos', 'approved'),
  ('amigos-pidio-bizum-3-euros', 'Un amigo me pidió Bizum por 3 euros de unas cervezas', '🍺', NULL, 'amigos', 'approved'),
  ('amigos-soy-tacano-grupo', 'Soy oficialmente el tacaño del grupo y lo asumo', '🪙', NULL, 'amigos', 'approved'),
  ('amigos-microvictoria-no-invitado', 'No me invitaron a un plan y sentí más alivio que pena', '😌', NULL, 'amigos', 'approved'),
  ('amigos-vi-fotos-plan-no-fui', 'Vi fotos en Instagram del plan al que dije que no podía ir', '📷', NULL, 'amigos', 'approved'),
  ('amigos-fake-malo-cama', 'Dije que estaba malo y me quedé toda la tarde en la cama viendo series', '🛋️', NULL, 'amigos', 'approved'),
  ('amigos-excusa-curro-falsa', 'Inventé una reunión de trabajo para no ir a una cena', '📊', NULL, 'amigos', 'approved'),
  ('amigos-excusa-suegra-falsa', 'Mentí diciendo que tenía cena con la familia política', '👵', NULL, 'amigos', 'approved'),
  ('amigos-cancelo-y-quedo-otra', 'Cancelé con unos amigos para quedar con otros más interesantes', '🔄', NULL, 'amigos', 'approved'),
  ('amigos-falso-malo-redes', 'Dije que estaba malo y luego subí stories en una terraza', '🤧', 'Me pillaron y no supe que decir.', 'amigos', 'approved'),
  ('amigos-ignore-cumple-evento', 'Ignoré la invitación de cumple y dejé el evento en visto', '🎂', NULL, 'amigos', 'approved'),
  ('amigos-llegar-tarde-justificar', 'Llegué tarde con una excusa que ni yo me creía', '🚇', NULL, 'amigos', 'approved'),
  ('amigos-evite-llamada-domingo', 'Vi la llamada de mi amiga un domingo y no devolví', '📞', NULL, 'amigos', 'approved'),
  ('amigos-quede-pa-callar', 'Quedé solo para que mi amiga dejara de insistir', '😶‍🌫️', NULL, 'amigos', 'approved'),
  ('amigos-meses-sin-quedar', 'Llevo seis meses sin quedar con mi mejor amiga y aún la llamo así', '⌛', NULL, 'amigos', 'approved'),
  ('amigos-quedamos-tomar-algo', 'Llevamos un año diciéndonos "tenemos que quedar a tomar algo"', '☕', NULL, 'amigos', 'approved'),
  ('amigos-nunca-da-paso', 'Soy siempre yo el que propone planes y un día dejé de hacerlo a ver qué pasaba', '🤐', NULL, 'amigos', 'approved'),
  ('amigos-deje-de-proponer', 'Dejé de proponer planes y descubrí que nadie proponía', '🦗', NULL, 'amigos', 'approved'),
  ('amigos-bloqueo-stories-amiga', 'Bloqueé las stories a una amiga sin que ella lo supiera', '🚫', NULL, 'amigos', 'approved'),
  ('amigos-elimine-foto-grupo', 'Eliminé fotos con un grupo de amigos del que ya no formo parte', '🗑️', NULL, 'amigos', 'approved'),
  ('amigos-perdi-amistad-pareja', 'Perdí una amistad cuando me eché pareja', '💑', NULL, 'amigos', 'approved'),
  ('amigos-pareja-aisla', 'Mi pareja me ha aislado de mis amigos y solo me doy cuenta ahora', '🔒', NULL, 'amigos', 'approved'),
  ('amigos-amigo-soltero-resentido', 'Soy el único soltero del grupo y odio cuando hablan de hipotecas', '🙄', NULL, 'amigos', 'approved'),
  ('amigos-amigo-padre-otro-mundo', 'Un amigo fue padre y dejé de entender de qué hablaba', '👶', NULL, 'amigos', 'approved'),
  ('amigos-cena-padres-aburrida', 'Aguanté una cena entera oyendo hablar de hipotecas y guarderías', '🥱', NULL, 'amigos', 'approved'),
  ('amigos-conoci-amigos-pareja', 'Mis nuevos amigos son los amigos de mi pareja', '🤝', 'Y aun no se si me caen bien.', 'amigos', 'approved'),
  ('amigos-amigos-de-mi-novia', 'Tengo más relación con los amigos de mi pareja que con los míos', '👥', NULL, 'amigos', 'approved'),
  ('amigos-dije-iba-no-fui', 'Confirmé asistencia y al final no aparecí sin avisar', '👻', NULL, 'amigos', 'approved'),
  ('amigos-fantasma-cumple', 'No fui al cumple, no felicité, no di señales', '🪦', NULL, 'amigos', 'approved'),
  ('amigos-grupo-bautizo-incomodo', 'Me invitaron a un bautizo y no sabía qué hacer ahí', '⛪', NULL, 'amigos', 'approved'),
  ('amigos-no-fui-funeral', 'No fui al funeral del padre de un amigo y aún me arrepiento', '🕯️', NULL, 'amigos', 'approved'),
  ('amigos-no-se-que-decir-perdida', 'No supe qué decirle a un amigo cuando perdió a alguien', '🥀', NULL, 'amigos', 'approved'),
  ('amigos-mande-rezo-fb', 'Le puse "mucho ánimo" en Facebook y me sentí fatal', '🙏', NULL, 'amigos', 'approved'),
  ('amigos-amistad-falsa-redes', 'Mantengo la amistad solo a base de likes', '👍', NULL, 'amigos', 'approved'),
  ('amigos-stalkeo-tfg', 'Stalkeé el TFG de un excompañero solo por curiosidad morbosa', '🎓', NULL, 'amigos', 'approved'),
  ('amigos-stalkeo-pareja-amigo', 'Stalkeo cada nueva pareja de mi mejor amiga durante una hora', '🔍', NULL, 'amigos', 'approved'),
  ('amigos-cotilleo-quien-esta-con-quien', 'Hago las stories solo para ver quién está con quién', '👀', NULL, 'amigos', 'approved'),
  ('amigos-grupo-paralelo-criticar', 'Tengo un grupo paralelo donde criticamos al grupo principal', '🤫', NULL, 'amigos', 'approved'),
  ('amigos-grupo-criticar-amigo', 'Estoy en un grupo de WhatsApp donde criticamos a una persona del grupo grande', '😈', NULL, 'amigos', 'approved'),
  ('amigos-saque-tema-criticar-cena', 'Saqué a colación un tema en una cena para criticar a alguien que no estaba', '🗯️', NULL, 'amigos', 'approved'),
  ('amigos-jugue-mediadora', 'Hice de mediadora entre dos amigas que se odiaban y acabé peor', '⚔️', NULL, 'amigos', 'approved'),
  ('amigos-tomar-partido-pelea', 'Tuve que tomar partido en una pelea de amigos y elegí mal', '🤺', NULL, 'amigos', 'approved'),
  ('amigos-no-defendi-cena', 'No defendí a un amigo cuando hablaban mal de él en una cena', '🫥', NULL, 'amigos', 'approved'),
  ('amigos-rie-broma-incomoda', 'Reí una broma de un amigo aunque me pareció hiriente', '😅', NULL, 'amigos', 'approved'),
  ('amigos-broma-hirio-y-segui', 'Hice una broma que dolió a un amigo y seguí como si nada', '🙊', NULL, 'amigos', 'approved'),
  ('amigos-pidio-perdon-no-acepte', 'Me pidió perdón y dije "tranqui no pasa nada" pero sí pasaba', '😐', NULL, 'amigos', 'approved'),
  ('amigos-rencor-anios', 'Llevo años aguantando rencor a una amiga sin que lo sepa', '🪨', NULL, 'amigos', 'approved'),
  ('amigos-corte-amistad-msg', 'Corté una amistad de 10 años con un mensaje de WhatsApp', '✂️', NULL, 'amigos', 'approved'),
  ('amigos-corte-fade-out', 'Acabé una amistad por desgaste sin decir nada', '🌫️', NULL, 'amigos', 'approved'),
  ('amigos-mejor-amigo-instituto', 'Mi mejor amigo del instituto es ahora literalmente un desconocido', '🥲', NULL, 'amigos', 'approved'),
  ('amigos-recuerdo-amistad-llore', 'Vi una foto vieja con mi exmejor amiga y lloré', '📸', NULL, 'amigos', 'approved'),
  ('amigos-borre-numero', 'Borré el número de un amigo en un arrebato', '📵', NULL, 'amigos', 'approved'),
  ('amigos-bloqueo-revertir', 'Bloqueé y desbloqueé a un amigo en menos de una hora', '🔁', NULL, 'amigos', 'approved'),
  ('amigos-vuelvo-stalkeo', 'Stalkeo a un amigo con el que ya no hablo cada dos por tres', '🕵️', NULL, 'amigos', 'approved'),
  ('amigos-segunda-cuenta-stalk', 'Tengo una cuenta secundaria solo para ver perfiles de excompañeros', '🤳', NULL, 'amigos', 'approved'),
  ('amigos-pelicula-amistad-llore', 'Vi una peli sobre amigos y me deprimí pensando en los míos', '🎬', NULL, 'amigos', 'approved'),
  ('amigos-amistades-superficiales-30', 'Llegué a los 30 con muchas amistades superficiales y pocas reales', '🫤', NULL, 'amigos', 'approved'),
  ('amigos-soledad-fin-de-semana', 'Pasé un fin de semana entero sin hablar con nadie y nadie lo notó', '🛏️', NULL, 'amigos', 'approved'),
  ('amigos-quedamos-y-no-dijeron', 'Quedaron y se enteré por casualidad por una historia', '🥺', NULL, 'amigos', 'approved'),
  ('amigos-grupo-pequeno-invitar', 'Hicieron un grupo más pequeño dentro del grupo y no me invitaron', '🚷', NULL, 'amigos', 'approved'),
  ('amigos-cumple-tres-personas', 'Mi cumpleaños fueron tres personas y me hice el feliz', '🎈', NULL, 'amigos', 'approved'),
  ('amigos-cumple-self-organize', 'Tuve que organizar mi propio cumpleaños porque nadie iba a hacerlo', '🎂', NULL, 'amigos', 'approved'),
  ('amigos-prepare-discurso-cena', 'Preparé un discurso para una cena de amigos y lo solté con vergüenza', '🎤', NULL, 'amigos', 'approved'),
  ('amigos-grite-bar-borracho', 'Me puse pesadísimo en un bar diciendo a mis amigos cuánto les quería', '🍻', NULL, 'amigos', 'approved'),
  ('amigos-llore-amigo-bar', 'Lloré en un bar con un amigo y a la mañana siguiente ninguno lo mencionó', '🍷', NULL, 'amigos', 'approved'),
  ('amigos-confesion-borracho-arrepentir', 'Le conté algo íntimo a un amigo borracho y al día siguiente quería desaparecer', '😵', NULL, 'amigos', 'approved'),
  ('amigos-canto-cumpleanos-feliz-yo', 'Canté Cumpleaños Feliz a una amiga por nota de voz desafinando', '🎶', NULL, 'amigos', 'approved'),
  ('amigos-grupo-cumple-rapido', 'Mandé "feliz cumple :)" sin emojis a una persona muy importante', '🥲', NULL, 'amigos', 'approved'),
  ('amigos-grupo-felicitan-uno-uno', 'Solo me felicitaron por el grupo de la familia y no por el de los amigos', '😶', NULL, 'amigos', 'approved'),
  ('amigos-pedi-disculpas-anos-despues', 'Le pedí perdón a una amiga seis años después por algo que ella ya había olvidado', '🕰️', NULL, 'amigos', 'approved'),
  ('amigos-no-fui-despedida', 'No fui a la despedida de soltera y le envié regalo de Amazon', '👰', NULL, 'amigos', 'approved'),
  ('amigos-llore-despedida-piso', 'Lloré en la despedida del piso de mis amigas como si no nos fuéramos a ver', '📦', NULL, 'amigos', 'approved'),
  ('amigos-mudanza-nunca-fui', 'Prometí ayudar en una mudanza y nunca aparecí', '📦', NULL, 'amigos', 'approved'),
  ('amigos-prestar-furgo-no-aparecer', 'Dije que ayudaba con la mudanza y le di excusa esa misma mañana', '🚚', NULL, 'amigos', 'approved'),
  ('amigos-piso-amigo-nunca-fui', 'Mi mejor amigo se mudó hace dos años y aún no he ido a su casa', '🏠', NULL, 'amigos', 'approved'),
  ('amigos-ciudad-nueva-no-visite', 'Mi amiga lleva tres años en otra ciudad y no la he visitado', '✈️', NULL, 'amigos', 'approved'),
  ('amigos-amigo-vuelve-erasmus', 'Volvió de Erasmus y nuestra amistad ya no era igual', '🌍', NULL, 'amigos', 'approved'),
  ('amigos-grupo-erasmus-muerto', 'Mi grupo de Erasmus es ya solo gente que no veré nunca más', '🪦', NULL, 'amigos', 'approved'),
  ('amigos-recordamos-erasmus-only', 'Solo nos recordamos por una foto vieja de Erasmus en aniversario', '🖼️', NULL, 'amigos', 'approved'),
  ('amigos-grupo-uni-disolvio', 'Mi grupo de la uni se disolvió cuando uno se hizo papá', '🍼', NULL, 'amigos', 'approved'),
  ('amigos-ciclo-grupos', 'He cambiado de grupo de amigos como tres veces en mi vida', '🔄', NULL, 'amigos', 'approved'),
  ('amigos-conozco-todos-no-amigo', 'Conozco a mucha gente y no sé si tengo un amigo de verdad', '🫥', NULL, 'amigos', 'approved'),
  ('amigos-amistad-nueva-30', 'A los 30 conocí a alguien con quien hice amistad de verdad', '🫶', NULL, 'amigos', 'approved'),
  ('amigos-amistad-yoga-app', 'Hice una amiga en una clase de yoga a los 28', '🧘', NULL, 'amigos', 'approved'),
  ('amigos-grupo-vinte-cinco', 'Mi grupo más fuerte se formó pasados los 25', '🌱', NULL, 'amigos', 'approved'),
  ('amigos-pidio-prestado-camiseta', 'Le presté una camiseta a un amigo y nunca volvió', '👕', NULL, 'amigos', 'approved'),
  ('amigos-pidio-libro-no-volvio', 'Presté un libro y desde entonces sé que no lo voy a recuperar', '📚', NULL, 'amigos', 'approved'),
  ('amigos-tupper-no-volvio', 'Le di un táper a una amiga y han pasado dos años', '🥡', NULL, 'amigos', 'approved'),
  ('amigos-ps5-amigo-meses', 'Le presté la PS5 a un amigo seis meses', '🎮', NULL, 'amigos', 'approved'),
  ('amigos-la-ultima-y-noche', 'Dije "una más y a casa" y acabé a las 7 con mi mejor amigo', '🍻', NULL, 'amigos', 'approved'),
  ('amigos-perdi-llaves-amigos', 'Perdí las llaves del piso volviendo de fiesta con mis amigos', '🔑', NULL, 'amigos', 'approved'),
  ('amigos-amigo-cargo-mi-borrachera', 'Mi amigo me llevó a casa cargado de borracho y nunca lo agradecí bien', '🤝', NULL, 'amigos', 'approved'),
  ('amigos-sostuve-pelo-amiga', 'Sostuve el pelo a una amiga vomitando y nos hicimos íntimas', '🤢', NULL, 'amigos', 'approved'),
  ('amigos-mejor-amiga-bano-discoteca', 'Hice mejor amiga del bar en el baño de una discoteca', '💃', NULL, 'amigos', 'approved'),
  ('amigos-no-volvi-ver-bar-amiga', 'La mejor amiga del bar no volví a verla en mi vida', '🌙', NULL, 'amigos', 'approved'),
  ('amigos-pagar-uber-amigo', 'Pagué el Uber del amigo borracho y nunca me lo Bizumeó', '🚖', NULL, 'amigos', 'approved'),
  ('amigos-amigo-llamo-llorar-3am', 'Atendí una llamada de un amigo a las 3am llorando y le ayudé', '📱', NULL, 'amigos', 'approved'),
  ('amigos-amigo-3am-yo-no-coji', 'Vi una llamada perdida a las 3am de un amigo y no devolví', '😴', NULL, 'amigos', 'approved'),
  ('amigos-pareja-rota-aguante', 'Aguanté tres horas de WhatsApp a una amiga rota tras una ruptura', '💔', NULL, 'amigos', 'approved'),
  ('amigos-conte-mismo-drama-tres', 'Conté el mismo drama mío a tres amigos distintos', '🎭', NULL, 'amigos', 'approved'),
  ('amigos-finji-escuchar-amiga', 'Fingí escuchar a una amiga mientras pensaba en mis cosas', '🫠', NULL, 'amigos', 'approved'),
  ('amigos-asentir-no-entender', 'Asentí mucho rato sin entender de qué iba la conversación', '🙂', NULL, 'amigos', 'approved'),
  ('amigos-amigo-alarga-cena', 'Mi amigo alarga las cenas hasta las 2am cuando yo solo quería irme', '🥱', NULL, 'amigos', 'approved'),
  ('amigos-fingi-llamada-amiga', 'Fingí una llamada para irme antes de una cena', '📞', NULL, 'amigos', 'approved'),
  ('amigos-irse-frances-grupo', 'Me fui a la francesa de una fiesta con amigos', '🚪', NULL, 'amigos', 'approved'),
  ('amigos-amiga-borde-no-dije', 'Una amiga me trató mal toda la noche y no dije nada', '😶', NULL, 'amigos', 'approved'),
  ('amigos-sumiso-grupo', 'En el grupo siempre acabo aceptando el plan que no quiero', '🦴', NULL, 'amigos', 'approved'),
  ('amigos-dije-todo-bien-no', 'Dije que todo estaba bien y luego me fui llorando al baño', '🚻', NULL, 'amigos', 'approved'),
  ('amigos-mi-amistad-trauma-bond', 'Mi mejor amistad se basa en trauma compartido', '🩹', NULL, 'amigos', 'approved'),
  ('amigos-amistad-medicacion', 'Mi amiga y yo nos contamos qué pastilla tomamos', '💊', NULL, 'amigos', 'approved'),
  ('amigos-llore-foto-grupo-vieja', 'Lloré viendo una foto vieja del grupo en la galería', '😢', NULL, 'amigos', 'approved'),
  ('amigos-busque-fotos-otra-vida', 'Busqué fotos antiguas para recordar que tenía amigos', '🖼️', NULL, 'amigos', 'approved'),
  ('amigos-volvi-leer-conversaciones-amigo', 'Releí conversaciones viejas con un amigo con el que ya no hablo', '💌', NULL, 'amigos', 'approved'),
  ('amigos-grupo-el-mejor-ano', 'Mi mejor año fue uno con un grupo que ya no existe', '🌅', NULL, 'amigos', 'approved'),
  ('amigos-amistad-soltera', 'Cuando se echó pareja la perdí casi del todo', '💔', NULL, 'amigos', 'approved'),
  ('amigos-recuperar-amistad-pelicula', 'Quedé con una amiga después de dos años y fue una peli', '🎞️', NULL, 'amigos', 'approved'),
  ('amigos-quede-uno-cero-grupo', 'Soy el único del grupo que sigue viviendo en el barrio', '🏘️', NULL, 'amigos', 'approved'),
  ('amigos-grupo-disuelto-piso', 'Mi grupo se disolvió cuando dejamos el piso compartido', '🏚️', NULL, 'amigos', 'approved'),
  ('amigos-piso-compartido-querer-matar', 'Quise matar a mi mejor amiga viviendo juntas', '🗡️', NULL, 'amigos', 'approved'),
  ('amigos-guerra-fria-piso', 'Estuve un mes sin hablar con mi compañera de piso por los platos', '🍽️', NULL, 'amigos', 'approved'),
  ('amigos-postit-pasivo-agresivo', 'Dejé un post-it pasivo-agresivo a mi amiga compi de piso', '📝', NULL, 'amigos', 'approved'),
  ('amigos-grupo-piso-cuentas', 'En mi piso compartido los Bizum eran un infierno', '💸', NULL, 'amigos', 'approved'),
  ('amigos-dormi-sofa-amigo-meses', 'Dormí en el sofá de un amigo cuatro meses', '🛋️', NULL, 'amigos', 'approved'),
  ('amigos-acoge-amigo-roto', 'Acogí a un amigo en mi casa cuando rompió con su pareja', '🛏️', NULL, 'amigos', 'approved'),
  ('amigos-recibi-llave-todos-perdi', 'Tuve la llave de la casa de tres amigas y la perdí en alguna fiesta', '🗝️', NULL, 'amigos', 'approved'),
  ('amigos-amigo-pareja-juntar', 'Junté a dos amigos como pareja y luego rompieron y todo fue raro', '💞', NULL, 'amigos', 'approved'),
  ('amigos-rollo-amigo-arrepiento', 'Tuve un rollo con un amigo del grupo y todos lo notaron', '😬', NULL, 'amigos', 'approved'),
  ('amigos-rollo-amiga-secreto', 'Tuve un rollo con la mejor amiga de mi mejor amiga y nunca lo conté', '🤐', NULL, 'amigos', 'approved'),
  ('amigos-cele-de-amistad', 'Tuve celos cuando mi amiga se hizo íntima de otra', '😒', NULL, 'amigos', 'approved'),
  ('amigos-amistad-hetero-tension', 'Tengo una amistad chico-chica que vive de tensión sexual no resuelta', '🌶️', NULL, 'amigos', 'approved'),
  ('amigos-rollo-noche-amistad-danada', 'Una noche con un amigo arruinó la amistad para siempre', '🕯️', NULL, 'amigos', 'approved'),
  ('amigos-amiga-pareja-amigo', 'Mi amiga se lió con un amigo mío y se incomodó todo', '🌀', NULL, 'amigos', 'approved'),
  ('amigos-grupo-rotos-pareja', 'Una pareja de amigos del grupo cortó y nos dividieron', '💔', NULL, 'amigos', 'approved'),
  ('amigos-tomar-bando-ruptura', 'Tuve que elegir bando en la ruptura de dos amigos y elegí mal', '⚖️', NULL, 'amigos', 'approved'),
  ('amigos-foto-grupo-alguien-falta', 'Vi una foto del grupo y noté que faltaba alguien que ya no está', '📸', NULL, 'amigos', 'approved'),
  ('amigos-cumple-faltar-foto-pareja', 'En mi cumple alguien hizo foto y mi mejor amigo no estaba', '🥲', NULL, 'amigos', 'approved'),
  ('amigos-no-tengo-fotos-recientes', 'No tengo una foto reciente con un solo amigo de verdad', '🤳', NULL, 'amigos', 'approved'),
  ('amigos-pago-cuenta-grupo-no-vino', 'Adelanté la cuenta de la cena y el que faltaba nunca pagó', '🧾', NULL, 'amigos', 'approved'),
  ('amigos-cumple-30-amigos-pareja', 'En mi cumple de 30 vinieron más amigos de mi pareja que míos', '🎂', NULL, 'amigos', 'approved'),
  ('amigos-llamar-pa-cosas-recientes', 'Llamo a mi madre antes que a un amigo cuando me pasa algo bueno', '📞', NULL, 'amigos', 'approved'),
  ('amigos-buena-noticia-no-cuento', 'Me pasó algo bueno y no se lo conté a nadie por pereza', '🤐', NULL, 'amigos', 'approved'),
  ('amigos-mensaje-no-leer-amigo', 'Tengo un mensaje sin leer de un amigo desde hace tres semanas', '📬', NULL, 'amigos', 'approved'),
  ('amigos-respondo-resumen-rapido', 'Respondo siempre con tres palabras a mi amiga que escribe novelas', '⌨️', NULL, 'amigos', 'approved'),
  ('amigos-amiga-novela-no-leo', 'Recibo audios de mi amiga y los oigo en x2 sin atención', '🎧', NULL, 'amigos', 'approved'),
  ('amigos-trans-cribir-audio', 'Transcribo los audios de mi amiga porque me da pereza escucharlos', '📝', NULL, 'amigos', 'approved'),
  ('amigos-leer-en-pareja-msg', 'Leo los mensajes del grupo desde la cuenta de mi pareja', '👥', NULL, 'amigos', 'approved'),
  ('amigos-pareja-traduce-grupo', 'Mi pareja conoce a mis amigos solo por lo que cuento del grupo', '💬', NULL, 'amigos', 'approved'),
  ('amigos-comentar-cena-pareja', 'Después de cada cena con amigos hago debrief con mi pareja una hora', '🛋️', NULL, 'amigos', 'approved'),
  ('amigos-conte-pareja-secreto', 'Le conté a mi pareja un secreto que un amigo me había confiado', '🗝️', NULL, 'amigos', 'approved'),
  ('amigos-grupo-foto-perfil-mismo', 'Toda la pandilla cambió la foto de perfil al grupo en una boda menos yo', '📷', NULL, 'amigos', 'approved'),
  ('amigos-foto-perfil-mismos-todos', 'Mi grupo tuvo una época en la que todos teníamos la misma foto de perfil', '🖼️', NULL, 'amigos', 'approved'),
  ('amigos-mote-grupo-vergonzoso', 'Mi grupo me puso un mote y no me he atrevido a decir que lo odio', '🏷️', NULL, 'amigos', 'approved'),
  ('amigos-grupo-mote-decadas', 'Llevo veinte años respondiendo a un mote del cole', '🏷️', NULL, 'amigos', 'approved'),
  ('amigos-grupo-broma-interna-explico', 'Tuve que explicarle una broma interna del grupo a un nuevo y se rompió la magia', '🪄', NULL, 'amigos', 'approved'),
  ('amigos-celos-broma-no-pillo', 'Mis amigos hicieron una broma interna que no pillé y me sentí fuera', '🥲', NULL, 'amigos', 'approved'),
  ('amigos-llegue-tarde-comer-mio', 'Llegué tarde a una comida y todos comieron sin mí', '🍝', NULL, 'amigos', 'approved'),
  ('amigos-ultima-en-llegar-cumple', 'Llegué la última a mi propio cumpleaños', '🎉', NULL, 'amigos', 'approved'),
  ('amigos-escape-room-pesado', 'Soy el pesado del escape room cuando voy con amigos', '🔓', NULL, 'amigos', 'approved'),
  ('amigos-juego-mesa-tramposo', 'Hago trampas en juegos de mesa con amigos y lo niego', '🎲', NULL, 'amigos', 'approved'),
  ('amigos-volver-3-noche-no-decir', 'Salí del bar sin avisar y mis amigos me buscaron una hora', '🌃', NULL, 'amigos', 'approved'),
  ('amigos-perdi-amigo-festival', 'Perdí a mis amigos en un festival y volví solo al hostel', '🎪', NULL, 'amigos', 'approved'),
  ('amigos-grupo-festi-nada-igual', 'Después del festival con mis amigos nada volvió a ser igual', '🌈', NULL, 'amigos', 'approved'),
  ('amigos-grupo-vacas-no-volver', 'Me fui de vacas con un grupo y nunca volveré a ir', '🏖️', NULL, 'amigos', 'approved'),
  ('amigos-cancelo-y-borro-grupo', 'Cancelé en el grupo y silencié notificaciones para no leer las quejas', '🔕', NULL, 'amigos', 'approved'),
  ('amigos-final-sin-pelea', 'La amistad acabó sin pelea, solo se diluyó', '🌫️', NULL, 'amigos', 'approved')
on conflict (slug) do nothing;
