-- =================================================================
-- Unlocked seed v3 — TRABAJO (200 entries)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- =================================================================

insert into achievements (slug, title, emoji, description, category, status) values
  ('trabajo-replied-all-error', 'Le di a "Responder a todos" en un correo que no debía', '📧', 'Quería que se me tragara la silla.', 'trabajo', 'approved'),
  ('trabajo-camara-encendida-pijama', 'Encendí la cámara en Teams y estaba en pijama', '😱', NULL, 'trabajo', 'approved'),
  ('trabajo-tupper-robado', 'Me robaron el túper del frigorífico de la oficina', '🍱', 'Llevaba lentejas de mi madre.', 'trabajo', 'approved'),
  ('trabajo-mute-mal-reunion', 'Hablé pestes del jefe sin saber que tenía el micro abierto', '🎤', NULL, 'trabajo', 'approved'),
  ('trabajo-mover-raton-fake', 'Compré uno de esos cacharros que mueven el ratón solo', '🖱️', 'Productividad teatro nivel pro.', 'trabajo', 'approved'),
  ('trabajo-llorar-en-el-bano', 'Lloré en el baño de la oficina entre reuniones', '🚽', NULL, 'trabajo', 'approved'),
  ('trabajo-dormir-en-teams', 'Me dormí en una reunión de Teams con la cámara puesta', '😴', 'Me despertó mi jefe diciendo mi nombre.', 'trabajo', 'approved'),
  ('trabajo-correo-sin-adjunto', 'Mandé un correo diciendo "adjunto" sin adjuntar nada', '📎', NULL, 'trabajo', 'approved'),
  ('trabajo-mensaje-canal-equivocado', 'Mandé un audio cachondo al canal de la empresa', '😅', 'Lo borré pero ya estaba leído.', 'trabajo', 'approved'),
  ('trabajo-online-2am', 'Me ha salido el verde de Slack a las 3 de la mañana', '🟢', NULL, 'trabajo', 'approved'),
  ('trabajo-jefe-otro-nombre', 'Mi jefe lleva 2 años llamándome por otro nombre', '🙃', 'Ya es tarde para corregirle.', 'trabajo', 'approved'),
  ('trabajo-onboarding-no-encuentro-bano', 'Estuve dos semanas sin saber dónde estaba el baño', '🚻', NULL, 'trabajo', 'approved'),
  ('trabajo-portatil-no-funciona-dia-uno', 'Mi primer día y el portátil no encendía', '💻', 'Me quedé mirando la pared 4 horas.', 'trabajo', 'approved'),
  ('trabajo-ensayar-dimision', 'Ensayé el discurso de dimisión 40 veces frente al espejo', '🪞', NULL, 'trabajo', 'approved'),
  ('trabajo-despido-sin-avisar', 'Me echaron un viernes a las 17:55', '📦', 'Recogí mis cosas en una bolsa de Mercadona.', 'trabajo', 'approved'),
  ('trabajo-mentir-excel', 'Puse "Excel avanzado" en el CV y solo sé sumar', '📊', NULL, 'trabajo', 'approved'),
  ('trabajo-llorar-tras-entrevista', 'Salí de una entrevista y me eché a llorar en el coche', '😢', NULL, 'trabajo', 'approved'),
  ('trabajo-asciendes-sin-subida', 'Me ascendieron pero sin subida de sueldo', '🎖️', 'Es una oportunidad de crecimiento, dijeron.', 'trabajo', 'approved'),
  ('trabajo-comparar-linkedin', 'He visto el ascenso de un ex compañero y se me ha caído el alma', '💼', NULL, 'trabajo', 'approved'),
  ('trabajo-domingo-ansiedad', 'El domingo a las 19h me entra una ansiedad que no veas', '😰', 'Sunday scaries nivel España.', 'trabajo', 'approved'),
  ('trabajo-zoom-desde-playa', 'He hecho una reunión por Zoom desde la playa', '🏖️', NULL, 'trabajo', 'approved'),
  ('trabajo-cama-todo-el-dia', 'He currado en remoto sin salir de la cama en todo el día', '🛏️', NULL, 'trabajo', 'approved'),
  ('trabajo-camara-apagada-siempre', 'Llevo 8 meses en remoto y nadie sabe qué cara tengo', '🫥', NULL, 'trabajo', 'approved'),
  ('trabajo-tabs-abiertas-200', 'Tengo 200 pestañas abiertas y no me atrevo a cerrarlas', '🌐', 'Ahí está mi vida laboral.', 'trabajo', 'approved'),
  ('trabajo-vomitar-cena-empresa', 'Vomité en la cena de empresa', '🤮', NULL, 'trabajo', 'approved'),
  ('trabajo-decir-verdad-borracho', 'Dije lo que pensaba del jefe en la cena de Navidad', '🍷', 'Al día siguiente me hice el dormido.', 'trabajo', 'approved'),
  ('trabajo-post-cringe-linkedin', 'Subí un post a LinkedIn que aún me da vergüenza', '📱', NULL, 'trabajo', 'approved'),
  ('trabajo-mancha-camisa-reunion', 'Llegué a una reunión con cliente con una mancha de café enorme', '☕', NULL, 'trabajo', 'approved'),
  ('trabajo-vestir-mal-formal', 'Llegué en chándal el día que todos iban de traje', '👕', 'Foto de equipo y todo.', 'trabajo', 'approved'),
  ('trabajo-microondas-pescado', 'Calenté pescado en el microondas comunal', '🐟', 'Me odian.', 'trabajo', 'approved'),
  ('trabajo-comer-triste-movil', 'He comido solo mirando el móvil 3 años seguidos', '📱', NULL, 'trabajo', 'approved'),
  ('trabajo-becario-pedir-cafes', 'Mandé al becario a por cafés y se equivocó con todos', '☕', NULL, 'trabajo', 'approved'),
  ('trabajo-jefe-atribuye-trabajo', 'Mi jefe presentó como suyo el trabajo que hice yo', '😤', NULL, 'trabajo', 'approved'),
  ('trabajo-no-me-mencionan-promo', 'No me mencionaron en el correo del proyecto que llevé yo', '📨', 'Como si no existiera.', 'trabajo', 'approved'),
  ('trabajo-cobrar-menos-companero', 'Descubrí que mi compañero cobra 600 más que yo', '💸', NULL, 'trabajo', 'approved'),
  ('trabajo-vuelta-vacaciones-odio', 'El primer día de vuelta de vacaciones me odio a mí mismo', '🌴', NULL, 'trabajo', 'approved'),
  ('trabajo-rrhh-cita-imprevista', 'RRHH me citó "para hablar" y casi me da algo', '📅', NULL, 'trabajo', 'approved'),
  ('trabajo-correo-jefe-cc-sin-querer', 'Puse en copia al jefe en un correo donde le criticaba', '😬', NULL, 'trabajo', 'approved'),
  ('trabajo-asunto-vacio-importante', 'Mandé un correo súper importante con el asunto vacío', '✉️', NULL, 'trabajo', 'approved'),
  ('trabajo-fwd-cadena-personal', 'Reenvié sin querer una cadena de mensajes privados al cliente', '📤', 'Aún tengo pesadillas.', 'trabajo', 'approved'),
  ('trabajo-llegar-tarde-zoom', 'Entré 20 minutos tarde a la reunión "porque iba la VPN"', '⏰', NULL, 'trabajo', 'approved'),
  ('trabajo-micro-bano', 'Me dejé el micro abierto mientras meaba en una reunión', '🚽', 'Lo escuchó toda la sala.', 'trabajo', 'approved'),
  ('trabajo-fondo-virtual-mal', 'Se me cayó el fondo virtual y se vio mi cuarto destrozado', '🛏️', NULL, 'trabajo', 'approved'),
  ('trabajo-perro-ladra-reunion', 'Mi perro se puso a ladrar a mitad de presentación', '🐕', NULL, 'trabajo', 'approved'),
  ('trabajo-padres-entran-reunion', 'Mi madre entró al cuarto en mitad de una reunión gritando', '🚪', '¿Te bajas a por pan?', 'trabajo', 'approved'),
  ('trabajo-pijama-cintura-abajo', 'Camisa arriba, pantalón de pijama abajo en todas las reuniones', '👔', NULL, 'trabajo', 'approved'),
  ('trabajo-no-saber-que-hago', 'Llevo 2 años en mi puesto y aún no sé qué hago exactamente', '🤷', NULL, 'trabajo', 'approved'),
  ('trabajo-tareas-tontas-jefe', 'Mi jefe me manda buscar cosas que él podría googlear', '🔍', NULL, 'trabajo', 'approved'),
  ('trabajo-microgestion-cada-hora', 'Mi jefe me pregunta cada hora cómo va', '⏱️', 'Va igual que hace una hora, Pedro.', 'trabajo', 'approved'),
  ('trabajo-jefe-ignora-mensajes', 'Mi jefe me deja en visto durante días', '👁️', NULL, 'trabajo', 'approved'),
  ('trabajo-companero-olor-fuerte', 'El que se trae cocido madrileño en tupper a la oficina', '🥘', NULL, 'trabajo', 'approved'),
  ('trabajo-companero-silencioso', 'Llevo 4 años sentado al lado de alguien que no me ha hablado', '🤐', NULL, 'trabajo', 'approved'),
  ('trabajo-no-saber-donde-sentarme', 'Día 1 y no sabía dónde sentarme, me quedé de pie media hora', '🪑', NULL, 'trabajo', 'approved'),
  ('trabajo-papel-bano-acabado', 'Me pillé sin papel en el baño de la oficina', '🧻', 'Llamé a un compañero por Slack.', 'trabajo', 'approved'),
  ('trabajo-ascensor-jefe-silencio', 'Coincidí en el ascensor con el director y no dije nada', '🛗', NULL, 'trabajo', 'approved'),
  ('trabajo-cv-error-empresa', 'Mandé el CV con el nombre de otra empresa en el asunto', '📄', NULL, 'trabajo', 'approved'),
  ('trabajo-mentir-ingles-c1', 'Puse C1 en inglés y solo sé "How are you"', '🇬🇧', NULL, 'trabajo', 'approved'),
  ('trabajo-entrevista-encantar-jefe-no-decide', 'Caí muy bien en la entrevista al que no tenía voto', '🤝', NULL, 'trabajo', 'approved'),
  ('trabajo-pregunta-debilidad', 'Dije que mi mayor defecto era ser perfeccionista', '😬', 'Vergüenza ajena nivel pro.', 'trabajo', 'approved'),
  ('trabajo-presentar-sin-preparar', 'Presenté unas slides que no había abierto ni una vez', '🎤', NULL, 'trabajo', 'approved'),
  ('trabajo-improvisar-power-point', 'Hice un Power Point en la pausa de café antes de presentarlo', '📊', NULL, 'trabajo', 'approved'),
  ('trabajo-no-saber-decir-no', 'Me cargaron con todo porque nunca digo que no', '😩', NULL, 'trabajo', 'approved'),
  ('trabajo-trabajar-fin-semana', 'He trabajado un domingo y nadie me lo agradeció', '📆', NULL, 'trabajo', 'approved'),
  ('trabajo-vacaciones-revisar-correo', 'En mis vacaciones miré el correo cada hora', '📧', NULL, 'trabajo', 'approved'),
  ('trabajo-cancelar-cita-medica', 'Cancelé el médico para asistir a una reunión que se canceló', '🏥', 'Vaya tela.', 'trabajo', 'approved'),
  ('trabajo-comer-en-mesa', 'He comido un bocadillo en la mesa mientras curraba', '🥪', 'Migas en el teclado.', 'trabajo', 'approved'),
  ('trabajo-cafe-decimo-del-dia', 'Me tomé el décimo café del día y me temblaba todo', '☕', NULL, 'trabajo', 'approved'),
  ('trabajo-renunciar-y-volver', 'Dimití y a los 6 meses me llamaron y volví', '🔄', NULL, 'trabajo', 'approved'),
  ('trabajo-jefe-pregunta-vacaciones', 'Vaya, justo cuando hay más curro me dijo al pedir vacaciones', '😒', NULL, 'trabajo', 'approved'),
  ('trabajo-cumple-en-oficina', 'Pasé mi cumpleaños currando hasta las 21h', '🎂', NULL, 'trabajo', 'approved'),
  ('trabajo-conectar-ex-linkedin', 'Conecté con mi ex en LinkedIn por aburrimiento', '💔', NULL, 'trabajo', 'approved'),
  ('trabajo-recruiter-rechazo-amable', 'Me rechazaron con un seguiremos en contacto y nunca más', '👻', NULL, 'trabajo', 'approved'),
  ('trabajo-aplicar-100-ofertas', 'Apliqué a 100 ofertas en una semana y solo respondieron 2', '📋', NULL, 'trabajo', 'approved'),
  ('trabajo-prueba-tecnica-no-pagada', 'Hice una prueba técnica de 8 horas y luego me ghostearon', '👻', NULL, 'trabajo', 'approved'),
  ('trabajo-feedback-vago-rechazo', 'Me rechazaron porque no encajaba con la cultura', '🤷', NULL, 'trabajo', 'approved'),
  ('trabajo-burnout-llorar-domingo', 'Lloré un domingo solo de pensar en el lunes', '😭', NULL, 'trabajo', 'approved'),
  ('trabajo-no-dormir-deadline', 'Pasé 3 noches sin dormir por una entrega que nadie miró', '🌙', NULL, 'trabajo', 'approved'),
  ('trabajo-postit-renuncia-cajon', 'Tengo un post-it con RENUNCIA pegado en el cajón', '📝', NULL, 'trabajo', 'approved'),
  ('trabajo-buscar-trabajo-en-trabajo', 'Busco trabajo desde el ordenador del trabajo', '🔎', NULL, 'trabajo', 'approved'),
  ('trabajo-mentir-baja-medica', 'Pedí baja con un dolor de espalda inventado', '🤒', 'Y me fui de finde a Cádiz.', 'trabajo', 'approved'),
  ('trabajo-resaca-trabajar-remoto', 'He currado con resaca brutal sin que se notase, creo', '🥴', NULL, 'trabajo', 'approved'),
  ('trabajo-llamada-perdida-jefe-domingo', 'Llamada perdida del jefe un domingo y casi me da algo', '📞', NULL, 'trabajo', 'approved'),
  ('trabajo-no-contestar-domingo', 'No contesté al jefe un domingo y me sentí muy adulto', '💪', NULL, 'trabajo', 'approved'),
  ('trabajo-grupo-whatsapp-trabajo', 'Estoy en un grupo de WhatsApp del curro y nunca he hablado', '🤐', NULL, 'trabajo', 'approved'),
  ('trabajo-silenciar-grupo-trabajo', 'Tengo silenciado el grupo del curro hasta el año 2099', '🔕', NULL, 'trabajo', 'approved'),
  ('trabajo-programar-correos-tarde', 'He programado correos a las 22h para que parezca que curro tarde', '🕙', NULL, 'trabajo', 'approved'),
  ('trabajo-alt-tab-jefe-pasa', 'Alt+tab compulsivo cada vez que pasa el jefe', '🖥️', NULL, 'trabajo', 'approved'),
  ('trabajo-no-hacer-nada-todo-dia', 'He pasado un día entero sin hacer absolutamente nada', '🦥', 'Y nadie se enteró.', 'trabajo', 'approved'),
  ('trabajo-jefe-pregunta-y-no-se', 'Me preguntó algo el jefe en una reunión y dije lo primero', '🎲', 'Y coló.', 'trabajo', 'approved'),
  ('trabajo-correo-en-cadena-mil-respuestas', 'Llevo 6 meses en una cadena de correos que ya no entiendo', '🔗', NULL, 'trabajo', 'approved'),
  ('trabajo-typo-correo-cliente', 'Mandé un correo al cliente con una falta enorme en el asunto', '📝', NULL, 'trabajo', 'approved'),
  ('trabajo-saludo-formal-mal', 'Empecé un correo con Estimado cuando ya nos tuteábamos', '✉️', NULL, 'trabajo', 'approved'),
  ('trabajo-confundir-canal-slack-personal', 'Mandé un meme de mierda al canal general por error', '💩', NULL, 'trabajo', 'approved'),
  ('trabajo-screenshot-conversacion-mismo-grupo', 'Hice screenshot de un mensaje de Slack y lo pegué en el mismo Slack', '📸', NULL, 'trabajo', 'approved'),
  ('trabajo-escribir-pareja-grupo-empresa', 'Le escribí te amo al grupo de la empresa pensando que era mi pareja', '💌', NULL, 'trabajo', 'approved'),
  ('trabajo-llamar-mama-jefe', 'Llamé mamá a mi jefa por error', '🤦', NULL, 'trabajo', 'approved'),
  ('trabajo-becario-mas-listo', 'El becario sabe más que yo y lo disimulo como puedo', '🤓', NULL, 'trabajo', 'approved'),
  ('trabajo-sentirse-obsoleto', 'Llegó un junior y me hizo sentir un dinosaurio', '🦖', NULL, 'trabajo', 'approved'),
  ('trabajo-no-entender-curso-online', 'Me pusieron a hacer un curso obligatorio y solo le di a siguiente', '📚', NULL, 'trabajo', 'approved'),
  ('trabajo-certificado-falso-curso', 'Le di a siguiente 50 veces y me dieron un certificado', '🏅', NULL, 'trabajo', 'approved'),
  ('trabajo-ticket-soporte-no-leido', 'Llevo un mes esperando que IT responda mi ticket', '🎫', NULL, 'trabajo', 'approved'),
  ('trabajo-it-apaga-y-enciende', 'IT me dijo apaga y enciende y funcionó, qué rabia', '🔌', NULL, 'trabajo', 'approved'),
  ('trabajo-perder-archivo-sin-guardar', 'Word se cerró sin guardar y perdí 4 horas de curro', '😭', NULL, 'trabajo', 'approved'),
  ('trabajo-borrar-excel-companero', 'Borré sin querer el Excel compartido del equipo', '😱', NULL, 'trabajo', 'approved'),
  ('trabajo-formulas-excel-no-funcionan', 'Llevo 3 horas peleándome con un VLOOKUP que no me sale', '📊', NULL, 'trabajo', 'approved'),
  ('trabajo-googlear-cosa-basica', 'He googleado cómo hacer una suma en Excel con 28 años', '🔍', NULL, 'trabajo', 'approved'),
  ('trabajo-chatgpt-respuestas-jefe', 'Le contesto al jefe con cosas que me genera ChatGPT', '🤖', NULL, 'trabajo', 'approved'),
  ('trabajo-ia-hace-mi-trabajo', 'La IA me hace el trabajo y me sobran 6 horas al día', '🤖', NULL, 'trabajo', 'approved'),
  ('trabajo-fingir-leer-pdf', 'Dije que había leído el PDF de 80 páginas sin abrirlo', '📄', NULL, 'trabajo', 'approved'),
  ('trabajo-preguntar-en-reunion-sin-saber', 'Pregunté algo en reunión y ya estaba contestado', '🙋', NULL, 'trabajo', 'approved'),
  ('trabajo-quedar-callado-reunion', 'Me he quedado mudo en una reunión y nadie ha notado mi presencia', '🤐', NULL, 'trabajo', 'approved'),
  ('trabajo-todos-asienten-no-entiendo', 'Asentí en una reunión sin entender ni una palabra', '🙂', NULL, 'trabajo', 'approved'),
  ('trabajo-reunion-podria-ser-correo', 'Me he tragado una reunión de 2h que era un correo', '😑', NULL, 'trabajo', 'approved'),
  ('trabajo-reunion-pre-reunion', 'Tuve una reunión para preparar otra reunión', '🔁', NULL, 'trabajo', 'approved'),
  ('trabajo-calendario-saturado', 'Tengo el calendario tan lleno que no me da tiempo a comer', '📅', NULL, 'trabajo', 'approved'),
  ('trabajo-doble-reunion-elegir', 'Acepté dos reuniones a la vez y me hice el desconectado', '📞', NULL, 'trabajo', 'approved'),
  ('trabajo-bonus-anual-decepcion', 'Llevo todo el año esperando el bonus y han sido 200€', '💸', NULL, 'trabajo', 'approved'),
  ('trabajo-subida-ipc-no-llega', 'La subida no llegó ni a cubrirme el IPC', '📉', NULL, 'trabajo', 'approved'),
  ('trabajo-pedir-aumento-no', 'Pedí aumento y me dijeron el año que viene, como siempre', '😅', NULL, 'trabajo', 'approved'),
  ('trabajo-revisar-nomina-llorar', 'Abrí la nómina y se me cayó el alma a los pies', '💰', NULL, 'trabajo', 'approved'),
  ('trabajo-trabajar-2-trabajos', 'Tengo dos curros remotos a la vez y no se enteran', '🥷', NULL, 'trabajo', 'approved'),
  ('trabajo-freelance-no-pagan', 'El cliente lleva 3 meses sin pagarme la factura', '🧾', NULL, 'trabajo', 'approved'),
  ('trabajo-autonomo-cuota', 'Pago la cuota de autónomo y me echo a llorar', '😭', NULL, 'trabajo', 'approved'),
  ('trabajo-hacienda-paralela', 'Me equivoqué con un modelo y Hacienda me trajo de cabeza', '🏛️', NULL, 'trabajo', 'approved'),
  ('trabajo-companero-pasivo-agresivo', 'Mi compañero me manda correos pasivo-agresivos en CC al jefe', '😡', NULL, 'trabajo', 'approved'),
  ('trabajo-meeting-no-agenda', 'Reunión sin agenda y se ha alargado 90 minutos', '🤯', NULL, 'trabajo', 'approved'),
  ('trabajo-foto-corporativa', 'Salí con cara de psicópata en la foto corporativa de la web', '📸', NULL, 'trabajo', 'approved'),
  ('trabajo-perfil-linkedin-sin-foto', 'Llevo 5 años con la misma foto de LinkedIn que no me parezco', '🖼️', NULL, 'trabajo', 'approved'),
  ('trabajo-entrevista-grupal-callado', 'En una dinámica de grupo no abrí la boca y no me cogieron', '🤐', NULL, 'trabajo', 'approved'),
  ('trabajo-ser-el-que-anota', 'Siempre me toca a mí ser el que toma actas', '✍️', NULL, 'trabajo', 'approved'),
  ('trabajo-organizar-cumple-companero', 'Organizo siempre los cumples y nadie organiza el mío', '🎂', NULL, 'trabajo', 'approved'),
  ('trabajo-amigo-invisible-chusta', 'Me tocó el amigo invisible y me regalaron un boli del banco', '🎁', NULL, 'trabajo', 'approved'),
  ('trabajo-team-building-paintball', 'Nos llevaron a paintball y acabé con moratones', '🎯', NULL, 'trabajo', 'approved'),
  ('trabajo-team-building-cringe', 'Tuvimos que decir una virtud del compañero y morí por dentro', '🙃', NULL, 'trabajo', 'approved'),
  ('trabajo-rol-play-formacion', 'Me hicieron hacer un role play en una formación, vergüenza máxima', '🎭', NULL, 'trabajo', 'approved'),
  ('trabajo-dinamica-romper-hielo', 'Me tocó decir un dato curioso sobre mí en el onboarding', '🧊', 'No tengo ningún dato curioso.', 'trabajo', 'approved'),
  ('trabajo-cliente-cambia-todo-final', 'El cliente lo cambió todo el día antes de la entrega', '🔄', NULL, 'trabajo', 'approved'),
  ('trabajo-cliente-no-sabe-lo-que-quiere', 'El cliente me dijo tú sabes lo que necesito', '🤡', NULL, 'trabajo', 'approved'),
  ('trabajo-cliente-llamar-fin-semana', 'Cliente me llamó un sábado a las 23h y respondí', '☎️', NULL, 'trabajo', 'approved'),
  ('trabajo-presentacion-no-funciona-proyector', 'Presentación importante y el proyector no funcionaba', '📽️', NULL, 'trabajo', 'approved'),
  ('trabajo-clicker-roto', 'Se me quedó tildado el clicker en mitad de la presentación', '🖱️', NULL, 'trabajo', 'approved'),
  ('trabajo-empresa-mudanza-oficina', 'Nos mudaron de oficina y ahora tardo 1h más al día', '🏢', NULL, 'trabajo', 'approved'),
  ('trabajo-vuelta-presencial-obligatoria', 'Nos hicieron volver presencial 5 días y me quiero morir', '🏬', NULL, 'trabajo', 'approved'),
  ('trabajo-metro-hora-punta', 'Cojo metro a las 8 de la mañana y soy una sardina', '🚇', NULL, 'trabajo', 'approved'),
  ('trabajo-aire-acondicionado-helado', 'En la oficina hacen 18 grados y curro con manta', '🥶', NULL, 'trabajo', 'approved'),
  ('trabajo-calefaccion-no-funciona', 'En invierno la oficina está a 14 grados y nadie hace nada', '🥶', NULL, 'trabajo', 'approved'),
  ('trabajo-silla-rota-no-me-cambian', 'Llevo 6 meses con la silla rota y RRHH dice ya veremos', '🪑', NULL, 'trabajo', 'approved'),
  ('trabajo-raton-pad-asqueroso', 'Mi alfombrilla está más sucia que las escaleras del metro', '🐀', NULL, 'trabajo', 'approved'),
  ('trabajo-recibir-merch-empresa', 'Me dieron una sudadera con el logo y la uso para dormir', '👕', NULL, 'trabajo', 'approved'),
  ('trabajo-fingir-no-recibir-mensaje', 'Vi el mensaje del jefe y dije que no me había llegado', '👻', NULL, 'trabajo', 'approved'),
  ('trabajo-hacer-recados-personales', 'He ido al banco y a hacer la compra entre reuniones', '🛒', NULL, 'trabajo', 'approved'),
  ('trabajo-tirar-toda-la-manana', 'He pasado toda la mañana en la cocina hablando con compañeros', '☕', NULL, 'trabajo', 'approved'),
  ('trabajo-fingir-tos-no-ir', 'Fingí una tos para no ir a la oficina', '🤧', NULL, 'trabajo', 'approved'),
  ('trabajo-cita-medica-falsa', 'Inventé una cita médica para salir antes', '🏥', NULL, 'trabajo', 'approved'),
  ('trabajo-novia-emergencia', 'Dije que mi pareja tenía una emergencia para salir antes', '💔', NULL, 'trabajo', 'approved'),
  ('trabajo-funeral-falso', 'Inventé un funeral para coger un día libre', '⚰️', 'No estoy orgulloso.', 'trabajo', 'approved'),
  ('trabajo-cabeza-tortilla', 'Me quedé en blanco delante de un cliente importante', '🧊', NULL, 'trabajo', 'approved'),
  ('trabajo-nombre-cliente-equivocado', 'Llamé al cliente por el nombre del cliente anterior', '😬', NULL, 'trabajo', 'approved'),
  ('trabajo-dejar-vista-conversacion', 'Le dejé en visto al cliente 3 días y aún no he contestado', '👁️', NULL, 'trabajo', 'approved'),
  ('trabajo-mentir-progreso-tarea', 'Dije que iba al 80% y aún no había empezado', '😅', NULL, 'trabajo', 'approved'),
  ('trabajo-empezar-tarea-deadline', 'Empecé el proyecto el día antes de la entrega', '⏰', NULL, 'trabajo', 'approved'),
  ('trabajo-deadline-pedir-prorroga', 'He pedido prórroga 5 veces de la misma tarea', '🐌', NULL, 'trabajo', 'approved'),
  ('trabajo-fin-de-dia-implica-noche', 'Para final del día significa que voy a currar hasta las 23h', '🌙', NULL, 'trabajo', 'approved'),
  ('trabajo-jefe-dice-rapido-y-no', 'Es algo rápido y me ha llevado 3 días', '🐢', NULL, 'trabajo', 'approved'),
  ('trabajo-scope-creep', 'Me pidieron una cosita y acabé haciendo todo el proyecto', '🌱', NULL, 'trabajo', 'approved'),
  ('trabajo-presupuesto-x4', 'Estimé un proyecto en 1 semana y duró 4', '📈', NULL, 'trabajo', 'approved'),
  ('trabajo-saltar-comida-deadline', 'No comí en todo el día por una entrega y nadie lo notó', '🥖', NULL, 'trabajo', 'approved'),
  ('trabajo-llamada-jefe-cena-amigos', 'Mi jefe me llamó en mitad de una cena con amigos y respondí', '🍽️', NULL, 'trabajo', 'approved'),
  ('trabajo-revisar-correo-en-cama', 'Reviso el correo en la cama antes de dormir todos los días', '🛏️', NULL, 'trabajo', 'approved'),
  ('trabajo-sonar-con-jefe', 'Soñé con mi jefe y me desperté llorando', '😱', NULL, 'trabajo', 'approved'),
  ('trabajo-ataque-ansiedad-trabajo', 'Tuve un ataque de ansiedad delante del ordenador', '😰', NULL, 'trabajo', 'approved'),
  ('trabajo-psicologa-por-curro', 'Voy al psicólogo solo por el trabajo', '🛋️', NULL, 'trabajo', 'approved'),
  ('trabajo-baja-ansiedad', 'Estuve de baja por ansiedad 2 meses', '🍃', NULL, 'trabajo', 'approved'),
  ('trabajo-gym-noche-recuperar', 'Voy al gym a las 22h porque es lo único que controlo del día', '💪', NULL, 'trabajo', 'approved'),
  ('trabajo-vino-todas-las-noches', 'Me bebo una copa de vino todas las noches después de currar', '🍷', NULL, 'trabajo', 'approved'),
  ('trabajo-domingo-tarde-deprime', 'Los domingos por la tarde me deprimo solo de pensar', '🌧️', NULL, 'trabajo', 'approved'),
  ('trabajo-sonar-con-dimitir', 'Sueño con dimitir todos los días pero no me atrevo', '🚪', NULL, 'trabajo', 'approved'),
  ('trabajo-comprobar-cuenta-bancaria', 'Reviso la cuenta el día 30 cada hora a ver si entra el sueldo', '🏦', NULL, 'trabajo', 'approved'),
  ('trabajo-dia-pago-esfumado', 'El sueldo me dura 4 días y luego cuenta atrás', '💸', NULL, 'trabajo', 'approved'),
  ('trabajo-prestamo-jefe-rechazado', 'Pedí un adelanto y casi me da algo de la vergüenza', '😳', NULL, 'trabajo', 'approved'),
  ('trabajo-empresa-quebrar-linkedin', 'La empresa quebró y me enteré por LinkedIn', '🚨', NULL, 'trabajo', 'approved'),
  ('trabajo-ere-en-empresa', 'Pasé un ERE y aún tengo pesadillas', '😵', NULL, 'trabajo', 'approved'),
  ('trabajo-no-renovar-contrato', 'No me renovaron el contrato y me enteré el último día', '📝', NULL, 'trabajo', 'approved'),
  ('trabajo-paro-verguenza', 'Cobré paro y me daba vergüenza decirlo', '🫥', NULL, 'trabajo', 'approved'),
  ('trabajo-volver-casa-padres', 'Tuve que volver a casa de mis padres con 30 años por el curro', '🏠', NULL, 'trabajo', 'approved'),
  ('trabajo-tener-que-pluriempleo', 'Tengo dos curros y aún así no llego a fin de mes', '😩', NULL, 'trabajo', 'approved'),
  ('trabajo-reposicion-camarero-uni', 'Acabé la carrera y al final estoy de camarero', '🍽️', NULL, 'trabajo', 'approved'),
  ('trabajo-fingir-saber-uso-printer', 'Llevo 2 años fingiendo que sé usar la impresora', '🖨️', NULL, 'trabajo', 'approved'),
  ('trabajo-papel-jam-impresora', 'Atasqué la impresora y me fui sin avisar', '🖨️', NULL, 'trabajo', 'approved'),
  ('trabajo-cargador-prestado-no-volver', 'Le presté el cargador a alguien y nunca lo recuperé', '🔌', NULL, 'trabajo', 'approved'),
  ('trabajo-grapadora-robada-mesa', 'Me roban la grapadora cada semana', '📎', NULL, 'trabajo', 'approved'),
  ('trabajo-encontrar-regalo-jefe', 'Tuve que comprar regalo para el jefe y no sabía qué', '🎁', NULL, 'trabajo', 'approved'),
  ('trabajo-cantar-cumple-oficina', 'Tuve que cantar el cumpleaños feliz en la oficina y morí', '🎂', NULL, 'trabajo', 'approved'),
  ('trabajo-pillar-jefe-llorando', 'Pillé al jefe llorando en su despacho y no supe qué hacer', '😶', NULL, 'trabajo', 'approved'),
  ('trabajo-pelea-companeros-en-medio', 'Vi a dos compañeras gritarse y me hice el invisible', '🙈', NULL, 'trabajo', 'approved'),
  ('trabajo-rumor-empresa-cierre', 'Llevo un mes con el rumor de que cierran y nadie dice nada', '🤫', NULL, 'trabajo', 'approved'),
  ('trabajo-curro-perfecto-no-existe', 'Llevo años buscando el curro perfecto y entiendo que no existe', '🦄', NULL, 'trabajo', 'approved'),
  ('trabajo-decir-soy-feliz-mentir', 'Cuando preguntan en familia digo muy contento con el curro', '🎭', 'Mentira piadosa.', 'trabajo', 'approved'),
  ('trabajo-pregunta-fines-semana-vacia', 'Me preguntan qué tal el finde y no tengo nada que contar', '🫥', NULL, 'trabajo', 'approved'),
  ('trabajo-ultimo-en-irse', 'Soy siempre el último en irme y nadie me lo agradece', '🌙', NULL, 'trabajo', 'approved')
on conflict (slug) do nothing;
