-- =================================================================
-- Unlocked seed v2 — Part 3 of 4
-- Aplicar en Supabase Dashboard -> SQL Editor (después de Part 2)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- =================================================================

insert into achievements (slug, title, emoji, category, status) values
  ('festivo-trabaje', 'He trabajado un festivo sin darme cuenta de que era festivo', '📅', 'random', 'approved'),
  ('fui-supermercado-hambre', 'He ido al supermercado con hambre', '🛒', 'random', 'approved'),
  ('me-perdi-en-ikea', 'Me perdí en el IKEA', '🪑', 'random', 'approved'),
  ('ensamble-ikea-mal', 'Monté un mueble de IKEA al revés y lo dejé así', '🔧', 'random', 'approved'),
  ('me-quede-dormido-concierto', 'Me quedé dormido en un concierto', '🎶', 'random', 'approved'),
  ('espere-mesa-restaurante-famoso', 'Esperé dos horas en la cola de un restaurante famoso', '⏳', 'random', 'approved'),
  ('perdi-contrasena', 'He perdido la contraseña de una cuenta importante', '🔐', 'random', 'approved'),
  ('olvide-cumpleanos-amigo', 'He olvidado el cumpleaños de mi mejor amigo', '🎂', 'random', 'approved'),
  ('tuve-vecino-ruidoso', 'He tenido el vecino más ruidoso del mundo', '🔊', 'random', 'approved'),
  ('me-equivoque-de-chat', 'Mandé un mensaje al chat equivocado', '💬', 'random', 'approved'),
  ('hice-foto-perfecta-por-accidente', 'Hice la mejor foto de mi vida por accidente', '📸', 'random', 'approved'),
  ('encontre-dinero-bolsillo', 'Encontré dinero en un bolsillo de ropa que no usaba', '💶', 'random', 'approved'),
  ('guarde-ropa-por-si-acaso', 'He guardado ropa que no me ponía "por si acaso" durante años', '👗', 'random', 'approved'),
  ('me-conecte-wifi-nombre-gracioso', 'Me he conectado al WiFi de alguien con nombre gracioso', '📶', 'random', 'approved'),
  ('me-calle-opinion-importante', 'Me callé una opinión importante en el momento en que más importaba', '🤐', 'random', 'approved'),
  ('ordene-cuarto-y-lo-destroce-al-dia', 'Ordené mi cuarto y lo destrocé al día siguiente', '🧹', 'random', 'approved'),
  ('me-di-cuenta-de-algo-anos-despues', 'Me di cuenta de algo evidente que pasé por alto años', '🤦', 'random', 'approved'),
  ('me-regale-a-mi-mismo', 'Me hice un regalo a mí mismo en un día malo', '🎁', 'random', 'approved'),
  ('vi-algo-en-la-calle-no-conte', 'Ví algo en la calle que nadie me creería si lo cuento', '👀', 'random', 'approved'),
  ('meti-ropa-lavadora-sin-separar', 'Teñí toda mi ropa blanca de rosa en la lavadora', '👕', 'random', 'approved'),
  ('me-apunte-newsletter', 'Me apunté a una newsletter y recibo 40 correos al día', '📧', 'random', 'approved'),
  ('llegue-a-tiempo-al-sitio-equivocado', 'Llegué puntual al sitio equivocado', '🗺️', 'random', 'approved'),
  ('comi-caducado', 'He comido algo caducado y me he enterado después', '🥛', 'random', 'approved'),
  ('me-quede-sin-bateria-en-momento-crucial', 'Se me fue el móvil en el momento más inoportuno', '🔋', 'random', 'approved'),
  ('llegue-a-un-sitio-cerrado', 'Llegué a un sitio que estaba cerrado ese día por festivo local', '🚪', 'random', 'approved'),
  ('me-sente-chicle', 'Me senté encima de un chicle en ropa cara', '🩰', 'random', 'approved'),
  ('gaste-en-algo-inutil', 'He gastado dinero en algo que usé una sola vez', '💸', 'random', 'approved'),
  ('me-olvide-de-decir-algo-importante', 'Me olvidé de decir algo importante en el momento correcto', '😶', 'random', 'approved'),
  ('abri-paraguas-adentro', 'Abrí el paraguas dentro de un edificio', '☂️', 'random', 'approved'),
  ('fui-evento-no-era', 'Fui a un evento equivocado', '🎪', 'random', 'approved'),
  ('me-quede-mirando-pantalla', 'Me quedé mirando el móvil sin saber qué estaba buscando', '📱', 'random', 'approved'),
  ('imprimi-mal', 'He imprimido un documento de 30 páginas al revés', '🖨️', 'random', 'approved'),
  ('gaste-en-moda-rapida', 'He comprado ropa que nunca me he puesto', '🛍️', 'random', 'approved'),
  ('me-falle-a-mi-mismo', 'Me prometí hacer algo durante un año y nunca lo hice', '🗓️', 'random', 'approved'),
  ('me-olvide-descongelar', 'Olvidé descongelar la cena y comí otra cosa', '🧊', 'random', 'approved'),
  ('me-dormi-plan', 'Me dormí antes de salir a un plan', '😴', 'random', 'approved'),
  ('camine-al-reves', 'Caminé cinco minutos en la dirección equivocada', '🧭', 'random', 'approved'),
  ('compre-regalo-tarde', 'Compré un regalo de cumpleaños con una semana de retraso', '🎁', 'random', 'approved'),
  ('respondi-no-se-a-pregunta-de-mi-trabajo', 'Respondí "no sé" en algo que debería saber de mi propio trabajo', '🤷', 'random', 'approved'),
  ('me-pille-dedos-cajon', 'Me pillé los dedos con el cajón tres veces seguidas', '🖐️', 'random', 'approved'),
  ('hice-screenshot-de-un-screenshot', 'He hecho captura de pantalla de una captura de pantalla', '📱', 'random', 'approved'),
  ('me-equivoque-de-piso-ascensor', 'Subí una planta de más en el ascensor', '🛗', 'random', 'approved'),
  ('guarde-por-si-acaso-borre', 'Guardé algo por si acaso y lo borré sin querer al poco', '🗑️', 'random', 'approved'),
  ('conteste-mi-propio-mail', 'Me contesté a mí mismo en un email', '📧', 'random', 'approved'),
  ('puse-despertador-tarde-por-error', 'Puse el despertador en PM en lugar de AM', '⏰', 'random', 'approved'),
  ('acumule-basura-sin-bajar', 'He tardado tres semanas en bajar la basura', '🗑️', 'random', 'approved'),
  ('hable-con-el-espejo', 'He practicado una conversación difícil con el espejo', '🪞', 'random', 'approved'),
  ('guarde-algo-para-nunca', 'He guardado algo especial para una ocasión que nunca llegó', '🍾', 'random', 'approved'),
  ('confundi-dia-festivo', 'Pensé que era festivo y no lo era', '📅', 'random', 'approved'),
  ('me-apunte-reto-30-dias', 'Me apunté a un reto de 30 días y lo dejé el día 4', '💪', 'random', 'approved'),
  ('llame-persona-equivocada', 'Llamé por teléfono a la persona equivocada del contacto', '📞', 'random', 'approved'),
  ('mande-voice-sin-querer', 'Mandé un audio de voz a alguien sin darme cuenta', '🎙️', 'random', 'approved'),
  ('compre-doble-lo-mismo', 'Compré algo que ya tenía en casa', '🛒', 'random', 'approved'),
  ('me-asuste-con-mi-reflejo', 'Me asusté con mi propio reflejo pasando por un espejo', '🪞', 'random', 'approved'),
  ('me-olvide-que-tenia-cita', 'Olvidé que tenía cita médica hasta que ya era tarde', '🏥', 'random', 'approved'),
  ('comi-en-orden-incorrecto', 'He comido el postre antes del plato principal sin querer', '🍰', 'random', 'approved'),
  ('me-puse-jersey-al-reves', 'Me puse el jersey del revés y no lo cambié', '🧥', 'random', 'approved'),
  ('me-pase-de-parada-autobus', 'Me pasé de parada del autobús mirando el móvil', '🚌', 'random', 'approved'),
  ('compre-sin-necesitarlo', 'He comprado algo en oferta que no necesitaba porque era oferta', '🏷️', 'random', 'approved'),
  ('me-confundi-de-dia-cita', 'Aparecí a la cita un día antes', '📆', 'random', 'approved'),
  ('me-despedi-con-beso-cuando-tocaba-mano', 'Me lancé a dar un beso de despedida cuando tocaba la mano', '🤝', 'random', 'approved'),
  ('me-olvide-apagar-la-tele', 'Salí de casa con la tele encendida tres días seguidos', '📺', 'random', 'approved'),
  ('deje-para-manana', 'He dejado para mañana algo que llevo dejando dos semanas', '⏳', 'random', 'approved'),
  ('intente-abrir-puerta-sin-llave', 'Intenté abrir la puerta sin la llave en la mano', '🔑', 'random', 'approved'),
  ('me-confundi-de-hora-cita', 'Llegué a una cita una hora antes o después por confusión', '⌚', 'random', 'approved'),
  ('guarde-numero-sin-nombre', 'Tengo un número guardado sin nombre en el móvil desde hace años', '📱', 'random', 'approved'),
  ('me-olvide-de-responder', 'He dejado un mensaje sin responder sin querer durante semanas', '💬', 'random', 'approved'),
  ('me-olvide-de-colgar', 'Colgué el teléfono sin despedirme', '📞', 'random', 'approved'),
  ('me-olvide-de-poner-sal', 'He cocinado algo entero y me olvidé de ponerle sal', '🧂', 'random', 'approved'),
  ('me-fui-gas-encendido', 'Me fui de casa y dejé el gas encendido', '🔥', 'random', 'approved'),
  ('perdi-mi-propio-paraguas', 'He perdido mi propio paraguas', '☂️', 'random', 'approved'),
  ('me-perdi-en-mi-propio-barrio', 'Me he perdido en mi propio barrio', '🗺️', 'random', 'approved'),
  ('compre-cargador-mismo-dia', 'Compré un cargador nuevo el mismo día que encontré el original', '🔌', 'random', 'approved'),
  ('me-equivoque-de-sobre', 'Metí una carta en el sobre equivocado', '✉️', 'random', 'approved'),
  ('vi-mismo-capitulo-dos-veces', 'He visto el mismo capítulo de una serie dos veces sin darme cuenta', '📺', 'random', 'approved'),
  ('me-rei-solo-recordando', 'Me reí solo en público recordando algo de hace tiempo', '😂', 'random', 'approved'),
  ('cometi-error-google-maps', 'Google Maps me llevó por el camino más largo posible', '🗺️', 'random', 'approved'),
  ('me-confundi-de-zapatillas', 'Me puse dos zapatillas distintas y salí a la calle', '👟', 'random', 'approved'),
  ('borre-foto-equivocada', 'Borré sin querer la foto que más quería', '📷', 'random', 'approved'),
  ('me-fui-sin-pagar', 'Me fui de un bar sin pagar sin querer', '🍺', 'random', 'approved'),
  ('me-descargue-peli-equivocada', 'Descargué la película equivocada la noche que la necesitaba', '🎬', 'random', 'approved'),
  ('meti-movil-lavadora', 'Metí el móvil en la lavadora', '📱', 'random', 'approved'),
  ('me-di-cuenta-tarde-del-chiste', 'Me reí de un chiste que no había entendido 10 minutos después', '😂', 'random', 'approved'),
  ('guarde-contrasena-donde-no-recuerdo', 'Guardé la contraseña en un sitio seguro que ya no recuerdo', '🔑', 'random', 'approved'),
  ('pague-aparcamiento-sin-coche', 'Pagué el aparcamiento cuando ya había sacado el coche', '🅿️', 'random', 'approved'),
  ('me-dormi-con-auriculares', 'Me dormí con los auriculares puestos y los encontré enredados', '🎧', 'random', 'approved'),
  ('busque-app-descargada', 'Busqué en la App Store una aplicación que ya tenía instalada', '📲', 'random', 'approved'),
  ('cogi-carrito-sin-moneda', 'Cogí un carro del supermercado sin la moneda y tuve que volver', '🛒', 'random', 'approved'),
  ('me-olvide-de-apagar-la-luz', 'Me fui de vacaciones dejando la luz del salón encendida', '💡', 'random', 'approved'),
  ('llegue-lugar-sin-saber-por-que', 'Llegué a una habitación y no recordé para qué había ido', '🚶', 'random', 'approved'),
  ('empece-a-escribir-y-perdi-el-hilo', 'Empecé a escribir algo y perdí el hilo a mitad', '✍️', 'random', 'approved'),
  ('me-fui-sin-lo-que-iba-a-buscar', 'Fui a buscar algo y volví sin ello', '🏃', 'random', 'approved'),
  ('hable-con-bot-pense-persona', 'He hablado con un bot de atención al cliente pensando que era humano', '🤖', 'random', 'approved'),
  ('respondi-antes-leer', 'He respondido a un mensaje sin leerlo entero', '💬', 'random', 'approved'),
  ('me-rei-sin-saber-de-que', 'Me dio la risa sin saber de qué en el peor momento', '😂', 'random', 'approved'),
  ('me-sente-silla-humeda', 'Me senté en una silla húmeda al aire libre', '🪑', 'random', 'approved'),
  ('mande-nota-de-voz-al-grupo', 'Mandé una nota de voz al grupo grande por error', '🎙️', 'random', 'approved'),
  ('me-confundi-de-idioma-responder', 'Respondí a alguien en otro idioma sin darme cuenta', '🌐', 'random', 'approved'),
  ('eche-algo-de-menos-demasiado-tarde', 'Me di cuenta de lo que tenía cuando ya no estaba', '🕊️', 'random', 'approved'),
  ('pregunte-algo-que-ya-me-habian-dicho', 'Pregunté algo que ya me habían explicado dos veces', '🙋', 'random', 'approved'),
  ('me-mande-nota-a-mi-mismo', 'Me mandé un mensaje a mí mismo en WhatsApp para no olvidarlo', '📱', 'random', 'approved'),
  ('me-quede-sin-datos', 'Se me acabaron los datos a mitad de mes', '📵', 'random', 'approved'),
  ('copie-mensaje-sin-querer-al-destinatario', 'Mandé la captura de un chat a la persona del chat', '📲', 'random', 'approved'),
  ('me-quede-sin-plan', 'Me quedé sin plan el viernes a las 10 PM', '🌙', 'random', 'approved'),
  ('llame-persona-equivocada-en-alto', 'Llamé por el nombre equivocado a alguien en voz alta', '📣', 'random', 'approved'),
  ('me-queje-de-algo-que-yo-hice', 'Me quejé de algo sin recordar que yo lo había causado', '🤦', 'random', 'approved'),
  ('me-levante-sin-motivo-noche', 'Me levanté de madrugada sin saber por qué y volví a la cama', '🌙', 'random', 'approved'),
  ('me-confundi-lado-coche', 'Intenté subir al coche por el lado del conductor cuando iba de copiloto', '🚗', 'random', 'approved'),
  ('di-gracias-a-una-maquina', 'Le di las gracias a un cajero automático', '🏧', 'random', 'approved'),
  ('me-confundi-de-acceso-metro', 'Entré por el acceso de salida del metro', '🚇', 'random', 'approved'),
  ('intente-entrar-a-sitio-cerrado', 'Empujé la puerta de un negocio cerrado durante 20 segundos', '🚪', 'random', 'approved'),
  ('puse-nombre-incorrecto-pedido', 'Puse un nombre aleatorio en el pedido del bar y me olvidé de cuál', '☕', 'random', 'approved'),
  ('me-subi-autobus-equivocado', 'Me subí al autobús equivocado porque el número era similar', '🚌', 'random', 'approved'),
  ('camine-mirando-movil-choque', 'Caminé mirando el móvil y choqué con alguien', '📱', 'random', 'approved'),
  ('abuela-no-entiende-videollamada', 'Mi abuela no entiende que me puede ver en la videollamada', '📹', 'familia', 'approved'),
  ('madre-compra-ropa-talla-mal', 'Mi madre me compra ropa una talla grande "para que no apriete"', '👕', 'familia', 'approved'),
  ('padre-pone-subtitulos', 'Mi padre pone subtítulos en español a series en español', '📺', 'familia', 'approved'),
  ('tia-pregunta-sueldo', 'Mi tía me preguntó cuánto gano en la cena de Navidad', '💶', 'familia', 'approved'),
  ('hermano-pide-cargador', 'Mi hermano me pide el cargador cada vez que viene a casa', '🔋', 'familia', 'approved'),
  ('madre-guarda-tuppers', 'Mi madre tiene más tuppers que vajilla', '🥡', 'familia', 'approved'),
  ('abuela-manda-bendicion', 'Mi abuela me manda una bendición por WhatsApp cada mañana', '🙏', 'familia', 'approved'),
  ('primo-cuenta-logros-suyos', 'Mi primo convierte cada conversación en un monólogo sobre él', '🗣️', 'familia', 'approved'),
  ('hermana-coge-ropa-sin-preguntar', 'Mi hermana coge mi ropa sin preguntar y me la devuelve distinta', '👗', 'familia', 'approved'),
  ('madre-avisa-que-llama', 'Mi madre manda un WhatsApp para avisar de que va a llamar', '📱', 'familia', 'approved'),
  ('abuelo-historia-guerra', 'Mi abuelo cuenta siempre la misma historia de posguerra', '📖', 'familia', 'approved'),
  ('cunada-dieta-vegana', 'Mi cuñada se hizo vegana y reorganizó la cena entera', '🥦', 'familia', 'approved'),
  ('primo-pide-ayuda-mudanza', 'Mi primo lleva cinco años pidiéndome ayuda para mudanzas', '📦', 'familia', 'approved'),
  ('familia-llega-visita-sin-avisar', 'Mi familia apareció de visita sin avisar', '🚪', 'familia', 'approved'),
  ('abuela-pregunta-novia', 'Mi abuela me pregunta si tengo novia cada vez que la veo', '💏', 'familia', 'approved'),
  ('madre-se-preocupa-frio', 'Mi madre me pregunta si llevo chaqueta aunque haga calor', '🧣', 'familia', 'approved'),
  ('tio-explica-como-ahorrar', 'Mi tío me explica cómo ahorrar dinero sin haber ahorrado en su vida', '💰', 'familia', 'approved'),
  ('hermano-olvida-cumpleanos', 'Mi hermano felicita el cumpleaños tres días tarde cada año', '🎂', 'familia', 'approved'),
  ('madre-no-espera-respuesta', 'Mi madre me hace una pregunta y responde ella sola', '🗣️', 'familia', 'approved'),
  ('abuelo-pide-ayuda-cajero', 'Acompañé a mi abuelo al cajero y tardamos 20 minutos', '🏧', 'familia', 'approved'),
  ('prima-pide-favores-imposibles', 'Mi prima me pide favores que solo yo puedo hacer', '🙏', 'familia', 'approved'),
  ('hermana-habla-suenos', 'Mi hermana me cuenta sus sueños con todo el detalle', '💭', 'familia', 'approved'),
  ('tio-filosofia-sobremesa', 'Mi tío se pone filosófico en la sobremesa del domingo', '🧐', 'familia', 'approved'),
  ('madre-llama-en-momentos-malos', 'Mi madre llama justo cuando estoy en algo importante', '📞', 'familia', 'approved'),
  ('tia-recomienda-series-viejas', 'Mi tía me recomienda series que ya tienen diez años', '📺', 'familia', 'approved'),
  ('madre-llora-anuncio-navidad', 'Mi madre llora con el anuncio de la Lotería de Navidad', '🎄', 'familia', 'approved'),
  ('hermana-presta-ropa-no-devuelve', 'Le presté ropa a mi hermana y sigo esperando que la devuelva', '👗', 'familia', 'approved'),
  ('tio-aporta-soluciones-que-no-pedi', 'Mi tío me da soluciones a problemas que no le he contado', '🔧', 'familia', 'approved'),
  ('abuela-llama-noticias', 'Mi abuela me llama cada vez que ve algo en las noticias que me podría afectar', '📺', 'familia', 'approved'),
  ('madre-pone-temperatura-alta', 'Mi madre sube la calefacción hasta que se puede vivir en manga corta en enero', '🌡️', 'familia', 'approved'),
  ('padre-no-escucha-primera-vez', 'Tengo que repetirle las cosas a mi padre siempre dos veces', '🗣️', 'familia', 'approved'),
  ('hermano-mayor-sabe-todo', 'Mi hermano mayor tiene una opinión sobre cada decisión de mi vida', '🧠', 'familia', 'approved'),
  ('madre-da-de-comer-sin-hambre', 'Mi madre me da de comer aunque diga que no tengo hambre', '🍽️', 'familia', 'approved'),
  ('tia-viaje-recomienda-restaurantes', 'Mi tía me recomienda restaurantes de hace diez años en cada viaje', '🍴', 'familia', 'approved'),
  ('prima-pide-que-le-guste-fotos', 'Mi prima me pide que le dé like a sus fotos el día que las sube', '❤️', 'familia', 'approved'),
  ('padre-arregla-tecnologia-mal', 'Mi padre "arregló" el router y tardamos dos días sin internet', '📡', 'familia', 'approved'),
  ('hermana-llora-el-dia-que-le-va-bien', 'Mi hermana me llama llorando cuando las cosas le van bien', '😭', 'familia', 'approved'),
  ('cunado-cuenta-dinero-que-gana', 'Mi cuñado menciona cuánto gana sin que nadie se lo pregunte', '💶', 'familia', 'approved'),
  ('abuela-da-propina-a-todos', 'Mi abuela le da dinero a todo nieto que aparece aunque ya tenga 30 años', '💵', 'familia', 'approved'),
  ('madre-guarda-recibos-todo', 'Mi madre guarda los recibos de todo', '🧾', 'familia', 'approved'),
  ('me-cai-pasarela', 'Me caí en una pasarela peatonal en plena calle', '🚶', 'verguenza', 'approved'),
  ('di-propina-de-mas', 'Di una propina enorme por no saber hacer la cuenta en otro país', '💸', 'verguenza', 'approved'),
  ('me-equivoque-de-cuarto-hotel', 'Intenté entrar a la habitación equivocada en un hotel', '🏨', 'verguenza', 'approved'),
  ('grite-en-silencio', 'Me salió un grito involuntario en un sitio completamente silencioso', '😱', 'verguenza', 'approved'),
  ('me-rei-solo', 'Me reí a carcajadas solo en el metro recordando algo', '😂', 'verguenza', 'approved'),
  ('empuje-puerta-giratoria-mal', 'No supe usar una puerta giratoria en un edificio importante', '🚪', 'verguenza', 'approved'),
  ('me-cague-con-el-frio', 'Me cagué encima de frío esperando el autobús', '🥶', 'verguenza', 'approved'),
  ('baile-solo-sin-musica', 'Empecé a bailar porque creí que había música y no la había', '🕺', 'verguenza', 'approved'),
  ('me-cai-ascensor-saliendo', 'Tropecé al salir del ascensor en un piso de oficinas lleno', '🛗', 'verguenza', 'approved'),
  ('pregunte-precio-menu-sin-ver-carta', 'Pregunté el precio del menú en un restaurante de alta gama', '🍽️', 'verguenza', 'approved'),
  ('aplaudi-en-presentacion-tecnica', 'Aplaudí en medio de una presentación técnica por error', '👏', 'verguenza', 'approved'),
  ('puse-altavoz-sin-querer', 'Puse el teléfono en altavoz sin querer en un sitio público', '📢', 'verguenza', 'approved'),
  ('confundi-policia-portero', 'Confundí a un policía con un portero de discoteca', '👮', 'verguenza', 'approved'),
  ('pregunte-que-pelicula-teatro', 'Pregunté qué película echaban en un teatro', '🎭', 'verguenza', 'approved'),
  ('pronuncie-mal-marca-famosa', 'Pronuncié mal el nombre de una marca famosa delante de dependientes', '🛍️', 'verguenza', 'approved'),
  ('llegue-fiesta-equivocada', 'Llegué a una fiesta que no era para mí', '🎉', 'verguenza', 'approved'),
  ('llame-taxista-por-nombre-app', 'Llamé al taxista por el nombre de la app cuando no era él', '🚕', 'verguenza', 'approved'),
  ('me-confundi-de-sala-cine', 'Entré a la sala de cine equivocada y me senté', '🎬', 'verguenza', 'approved'),
  ('le-di-las-llaves-a-extrano', 'Di las llaves de casa a un extraño creyendo que era el repartidor', '🔑', 'verguenza', 'approved'),
  ('confundi-cumpleanos-con-otro', 'Felicité a alguien por su cumpleaños el día del cumpleaños de otra persona', '🎂', 'verguenza', 'approved'),
  ('tuve-mancha-espalda-todo-el-dia', 'Llevé una mancha en la espalda todo un día y nadie me lo dijo', '👕', 'verguenza', 'approved'),
  ('me-queme-intentando-impresionar', 'Me quemé en la cocina intentando impresionar a alguien', '🍳', 'verguenza', 'approved'),
  ('me-cai-silla-oficina', 'Me caí de la silla de la oficina sin nadie alrededor', '🪑', 'verguenza', 'approved'),
  ('confundi-jefe-cliente', 'Confundí a mi jefe con un cliente en una reunión importante', '🤝', 'verguenza', 'approved'),
  ('me-atranque-bano-ajeno', 'Me quedé atascado en el baño de casa de alguien que conocía poco', '🚽', 'verguenza', 'approved'),
  ('hice-reverencia-sin-motivo', 'Hice una reverencia involuntaria al despedirme de alguien', '🙇', 'verguenza', 'approved'),
  ('sali-sin-pagar-cafe', 'Me fui del bar sin pagar el café por despiste', '☕', 'verguenza', 'approved'),
  ('pregunte-si-estaba-abierto-dentro', 'Pregunté si el establecimiento estaba abierto estando dentro', '🚪', 'verguenza', 'approved'),
  ('me-cai-con-bandeja-cafeteria', 'Se me cayó la bandeja de la cafetería', '🍽️', 'verguenza', 'approved'),
  ('me-rie-chiste-propio', 'Me reí de mi propio chiste antes de terminarlo', '😂', 'verguenza', 'approved'),
  ('me-quede-en-blanco', 'Me quedé en blanco hablando en público en el momento más importante', '🎤', 'verguenza', 'approved'),
  ('me-puse-rojo-sin-motivo', 'Me puse rojo sin motivo cuando alguien me miró', '😳', 'verguenza', 'approved'),
  ('hable-demasiado-nerviosismo', 'No pude parar de hablar de los nervios en una situación importante', '🗣️', 'verguenza', 'approved'),
  ('me-meti-en-una-foto-ajena', 'Me metí sin querer en la foto de unos desconocidos', '📷', 'verguenza', 'approved'),
  ('pregunte-precio-en-voz-alta', 'Pregunté el precio en voz alta y era el más caro de la carta', '📢', 'verguenza', 'approved'),
  ('me-colgaron-en-plena-frase', 'Me colgaron el teléfono mientras estaba a mitad de frase', '📞', 'verguenza', 'approved'),
  ('confundi-escalera-ascensor', 'Fui a la escalera pensando que era el ascensor', '🛗', 'verguenza', 'approved'),
  ('entre-bano-equivocado', 'Entré al baño equivocado y no me di cuenta hasta dentro', '🚻', 'verguenza', 'approved'),
  ('me-cruce-con-alguien-que-ignore', 'Me crucé con alguien al que ignoré por error la semana anterior', '😶', 'verguenza', 'approved'),
  ('hable-solo-en-voz-alta-transporte', 'Hablé solo en voz alta en el transporte público', '🚇', 'verguenza', 'approved'),
  ('respondi-por-hablar', 'Respondí a algo por hablar sin haber escuchado lo que me dijeron', '👂', 'verguenza', 'approved'),
  ('di-mal-la-mano', 'Di mal la mano en un saludo importante', '🤝', 'verguenza', 'approved'),
  ('confundi-arriba-con-abajo-edificio', 'Bajé cuando tenía que subir en el ascensor del trabajo', '🛗', 'verguenza', 'approved'),
  ('me-sente-en-sitio-reservado', 'Me senté en el sitio reservado de alguien en un evento', '🪑', 'verguenza', 'approved'),
  ('me-quede-sin-bateria-haciendo-foto', 'Se me fue el móvil justo al intentar hacer la foto del momento', '📱', 'verguenza', 'approved'),
  ('pregunte-si-estaba-libre-ocupado', 'Pregunté si el baño estaba ocupado tirando de la puerta', '🚽', 'verguenza', 'approved'),
  ('me-confundi-de-tono-mensaje', 'Mandé un mensaje serio con un emoji irónico sin querer', '😅', 'verguenza', 'approved'),
  ('no-encontre-la-salida-de-emergencia', 'Busqué la salida de emergencia en el cine y no la encontré', '🚪', 'verguenza', 'approved'),
  ('me-perdi-en-el-parking', 'No encontré el coche en el aparcamiento durante 20 minutos', '🅿️', 'verguenza', 'approved'),
  ('quede-de-pie-todos-sentados', 'Me quedé de pie aplaudiendo cuando todos ya se habían sentado', '👏', 'verguenza', 'approved'),
  ('me-tropece-entrando-tienda', 'Tropecé en el escalón de la entrada de una tienda', '🛍️', 'verguenza', 'approved'),
  ('mande-meme-incorrecto-grupo', 'Mandé un meme al grupo de familia en lugar del grupo de amigos', '📲', 'verguenza', 'approved'),
  ('hice-un-chiste-raro-en-entrevista', 'Hice un chiste en una entrevista que nadie entendió', '😬', 'verguenza', 'approved'),
  ('di-nombre-equivocado-al-presentarme', 'Me equivoqué con mi propio apellido al presentarme', '🤦', 'verguenza', 'approved'),
  ('me-olvide-de-colgar-cuando-debi', 'Estuve al teléfono un minuto sin darme cuenta de que habían colgado', '📞', 'verguenza', 'approved'),
  ('use-demasiada-colonia', 'Me puse demasiada colonia y se notó en toda la oficina', '🪥', 'verguenza', 'approved'),
  ('me-confundi-de-persona-en-dark', 'Hablé con quien no era en un sitio oscuro', '🌑', 'verguenza', 'approved'),
  ('no-pude-abrir-el-envase', 'No pude abrir un envase en un restaurante y tuve que pedir ayuda', '🥤', 'verguenza', 'approved'),
  ('estornude-encima-de-comida', 'Estornudé encima de la comida de otro en un restaurante', '🤧', 'verguenza', 'approved'),
  ('me-levante-palomitas-cine', 'Volqué las palomitas al levantarme a mitad de película', '🍿', 'verguenza', 'approved'),
  ('hable-de-alguien-delante', 'Hablé de alguien sin saber que estaba detrás mío', '😳', 'verguenza', 'approved'),
  ('me-rei-al-recibir-mala-noticia', 'Me dio la risa nerviosa al recibir una mala noticia', '😬', 'verguenza', 'approved'),
  ('me-puse-mal-con-emocion', 'Se me fueron los ojos en agua en un momento inapropiado', '😢', 'verguenza', 'approved'),
  ('confundi-ascensor-bano', 'Fui al baño y entré en el armario del pasillo', '🚪', 'verguenza', 'approved'),
  ('dije-palabra-malsonante-delante-ninos', 'Se me escapó una palabrota delante de niños en una reunión familiar', '😬', 'verguenza', 'approved'),
  ('firme-en-el-sitio-incorrecto', 'Firmé en el sitio incorrecto de un contrato importante', '✒️', 'verguenza', 'approved'),
  ('me-pase-saludando', 'Saludé tres veces a la misma persona en el mismo día', '👋', 'verguenza', 'approved'),
  ('confundi-metro-con-cercanias', 'Me equivoqué de red de transporte y llegué a otro municipio', '🚇', 'verguenza', 'approved'),
  ('me-comi-la-decoracion', 'Me comí la decoración del plato pensando que era comible', '🌿', 'verguenza', 'approved'),
  ('deje-la-luz-puesta-toda-la-reunion', 'Olvidé apagar la luz del fondo en una videollamada importante', '💡', 'verguenza', 'approved'),
  ('desperte-sin-saber-donde', 'Me desperté sin saber en qué ciudad estaba', '🌍', 'resaca', 'approved'),
  ('me-gaste-el-alquiler', 'Me gasté el dinero del alquiler en una sola noche', '💸', 'resaca', 'approved'),
  ('comi-kebab-antes-de-dormir', 'Pedí un kebab y me quedé dormido antes de que llegara', '🥙', 'resaca', 'approved'),
  ('me-cayo-el-movil-en-el-inodoro', 'Se me cayó el móvil en el inodoro del bar', '📱', 'resaca', 'approved'),
  ('olvide-que-habia-pasado', 'Llegué a casa sin recordar cómo llegué', '🌀', 'resaca', 'approved'),
  ('mande-meme-equivocado-borracho', 'Mandé el meme más inapropiado posible al grupo de familia', '📲', 'resaca', 'approved'),
  ('baile-reggaeton-a-camara-lenta', 'Bailé reggaeton a cámara lenta y lo subí a Instagram', '🕺', 'resaca', 'approved'),
  ('me-puse-cunado', 'Me puse en modo cuñado en una conversación de madrugada', '🍺', 'resaca', 'approved'),
  ('perdi-gorra-que-queria', 'Perdí la gorra favorita en una fiesta', '🧢', 'resaca', 'approved'),
  ('pague-dos-veces-barra', 'Pagué dos veces en la barra sin darme cuenta', '💳', 'resaca', 'approved'),
  ('llame-a-alguien-que-no-debia', 'Llamé a alguien que no debía en un momento de baja guardia', '📞', 'resaca', 'approved'),
  ('perdi-la-chaqueta-de-siempre', 'Perdí la chaqueta favorita en una noche de fiesta', '🧥', 'resaca', 'approved'),
  ('declare-amistad-eterna-a-desconocido', 'Le declaré amistad eterna a alguien que no conocía', '🤝', 'resaca', 'approved'),
  ('me-fui-sin-movil', 'Me fui de casa de un amigo sin el móvil y no me enteré hasta el metro', '📱', 'resaca', 'approved'),
  ('me-quede-en-el-bano-tiempo', 'Me quedé encerrado en el baño del bar más tiempo del que debía', '🚽', 'resaca', 'approved'),
  ('me-cai-con-copa-en-mano', 'Me caí sin derramar la copa', '🥂', 'resaca', 'approved'),
  ('hable-de-mis-sentimientos-con-todo-el-mundo', 'Hablé de mis sentimientos con desconocidos a las 4 AM', '💬', 'resaca', 'approved'),
  ('perdi-las-gafas-de-sol', 'Perdí las gafas en la fiesta del verano', '🕶️', 'resaca', 'approved'),
  ('me-acoste-con-zapatos', 'Me acosté con los zapatos puestos', '👟', 'resaca', 'approved')
on conflict (slug) do nothing;
