-- =================================================================
-- Unlocked seed v2 — Part 1 of 4
-- Aplicar primero en Supabase Dashboard -> SQL Editor
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- =================================================================

insert into achievements (slug, title, emoji, description, category, status) values
  ('mi-padre-tabaco', 'Mi padre se fue a por tabaco y no volvió', '🚬', 'Un clásico atemporal del trauma español.', 'familia', 'approved'),
  ('madre-usb', 'Mi madre me ha llamado para ver cómo se mete una USB', '💾', 'Y ha tardado 20 minutos.', 'familia', 'approved'),
  ('cunado-cripto', 'Mi cuñado me explica criptomonedas en cada cumpleaños', '💸', 'Sin que nadie se lo haya pedido.', 'familia', 'approved'),
  ('tio-fuente-boda', 'Mi tío bebió de la fuente decorativa de la boda', '🥂', 'Pensó que era un catering de diseño.', 'familia', 'approved'),
  ('abuela-guapo', 'Mi abuela me ha llamado guapo en mi peor día', '🤍', 'La única que siempre miente bien.', 'familia', 'approved'),
  ('padre-llorando-serie', 'Me he pillado a mi padre llorando con una serie', '😢', 'Dijo que le había entrado algo en el ojo.', 'familia', 'approved'),
  ('madre-captura-camara', 'Mi madre me ha mandado capturas de pantalla con la cámara', '📸', 'Foto de foto de foto.', 'familia', 'approved'),
  ('padre-chiste-navidad', 'Mi padre cuenta el mismo chiste cada Navidad desde hace 12 años', '🎄', 'Y todos nos reímos igual.', 'familia', 'approved'),
  ('grupo-sin-mi', 'Mi familia entera tiene grupo de WhatsApp y yo no estoy', '📱', 'Me enteré por mi prima en persona.', 'familia', 'approved'),
  ('cunado-futbol', 'He sido cuñado experto en fútbol sin haber jugado nunca', '⚽', 'Años de FIFA cuentan.', 'familia', 'approved'),
  ('abuela-stickers', 'Mi abuela manda stickers de WhatsApp sin saber qué significan', '🦋', 'El corazón roto lo manda para todo.', 'familia', 'approved'),
  ('madre-facebook', 'Mi madre comenta mis fotos de Instagram en Facebook', '👩‍💻', 'Le da igual el canal.', 'familia', 'approved'),
  ('padre-whatsapp-mayusculas', 'Mi padre escribe todos los WhatsApps en mayúsculas', '📲', 'Dice que se lee mejor.', 'familia', 'approved'),
  ('tio-conspiraciones', 'Mi tío me explica conspiraciones en la cena de Navidad', '🎅', 'Este año tocó la luna.', 'familia', 'approved'),
  ('prima-instagram', 'Mi prima me ha pedido follow en Instagram sin seguirme de vuelta', '📷', NULL, 'familia', 'approved'),
  ('abuelo-movil-nuevo', 'He configurado el móvil nuevo de mi abuelo cuatro veces', '📱', 'Cada vez lo pone a cero sin querer.', 'familia', 'approved'),
  ('madre-meme-desfasado', 'Mi madre me manda memes de 2015 como si fuesen nuevos', '😂', NULL, 'familia', 'approved'),
  ('cena-navidad-politica', 'He sobrevivido a una cena de Navidad sin hablar de política', '🍽️', 'Milagro de proporciones bíblicas.', 'familia', 'approved'),
  ('hermano-wifi', 'Mi hermano me llama solo cuando se cae el WiFi', '📶', NULL, 'familia', 'approved'),
  ('madre-llama-novia-exnovia', 'Mi madre sigue llamando a mi ex por su nombre a mis nuevas parejas', '🤦', 'Ya van tres años.', 'familia', 'approved'),
  ('tia-pregunta-novio', 'Mi tía me pregunta cuándo me caso en cada reunión familiar', '💒', 'Yo tengo 24 años, tía.', 'familia', 'approved'),
  ('madre-reenviar-cadena', 'Mi madre me ha reenviado una cadena de la suerte tres veces hoy', '🔗', NULL, 'familia', 'approved'),
  ('hermana-spotify-familia', 'Mi hermana cambia mi música de Spotify desde el plan familiar', '🎵', 'A Bad Bunny. Siempre a Bad Bunny.', 'familia', 'approved'),
  ('primo-prestamo', 'Mi primo me pidió 50 euros prestados en 2019', '💶', 'Seguimos esperando.', 'familia', 'approved'),
  ('abuela-llamada-larga', 'He pasado 40 minutos al teléfono con mi abuela sin decir nada nuevo', '☎️', 'Pero era necesario.', 'familia', 'approved'),
  ('padre-llama-aplicacion-programa', 'Mi padre llama aplicaciones "programas"', '💻', 'Y los emojis "muñequitos".', 'familia', 'approved'),
  ('madre-diagnostico-youtube', 'Mi madre me ha diagnosticado una enfermedad rara por YouTube', '🏥', 'Tenía un grano.', 'familia', 'approved'),
  ('cena-empresa-cunado', 'He aguantado a mi cuñado en todas las cenas familiares del año', '🙃', NULL, 'familia', 'approved'),
  ('abuelo-huerta', 'Mi abuelo me trae verduras de la huerta cada semana', '🥬', 'No se puede rechazar.', 'familia', 'approved'),
  ('madre-preocupa-llamar', 'Mi madre se preocupa si no la llamo dos días seguidos', '😟', 'Manda a mi tía a comprobar que sigo vivo.', 'familia', 'approved'),
  ('familiar-regalo-mal', 'Me han regalado algo que pedí hace tres años', '🎁', 'Pasada la fecha, el regalo igual.', 'familia', 'approved'),
  ('hermano-videojuegos-toda-noche', 'He estado en modo "hermano mayor responsable" toda mi adolescencia', '🎮', 'Y luego mi hermano hizo lo que quiso.', 'familia', 'approved'),
  ('prima-influencer', 'Mi prima se ha hecho "influencer" y me pide que le dé likes', '📸', NULL, 'familia', 'approved'),
  ('padre-cargador', 'Mi padre me coge el cargador sin preguntar desde 2017', '🔌', 'Ya ni me molesto en buscar el mío.', 'familia', 'approved'),
  ('madre-no-tira-nada', 'Mi madre guarda bolsas de plástico dentro de otras bolsas de plástico', '🛍️', 'Hay una bolsa desde 1998.', 'familia', 'approved'),
  ('abuela-guisa-para-ejercito', 'Mi abuela cocina para 12 aunque vengan 3', '🍲', 'Siempre hay que llevarse tupper.', 'familia', 'approved'),
  ('tia-foto-familiar-mala', 'Soy el responsable de hacer la foto familiar en cada reunión', '📷', 'Y siempre hay uno que mueve.', 'familia', 'approved'),
  ('hermano-llama-solo-problemas', 'Mi hermano solo me llama cuando tiene un problema', '📞', 'Y desaparece cuando lo solucionamos.', 'familia', 'approved'),
  ('padre-cine-explica-peli', 'Mi padre comenta la película mientras la vemos juntos', '🎬', NULL, 'familia', 'approved'),
  ('madre-compra-sin-lista', 'Mi madre hace la compra sin lista y vuelve con tres cosas que no necesitamos', '🧺', NULL, 'familia', 'approved'),
  ('abuela-llama-por-otro-nombre', 'Mi abuela me llama por el nombre de mi primo cuando me regaña', '😅', 'Ya no corrijo.', 'familia', 'approved'),
  ('padre-pausa-television', 'Mi padre pausa la tele para hablarme aunque sea una llamada de 2 min', '⏸️', NULL, 'familia', 'approved'),
  ('madre-cuenta-historia-larga', 'Mi madre me ha contado la misma historia de su juventud por décima vez', '👵', 'Y yo la he escuchado igual que la primera.', 'familia', 'approved'),
  ('tio-trae-invitado-sorpresa', 'Mi tío ha traído un invitado sorpresa a una cena íntima', '🚶', 'Sin avisar.', 'familia', 'approved'),
  ('abuelo-pastilla-diaria', 'He organizado las pastillas de mi abuelo durante una semana', '💊', NULL, 'familia', 'approved'),
  ('primo-pide-favor-finde', 'Mi primo siempre me pide favores el viernes por la noche', '🌙', NULL, 'familia', 'approved'),
  ('hermana-bano-hora', 'Mi hermana ha ocupado el baño una hora antes de una cita mía importante', '🚿', 'Una hora exacta.', 'familia', 'approved'),
  ('madre-whatsapp-voz', 'Mi madre manda audios de WhatsApp de más de tres minutos para decir una cosa', '🎙️', NULL, 'familia', 'approved'),
  ('padre-busca-gafas', 'Mi padre me ha llamado para buscar sus gafas y las tenía puestas', '👓', 'Tercera vez este mes.', 'familia', 'approved'),
  ('familiar-opinion-no-pedida', 'Un familiar me ha dado su opinión sobre mi físico en una cena', '😶', 'Sin preguntársela.', 'familia', 'approved'),
  ('abuela-llora-despedida', 'Mi abuela llora cada vez que me voy aunque viva a 40 minutos', '😭', NULL, 'familia', 'approved'),
  ('cunada-dieta', 'Mi cuñada me explica su nueva dieta en cada quedada familiar', '🥗', 'Son 12 dietas en tres años.', 'familia', 'approved'),
  ('padre-no-pide-ayuda', 'Mi padre ha arreglado algo de la casa y lo ha dejado peor', '🔧', 'Pero no pidió ayuda.', 'familia', 'approved'),
  ('madre-regalo-de-casa', 'Mi madre me ha comprado ropa que nunca me pondría', '👕', 'Y hay que ponérsela cuando va a visitar.', 'familia', 'approved'),
  ('tio-regalo-efectivo', 'Mi tío siempre regala dinero en efectivo en un sobre arrugado', '💵', 'El gesto es innegociable.', 'familia', 'approved'),
  ('hermano-culpa-algo', 'He echado la culpa a mi hermano de algo que hice yo de pequeño', '😇', 'Y lo creen todavía.', 'familia', 'approved'),
  ('abuelo-explica-precio', 'Mi abuelo me explica el precio de todo lo que había hace 40 años', '💰', '"Eso valía 10 pesetas."', 'familia', 'approved'),
  ('madre-sabe-que-pasa', 'Mi madre sabe que algo me pasa antes de que yo lo sepa', '🔮', NULL, 'familia', 'approved'),
  ('primo-cumpleanos-tarde', 'Mi primo siempre felicita el cumpleaños al día siguiente', '🎂', 'Y lo hace como si fuera el primero.', 'familia', 'approved'),
  ('padre-coche-radio-maxima', 'Mi padre pone la radio al máximo en el coche y no habla', '📻', NULL, 'familia', 'approved'),
  ('abuela-sobremesa', 'He aguantado una sobremesa familiar de cuatro horas sin salida', '🍴', NULL, 'familia', 'approved'),
  ('saludo-desconocido', 'Saludé a un desconocido pensando que era amigo de la uni', '🫥', 'Ya era tarde para dar marcha atrás.', 'verguenza', 'approved'),
  ('nombre-clase', 'Me llamaron por mi nombre real en clase y no respondí', '🙃', 'Estaba convencido de que llamaban a otro.', 'verguenza', 'approved'),
  ('cague-boda', 'Me cagué encima en una boda', '😬', 'No fue diarrea. Fue destino.', 'verguenza', 'approved'),
  ('nombre-limpiadora', 'Llevo 3 años en una empresa y no sé el nombre de la limpiadora', '🧹', 'Ya es tarde para preguntar.', 'verguenza', 'approved'),
  ('caca-coche', 'Pisé caca y entré en mi propio coche', '💩', 'No lo descubrí hasta el día siguiente.', 'verguenza', 'approved'),
  ('caida-mercadona', 'Me caí por las escaleras del Mercadona con el carro', '🛒', 'Todo el mundo miró.', 'verguenza', 'approved'),
  ('aplaudi-solo-cine', 'Empecé a aplaudir en el cine sin que aplaudiese nadie más', '👏', 'Ni la película lo merecía tanto.', 'verguenza', 'approved'),
  ('audio-largo-texto', 'Mandé un audio de 8 minutos pensando que era texto', '🎙️', 'No lo escucho ni yo.', 'verguenza', 'approved'),
  ('bragueta-entrevista', 'Llevé la bragueta abierta toda una entrevista', '👖', 'Me la dieron igualmente.', 'verguenza', 'approved'),
  ('dormido-historia-pareja', 'Me dormí mientras mi pareja me contaba una historia importante', '😴', 'Tardé dos semanas en recuperar la confianza.', 'verguenza', 'approved'),
  ('confundi-cumpleanos', 'Felicité el cumpleaños a alguien que no era su cumpleaños', '🎂', 'Con pastel y todo.', 'verguenza', 'approved'),
  ('llame-profe-mama', 'Llamé "mamá" a mi profesora delante de toda la clase', '👩‍🏫', 'No me miró igual el resto del curso.', 'verguenza', 'approved'),
  ('selfie-sin-querer', 'He enviado una foto accidental a un grupo de trabajo', '📱', 'Era de mi cara a las 7 AM.', 'verguenza', 'approved'),
  ('puerta-tirar-empujar', 'He empujado una puerta de tirar delante de mucha gente', '🚪', 'Y luego he vuelto a empujar.', 'verguenza', 'approved'),
  ('responde-ok-jefe', 'Le respondí OK a mi jefe cuando me dijo que mi presentación era un desastre', '👍', 'No sé por qué lo hice.', 'verguenza', 'approved'),
  ('pronuncie-mal', 'He pronunciado mal una palabra en inglés delante de nativos', '🗣️', 'Silencio incómodo.', 'verguenza', 'approved'),
  ('equivoque-piso', 'He llamado al timbre del piso equivocado y esperado cinco minutos', '🔔', NULL, 'verguenza', 'approved'),
  ('cai-escalon', 'Me tropecé en un escalón que no existía en plena calle', '🚶', 'Delante de una terraza llena.', 'verguenza', 'approved'),
  ('conteste-siri-publico', 'Le contesté a Siri en voz alta en el metro', '🎤', 'Pensé que era una persona.', 'verguenza', 'approved'),
  ('risa-funeral', 'Me dio la risa en un funeral', '😶', 'No me puse bien hasta el día siguiente.', 'verguenza', 'approved'),
  ('mande-audio-jefe', 'Mandé un audio de WhatsApp a mi jefe que era para mi amigo', '📲', 'Hablaba de él.', 'verguenza', 'approved'),
  ('bailando-solo-visto', 'Me han pillado bailando solo en el salón a través del portal', '💃', NULL, 'verguenza', 'approved'),
  ('llore-pelicula-avion', 'Lloré en una película del avión y el de al lado me vio', '✈️', 'Era una de acción.', 'verguenza', 'approved'),
  ('pregunta-embarazo', 'Le pregunté a alguien cuándo salía de cuentas y no estaba embarazada', '🤰', 'Tierra, trágame.', 'verguenza', 'approved'),
  ('quede-sin-dinero-caja', 'Me quedé sin saldo en caja del Mercadona con la gente detrás', '💳', 'Tardé tres minutos en buscar otra tarjeta.', 'verguenza', 'approved'),
  ('tire-copa-restaurante', 'Tiré una copa de vino encima del mantel de un restaurante caro', '🍷', 'Era de otro cliente.', 'verguenza', 'approved'),
  ('cante-cumpleanos-solo', 'Empecé a cantar el cumpleaños feliz solo y nadie se sumó', '🎂', NULL, 'verguenza', 'approved'),
  ('olvide-nombre-conocido', 'Se me olvidó el nombre de alguien que conozco desde hace años', '🫣', 'Tuve que presentarle a alguien sin decir su nombre.', 'verguenza', 'approved'),
  ('ropa-reves-todo-el-dia', 'He llevado la camiseta del revés todo un día de trabajo', '👕', 'Nadie me lo dijo.', 'verguenza', 'approved'),
  ('confundi-cara-persona', 'He confundido a dos personas que no se parecen en nada', '👀', NULL, 'verguenza', 'approved'),
  ('pregunte-precio-decoracion', 'Pregunté el precio de algo en una tienda y era decorativo', '🪴', 'La dependienta no supo qué decir.', 'verguenza', 'approved'),
  ('snapchat-historia-grupo', 'Publiqué una historia pensando que era un mensaje directo', '📱', 'La vieron 340 personas.', 'verguenza', 'approved'),
  ('pague-propina-sin-querer', 'Pagué propina sin querer en un sitio de autoservicio', '💸', 'Le di al botón equivocado delante del cajero.', 'verguenza', 'approved'),
  ('conteste-mal-pregunta-facil', 'Fallé una pregunta facilísima en un concurso de bar', '🎯', 'Todavía me la recuerdan.', 'verguenza', 'approved'),
  ('hable-con-muro', 'He hablado con alguien que no me escuchaba porque llevaba auriculares', '🎧', 'Un minuto entero.', 'verguenza', 'approved'),
  ('mande-corazon-jefe', 'Mandé un corazón a mi jefe por error', '❤️', 'Costó semanas normalizar la situación.', 'verguenza', 'approved'),
  ('resbale-hielo', 'Resbalé en el hielo y traté de hacerlo parecer intencional', '🧊', 'No coló.', 'verguenza', 'approved'),
  ('snob-restaurante', 'Pedí algo en inglés en un restaurante español pensando que era más guay', '🍽️', 'El camarero me respondió en valenciano.', 'verguenza', 'approved'),
  ('me-baje-tren-equivocado', 'Me bajé en la estación equivocada del metro y esperé el siguiente en silencio', '🚇', NULL, 'verguenza', 'approved'),
  ('pense-era-conocido', 'Saludé a alguien desde lejos haciéndolo gestos durante 30 segundos', '🙋', 'Era un extraño que esperaba a otro.', 'verguenza', 'approved'),
  ('presente-mal-apellido', 'Me presenté con el apellido de mi ex en una reunión de trabajo', '🗂️', NULL, 'verguenza', 'approved'),
  ('foto-fea-grupo', 'Soy el que sale mal en todas las fotos de grupo', '📷', 'Siempre.', 'verguenza', 'approved'),
  ('hice-silencio-cuento-chiste', 'Conté un chiste en una cena y no se rió nadie', '😐', 'Acabé explicándolo.', 'verguenza', 'approved'),
  ('pregunte-hora-tengo-movil', 'Le pregunté la hora a alguien teniendo el móvil en la mano', '⌚', NULL, 'verguenza', 'approved'),
  ('me-quede-sin-papel-bano', 'Me quedé sin papel en el baño de casa de alguien que acababa de conocer', '🧻', NULL, 'verguenza', 'approved'),
  ('sali-aseo-con-papel', 'Salí del baño de un bar con papel de váter enganchado al zapato', '🚽', NULL, 'verguenza', 'approved'),
  ('volvi-buscar-algo-olvidado', 'Volví a casa a por algo y me olvidé de lo que había vuelto a buscar', '🔑', NULL, 'verguenza', 'approved'),
  ('cambie-sitio-mal', 'Me cambié de asiento en el tren y era el asiento de otro', '🪑', 'Me lo pidió de vuelta a los 10 minutos.', 'verguenza', 'approved'),
  ('no-reconoci-nuevo-corte', 'No reconocí a mi amigo con el pelo corto y lo ignoré en la calle', '💇', NULL, 'verguenza', 'approved'),
  ('me-mordi-lengua-comiendo', 'Me mordí la lengua comiendo delante de una primera cita', '😬', 'Fue visible.', 'verguenza', 'approved'),
  ('dije-adios-dos-veces', 'Me despedí de alguien y fui en la misma dirección que él', '🚶', 'Durante tres manzanas.', 'verguenza', 'approved'),
  ('olvide-nombre-recien-presentado', 'Olvidé el nombre de alguien nada más que me lo dijeron', '🙈', 'Tuve que volver a preguntar a los 30 segundos.', 'verguenza', 'approved'),
  ('me-pillo-mirando', 'Me pilló mirando fijamente a alguien en el metro', '👁️', 'Nuestras miradas se cruzaron durante 10 segundos.', 'verguenza', 'approved'),
  ('aplaudi-fin-presentacion', 'Aplaudí cuando terminó una presentación y era la diapositiva de preguntas', '👏', NULL, 'verguenza', 'approved'),
  ('me-cambie-pantalon-metro', 'Me di cuenta de que llevaba dos calcetines distintos ya en la oficina', '🧦', NULL, 'verguenza', 'approved'),
  ('olvide-apagar-micro-reunion', 'No apagué el micro en una reunión de Teams y me oyeron hablar solo', '💻', NULL, 'verguenza', 'approved'),
  ('cai-hamaca-playa', 'Me caí de la hamaca en la playa delante de todo el paseo', '🏖️', NULL, 'verguenza', 'approved'),
  ('respone-gracias-cuando-cumpleanos', 'Alguien me dijo "felicidades" y yo respondí "igualmente"', '🎉', NULL, 'verguenza', 'approved'),
  ('pregunte-cuanto-cuesta-algo-regalo', 'Pregunté el precio de un regalo que me habían hecho delante del que lo regaló', '🎁', NULL, 'verguenza', 'approved'),
  ('sone-en-clase', 'Me sonó el móvil en clase con el tono más vergonzoso posible', '📳', 'El de fábrica. A todo volumen.', 'verguenza', 'approved'),
  ('confundi-hombre-mujer', 'Llamé "señor" a una señora desde detrás', '😳', 'Se giró.', 'verguenza', 'approved'),
  ('estornude-caro', 'Estornudé en pleno silencio de una reunión importante', '🤧', 'Sonó el eco.', 'verguenza', 'approved'),
  ('me-gire-sin-motivo', 'Me giré convencido de que alguien me llamaba y no era nadie', '🫠', 'Tres veces seguidas.', 'verguenza', 'approved'),
  ('cai-intentar-entrar-coche', 'Me caí al intentar entrar en el coche de alguien que acababa de conocer', '🚗', NULL, 'verguenza', 'approved'),
  ('dije-te-quiero-amigo-colgar', 'Le dije "te quiero" a un amigo al colgar el teléfono', '❤️', 'Por inercia. Me lo dijo de vuelta.', 'verguenza', 'approved'),
  ('llame-profe-nombre', 'Llamé al profesor por su nombre de pila en clase', '🎓', 'Me miró fijamente tres segundos.', 'verguenza', 'approved'),
  ('equivoque-planta-hospital', 'Me perdí dentro del hospital y tuve que preguntar tres veces', '🏥', NULL, 'verguenza', 'approved'),
  ('no-reconoci-jefe-casual', 'No reconocí a mi jefe vestido de calle en el Lidl', '🛒', 'Le ignoré activamente.', 'verguenza', 'approved'),
  ('me-quede-colgado-ascensor', 'Me quedé en el ascensor con un desconocido en silencio 8 minutos', '🛗', NULL, 'verguenza', 'approved'),
  ('me-sente-silla-rota', 'Me senté en una silla rota en una entrevista de trabajo', '🪑', 'Se notó.', 'verguenza', 'approved'),
  ('confundi-fila-supermercado', 'Me colé sin querer en la fila del supermercado y tardé en darme cuenta', '🛒', NULL, 'verguenza', 'approved'),
  ('me-pillaron-foto-museo', 'Me pillaron haciéndome una foto en un museo donde estaba prohibido', '🏛️', NULL, 'verguenza', 'approved'),
  ('pedi-la-cuenta-sin-querer', 'Pedí la cuenta en un restaurante y era la mitad de la comida', '🍝', NULL, 'verguenza', 'approved'),
  ('conteste-correo-todos', 'Di a "responder a todos" en un correo del trabajo sin querer', '📧', 'Era un comentario privado.', 'verguenza', 'approved'),
  ('me-equivoque-idioma', 'Le hablé en inglés a alguien español', '🇬🇧', 'Sin saber por qué lo hice.', 'verguenza', 'approved'),
  ('comi-comida-ajena', 'Me comí sin querer el bocadillo de un compañero de trabajo', '🥪', 'El que tenía su nombre escrito.', 'verguenza', 'approved'),
  ('me-pillo-cantando-coche', 'Me pillaron cantando a pleno pulmón en el semáforo', '🚗', NULL, 'verguenza', 'approved'),
  ('me-salte-saludo', 'Me olvidé de saludar a alguien cuando entré en una sala y lo ignoré todo el rato', '😶', NULL, 'verguenza', 'approved'),
  ('presumi-de-algo-falso', 'Presumí de saber hacer algo que no sabía hacer y tuve que demostrarlo', '😅', NULL, 'verguenza', 'approved'),
  ('busque-movil-con-linterna-movil', 'Busqué el móvil usando el móvil como linterna', '🔦', NULL, 'verguenza', 'approved'),
  ('finde-sin-dormir', '1 finde sin dormir', '😴', 'El cuerpo aguanta. La mente no.', 'resaca', 'approved'),
  ('vomite-cabify', 'He vomitado en un Cabify', '🤢', 'Un 4,9 de valoración. Ya no.', 'resaca', 'approved'),
  ('desayune-kebab', 'He desayunado kebab', '🥙', 'A las 10 de la mañana. Estaba buenísimo.', 'resaca', 'approved'),
  ('llore-6am-amigos', 'Lloré por nada delante de mis amigos a las 6 AM', '😭', 'Ni yo supe explicarlo.', 'resaca', 'approved'),
  ('llame-ex-4am', 'Llamé a mi ex a las 4 AM para nada', '📞', 'Sonó. Colgué. Siguiente.', 'resaca', 'approved'),
  ('desperte-ciudad-ajena', 'Me desperté en una ciudad que no era la mía', '🌆', 'El tren de las 6 me lo confirmó.', 'resaca', 'approved'),
  ('pague-47-cabify', 'He pagado 47 € de Cabify a las 6 AM', '💸', 'Valió cada euro.', 'resaca', 'approved'),
  ('llave-puerta-toda-noche', 'Dejé las llaves en la puerta toda la noche', '🔑', 'Y seguían ahí por la mañana.', 'resaca', 'approved'),
  ('pasta-hidratante', 'He confundido pasta de dientes con crema hidratante', '🪥', 'A oscuras. A las 4 AM.', 'resaca', 'approved'),
  ('beber-11am', 'He empezado a beber a las 11 AM', '🍻', 'El sábado tiene esas cosas.', 'resaca', 'approved'),
  ('perdi-cartera-fiesta', 'He perdido la cartera en una fiesta y la he encontrado en el congelador', '🧊', NULL, 'resaca', 'approved'),
  ('baile-mesa-bar', 'He bailado encima de una mesa de bar', '🕺', 'Lo vi en vídeo al día siguiente.', 'resaca', 'approved'),
  ('dormi-suelo', 'He dormido en el suelo de casa de un conocido', '🛌', 'Ni sé cómo llegué ahí.', 'resaca', 'approved'),
  ('pedi-comida-durmiendo', 'He pedido comida a domicilio dormido y no lo recordaba', '🍕', 'Llegó y ya.', 'resaca', 'approved'),
  ('perdi-zapato-fiesta', 'He perdido un zapato en una fiesta y llegué a casa con uno', '👟', NULL, 'resaca', 'approved'),
  ('llame-madre-llorando', 'Llamé a mi madre llorando sin saber exactamente por qué', '📱', 'A las 5 AM. Ella cogió.', 'resaca', 'approved'),
  ('me-quede-dormido-taxi', 'Me quedé dormido en el taxi y el taxista me despertó tres paradas tarde', '🚕', NULL, 'resaca', 'approved'),
  ('me-desperte-sin-camiseta', 'Me desperté sin camiseta en casa y no recordaba haberla quitado', '👕', NULL, 'resaca', 'approved'),
  ('desayune-pizza-fria', 'He desayunado pizza fría del día anterior', '🍕', 'Y estaba mejor que la cena.', 'resaca', 'approved'),
  ('llegue-tarde-boda-resacoso', 'Llegué a una boda con resaca visible del día anterior', '💒', 'Alguien me dio una Aspirina en la puerta.', 'resaca', 'approved'),
  ('no-recorde-nada', 'No he recordado cómo llegué a casa', '🌀', 'Pero llegué.', 'resaca', 'approved'),
  ('me-quede-dormido-disco', 'Me quedé dormido en una discoteca', '🎵', 'En el sofá de la zona VIP.', 'resaca', 'approved'),
  ('mande-mensaje-equivocado-borracho', 'Mandé un mensaje borracho al contacto equivocado', '📩', NULL, 'resaca', 'approved'),
  ('beber-agua-caldo', 'He confundido agua con caldo en plena resaca', '🍶', NULL, 'resaca', 'approved'),
  ('perdi-movil-encontre-en-nevera', 'Encontré el móvil en la nevera al día siguiente de una fiesta', '📱', NULL, 'resaca', 'approved'),
  ('tostada-miel-con-tomate', 'He comido tostadas con lo primero que encontré a las 7 AM', '🍞', 'Mermelada y aceitunas. Sin remordimiento.', 'resaca', 'approved'),
  ('perdi-llaves-encontre-en-bolsillo', 'Busqué las llaves 20 minutos y estaban en el bolsillo', '🔑', 'De la chaqueta que llevaba puesta.', 'resaca', 'approved'),
  ('foto-comprometida-historia', 'He subido una foto comprometida a stories sin darme cuenta', '📸', 'Duró 6 minutos antes de que alguien me avisara.', 'resaca', 'approved'),
  ('prometi-cosas-que-no-recuerdo', 'He prometido cosas borracho que no recuerdo haber prometido', '🤝', 'Y hay testigos.', 'resaca', 'approved'),
  ('lie-en-boda', 'Me lié con alguien en la boda de un familiar', '💋', 'Alguien lo vio.', 'resaca', 'approved'),
  ('perdi-tren', 'Perdí el tren de vuelta por quedarme dormido en el bar', '🚆', NULL, 'resaca', 'approved'),
  ('confundi-dia-semana', 'Me desperté convencido de que era domingo y era lunes', '📅', 'A las 10 de la mañana.', 'resaca', 'approved'),
  ('cruce-ciudad-a-pie-resaca', 'He cruzado media ciudad a pie con resaca porque no había Cabify', '🚶', NULL, 'resaca', 'approved'),
  ('llegue-trabajo-mismo-ropa', 'Llegué al trabajo con la misma ropa del día anterior', '👔', 'Dije que era "reutilización consciente".', 'resaca', 'approved'),
  ('vomite-ascensor', 'He vomitado en el ascensor de mi propio edificio', '🛗', NULL, 'resaca', 'approved'),
  ('me-gaste-todo-en-fiesta', 'Me gasté el presupuesto del mes en una sola noche', '💳', 'No me arrepentí hasta el día 15.', 'resaca', 'approved'),
  ('recupere-el-dia-siguiente', 'He necesitado dos días para recuperarme de una noche', '🛌', 'Ya no tengo 22 años.', 'resaca', 'approved'),
  ('me-perdi-en-mi-ciudad', 'Me perdí en mi propia ciudad a las 5 AM', '🗺️', NULL, 'resaca', 'approved'),
  ('prometi-no-beber-mas', 'He prometido no volver a beber mientras vomitaba', '🚫', 'El siguiente finde quedamos.', 'resaca', 'approved'),
  ('me-bebi-el-agua-de-los-hielos', 'Me bebí el agua de los cubitos fundidos del vaso del día anterior', '🧊', NULL, 'resaca', 'approved'),
  ('baile-sin-musica', 'He bailado en una zona sin música creyendo que había música', '🎶', NULL, 'resaca', 'approved'),
  ('me-fui-sin-despedirme', 'Me fui de una fiesta sin despedirme de nadie', '🌙', 'El Irish goodbye puro.', 'resaca', 'approved'),
  ('pague-ronda-sin-querer', 'Invité a una ronda entera sin querer al darle al botón de Bizum equivocado', '🍺', NULL, 'resaca', 'approved'),
  ('llegue-sol-a-casa', 'Llegué a casa cuando ya amanecía', '🌅', 'Mejor no mirar la hora.', 'resaca', 'approved'),
  ('me-acoste-con-abrigo', 'Me acosté con el abrigo puesto sin darme cuenta', '🧥', NULL, 'resaca', 'approved'),
  ('dormi-con-lentillas', 'Dormí con las lentillas puestas y me desperté ciego', '👁️', 'Una por cada año de la condena.', 'resaca', 'approved'),
  ('me-cai-portal', 'Me caí en el portal de mi propio edificio al llegar de noche', '🏠', 'El portero lo vio.', 'resaca', 'approved'),
  ('me-sente-bordillo', 'Me he sentado en un bordillo a las 4 AM a comer un bocadillo', '🌙', 'El mejor bocadillo de mi vida.', 'resaca', 'approved'),
  ('confundi-habitaciones-hotel', 'Intenté abrir la habitación de otra persona en el hotel a las 3 AM', '🏨', 'Dos veces.', 'resaca', 'approved'),
  ('perdi-auriculares', 'He perdido los auriculares en una noche de fiesta', '🎧', 'Eran los buenos.', 'resaca', 'approved'),
  ('me-pase-de-parada', 'Me pasé de parada durmiendo en el metro y llegué al final de la línea', '🚇', NULL, 'resaca', 'approved'),
  ('fotos-vergonzosas-stories', 'He tenido que borrar cinco stories al despertar', '📱', 'Estaban subidas. Las vio gente.', 'resaca', 'approved'),
  ('dicho-cosas-que-no-recorde', 'He dicho cosas que no recordaba haber dicho', '🗣️', 'Me las recordaron con detalle.', 'resaca', 'approved'),
  ('compre-algo-online-dormido', 'Compré algo en Amazon durmiendo y no sé qué es', '📦', 'Llega el martes.', 'resaca', 'approved'),
  ('me-comi-lo-del-frigorifico', 'Me comí todo lo que había en la nevera a las 5 AM', '🌮', NULL, 'resaca', 'approved'),
  ('me-dormi-parada-bus', 'Me dormí en la parada del autobús esperando', '🚌', NULL, 'resaca', 'approved'),
  ('vomite-fuente', 'He vomitado en una fuente pública', '⛲', NULL, 'resaca', 'approved'),
  ('descubri-nuevo-amigo', 'He hecho un amigo eterno a las 3 AM que no recuerdo al día siguiente', '🤝', NULL, 'resaca', 'approved'),
  ('me-puse-mal-antes-de-empezar', 'Me puse malo antes de llegar a la fiesta', '🤢', NULL, 'resaca', 'approved'),
  ('fui-a-trabajar-sin-dormir', 'Fui a trabajar directamente desde la fiesta sin dormir', '☕', 'Con gafas de sol dentro de la oficina.', 'resaca', 'approved'),
  ('me-desperte-en-el-suelo', 'Me desperté en el suelo de mi salón con la puerta abierta', '🏠', NULL, 'resaca', 'approved'),
  ('pedi-pizza-sin-acordarme', 'Me llegó una pizza a las 10 AM que pedí sin recordarlo', '🍕', NULL, 'resaca', 'approved'),
  ('empece-fiesta-antes-de-cenar', 'Empecé a beber antes de cenar y no llegué a cenar', '🍾', NULL, 'resaca', 'approved'),
  ('perdi-a-mis-amigos', 'Perdí a todos mis amigos en una fiesta y llegué solo a casa', '🎉', 'Sin saber cómo.', 'resaca', 'approved'),
  ('fui-avion-resacoso', 'He cogido un avión con resaca', '✈️', 'El despegue fue literalmente un infierno.', 'resaca', 'approved'),
  ('cuernos-dos-veces', 'Me han puesto los cuernos +2 veces', '💔', 'El primero enseña. El segundo confirma.', 'amor', 'approved'),
  ('ex-stories-sin-like', 'Mi ex sigue viendo todos mis stories sin dar like', '👀', 'Ya en el cuarto año.', 'amor', 'approved'),
  ('declaracion-visto', 'Le declaré mi amor por WhatsApp y vi dos ticks azules', '✓✓', 'El silencio más ruidoso de mi vida.', 'amor', 'approved'),
  ('sabanas-ruptura', 'Me quedé tres días sin lavar las sábanas tras una ruptura', '😶', 'El olor era lo único que quedaba.', 'amor', 'approved'),
  ('llore-ikea', 'Lloré con un anuncio de IKEA tras romper', '🪑', 'Era de un sofá.', 'amor', 'approved'),
  ('volvi-ex', 'He vuelto con mi ex sabiendo que era una mala idea', '🔁', 'Lo sabíamos los dos.', 'amor', 'approved'),
  ('stalk-novia-nueva', 'He caído en stalk profundo del Instagram de la novia nueva de mi ex', '🕵️', NULL, 'amor', 'approved'),
  ('mensaje-borracho-no-debi', 'He mandado mensaje borracho que no debí', '🍷', NULL, 'amor', 'approved'),
  ('dejaron-ok', 'Me dejaron por mensaje y le di OK', '👍', 'La respuesta más honesta que se me ocurrió.', 'amor', 'approved'),
  ('enamorado-sin-saber', 'He estado años enamorado de alguien que ni sabía que existía', '🥀', NULL, 'amor', 'approved'),
  ('ghosting-despues-primera-cita', 'Me hicieron ghosting después de una primera cita perfecta', '👻', 'Creí que había ido bien.', 'amor', 'approved'),
  ('escribi-borre-mensaje', 'He escrito y borrado el mismo mensaje diez veces sin enviarlo', '✏️', NULL, 'amor', 'approved'),
  ('match-tinder-sin-hablar', 'He tenido un match de Tinder sin hablarle nunca', '📱', 'Caducó.', 'amor', 'approved'),
  ('vi-ex-en-mercadona', 'Me crucé con mi ex en el Mercadona sin avisar', '🛒', 'El carrito me traicionó.', 'amor', 'approved'),
  ('deje-por-texto', 'He dejado a alguien por WhatsApp', '💬', 'No fue mi mejor momento.', 'amor', 'approved'),
  ('me-dejaron-cumpleanos', 'Me dejaron el día de mi cumpleaños', '🎂', 'No han batido ese récord.', 'amor', 'approved'),
  ('mande-foto-equivocada', 'Mandé una foto íntima al grupo de amigos equivocado', '📲', NULL, 'amor', 'approved'),
  ('busque-senales', 'He buscado señales en los estados de WhatsApp de mi ex durante meses', '💭', NULL, 'amor', 'approved'),
  ('hice-like-foto-antigua', 'Le di like a una foto de 2016 stalkeando a alguien que me gusta', '📸', 'El like fantasma.', 'amor', 'approved'),
  ('ex-nueva-pareja-instagram', 'Vi que mi ex subía fotos con alguien nuevo en Instagram', '💔', 'Sin estar preparado.', 'amor', 'approved'),
  ('cita-hinge-horrorosa', 'He tenido la peor cita de mi vida', '😬', 'Llegué antes. Me fui con disculpa médica.', 'amor', 'approved'),
  ('me-enamore-de-un-amigo', 'Me enamoré de un amigo y lo arruiné todo', '😔', NULL, 'amor', 'approved'),
  ('plante-primera-cita', 'Planté a alguien en una primera cita', '🪴', 'Con excusa de última hora.', 'amor', 'approved'),
  ('me-plantaron', 'Me plantaron en una primera cita', '🌵', 'Esperé cuarenta minutos.', 'amor', 'approved'),
  ('llore-cancion-que-era-nuestra', 'Lloré con una canción que era nuestra en el coche', '🎵', 'Dos años después.', 'amor', 'approved'),
  ('texte-yo-siempre', 'Siempre he sido yo quien textea primero', '📲', 'Hice el experimento de parar. No me escribió.', 'amor', 'approved'),
  ('me-rechazaron-en-persona', 'Me rechazaron en persona delante de mis amigos', '😰', NULL, 'amor', 'approved'),
  ('guarde-conversaciones', 'He guardado conversaciones de WhatsApp con mi ex en capturas', '📁', NULL, 'amor', 'approved'),
  ('abri-cuaderno-de-penas', 'He escrito lo que sentía en un doc de Word durante una ruptura', '📝', 'Dios mío.', 'amor', 'approved'),
  ('vi-perfil-tinder-ex', 'Vi el perfil de mi ex en Tinder mientras seguíamos juntos', '😐', NULL, 'amor', 'approved'),
  ('enamore-sin-posibilidad', 'Me enamoré de alguien que vivía en otra ciudad sabiendo que era imposible', '🚄', NULL, 'amor', 'approved'),
  ('estuve-en-zona-amiga', 'Estuve en la zona de amigos de alguien durante dos años', '🪤', 'Me lo hicieron saber de forma indirecta.', 'amor', 'approved'),
  ('compre-regalos-para-nada', 'He comprado regalos para alguien que nunca llegó a ser mi pareja', '🎁', NULL, 'amor', 'approved'),
  ('cambie-planes-por-alguien', 'He cancelado planes con mis amigos para esperar un mensaje que no llegó', '📵', NULL, 'amor', 'approved'),
  ('vi-pelicula-triste-sola', 'He visto una película de amor sola llorando con helado', '🍦', 'No me avergüenzo.', 'amor', 'approved'),
  ('me-pusieron-cuernos-en-navidad', 'Me pusieron los cuernos en Navidad', '🎄', 'El regalo más inesperado.', 'amor', 'approved'),
  ('quede-con-alguien-del-trabajo', 'Quedé con alguien del trabajo y fue raro el lunes siguiente', '🗂️', NULL, 'amor', 'approved')
on conflict (slug) do nothing;
