-- =================================================================
-- Unlocked seed v2 — Part 4 of 4
-- Aplicar en Supabase Dashboard -> SQL Editor (después de Part 3)
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- =================================================================

insert into achievements (slug, title, emoji, category, status) values
  ('quede-con-alguien-que-no-debia', 'Quedé con alguien que no debía haber quedado', '📅', 'resaca', 'approved'),
  ('borre-conversacion-importante', 'Borré una conversación de WhatsApp importante sin querer a las 2 AM', '🗑️', 'resaca', 'approved'),
  ('me-comi-lo-del-dia-siguiente', 'Me comí la comida que había preparado para el día siguiente', '🍱', 'resaca', 'approved'),
  ('fui-a-misa-resacoso', 'Acompañé a mi abuela a misa con resaca', '⛪', 'resaca', 'approved'),
  ('me-hice-sangre', 'Me hice una herida que no sé de dónde viene y no recuerdo', '🩹', 'resaca', 'approved'),
  ('me-olvide-de-pagar-fiesta', 'Me fui de una fiesta de pago sin pagar la entrada', '🎟️', 'resaca', 'approved'),
  ('hable-de-mi-ex-toda-la-noche', 'Hablé de mi ex durante toda la noche a quien me quiso escuchar', '💔', 'resaca', 'approved'),
  ('me-puse-a-cantar-el-himno', 'Me puse a cantar el himno de algo sin que nadie me lo pidiera', '🎤', 'resaca', 'approved'),
  ('pedi-perdon-por-todo', 'Me puse a pedir perdón a todo el mundo por cosas antiguas', '🙏', 'resaca', 'approved'),
  ('me-sente-en-el-suelo-bar', 'Me senté directamente en el suelo del bar', '🍺', 'resaca', 'approved'),
  ('perdi-billetera-la-encontre-manana', 'Perdí la billetera y la encontré en el congelador al día siguiente', '🧊', 'resaca', 'approved'),
  ('me-puse-gafas-sol-de-noche', 'Llevé gafas de sol dentro de la discoteca toda la noche', '🕶️', 'resaca', 'approved'),
  ('me-confundi-de-piso-llegando-casa', 'Intenté abrir el piso de un vecino pensando que era el mío', '🏠', 'resaca', 'approved'),
  ('comi-pizza-de-la-basura', 'Rescaté una pizza de la cocina que ya había tirado al cubo', '🍕', 'resaca', 'approved'),
  ('me-acoste-con-maquillaje', 'Me acosté con todo el maquillaje puesto', '💄', 'resaca', 'approved'),
  ('me-puse-triste-nada', 'Me puse triste por nada a las 3 AM', '😢', 'resaca', 'approved'),
  ('me-cayo-comida-encima', 'Se me cayó la comida encima al llegar a casa', '🌮', 'resaca', 'approved'),
  ('me-dormi-hablando-con-alguien', 'Me dormí hablando por teléfono con alguien', '📞', 'resaca', 'approved'),
  ('le-preste-dinero-a-alguien-desconocido', 'Le presté dinero a alguien que no conocía de nada', '💶', 'resaca', 'approved'),
  ('mande-nota-larga-innecesaria', 'Mandé una nota de voz de 6 minutos a un conocido sin razón', '🎙️', 'resaca', 'approved'),
  ('me-saque-foto-horrible-en-espejo-bano', 'Me hice una foto en el espejo del baño y la subí a Instagram', '📸', 'resaca', 'approved'),
  ('me-arrepenti-del-tatuaje', 'Me arrepentí de un tatuaje que me hice de impulso', '🖊️', 'resaca', 'approved'),
  ('discuti-con-desconocido', 'Discutí con un desconocido sobre algo que no importaba', '💬', 'resaca', 'approved'),
  ('me-declare-sin-venir-a-cuento', 'Le dije a alguien que me gustaba sin venir a cuento', '💘', 'resaca', 'approved'),
  ('me-fui-de-la-fiesta-equivocado', 'Me fui de la fiesta pero me marché a otro bar sin pretenderlo', '🎊', 'resaca', 'approved'),
  ('me-quitaron-la-copa-de-la-mano', 'Me quitaron la copa de la mano por mi bien', '🥂', 'resaca', 'approved'),
  ('prometi-un-viaje', 'Prometí un viaje en grupo que nunca organicé', '✈️', 'resaca', 'approved'),
  ('me-confundi-de-casa', 'Fui a la casa equivocada después de una noche larga', '🏠', 'resaca', 'approved'),
  ('me-olvide-de-llevar-llaves', 'Salí de casa sin llaves y tuve que esperar dos horas', '🔑', 'resaca', 'approved'),
  ('me-moje-los-pies-lluvia', 'Llegué a casa con los pies empapados sin recordar cuándo llovió', '🌧️', 'resaca', 'approved'),
  ('desayune-lo-que-sobro-fiesta', 'Desayuné las sobras de la fiesta del día anterior', '🥧', 'resaca', 'approved'),
  ('me-cai-portal-borracho', 'Me caí en el portal de mi edificio a las 5 AM', '🏢', 'resaca', 'approved'),
  ('llame-jefe-noche', 'Llamé a mi jefe de noche por accidente', '📞', 'resaca', 'approved'),
  ('me-perdi-en-el-barrio-de-siempre', 'Me perdí en el barrio de siempre a las 3 de la mañana', '🗺️', 'resaca', 'approved'),
  ('tarde-en-recordar-mi-nombre', 'Tardé más de lo normal en recordar mi nombre completo', '🧠', 'resaca', 'approved'),
  ('bebi-agua-del-grifo-de-un-tiron', 'Me bebí un litro de agua de un grifo a las 4 AM de rodillas', '🚿', 'resaca', 'approved'),
  ('me-puse-dos-zapatos-distintos', 'Salí con dos zapatos distintos a la fiesta', '👟', 'resaca', 'approved'),
  ('no-encontre-el-bano', 'Busqué el baño de un bar durante cinco minutos', '🚽', 'resaca', 'approved'),
  ('mande-audio-muy-largo-al-despertar', 'Encontré un audio mío de 11 minutos mandado a las 2 AM', '🎙️', 'resaca', 'approved'),
  ('me-dormi-comiendo', 'Me quedé dormido con la cena a medias', '🍝', 'resaca', 'approved'),
  ('prometi-dejar-de-beber', 'Prometí dejar de beber mientras pedía otra ronda', '🍺', 'resaca', 'approved'),
  ('llegue-a-casa-con-algo-ajeno', 'Llegué a casa con un objeto que no era mío y no sé cómo', '🧢', 'resaca', 'approved'),
  ('me-puse-musica-a-tope-en-casa', 'Puse la música a tope en casa y tuvieron que llamar al timbre', '🔊', 'resaca', 'approved'),
  ('dormi-en-el-taxi-de-vuelta', 'Me dormí en el taxi y el conductor me tuvo que despertar', '🚕', 'resaca', 'approved'),
  ('me-sente-en-el-suelo-de-casa', 'Llegué a casa y me senté en el suelo del salón 20 minutos antes de moverme', '🛋️', 'resaca', 'approved'),
  ('le-pregunte-algo-absurdo-al-portero', 'Le pregunté algo absurdo al portero de mi edificio al llegar', '🏢', 'resaca', 'approved'),
  ('busque-su-nombre-en-google', 'He buscado en Google a alguien que me gustaba', '🔍', 'amor', 'approved'),
  ('quede-con-alguien-por-pena', 'He quedado con alguien por no saber decir que no', '😶', 'amor', 'approved'),
  ('le-guste-antes-de-que-me-gustara', 'Alguien me gustó justo cuando dejé de gustarle a él', '🔄', 'amor', 'approved'),
  ('me-gusto-su-ex', 'Me gustó la ex de mi ex sin buscarlo', '😅', 'amor', 'approved'),
  ('vi-a-mi-ex-con-mejor-aspecto', 'Vi a mi ex con mejor aspecto que nunca después de dejarlo', '😤', 'amor', 'approved'),
  ('fingi-no-volver-a-verle', 'Fingí que no lo había visto y crucé la calle', '🚶', 'amor', 'approved'),
  ('me-enamore-en-un-festival', 'Me enamoré de alguien en un festival que no volvería a ver', '🎪', 'amor', 'approved'),
  ('empece-a-escuchar-su-musica', 'Empecé a escuchar la música de alguien que me gustaba para hablar de ello', '🎵', 'amor', 'approved'),
  ('me-hice-el-interesante', 'Me hice el interesante con alguien que me gustaba y no coló', '😐', 'amor', 'approved'),
  ('me-rechazaron-con-clase', 'Me rechazaron de la forma más educada posible y dolió igualmente', '🌷', 'amor', 'approved'),
  ('deje-cosas-en-casa-de-mi-ex', 'Dejé cosas en casa de mi ex para tener excusa para volver', '📦', 'amor', 'approved'),
  ('fui-a-sitio-de-mi-ex', 'Fui al bar favorito de mi ex esperando cruzarme con él', '🍷', 'amor', 'approved'),
  ('me-gusto-alguien-casado', 'Me gustó alguien que tenía pareja y no lo sabía hasta que era tarde', '💍', 'amor', 'approved'),
  ('pregunte-por-el-a-sus-amigos', 'Pregunté por alguien a través de sus amigos sin parecer interesado', '🕵️', 'amor', 'approved'),
  ('me-dejaron-por-telefono-en-publico', 'Me dejaron por teléfono estando en un sitio público', '😶', 'amor', 'approved'),
  ('me-bloqueo-en-redes', 'Alguien me bloqueó en todas las redes sin explicación', '🔒', 'amor', 'approved'),
  ('tuve-relacion-de-verano', 'Tuve una relación de verano que sabía que no iba a durar', '☀️', 'amor', 'approved'),
  ('me-puse-celoso-de-nadie', 'Me puse celoso de alguien que ni salía con la otra persona', '😤', 'amor', 'approved'),
  ('no-entendi-que-era-una-cita', 'Quedé con alguien sin saber que era una cita hasta la mitad', '😳', 'amor', 'approved'),
  ('me-compararon-con-serie', 'Me compararon favorablemente con un personaje de serie', '📺', 'amor', 'approved'),
  ('fingi-no-haber-visto-su-historia', 'Fingí no haber visto la historia de Instagram de alguien que me interesaba', '📱', 'amor', 'approved'),
  ('me-gusto-alguien-de-mi-trabajo', 'Me gustó alguien del trabajo y arruiné la dinámica del equipo', '🗂️', 'amor', 'approved'),
  ('invente-excusa-para-verle', 'Inventé una excusa para quedar con alguien que me gustaba', '💭', 'amor', 'approved'),
  ('me-rechazaron-con-el-mejor-amigo', 'Me rechazaron y acabaron con mi mejor amigo', '👬', 'amor', 'approved'),
  ('sigo-con-el-numero-guardado', 'Sigo con el número de alguien guardado aunque no debería', '📱', 'amor', 'approved'),
  ('fui-a-buscar-a-alguien', 'Fui a buscar a alguien a su trabajo sin avisar', '🏢', 'amor', 'approved'),
  ('estuve-con-alguien-que-no-sentia-nada', 'Estuve con alguien sin sentir nada durante demasiado tiempo', '😶', 'amor', 'approved'),
  ('me-dieron-lastima', 'Seguí una relación por lástima más tiempo del razonable', '💔', 'amor', 'approved'),
  ('cambie-mis-planes-por-alguien', 'Reorganicé mi vida entera por alguien que no lo hizo', '🗓️', 'amor', 'approved'),
  ('lleve-de-vacaciones-a-quien-no-debia', 'Me fui de vacaciones con alguien con quien nunca debería haber ido', '✈️', 'amor', 'approved'),
  ('tuve-primera-cita-con-alguien-del-grupo', 'Quedé con alguien del grupo y lo complicó todo', '🫂', 'amor', 'approved'),
  ('me-prometi-no-volver-a-querer', 'Me prometí no volver a enamorarme y duré tres semanas', '💘', 'amor', 'approved'),
  ('no-supe-que-significaba-lo-nuestro', 'Nunca supe exactamente qué éramos el uno para el otro', '❓', 'amor', 'approved'),
  ('cambie-cancion-al-escucharla', 'He cambiado una canción sin poder terminar de escucharla', '🎵', 'amor', 'approved'),
  ('me-escribio-en-san-valentin', 'Me escribió en San Valentín sin tener nada establecido entre nosotros', '💌', 'amor', 'approved'),
  ('vi-a-mi-ex-rehacer-su-vida', 'Vi cómo mi ex rehacía su vida más rápido de lo que esperaba', '⏩', 'amor', 'approved'),
  ('pense-que-era-senal', 'Vi algo como señal del universo y resultó no serlo', '🌌', 'amor', 'approved'),
  ('mande-flores-sin-reciprocidad', 'Mandé flores y la respuesta fue un "gracias :)"', '💐', 'amor', 'approved'),
  ('me-pidio-que-fuera-su-amigo', 'Me pidió explícitamente que fuera solo su amigo', '🫂', 'amor', 'approved'),
  ('le-puse-al-dia-de-mi-vida', 'Le conté toda mi vida a alguien que llevaba un mes sin escribirme', '📝', 'amor', 'approved'),
  ('me-enamore-del-personaje-no-de-la-persona', 'Me enamoré de una idea de alguien que no era real', '💭', 'amor', 'approved'),
  ('me-mandaron-de-vuelta-a-zona-amiga', 'Me sacaron de la zona de amigos para volver a meterme', '🔄', 'amor', 'approved'),
  ('estuve-esperando-que-me-llamara', 'Estuve esperando una llamada que nunca llegó', '📞', 'amor', 'approved'),
  ('fui-a-un-evento-que-no-me-gustaba', 'Fui a un concierto que odiaba porque él iba', '🎤', 'amor', 'approved'),
  ('no-reconoci-senales-claras', 'No vi las señales más obvias del mundo hasta que fue tarde', '🚦', 'amor', 'approved'),
  ('me-puse-en-plan-intenso', 'Me puse intenso demasiado rápido y lo espanté', '💨', 'amor', 'approved'),
  ('discutimos-en-un-viaje', 'Discutimos en un viaje y tardamos en volver a hablar', '🗺️', 'amor', 'approved'),
  ('me-enamore-en-ano-bisiesto', 'Me enamoré el año en que menos lo esperaba', '💫', 'amor', 'approved'),
  ('me-gusto-alguien-de-quien-me-habia-quejado', 'Me gustó alguien de quien me había quejado con mis amigos', '😅', 'amor', 'approved'),
  ('me-dejaron-en-un-buen-momento', 'Me dejaron cuando las cosas iban bien', '😶', 'amor', 'approved'),
  ('me-mando-el-audio-equivocado', 'Me mandó un audio que era para otra persona hablando de mí', '🎙️', 'amor', 'approved'),
  ('empece-a-ver-su-serie', 'Empecé a ver la serie de mi ex para poder hablar de algo', '📺', 'amor', 'approved'),
  ('me-entere-que-le-gustaba-por-terceros', 'Me enteré de que le gustaba a alguien por sus amigos', '🗣️', 'amor', 'approved'),
  ('le-di-like-sin-querer-en-foto-antigua', 'Le di like a una foto de 2018 mientras miraba su perfil', '📷', 'amor', 'approved'),
  ('me-fui-antes-de-que-me-dejaran', 'Me fui antes de que me dejaran sabiendo lo que venía', '🚶', 'amor', 'approved'),
  ('comparti-algo-que-no-debia', 'Compartí algo íntimo demasiado pronto', '💬', 'amor', 'approved'),
  ('me-compararon-con-su-padre', 'Me compararon con su padre sin pretender que fuera un halago', '🧓', 'amor', 'approved'),
  ('me-dejo-en-visto-tres-dias', 'Me dejó en visto tres días seguidos sin explicación', '👁️', 'amor', 'approved'),
  ('me-queje-de-no-tener-pareja-con-pareja', 'Me quejé de estar solo delante de alguien que quería algo conmigo', '😬', 'amor', 'approved'),
  ('me-bloqueo-y-luego-me-desbloqueo', 'Me bloqueó, me desbloqueó y no dijo nada', '🔄', 'amor', 'approved'),
  ('me-di-cuenta-tarde', 'Me di cuenta de lo que sentía cuando ya no tenía sentido decirlo', '⌛', 'amor', 'approved'),
  ('vi-photo-antigua-juntos', 'Vi una foto nuestra de hace años sin querer buscarla', '📷', 'amor', 'approved'),
  ('tuve-celos-de-mi-propio-amigo', 'Tuve celos de mi mejor amigo por algo que no tenía sentido', '🫂', 'amor', 'approved'),
  ('me-acostumbre-a-algo-que-ya-no-existia', 'Seguí esperando algo que había dejado de existir', '⏳', 'amor', 'approved'),
  ('no-volvi-a-hablar-tras-la-ruptura', 'Nunca más volvimos a hablar tras la ruptura', '🚪', 'amor', 'approved'),
  ('me-aplaudieron-en-reunion-sin-querer', 'Me aplaudieron en una reunión que no entendí', '👏', 'trabajo', 'approved'),
  ('puse-fuera-de-oficina-sin-estarlo', 'Puse el aviso de vacaciones sin estar de vacaciones', '🏖️', 'trabajo', 'approved'),
  ('me-quede-sin-tinta-impresora', 'La impresora se quedó sin tinta justo antes de imprimir lo urgente', '🖨️', 'trabajo', 'approved'),
  ('tuve-reunion-que-se-podia-email', 'He asistido a una reunión de 90 minutos que era un email de tres líneas', '📧', 'trabajo', 'approved'),
  ('comi-solo-todos-los-dias', 'He comido solo en la mesa del trabajo todos los días de la semana', '🥪', 'trabajo', 'approved'),
  ('me-pusieron-al-mando-sin-avisar', 'Me pusieron al mando de algo sin haberme avisado', '👔', 'trabajo', 'approved'),
  ('no-lei-el-correo-con-info-clave', 'No leí el correo con la información clave antes de la reunión', '📧', 'trabajo', 'approved'),
  ('menti-sobre-conocer-herramienta', 'Dije que sabía usar una herramienta que no había visto en mi vida', '💻', 'trabajo', 'approved'),
  ('me-bloquearon-el-acceso', 'Me bloquearon el acceso sin avisarme el primer día', '🔑', 'trabajo', 'approved'),
  ('me-confundi-de-cliente', 'Llamé a un cliente por el nombre de otro', '📞', 'trabajo', 'approved'),
  ('me-pusieron-en-copia-error', 'Me añadieron a un hilo de correo que no era para mí', '📥', 'trabajo', 'approved'),
  ('tuve-jefe-mas-joven', 'Tuve un jefe más joven que yo', '👶', 'trabajo', 'approved'),
  ('perdi-un-archivo-importante', 'Perdí un archivo importante sin copia de seguridad', '💾', 'trabajo', 'approved'),
  ('me-fui-sin-cerrar-sesion', 'Me fui de la oficina sin cerrar sesión y alguien entró', '💻', 'trabajo', 'approved'),
  ('di-presentacion-a-destiempo', 'Empecé a hablar en la presentación antes de tiempo', '🎤', 'trabajo', 'approved'),
  ('me-olvide-poner-firma', 'Mandé 20 correos sin firma profesional', '📧', 'trabajo', 'approved'),
  ('pregunte-algo-ya-en-la-web', 'Pregunté por email algo que estaba en la página web de la empresa', '🌐', 'trabajo', 'approved'),
  ('me-cambie-de-equipo-voluntariamente', 'Pedí cambiarme de equipo y fue peor', '🔀', 'trabajo', 'approved'),
  ('abri-correo-de-otro', 'Abrí por error un correo de un compañero', '📬', 'trabajo', 'approved'),
  ('tuve-companero-que-no-trabajaba', 'He tenido un compañero que no hacía nada y no pasó nada', '🤷', 'trabajo', 'approved'),
  ('guarde-mal-el-proyecto', 'Guardé el proyecto encima del proyecto anterior', '💾', 'trabajo', 'approved'),
  ('llegue-tarde-excusa-ninos', 'Llegué tarde con excusa de "problema en el colegio de mi sobrino"', '🏫', 'trabajo', 'approved'),
  ('me-cole-en-reunion-equivocada', 'Me metí en una reunión de Teams equivocada', '💻', 'trabajo', 'approved'),
  ('firme-con-el-boligrafo-muerto', 'Intenté firmar con un bolígrafo sin tinta delante del cliente', '🖊️', 'trabajo', 'approved'),
  ('puse-fondo-gracioso-sin-querer', 'Se me activó un fondo de Teams ridículo en reunión con clientes', '🖥️', 'trabajo', 'approved'),
  ('me-olvide-de-actualizar-el-estado', 'Me olvidé de cambiar el estado del Slack a "ocupado" en momento clave', '🟢', 'trabajo', 'approved'),
  ('tuve-jefe-que-desaparecia', 'Tuve un jefe que no respondía correos en dos semanas', '📧', 'trabajo', 'approved'),
  ('comi-comida-de-otro-frigorifico', 'Me comí la comida de otro del frigorífico de la empresa', '🧊', 'trabajo', 'approved'),
  ('me-fui-antes-de-hora', 'Me fui 10 minutos antes sin que nadie me viera', '🏃', 'trabajo', 'approved'),
  ('me-pusieron-en-cc-por-error', 'Me pusieron en copia de un correo interno sobre mí', '📧', 'trabajo', 'approved'),
  ('tuve-videoconferencia-en-pijama', 'Tuve una videollamada importante en pijama de cintura para abajo', '👖', 'trabajo', 'approved'),
  ('me-llamo-el-cliente-directo', 'Me llamó directamente el cliente sin pasar por el proceso', '📞', 'trabajo', 'approved'),
  ('di-mi-opinion-sin-pedirla', 'Di mi opinión en una conversación sin que me la pidieran', '🗣️', 'trabajo', 'approved'),
  ('me-confundi-de-asunto', 'Mandé un correo con el asunto de otro correo anterior', '📧', 'trabajo', 'approved'),
  ('me-quede-sin-descanso', 'Trabajé cuatro horas sin parar sin darme cuenta', '⏱️', 'trabajo', 'approved'),
  ('tuve-que-pedir-perdon-al-cliente', 'Tuve que disculparme con un cliente por algo que no hice yo', '🙏', 'trabajo', 'approved'),
  ('me-equivoque-de-empresa-al-escribir', 'Escribí el nombre de una empresa competidora en un documento oficial', '📄', 'trabajo', 'approved'),
  ('tuve-evaluacion-que-no-esperaba', 'Me hicieron una evaluación de rendimiento por sorpresa', '📊', 'trabajo', 'approved'),
  ('me-llamaron-de-recursos-humanos', 'Me llamó Recursos Humanos y pensé que me echaban', '📞', 'trabajo', 'approved'),
  ('use-empresa-anterior-para-comparar', 'Hablé de mi empresa anterior como referencia en reunión', '🏢', 'trabajo', 'approved'),
  ('me-mandaron-tareas-viernes-tarde', 'Me mandaron tareas urgentes el viernes a las 6 PM', '📅', 'trabajo', 'approved'),
  ('tuve-companero-ruidoso', 'Tuve un compañero que hacía ruido al masticar todo el año', '🍽️', 'trabajo', 'approved'),
  ('llegue-a-la-empresa-sin-contrato', 'Empecé a trabajar sin haber firmado el contrato todavía', '📋', 'trabajo', 'approved'),
  ('conteste-sin-leer', 'Respondí a una petición sin leerla completa', '📧', 'trabajo', 'approved'),
  ('no-sabia-como-usar-la-cafetera', 'No supe usar la cafetera de la oficina el primer mes', '☕', 'trabajo', 'approved'),
  ('tuve-el-mismo-sueldo-tres-anos', 'Tuve el mismo sueldo tres años seguidos', '💶', 'trabajo', 'approved'),
  ('me-olvide-de-adjuntar', 'Mandé un correo diciendo "adjunto" sin adjuntar nada', '📎', 'trabajo', 'approved'),
  ('tuve-reunion-con-micro-abierto-en-bano', 'Fui al baño con el micro abierto en una conferencia', '🚽', 'trabajo', 'approved'),
  ('me-bajo-la-tension-de-pie', 'Me bajó la tensión estando de pie en una cola', '🏥', 'salud', 'approved'),
  ('me-pico-algo-en-la-nariz', 'Me picó la nariz en el momento más inoportuno', '🤧', 'salud', 'approved'),
  ('me-clave-la-una', 'Me clavé mi propia uña sin saber cómo', '🤌', 'salud', 'approved'),
  ('me-torci-pulsera', 'Me lesioné la muñeca con una pulsera demasiado apretada', '⌚', 'salud', 'approved'),
  ('me-hice-dano-abrochando-cinturon', 'Me hice daño con el cinturón de seguridad', '🚗', 'salud', 'approved'),
  ('me-lastime-jugando-con-gato', 'Me arañó mi gato sin motivo aparente', '🐱', 'salud', 'approved'),
  ('dormi-raro-semana', 'Dormí raro dos semanas seguidas sin saber por qué', '😴', 'salud', 'approved'),
  ('me-clave-aguja-costura', 'Me clavé una aguja de coser sin haber cosido nunca bien', '🧵', 'salud', 'approved'),
  ('me-atragante-con-chicle', 'Me atragante con un chicle que llevaba masticando horas', '😮', 'salud', 'approved'),
  ('me-queme-planchando-camiseta', 'Me quemé la mano planchando una camiseta de algodón fino', '🔥', 'salud', 'approved'),
  ('me-golpee-ojo-con-gafas', 'Me pegué en el ojo con la varilla de mis propias gafas', '👓', 'salud', 'approved'),
  ('me-cai-doblando-ropa', 'Me caí doblando ropa en la habitación', '👕', 'salud', 'approved'),
  ('me-hice-pupa-abriendo-lata', 'Me corté abriendo una lata', '🥫', 'salud', 'approved'),
  ('me-lastime-subiendo-escalera-dos', 'Me torcí el tobillo subiendo los escalones de dos en dos', '🦶', 'salud', 'approved'),
  ('me-raspe-con-silla-madera', 'Me clavé una astilla de la silla', '🪑', 'salud', 'approved'),
  ('me-golpee-cabeza-ducha', 'Me golpeé la cabeza en el grifo de la ducha', '🚿', 'salud', 'approved'),
  ('me-clave-la-llave-en-la-mano', 'Me clavé la llave sin querer al meter la mano en el bolsillo', '🔑', 'salud', 'approved'),
  ('me-pellizce-con-cierre', 'Me pellizcé con el cierre de la chaqueta', '🧥', 'salud', 'approved'),
  ('me-dio-dolor-espalda-estirando', 'Me dio un tirón en la espalda al estirarme', '🧘', 'salud', 'approved'),
  ('me-hice-ampolla-zapato-nuevo', 'Me hice una ampolla el primer día con zapatos nuevos', '👟', 'salud', 'approved'),
  ('me-maree-sol-fuerte', 'Me mareé con el calor estando quieto', '☀️', 'salud', 'approved'),
  ('me-irrite-el-ojo-sin-razon', 'Me irrité el ojo sin tocármelo', '👁️', 'salud', 'approved'),
  ('me-pinche-dedo-con-hoja', 'Me pinché el dedo con una hoja de papel', '📄', 'salud', 'approved'),
  ('me-cai-banera', 'Resbalé en la bañera al salir', '🛁', 'salud', 'approved'),
  ('me-queme-orejas-sol', 'Se me quemaron las orejas sin protegerlas del sol', '👂', 'salud', 'approved'),
  ('me-electrocute-enchufe', 'Me electrocuté levemente enchufando algo', '🔌', 'salud', 'approved'),
  ('me-clave-alfiler-ropa', 'Me clavé un alfiler de la ropa nueva sin quitar etiqueta', '📌', 'salud', 'approved'),
  ('me-di-con-gaveta', 'Me di con el cajón abierto al levantarme de la silla', '🗄️', 'salud', 'approved'),
  ('me-corte-lengua-sobre', 'Me corté la lengua con el sobre que pegué', '✉️', 'salud', 'approved'),
  ('dormi-aeropuerto-con-cuello', 'Dormí en el aeropuerto con almohada de cuello y no me avergoncé', '✈️', 'viajes', 'approved'),
  ('comi-solo-en-restaurante-caro', 'Comí solo en un restaurante caro sin ningún reparo', '🍽️', 'viajes', 'approved'),
  ('me-perdi-en-un-pueblo', 'Me perdí en un pueblo de 300 habitantes', '🏘️', 'viajes', 'approved'),
  ('tuve-conductor-peligroso', 'Tuve el conductor de autobús más temerario del país', '🚌', 'viajes', 'approved'),
  ('vi-algo-increible-sin-foto', 'Vi algo increíble y no saqué el móvil', '🌄', 'viajes', 'approved'),
  ('me-quede-sin-reserva-hotel', 'La reserva del hotel se canceló sin avisar', '🏨', 'viajes', 'approved'),
  ('comi-de-pie-en-la-calle', 'Comí de pie en una calle desconocida', '🥙', 'viajes', 'approved'),
  ('me-perdi-la-ultima-visita-del-dia', 'Llegué tarde a la última visita del día y la perdí', '🏛️', 'viajes', 'approved'),
  ('dormi-en-saco-suelo', 'Dormí en el suelo de una cabaña en saco de dormir', '🛌', 'viajes', 'approved'),
  ('me-equivoque-de-terminal', 'Fui al terminal equivocado del aeropuerto', '✈️', 'viajes', 'approved'),
  ('pague-propina-que-no-debia', 'Pagué propina en un país donde no se propina', '💶', 'viajes', 'approved'),
  ('no-supe-pagar-metro', 'No supe pagar el metro de una ciudad europea', '🚇', 'viajes', 'approved'),
  ('pedi-en-idioma-incorrecto', 'Pedí en el idioma incorrecto en un restaurante', '🍽️', 'viajes', 'approved'),
  ('me-queme-dos-veces', 'Me quemé dos veces en el mismo viaje de playa', '🌞', 'viajes', 'approved'),
  ('llegue-ciudad-sin-mapa', 'Llegué a una ciudad nueva sin mapa ni datos', '📵', 'viajes', 'approved'),
  ('fui-noche-a-sitio-cerrado', 'Fui a un mirador de noche y estaba cerrado por obras', '🌙', 'viajes', 'approved'),
  ('compre-recuerdo-roto', 'El souvenir se rompió antes de llegar a casa', '🗿', 'viajes', 'approved'),
  ('me-enganaron-cambio', 'Me dieron cambio de menos en moneda extranjera', '💵', 'viajes', 'approved'),
  ('me-quede-sin-bateria-foto-importante', 'Se fue el móvil justo antes de la foto más importante del viaje', '📷', 'viajes', 'approved'),
  ('dormi-con-desconocidos-en-furgoneta', 'Dormí en una furgoneta con cinco personas que no conocía', '🚐', 'viajes', 'approved'),
  ('me-perdi-ruta-senderismo', 'Me perdí en una ruta de senderismo señalizada', '🥾', 'viajes', 'approved'),
  ('llegue-aeropuerto-con-desvio', 'El taxi me llevó por el camino más largo sin mapa', '🚕', 'viajes', 'approved'),
  ('me-retuvieron-en-aduana', 'Me retuvieron en aduana por error', '🛂', 'viajes', 'approved'),
  ('olvide-voltaje-adaptador', 'Llegué con el adaptador de corriente equivocado', '🔌', 'viajes', 'approved'),
  ('me-esperaron-todos-en-el-autobus', 'Me esperó el autobús de un grupo mientras yo no aparecía', '🚌', 'viajes', 'approved'),
  ('perdi-sombrero-en-viento', 'Se me llevó el viento el sombrero frente al mar', '🎩', 'viajes', 'approved'),
  ('me-queje-del-tiempo', 'Me quejé del tiempo de un país que visité por su buen tiempo', '🌧️', 'viajes', 'approved'),
  ('me-meti-en-playa-privada', 'Entré a una playa privada sin saberlo', '🏖️', 'viajes', 'approved'),
  ('llegue-sin-dinero-local', 'Llegué al destino sin dinero local y sin cajero a la vista', '💳', 'viajes', 'approved'),
  ('me-bebi-agua-del-grifo-que-no-debia', 'Me bebí agua del grifo donde no se debía beber del grifo', '🚰', 'viajes', 'approved'),
  ('me-comi-algo-demasiado-picante', 'Pedí comida picante en un país picante de verdad', '🌶️', 'viajes', 'approved'),
  ('me-confundi-de-moneda', 'Pagué con la moneda equivocada sin querer', '💱', 'viajes', 'approved'),
  ('me-vieron-en-fotos-de-desconocidos', 'Salí en las fotos de turistas desconocidos de fondo', '📸', 'viajes', 'approved'),
  ('hice-mejor-foto-de-mi-vida', 'Hice la mejor foto de mi vida en un viaje inesperado', '🌟', 'viajes', 'approved'),
  ('llegue-sin-ropa-de-abrigo', 'Llegué a un destino frío sin ropa de abrigo', '🥶', 'viajes', 'approved'),
  ('tuve-companero-viaje-insoportable', 'Compartí trayecto con alguien que no paró de hablar', '🚌', 'viajes', 'approved'),
  ('me-encasquille-maleta', 'La maleta se me encasquilló en el aeropuerto', '🧳', 'viajes', 'approved'),
  ('llegue-con-fiebre', 'Llegué al destino con fiebre el primer día', '🤒', 'viajes', 'approved'),
  ('me-cobaron-tasa-turista', 'Me cobraron una tasa turista que no esperaba', '🏨', 'viajes', 'approved'),
  ('abri-regalo-sin-esperar', 'Abrí mi propio regalo de cumpleaños sin esperar al día', '🎁', 'random', 'approved'),
  ('deje-grifo-abierto', 'Me fui de casa con el grifo abierto', '🚰', 'random', 'approved'),
  ('me-confundi-de-fila', 'Me puse en la cola equivocada y tardé en darme cuenta', '🧍', 'random', 'approved'),
  ('gaste-en-suscripcion-olvidada', 'Descubrí que llevo un año pagando una suscripción que no uso', '💸', 'random', 'approved'),
  ('me-dormi-en-tren-de-pie', 'Me dormí de pie en el metro', '🚇', 'random', 'approved'),
  ('me-equivoque-de-boton-ascensor', 'Aprete el botón equivocado del ascensor cuatro veces seguidas', '🛗', 'random', 'approved'),
  ('perdi-paraguas-nuevo', 'Perdí un paraguas nuevo el primer día que lo usé', '☂️', 'random', 'approved'),
  ('me-confundi-de-llave', 'Intenté abrir la puerta con la llave del trabajo', '🔑', 'random', 'approved'),
  ('olvide-apagar-la-radio', 'Dejé la radio encendida dos días sin querer', '📻', 'random', 'approved'),
  ('me-olvide-de-la-compra-en-caja', 'Pagué la compra y me olvidé una bolsa en la caja', '🛒', 'random', 'approved'),
  ('compre-algo-que-ya-tenia', 'Compré un libro que ya había comprado y leído', '📚', 'random', 'approved'),
  ('me-levante-sin-despertador', 'Me desperté cinco minutos antes del despertador un lunes', '⏰', 'random', 'approved'),
  ('me-confundi-de-direccion', 'Puse la dirección al revés en el GPS y no me di cuenta', '🗺️', 'random', 'approved'),
  ('me-sente-encima-mando', 'Me senté encima del mando y cambié de canal', '📺', 'random', 'approved'),
  ('me-deje-las-gafas-en-casa', 'Llegué al optometrista sin las gafas para enseñárselas', '👓', 'random', 'approved')
on conflict (slug) do nothing;
