-- Production seed for Unlocked MVP
-- 200 curated achievements distributed across 8 categories
-- Apply via Supabase Dashboard → SQL Editor (or via supabase db push)
-- Idempotent: ON CONFLICT (slug) DO NOTHING means re-running is safe.

insert into achievements (slug, title, emoji, description, category, status) values

  -- ===== FAMILIA (25) =====
  ('mi-padre-tabaco', 'Mi padre se fue a por tabaco y no volvió', '🚬', 'Un clásico atemporal del trauma español.', 'familia', 'approved'),
  ('madre-usb', 'Mi madre me llamó para preguntarme cómo se mete una USB', '💾', 'Le puede el mundo digital.', 'familia', 'approved'),
  ('tio-fuente-boda', 'Mi tío bebió de la fuente decorativa en la boda', '⛲', 'La confundió con la barra libre.', 'familia', 'approved'),
  ('abuela-guapo', 'Mi abuela me llamó guapo en mi peor día de la vida', '👵', 'Y lo dijo en serio.', 'familia', 'approved'),
  ('primo-finde', 'Mi primo me durmió tres fines de semana seguidos en el sofá', '🛋️', 'Llegó con una bolsa. Se quedó un mes.', 'familia', 'approved'),
  ('madre-wasap', 'Mi madre me mandó un cadena de WhatsApp de 2008', '📲', 'Con el "reenvía esto a 10 personas o te pasará algo malo".', 'familia', 'approved'),
  ('hermano-novio', 'Mi hermano se lio con mi ex sin decirme nada', '😤', 'Lo supe por Instagram.', 'familia', 'approved'),
  ('padre-girar', 'Mi padre giró mal en la autopista y no lo reconoció hasta tres salidas después', '🚗', 'El GPS lo decía. Él no lo aceptaba.', 'familia', 'approved'),
  ('cunado-experto', 'Mi cuñado me explicó mi propio trabajo en la cena de Navidad', '🎄', 'Con datos que se inventó en el momento.', 'familia', 'approved'),
  ('abuelo-remoto', 'Le configuré el mando al abuelo por décima vez este año', '📺', 'Siempre el mismo mando. Siempre el mismo canal.', 'familia', 'approved'),
  ('madre-foto-mayor', 'Mi madre mandó mi foto de bebé al grupo familiar de WhatsApp', '📸', 'Sin avisar. Sin piedad.', 'familia', 'approved'),
  ('tia-pregunta', 'Mi tía me preguntó cuándo me caso en cada reunión familiar', '💍', 'Desde los 22 años. Sin excepción.', 'familia', 'approved'),
  ('hermana-ropa', 'Mi hermana cogió mi ropa sin pedir permiso y la volvió fatal', '👗', 'Y encima dice que le queda mejor a ella.', 'familia', 'approved'),
  ('padre-comunion', 'Mi padre lloró en mi comunión y nunca lo ha admitido', '😭', 'Lo vimos todos. Él dice que le entró algo en el ojo.', 'familia', 'approved'),
  ('primo-pedir', 'Mi primo me pidió dinero prestado y no me lo ha devuelto en cuatro años', '💸', 'Pero en Navidad me da las gracias por ser buena persona.', 'familia', 'approved'),
  ('madre-cena', 'Mi madre me preparó la cena a los 30 años cuando fui a visitarla', '🍽️', 'Como si nunca me hubiera ido de casa.', 'familia', 'approved'),
  ('abuelo-nombre', 'Mi abuelo me llama con el nombre de mi padre', '👴', 'Llevamos cinco años sin que corrija el error.', 'familia', 'approved'),
  ('familiar-politica', 'Sobreviví una cena familiar con debate político sin levantarme de la mesa', '🗳️', 'Un milagro de la moderación.', 'familia', 'approved'),
  ('tio-chiste', 'Mi tío contó el mismo chiste en tres bodas distintas', '🎤', 'Y cada vez se ríe más que la vez anterior.', 'familia', 'approved'),
  ('hermano-juego', 'Mi hermano me rompió un mando de PlayStation y nunca lo reconoció', '🎮', 'Me dijo que "se rompió solo".', 'familia', 'approved'),
  ('madre-llamar', 'Mi madre me llama si no la llamo yo antes de las 10 de la mañana', '📞', 'A las 10:01. Sin falta.', 'familia', 'approved'),
  ('abuela-receta', 'Mi abuela me enseñó una receta que no está escrita en ningún sitio', '📝', 'Está en su cabeza. Y en la mía ahora.', 'familia', 'approved'),
  ('padre-orgullo', 'Mi padre presumió de mí con desconocidos en el bar', '🍺', 'No me lo dijo a mí. Me lo contaron ellos.', 'familia', 'approved'),
  ('cunada-instagram', 'Mi cuñada publicó una foto mía sin filtro en Instagram', '📱', 'Con etiqueta. Sin consultar.', 'familia', 'approved'),
  ('madre-opinion', 'Mi madre me dio su opinión sobre mi ropa antes de salir de casa', '🧥', 'No se la pedí. Pero tenía razón.', 'familia', 'approved'),

  -- ===== VERGUENZA (30) =====
  ('cague-encima', 'Me cagué encima en una boda', '😬', 'No fue diarrea. Fue destino.', 'verguenza', 'approved'),
  ('saludo-desconocido', 'Saludé a un desconocido pensando que era mi amigo', '👋', 'Me abracé. Me rechazó. Seguí caminando.', 'verguenza', 'approved'),
  ('nombre-clase', 'Me llamaron por mi nombre en clase y no respondí', '🙋', 'Tres veces. La tercera ya me señalaron.', 'verguenza', 'approved'),
  ('reir-funeral', 'Me entró la risa en un funeral', '⚰️', 'No pude pararlo. Nadie me perdonó.', 'verguenza', 'approved'),
  ('caer-escaleras', 'Me caí por las escaleras del metro con gente mirando', '🚇', 'Me levanté y seguí como si nada.', 'verguenza', 'approved'),
  ('micro-abierto', 'Me quedé con el micro abierto en una reunión online', '🎙️', 'Dijeron cosas que no estaban para el grupo.', 'verguenza', 'approved'),
  ('llamar-profe-mama', 'Llamé mamá a un profesor sin querer', '🍎', 'En voz alta. Delante de la clase.', 'verguenza', 'approved'),
  ('baile-boda', 'Bailé solo en la pista vacía de una boda', '💃', 'Nadie se apuntó. Seguí igual.', 'verguenza', 'approved'),
  ('tarjeta-rechazada', 'Me rechazaron la tarjeta en el supermercado con cola', '💳', 'Cinco personas detrás. Un silencio eterno.', 'verguenza', 'approved'),
  ('mancha-camisa', 'Fui a una reunión importante con mancha en la camisa', '👔', 'La vi al salir del baño. Demasiado tarde.', 'verguenza', 'approved'),
  ('puerta-cristal', 'Me choqué contra una puerta de cristal en público', '🪟', 'Estaba limpia. Era invisible.', 'verguenza', 'approved'),
  ('chat-equivocado', 'Envié un mensaje privado al chat grupal del trabajo', '💬', 'Sobre alguien del chat grupal del trabajo.', 'verguenza', 'approved'),
  ('olvide-cumple', 'Felicité el cumpleaños a alguien un día después', '🎂', 'Lo vi en Instagram. Ya era tarde.', 'verguenza', 'approved'),
  ('pronunciar-mal', 'Pronuncié mal una palabra en inglés en una presentación', '🗣️', 'Nadie dijo nada. Todos lo notaron.', 'verguenza', 'approved'),
  ('dormido-metro', 'Me quedé dormido en el metro y pasé mi parada seis veces', '😴', 'Una anciana me despertó al final del trayecto.', 'verguenza', 'approved'),
  ('aplaudir-final', 'Aplaudí cuando no había que aplaudir en un concierto', '👏', 'Fue un silencio para el recuerdo.', 'verguenza', 'approved'),
  ('llamar-jefe-mama', 'Llamé mamá a mi jefe sin querer', '👨‍💼', 'Por teléfono. Delante de clientes.', 'verguenza', 'approved'),
  ('foto-ex', 'Me pillaron mirando el perfil de mi ex en su boda', '📱', 'Me preguntaron qué hacía. No supe qué decir.', 'verguenza', 'approved'),
  ('olvidar-nombre', 'Olvidé el nombre de alguien que conozco desde hace cinco años', '🧠', 'Me presentaron a su madre y tuve que improvisar.', 'verguenza', 'approved'),
  ('equivoque-piso', 'Me equivoqué de piso y entré a casa de un desconocido', '🚪', 'Usé la llave. Abrió. Me miró.', 'verguenza', 'approved'),
  ('risa-cine', 'Me entró la risa en el momento más dramático del cine', '🎬', 'Solo yo. Todo el cine mirándome.', 'verguenza', 'approved'),
  ('cantar-solo', 'Canté en voz alta pensando que estaba solo y no estaba solo', '🎵', 'Llevaba cuánto tiempo. Nunca lo sabré.', 'verguenza', 'approved'),
  ('caerse-foto', 'Me caí en la foto de grupo de una boda', '📷', 'La foto salió. Yo estaba en el suelo.', 'verguenza', 'approved'),
  ('olvidar-pantalon', 'Llegué al gimnasio sin pantalones de deporte', '🩳', 'Solo me di cuenta en el vestuario.', 'verguenza', 'approved'),
  ('saludo-mal', 'Me confundí al saludar y le metí un beso a alguien que quería dar la mano', '🤝', 'Él ya tenía la mano extendida. Yo ya estaba inclinado.', 'verguenza', 'approved'),
  ('responder-grupo', 'Respondí en el grupo de clase pensando que era un chat privado', '📨', 'Era una queja sobre el grupo de clase.', 'verguenza', 'approved'),
  ('camara-encendida', 'Hice algo vergonzoso sin saber que la cámara estaba encendida', '📹', 'La reunión seguía. Yo me había olvidado.', 'verguenza', 'approved'),
  ('comer-solo-restaurante', 'Me quejé de la comida en voz alta en un restaurante y el cocinero lo oyó', '🍴', 'Salió a ver quién era. Le miré a los ojos. Comí todo.', 'verguenza', 'approved'),
  ('equivoque-aseo', 'Entré al baño equivocado en una discoteca', '🚻', 'Lo noté por los zapatos. Salí muy tranquilo.', 'verguenza', 'approved'),
  ('felicitar-embarazo', 'Felicité a alguien por su embarazo y no estaba embarazada', '🤰', 'Se hizo un silencio. Seguimos sin hablar.', 'verguenza', 'approved'),

  -- ===== RESACA (25) =====
  ('finde-sin-dormir', '1 finde sin dormir', '😴', 'De jueves a domingo. Sin pegar ojo.', 'resaca', 'approved'),
  ('vomitar-cabify', 'He vomitado en un Cabify', '🚕', 'El conductor no lo vio. Yo sí recuerdo.', 'resaca', 'approved'),
  ('desayuno-kebab', 'He desayunado kebab', '🥙', 'A las 8 de la mañana. Frío de la noche anterior.', 'resaca', 'approved'),
  ('dormir-parque', 'Me quedé dormido en un banco del parque', '🌳', 'Amanecí con una paloma al lado.', 'resaca', 'approved'),
  ('perder-zapato', 'Perdí un zapato en una noche de fiesta', '👟', 'Llegué a casa cojeando. El zapato nunca apareció.', 'resaca', 'approved'),
  ('no-recordar-noche', 'No recuerdo nada de una noche completa', '🌑', 'Solo la resaca del día siguiente lo confirma.', 'resaca', 'approved'),
  ('llamar-ex-noche', 'Llamé a mi ex a las 4 de la madrugada', '📞', 'No lo recuerdo. El historial sí.', 'resaca', 'approved'),
  ('macdonalds-suelo', 'Me comí un Big Mac en el suelo de un McDonald\'s', '🍔', 'No había sillas libres. Tampoco busqué mucho.', 'resaca', 'approved'),
  ('resaca-boda', 'Llegué resacoso a una boda al día siguiente de la despedida', '💒', 'Con gafas de sol. Dentro de la iglesia.', 'resaca', 'approved'),
  ('pedir-pizza-3am', 'Pedí una pizza a las 3 de la madrugada y me la comí entera', '🍕', 'Ni la caja sobrevivió.', 'resaca', 'approved'),
  ('metro-perdido', 'Me perdí en el metro a las 6 de la mañana', '🚇', 'Sober habría tardado diez minutos. Tardé una hora.', 'resaca', 'approved'),
  ('dormir-taxi', 'Me quedé dormido en el taxi y llegué al punto de partida', '🚖', 'El taxista me despertó. Pagué dos veces el trayecto.', 'resaca', 'approved'),
  ('despertar-ciudad', 'Me desperté en una ciudad diferente sin haberlo planeado', '🌆', 'El último AVE de vuelta era por la mañana.', 'resaca', 'approved'),
  ('fiesta-trabajo', 'Llegué a trabajar sin dormir desde la noche anterior', '💼', 'Con la misma ropa. Dije que era casual friday.', 'resaca', 'approved'),
  ('compra-online-borracho', 'Hice una compra online de madrugada que no recuerdo', '🛒', 'El paquete llegó. No lo esperaba ninguno de mis dos yos.', 'resaca', 'approved'),
  ('perderse-festival', 'Me perdí del grupo en un festival y no los encontré hasta el día siguiente', '🎪', 'El teléfono muerto. La tienda sin encontrar.', 'resaca', 'approved'),
  ('agua-sal', 'Bebí agua salada pensando que era agua del grifo', '💧', 'A las 5 AM. En casa de alguien que no sé quién era.', 'resaca', 'approved'),
  ('vuelo-resaca', 'Cogí un vuelo con resaca y vomité en el avión', '✈️', 'No fue la turbulencia.', 'resaca', 'approved'),
  ('contar-secreto', 'Le conté un secreto a alguien que no debía saber ese secreto', '🤫', 'No lo recuerdo. Ellos sí.', 'resaca', 'approved'),
  ('bailar-solo-discoteca', 'Bailé solo en la pista durante veinte minutos sin darme cuenta', '🕺', 'Me lo grabaron. Lo he visto. No cambia nada.', 'resaca', 'approved'),
  ('perdido-cartera', 'Perdí la cartera una noche y la encontré en el congelador al día siguiente', '🧊', 'No hay explicación. Nunca la hubo.', 'resaca', 'approved'),
  ('comer-nevera', 'Me comí todo lo que había en la nevera al llegar a casa', '🧀', 'Alimentos sin lógica. Sin orden. Sin arrepentimiento.', 'resaca', 'approved'),
  ('subir-monumento', 'Me subí a un monumento de madrugada', '🗿', 'Era ilegal. Lo hice. Me bajé. Seguí.', 'resaca', 'approved'),
  ('promesas-resaca', 'Prometí cosas en una noche que no pude cumplir a la mañana siguiente', '🤞', 'El arrepentimiento llegó antes que el café.', 'resaca', 'approved'),
  ('cena-empresa-noche', 'Acabé la noche de la cena de empresa bailando en la barra', '🕺', 'El lunes fue un lunes muy largo.', 'resaca', 'approved'),

  -- ===== AMOR (25) =====
  ('cuernos-2', 'Me han puesto los cuernos +2 veces', '💔', 'No es mala suerte. Eres tú.', 'amor', 'approved'),
  ('ex-stories', 'Mi ex me sigue viendo los stories tres años después', '👁️', 'Sin hablar. Sin comentar. Solo mirando.', 'amor', 'approved'),
  ('whatsapp-leido', 'Le declaré mi amor por WhatsApp y vi "leído"', '✉️', 'Nunca respondió. Sigo vivo.', 'amor', 'approved'),
  ('llorar-peli-cita', 'Lloré en el cine en una primera cita', '🎭', 'Era una comedia.', 'amor', 'approved'),
  ('visto-ex-mercadona', 'Me escondí en el Mercadona para no cruzarme con mi ex', '🛒', 'Detrás de los cereales. Siete minutos.', 'amor', 'approved'),
  ('dedicar-cancion', 'Dediqué una canción en la radio sin que lo supieran', '📻', 'La oyeron. No supieron que era para ellos.', 'amor', 'approved'),
  ('foto-juntos', 'Guardé todas las fotos de una relación en una carpeta oculta', '📂', 'No las he abierto. No las he borrado.', 'amor', 'approved'),
  ('stalkear-instagram', 'Llegué al 2015 del Instagram de alguien que me gusta', '📸', 'Puse like sin querer. Retiré el like. Ellos ya lo vieron.', 'amor', 'approved'),
  ('carta-amor', 'Escribí una carta de amor que nunca envié', '💌', 'Sigue en un cajón. La escribí a mano.', 'amor', 'approved'),
  ('celos-foto', 'Me puse celoso de una foto del 2013 de mi pareja', '😒', 'Lo disimulé regular.', 'amor', 'approved'),
  ('match-ex', 'Hice match con mi ex en Tinder', '💘', 'Ninguno de los dos escribió primero.', 'amor', 'approved'),
  ('discutir-tonteria', 'Discutí con mi pareja por algo que ahora no recuerdo', '🤦', 'Fue épico en el momento.', 'amor', 'approved'),
  ('llorar-cancion', 'Lloré escuchando una canción que me recuerda a alguien', '🎶', 'En el autobús. Con auriculares. Cara mojada.', 'amor', 'approved'),
  ('hablar-amigos', 'Hablé de mi ex con sus amigos sin que me diera cuenta de quiénes eran', '😳', 'Lo noté cuando enseñaron la foto.', 'amor', 'approved'),
  ('rechazado-nota', 'Me rechazaron pasándome una nota en clase', '📝', 'Tuve que seguir en esa clase el resto del curso.', 'amor', 'approved'),
  ('noche-llorando', 'Me quedé despierto hasta las 4 AM llorando por alguien que no lo merece', '😢', 'Lo sabía entonces. Lo sigo sabiendo.', 'amor', 'approved'),
  ('cita-mal', 'Salí de una primera cita por la ventana del baño', '🚪', 'No metafóricamente. Por la ventana literal.', 'amor', 'approved'),
  ('bloquear-desbloquear', 'Bloqueé y desbloqueé a alguien cinco veces en un mismo día', '🔄', 'No fui consistente.', 'amor', 'approved'),
  ('escuchar-llanto', 'Me oyeron llorar a través de la pared del apartamento', '🧱', 'El vecino preguntó si estaba bien al día siguiente.', 'amor', 'approved'),
  ('gift-devolver', 'Devolví un regalo después de una ruptura', '🎁', 'Lo pensé mucho. Lo hice igual.', 'amor', 'approved'),
  ('ver-serie-sin-ellos', 'Vi el siguiente capítulo sin mi pareja después de prometer que esperaríamos', '📺', 'Lo negué tres días. Confesé al cuarto.', 'amor', 'approved'),
  ('olvidar-aniversario', 'Olvidé el aniversario', '📅', 'Lo recordé a las 23:58. No fue suficiente.', 'amor', 'approved'),
  ('declaracion-mal', 'Me declaré en el momento más inoportuno de la historia', '😅', 'En un ascensor. Cinco plantas. Cinco eternidades.', 'amor', 'approved'),
  ('guardar-numero', 'Guardé el número de alguien que me gustaba como "No llamar"', '📵', 'Para no llamar. Llamé.', 'amor', 'approved'),
  ('perfil-nueva-pareja', 'Revisé el perfil de la nueva pareja de mi ex durante cuarenta minutos', '🔍', 'Sin querer. Sin poder parar.', 'amor', 'approved'),

  -- ===== TRABAJO (20) =====
  ('vomitar-cena-empresa', 'Vomité en la cena de empresa', '🤮', 'Antes del postre.', 'trabajo', 'approved'),
  ('llamar-mama-jefe', 'Llamé "mamá" a mi jefe sin querer', '📞', 'En una reunión. Con gente.', 'trabajo', 'approved'),
  ('dormir-reunion', 'Me quedé dormido en una reunión de trabajo', '😪', 'Con el jefe hablando. Me despertaron de un codazo.', 'trabajo', 'approved'),
  ('enviar-queja-jefe', 'Le envié a mi jefe el correo donde me quejaba de mi jefe', '📧', 'Hay un antes y un después en mi historial laboral.', 'trabajo', 'approved'),
  ('cv-falso', 'Puse algo en el CV que no sabía hacer y luego tuve que aprenderlo en tres días', '📋', 'Lo conseguí. No lo repito.', 'trabajo', 'approved'),
  ('zoom-sin-camisa', 'Estuve en una videollamada de trabajo sin camisa por debajo de la pantalla', '👕', 'No lo saben. Ahora lo saben.', 'trabajo', 'approved'),
  ('llegar-tarde-entrevista', 'Llegué tarde a mi propia entrevista de trabajo', '🏃', 'Dije que había tráfico. En la entrevista remota.', 'trabajo', 'approved'),
  ('autoescuela', 'Suspendicé el examen teórico de la autoescuela más de dos veces', '🚗', 'La tercera fue la vencida. O la cuarta.', 'trabajo', 'approved'),
  ('googlear-trabajo', 'Busqué en Google cómo hacer mi trabajo mientras me lo explicaban', '🔍', 'Asintiendo. Con cara de que ya lo sabía.', 'trabajo', 'approved'),
  ('error-produccion', 'Mandé algo en producción sin haberlo probado y se cayó todo', '💥', 'El silencio del Slack fue ensordecedor.', 'trabajo', 'approved'),
  ('presentacion-jefe', 'Me equivoqué de diapositiva en una presentación al jefe', '📊', 'Salió la personal. Con mis vacaciones planeadas.', 'trabajo', 'approved'),
  ('nodo-impresora', 'Intenté arreglar la impresora de la oficina y la dejé peor', '🖨️', 'Nunca volvió a imprimir en color.', 'trabajo', 'approved'),
  ('silencio-reunion', 'Me preguntaron algo en una reunión y me quedé en silencio cinco segundos', '🤐', 'Luego dije "buena pregunta". No respondí.', 'trabajo', 'approved'),
  ('comer-olor-oficina', 'Calenté pescado en el microondas de la oficina', '🐟', 'Nadie me lo perdonó ese día.', 'trabajo', 'approved'),
  ('subida-sueldo-nunca', 'Esperé la subida de sueldo que me prometieron hace un año', '💰', 'La promesa sigue ahí. El sueldo no cambió.', 'trabajo', 'approved'),
  ('pasillo-jefe', 'Me escondí en el pasillo para no encontrarme con el jefe', '🚶', 'No quería tener esa conversación ese día.', 'trabajo', 'approved'),
  ('no-sabe-imprimir', 'Nadie en mi oficina sabe imprimir a doble cara de verdad', '🖨️', 'Todos hemos intentado. Todos hemos fracasado.', 'trabajo', 'approved'),
  ('llamada-mute', 'Hablé dos minutos en una llamada con el micro en mute', '🎙️', 'Todos esperaban. Yo creía que algo pasaba con ellos.', 'trabajo', 'approved'),
  ('fin-de-semana-mail', 'Mi jefe me mandó un correo el viernes a las 6 PM con "urgente"', '📨', 'No era urgente. Era costumbre.', 'trabajo', 'approved'),
  ('contrato-leer', 'Firmé un contrato sin leerlo entero', '✍️', 'Scrolleé muy rápido y di click en aceptar.', 'trabajo', 'approved'),

  -- ===== SALUD (20) =====
  ('me-cai-cabeza', 'Me caí y me rompí la cabeza', '🤕', 'Literalmente.', 'salud', 'approved'),
  ('hueso-aceituna', 'Me tragué un hueso de aceituna en una cena', '🫒', 'Seguí comiendo. No dije nada.', 'salud', 'approved'),
  ('lumbalgia-cordones', 'Me dio una lumbalgia atando los cordones', '🦴', 'Los 30 llegan sin avisar.', 'salud', 'approved'),
  ('alergia-desconocida', 'Descubrí una alergia que no sabía que tenía en el peor momento posible', '🤧', 'Primera cita. Ojos rojos. Nariz llena.', 'salud', 'approved'),
  ('urgencias-verguenza', 'Fui a urgencias por algo vergonzoso y tuve que explicarlo', '🏥', 'El médico lo escribió en el informe con lujo de detalles.', 'salud', 'approved'),
  ('calentura-trabajo', 'Fui a trabajar con fiebre porque no me atrevía a decirlo', '🌡️', 'Treinta y ocho. Lo conseguí. Me volví a casa a las tres.', 'salud', 'approved'),
  ('dormida-brazo', 'Me quedé el brazo dormido durmiendo y no podía moverlo durante un minuto', '💪', 'Pensé lo peor. Era postura.', 'salud', 'approved'),
  ('lesion-tontera', 'Me lesioné haciendo algo que no debería lesionarme', '🩹', 'Levantando una caja. Saliendo del coche. Estirando.', 'salud', 'approved'),
  ('medico-anyo', 'No fui al médico en más de un año aunque lo necesitaba', '🩺', 'El formulario de cita previa me detuvo.', 'salud', 'approved'),
  ('googlear-sintomas', 'Busqué síntomas en Google y me autodiagnostiqué algo grave', '🔍', 'Era agujetas. Google dijo otra cosa.', 'salud', 'approved'),
  ('pastilla-equivocada', 'Me tomé una pastilla que no era la mía por error', '💊', 'Era del mismo tamaño. El envase no lo era.', 'salud', 'approved'),
  ('operacion-miedo', 'Me desmayé antes de que me pusieran la anestesia de puro miedo', '😵', 'El equipo médico lo vio. Yo no lo recuerdo.', 'salud', 'approved'),
  ('correr-primero', 'Salí a correr por primera vez en años y tardé dos días en recuperarme', '🏃', 'Un kilómetro. Dos días en el sofá.', 'salud', 'approved'),
  ('dedo-puerta', 'Me pillé el dedo con la puerta y fingí que no dolía delante de gente', '🤛', 'Dolía. Mucho. Nadie lo notó. Bien.', 'salud', 'approved'),
  ('diente-palomita', 'Me rompí un diente comiendo palomitas en el cine', '🦷', 'Las palomitas de siempre. No estaba listo.', 'salud', 'approved'),
  ('resfriar-verano', 'Me resfríe en pleno agosto', '🤧', 'Con 35 grados. Bufanda incluida.', 'salud', 'approved'),
  ('tobillo-nada', 'Me torcí el tobillo caminando sobre suelo plano', '🦶', 'No había escalón. No había obstáculo. Solo yo.', 'salud', 'approved'),
  ('hipocondria-analisis', 'Me hice análisis de sangre por hipocondría y todo salió perfecto', '🩸', 'El médico sonrió. Yo no lo creí.', 'salud', 'approved'),
  ('caer-cama', 'Me caí de la cama mientras dormía de adulto', '🛏️', 'No fue sueño. Fue física.', 'salud', 'approved'),
  ('quemadura-cacharros', 'Me quemé con el microondas cuando el plato "no estaba caliente"', '🔥', 'El plato estaba caliente. Siempre está caliente.', 'salud', 'approved'),

  -- ===== VIAJES (25) =====
  ('he-visto-ballena', 'He visto una ballena', '🐳', 'En vivo y en directo.', 'viajes', 'approved'),
  ('pasaporte-sellado-mal', 'Me sellaron el pasaporte mal en una frontera', '🛂', 'Tres horas explicándoselo. Cuatro funcionarios.', 'viajes', 'approved'),
  ('perdido-aeropuerto', 'Me perdí dentro de un aeropuerto durante más de una hora', '✈️', 'El aeropuerto tenía señalización. Yo la ignoré.', 'viajes', 'approved'),
  ('maleta-otra-ciudad', 'Mi maleta llegó a otra ciudad diferente a la mía', '🧳', 'Tres días con la misma ropa. Me la enviaron al cuarto.', 'viajes', 'approved'),
  ('perder-tren', 'Perdí un tren en Francia y me quedé en una estación que no sabía ni cómo se llamaba', '🚂', 'Sin datos. Sin francés. Con hambre.', 'viajes', 'approved'),
  ('erasmus-perdido', 'Me perdí en mi primera semana de Erasmus sin hablar el idioma', '🗺️', 'Señalé cosas en el mapa que no eran el lugar correcto.', 'viajes', 'approved'),
  ('moneda-equivocada', 'Pagué con la moneda equivocada en un país sin darme cuenta', '💱', 'El cajero tardó en notarlo. Yo no lo noté nunca.', 'viajes', 'approved'),
  ('vuelo-perdido', 'Perdí un vuelo por quedarme dormido en la sala de espera', '😴', 'El anuncio sonó. Yo no.', 'viajes', 'approved'),
  ('alojamiento-horror', 'Mi alojamiento de Airbnb no existía cuando llegué', '🏠', 'La dirección era real. El apartamento no tanto.', 'viajes', 'approved'),
  ('ave-sin-billete', 'Subí al AVE sin billete por error', '🚄', 'Lo descubrí cuando vino el revisor. Seguí hasta Barcelona.', 'viajes', 'approved'),
  ('intoxicacion-viaje', 'Me intoxiqué con comida en el primer día de vacaciones', '🤢', 'El Pepto-Bismol se convirtió en mi mejor recuerdo del viaje.', 'viajes', 'approved'),
  ('foto-cartel', 'Me multaron por hacerme una foto en un sitio donde no se podía', '📸', 'El cartel lo decía en cinco idiomas. No vi ninguno.', 'viajes', 'approved'),
  ('olvidar-pasaporte', 'Me dejé el pasaporte en casa el día del vuelo', '📄', 'Llegué al aeropuerto. Volví. Milagro.', 'viajes', 'approved'),
  ('camping-lluvia', 'Me fui de camping y llovió los cinco días sin parar', '⛺', 'La previsión decía soleado. La previsión mentía.', 'viajes', 'approved'),
  ('perdido-pueblo', 'Me perdí en un pueblo de menos de 300 habitantes', '🏘️', 'Pregunté. Me miraron raro. Me fui a pie.', 'viajes', 'approved'),
  ('idioma-embarazoso', 'Dije algo embarazoso en el idioma del país sin saberlo', '🗣️', 'La gente se rio. Tardé en entender por qué.', 'viajes', 'approved'),
  ('dormir-aeropuerto', 'Dormí en el suelo de un aeropuerto', '🛫', 'Con la chaqueta de almohada. El frío era real.', 'viajes', 'approved'),
  ('feria-pueblo-perdido', 'Me quedé atrapado en la feria de un pueblo sin transporte de vuelta', '🎡', 'El último autobús a las 9. Yo a las 11. A pie.', 'viajes', 'approved'),
  ('foto-turista-clasica', 'Hice la foto de sujetar la Torre Eiffel con los dedos', '🗼', 'La tengo en el móvil. No la he borrado.', 'viajes', 'approved'),
  ('google-maps-campo', 'Google Maps me llevó por un camino de tierra en coche de alquiler', '🗺️', 'Llegamos. El coche no llegó igual que salió.', 'viajes', 'approved'),
  ('hablar-mal-idioma', 'Hablé durante diez minutos en el idioma equivocado con un extranjero', '🤷', 'Él también siguió. Nos entendimos mal en dos idiomas.', 'viajes', 'approved'),
  ('mochila-robada', 'Me robaron la mochila en el primer día de un viaje', '🎒', 'Quedaban once días. Solo tenía lo que llevaba encima.', 'viajes', 'approved'),
  ('perdido-metro-extranjero', 'Me perdí en el metro de una ciudad extranjera sin internet', '🚇', 'El papel de la línea de metro era de la línea equivocada.', 'viajes', 'approved'),
  ('compra-souvenir-inutil', 'Compré un souvenir que nunca salió de la bolsa del aeropuerto', '🎁', 'Sigue en el armario. Aún con la etiqueta.', 'viajes', 'approved'),
  ('surf-fail', 'Intenté hacer surf y no me levanté ni una sola vez en toda la clase', '🏄', 'El instructor dijo que era normal. Mentía.', 'viajes', 'approved'),

  -- ===== RANDOM (30) =====
  ('beber-11am', 'Empezar a beber a las 11 AM', '🍻', 'En domingo. En el aeropuerto.', 'random', 'approved'),
  ('escarabajo-crudo', 'Me he comido un escarabajo crudo', '🪲', 'Y no estabas en la jungla.', 'random', 'approved'),
  ('cura-tabaco', 'He visto a un cura comprar tabaco a las 7 AM', '⛪', 'Marca blanca. Sin mirarme a los ojos.', 'random', 'approved'),
  ('aprender-punto', 'Aprendí a hacer punto en una tarde de aburrimiento', '🧶', 'No lo he vuelto a hacer. Pero sé.', 'random', 'approved'),
  ('hablar-solo', 'Me pillaron hablando solo en la calle', '🗣️', 'Con gestos. Era una conversación seria.', 'random', 'approved'),
  ('llorar-anuncio', 'Lloré con un anuncio de televisión', '📺', 'Era el de la lotería de Navidad. Otra vez.', 'random', 'approved'),
  ('carrefour-medianoche', 'He ido al Carrefour a las 12 de la noche sin motivo claro', '🛒', 'Entré sin lista. Salí con cosas raras.', 'random', 'approved'),
  ('recoger-moneda', 'Recogí una moneda del suelo en público', '🪙', 'Era de un céntimo. Lo hice de todas formas.', 'random', 'approved'),
  ('hablar-animal', 'He tenido una conversación completa con un animal', '🐕', 'Argumento sólido. Respuesta razonable. Nadie nos juzgó.', 'random', 'approved'),
  ('mercadona-cola', 'Me puse en la cola equivocada del Mercadona y no me moví', '🧺', 'Era la de la farmacia. Esperé diez minutos igual.', 'random', 'approved'),
  ('google-pregunta', 'Busqué algo en Google tan extraño que me asusté de mí mismo', '🔍', 'El historial sigue ahí. No lo borro.', 'random', 'approved'),
  ('dormir-tarde-serie', 'Me quedé dormido viendo una serie y soñé que seguía viéndola', '🛋️', 'Me desperté y no supe qué era real.', 'random', 'approved'),
  ('comprar-algo-nunca-usar', 'Compré un aparato de cocina que nunca usé ni una vez', '🫕', 'Sigue en la caja. Tengo el ticket.', 'random', 'approved'),
  ('olvidar-nombre-pelicula', 'Estuve dos días intentando recordar el nombre de una película', '🎬', 'La busqué por la escena, por el actor, por el año.', 'random', 'approved'),
  ('llevar-paraguas', 'Llevé paraguas todo el día y no llovió. El día que no lo llevé, diluvió.', '☂️', 'La ley del paraguas es inmutable.', 'random', 'approved'),
  ('autobus-equivocado', 'Me monté en el autobús equivocado y lo supe en la tercera parada', '🚌', 'Seguí hasta el final. Era más barato que bajarme.', 'random', 'approved'),
  ('nombre-planta', 'Le puse nombre a una planta', '🪴', 'Tiene personalidad. Necesitaba nombre.', 'random', 'approved'),
  ('baile-cocina', 'Bailo en la cocina cuando creo que no me ve nadie', '💃', 'Alguien me ha visto. Más de una vez.', 'random', 'approved'),
  ('pelicula-mal-genero', 'Fui a ver una película de miedo pensando que era de acción', '😱', 'El título engañaba. Yo no pude salir.', 'random', 'approved'),
  ('recordar-1am', 'Me acordé de algo urgente a la 1 de la madrugada y no pude dormir', '🌙', 'No era urgente. A las 8 AM tampoco lo era.', 'random', 'approved'),
  ('app-nunca-usar', 'Me bajé una app con muy buenas intenciones y no la abrí ni una vez', '📱', 'El icono me da vergüenza. Lo tengo escondido.', 'random', 'approved'),
  ('retrasar-alarma', 'Puse la alarma cinco veces seguidas', '⏰', 'La última era para cuando ya llegaba tarde.', 'random', 'approved'),
  ('tarea-ultimo-momento', 'Hice algo importante en el último minuto literal', '⏱️', 'Lo entregué a tiempo. No volverá a pasar. O sí.', 'random', 'approved'),
  ('vecino-ascensor', 'Me encontré con mi vecino en el ascensor y no supe qué decir', '🛗', 'Tres pisos. Silencio. Los dos mirando el suelo.', 'random', 'approved'),
  ('pensar-gato', 'Pensé que mi gato me entendía y le conté mis problemas', '🐱', 'Me miró. Luego se fue. Fue lo que necesitaba.', 'random', 'approved'),
  ('feria-pueblo', 'Fui a la feria del pueblo de adulto y lo disfruté más que de niño', '🎠', 'El algodón de azúcar no ha cambiado. Yo tampoco.', 'random', 'approved'),
  ('lista-tareas', 'Hice una lista de tareas y no hice ninguna de la lista', '📋', 'La lista fue la única tarea del día.', 'random', 'approved'),
  ('apagar-luz', 'Volví a casa solo para ver si había apagado la luz', '💡', 'Estaba apagada. Tardé cuarenta minutos.', 'random', 'approved'),
  ('chatgpt-pregunta', 'Le pregunté algo a una IA que me daba vergüenza preguntar a un humano', '🤖', 'No juzgó. Respondió. Lo agradezco.', 'random', 'approved'),
  ('comunion-dinero', 'Usé el dinero de mi comunión en algo que mis padres nunca supieron', '💒', 'Lo sabían. Lo saben ahora.', 'random', 'approved')

on conflict (slug) do nothing;
