-- =================================================================
-- Unlocked seed v2 — Part 1 of 4
-- Aplicar primero en Supabase Dashboard -> SQL Editor
-- Idempotente: ON CONFLICT (slug) DO NOTHING
-- =================================================================

insert into achievements (slug, title, emoji, category, status) values
  ('mi-padre-tabaco', 'Mi padre se fue a por tabaco y no volvió', '🚬', 'familia', 'approved'),
  ('madre-usb', 'Mi madre me ha llamado para ver cómo se mete una USB', '💾', 'familia', 'approved'),
  ('cunado-cripto', 'Mi cuñado me explica criptomonedas en cada cumpleaños', '💸', 'familia', 'approved'),
  ('tio-fuente-boda', 'Mi tío bebió de la fuente decorativa de la boda', '🥂', 'familia', 'approved'),
  ('abuela-guapo', 'Mi abuela me ha llamado guapo en mi peor día', '🤍', 'familia', 'approved'),
  ('padre-llorando-serie', 'Me he pillado a mi padre llorando con una serie', '😢', 'familia', 'approved'),
  ('madre-captura-camara', 'Mi madre me ha mandado capturas de pantalla con la cámara', '📸', 'familia', 'approved'),
  ('padre-chiste-navidad', 'Mi padre cuenta el mismo chiste cada Navidad desde hace 12 años', '🎄', 'familia', 'approved'),
  ('grupo-sin-mi', 'Mi familia entera tiene grupo de WhatsApp y yo no estoy', '📱', 'familia', 'approved'),
  ('cunado-futbol', 'He sido cuñado experto en fútbol sin haber jugado nunca', '⚽', 'familia', 'approved'),
  ('abuela-stickers', 'Mi abuela manda stickers de WhatsApp sin saber qué significan', '🦋', 'familia', 'approved'),
  ('madre-facebook', 'Mi madre comenta mis fotos de Instagram en Facebook', '👩‍💻', 'familia', 'approved'),
  ('padre-whatsapp-mayusculas', 'Mi padre escribe todos los WhatsApps en mayúsculas', '📲', 'familia', 'approved'),
  ('tio-conspiraciones', 'Mi tío me explica conspiraciones en la cena de Navidad', '🎅', 'familia', 'approved'),
  ('prima-instagram', 'Mi prima me ha pedido follow en Instagram sin seguirme de vuelta', '📷', 'familia', 'approved'),
  ('abuelo-movil-nuevo', 'He configurado el móvil nuevo de mi abuelo cuatro veces', '📱', 'familia', 'approved'),
  ('madre-meme-desfasado', 'Mi madre me manda memes de 2015 como si fuesen nuevos', '😂', 'familia', 'approved'),
  ('cena-navidad-politica', 'He sobrevivido a una cena de Navidad sin hablar de política', '🍽️', 'familia', 'approved'),
  ('hermano-wifi', 'Mi hermano me llama solo cuando se cae el WiFi', '📶', 'familia', 'approved'),
  ('madre-llama-novia-exnovia', 'Mi madre sigue llamando a mi ex por su nombre a mis nuevas parejas', '🤦', 'familia', 'approved'),
  ('tia-pregunta-novio', 'Mi tía me pregunta cuándo me caso en cada reunión familiar', '💒', 'familia', 'approved'),
  ('madre-reenviar-cadena', 'Mi madre me ha reenviado una cadena de la suerte tres veces hoy', '🔗', 'familia', 'approved'),
  ('hermana-spotify-familia', 'Mi hermana cambia mi música de Spotify desde el plan familiar', '🎵', 'familia', 'approved'),
  ('primo-prestamo', 'Mi primo me pidió 50 euros prestados en 2019', '💶', 'familia', 'approved'),
  ('abuela-llamada-larga', 'He pasado 40 minutos al teléfono con mi abuela sin decir nada nuevo', '☎️', 'familia', 'approved'),
  ('padre-llama-aplicacion-programa', 'Mi padre llama aplicaciones "programas"', '💻', 'familia', 'approved'),
  ('madre-diagnostico-youtube', 'Mi madre me ha diagnosticado una enfermedad rara por YouTube', '🏥', 'familia', 'approved'),
  ('cena-empresa-cunado', 'He aguantado a mi cuñado en todas las cenas familiares del año', '🙃', 'familia', 'approved'),
  ('abuelo-huerta', 'Mi abuelo me trae verduras de la huerta cada semana', '🥬', 'familia', 'approved'),
  ('madre-preocupa-llamar', 'Mi madre se preocupa si no la llamo dos días seguidos', '😟', 'familia', 'approved'),
  ('familiar-regalo-mal', 'Me han regalado algo que pedí hace tres años', '🎁', 'familia', 'approved'),
  ('hermano-videojuegos-toda-noche', 'He estado en modo "hermano mayor responsable" toda mi adolescencia', '🎮', 'familia', 'approved'),
  ('prima-influencer', 'Mi prima se ha hecho "influencer" y me pide que le dé likes', '📸', 'familia', 'approved'),
  ('padre-cargador', 'Mi padre me coge el cargador sin preguntar desde 2017', '🔌', 'familia', 'approved'),
  ('madre-no-tira-nada', 'Mi madre guarda bolsas de plástico dentro de otras bolsas de plástico', '🛍️', 'familia', 'approved'),
  ('abuela-guisa-para-ejercito', 'Mi abuela cocina para 12 aunque vengan 3', '🍲', 'familia', 'approved'),
  ('tia-foto-familiar-mala', 'Soy el responsable de hacer la foto familiar en cada reunión', '📷', 'familia', 'approved'),
  ('hermano-llama-solo-problemas', 'Mi hermano solo me llama cuando tiene un problema', '📞', 'familia', 'approved'),
  ('padre-cine-explica-peli', 'Mi padre comenta la película mientras la vemos juntos', '🎬', 'familia', 'approved'),
  ('madre-compra-sin-lista', 'Mi madre hace la compra sin lista y vuelve con tres cosas que no necesitamos', '🧺', 'familia', 'approved'),
  ('abuela-llama-por-otro-nombre', 'Mi abuela me llama por el nombre de mi primo cuando me regaña', '😅', 'familia', 'approved'),
  ('padre-pausa-television', 'Mi padre pausa la tele para hablarme aunque sea una llamada de 2 min', '⏸️', 'familia', 'approved'),
  ('madre-cuenta-historia-larga', 'Mi madre me ha contado la misma historia de su juventud por décima vez', '👵', 'familia', 'approved'),
  ('tio-trae-invitado-sorpresa', 'Mi tío ha traído un invitado sorpresa a una cena íntima', '🚶', 'familia', 'approved'),
  ('abuelo-pastilla-diaria', 'He organizado las pastillas de mi abuelo durante una semana', '💊', 'familia', 'approved'),
  ('primo-pide-favor-finde', 'Mi primo siempre me pide favores el viernes por la noche', '🌙', 'familia', 'approved'),
  ('hermana-bano-hora', 'Mi hermana ha ocupado el baño una hora antes de una cita mía importante', '🚿', 'familia', 'approved'),
  ('madre-whatsapp-voz', 'Mi madre manda audios de WhatsApp de más de tres minutos para decir una cosa', '🎙️', 'familia', 'approved'),
  ('padre-busca-gafas', 'Mi padre me ha llamado para buscar sus gafas y las tenía puestas', '👓', 'familia', 'approved'),
  ('familiar-opinion-no-pedida', 'Un familiar me ha dado su opinión sobre mi físico en una cena', '😶', 'familia', 'approved'),
  ('abuela-llora-despedida', 'Mi abuela llora cada vez que me voy aunque viva a 40 minutos', '😭', 'familia', 'approved'),
  ('cunada-dieta', 'Mi cuñada me explica su nueva dieta en cada quedada familiar', '🥗', 'familia', 'approved'),
  ('padre-no-pide-ayuda', 'Mi padre ha arreglado algo de la casa y lo ha dejado peor', '🔧', 'familia', 'approved'),
  ('madre-regalo-de-casa', 'Mi madre me ha comprado ropa que nunca me pondría', '👕', 'familia', 'approved'),
  ('tio-regalo-efectivo', 'Mi tío siempre regala dinero en efectivo en un sobre arrugado', '💵', 'familia', 'approved'),
  ('hermano-culpa-algo', 'He echado la culpa a mi hermano de algo que hice yo de pequeño', '😇', 'familia', 'approved'),
  ('abuelo-explica-precio', 'Mi abuelo me explica el precio de todo lo que había hace 40 años', '💰', 'familia', 'approved'),
  ('madre-sabe-que-pasa', 'Mi madre sabe que algo me pasa antes de que yo lo sepa', '🔮', 'familia', 'approved'),
  ('primo-cumpleanos-tarde', 'Mi primo siempre felicita el cumpleaños al día siguiente', '🎂', 'familia', 'approved'),
  ('padre-coche-radio-maxima', 'Mi padre pone la radio al máximo en el coche y no habla', '📻', 'familia', 'approved'),
  ('abuela-sobremesa', 'He aguantado una sobremesa familiar de cuatro horas sin salida', '🍴', 'familia', 'approved'),
  ('saludo-desconocido', 'Saludé a un desconocido pensando que era amigo de la uni', '🫥', 'verguenza', 'approved'),
  ('nombre-clase', 'Me llamaron por mi nombre real en clase y no respondí', '🙃', 'verguenza', 'approved'),
  ('cague-boda', 'Me cagué encima en una boda', '😬', 'verguenza', 'approved'),
  ('nombre-limpiadora', 'Llevo 3 años en una empresa y no sé el nombre de la limpiadora', '🧹', 'verguenza', 'approved'),
  ('caca-coche', 'Pisé caca y entré en mi propio coche', '💩', 'verguenza', 'approved'),
  ('caida-mercadona', 'Me caí por las escaleras del Mercadona con el carro', '🛒', 'verguenza', 'approved'),
  ('aplaudi-solo-cine', 'Empecé a aplaudir en el cine sin que aplaudiese nadie más', '👏', 'verguenza', 'approved'),
  ('audio-largo-texto', 'Mandé un audio de 8 minutos pensando que era texto', '🎙️', 'verguenza', 'approved'),
  ('bragueta-entrevista', 'Llevé la bragueta abierta toda una entrevista', '👖', 'verguenza', 'approved'),
  ('dormido-historia-pareja', 'Me dormí mientras mi pareja me contaba una historia importante', '😴', 'verguenza', 'approved'),
  ('confundi-cumpleanos', 'Felicité el cumpleaños a alguien que no era su cumpleaños', '🎂', 'verguenza', 'approved'),
  ('llame-profe-mama', 'Llamé "mamá" a mi profesora delante de toda la clase', '👩‍🏫', 'verguenza', 'approved'),
  ('selfie-sin-querer', 'He enviado una foto accidental a un grupo de trabajo', '📱', 'verguenza', 'approved'),
  ('puerta-tirar-empujar', 'He empujado una puerta de tirar delante de mucha gente', '🚪', 'verguenza', 'approved'),
  ('responde-ok-jefe', 'Le respondí OK a mi jefe cuando me dijo que mi presentación era un desastre', '👍', 'verguenza', 'approved'),
  ('pronuncie-mal', 'He pronunciado mal una palabra en inglés delante de nativos', '🗣️', 'verguenza', 'approved'),
  ('equivoque-piso', 'He llamado al timbre del piso equivocado y esperado cinco minutos', '🔔', 'verguenza', 'approved'),
  ('cai-escalon', 'Me tropecé en un escalón que no existía en plena calle', '🚶', 'verguenza', 'approved'),
  ('conteste-siri-publico', 'Le contesté a Siri en voz alta en el metro', '🎤', 'verguenza', 'approved'),
  ('risa-funeral', 'Me dio la risa en un funeral', '😶', 'verguenza', 'approved'),
  ('mande-audio-jefe', 'Mandé un audio de WhatsApp a mi jefe que era para mi amigo', '📲', 'verguenza', 'approved'),
  ('bailando-solo-visto', 'Me han pillado bailando solo en el salón a través del portal', '💃', 'verguenza', 'approved'),
  ('llore-pelicula-avion', 'Lloré en una película del avión y el de al lado me vio', '✈️', 'verguenza', 'approved'),
  ('pregunta-embarazo', 'Le pregunté a alguien cuándo salía de cuentas y no estaba embarazada', '🤰', 'verguenza', 'approved'),
  ('quede-sin-dinero-caja', 'Me quedé sin saldo en caja del Mercadona con la gente detrás', '💳', 'verguenza', 'approved'),
  ('tire-copa-restaurante', 'Tiré una copa de vino encima del mantel de un restaurante caro', '🍷', 'verguenza', 'approved'),
  ('cante-cumpleanos-solo', 'Empecé a cantar el cumpleaños feliz solo y nadie se sumó', '🎂', 'verguenza', 'approved'),
  ('olvide-nombre-conocido', 'Se me olvidó el nombre de alguien que conozco desde hace años', '🫣', 'verguenza', 'approved'),
  ('ropa-reves-todo-el-dia', 'He llevado la camiseta del revés todo un día de trabajo', '👕', 'verguenza', 'approved'),
  ('confundi-cara-persona', 'He confundido a dos personas que no se parecen en nada', '👀', 'verguenza', 'approved'),
  ('pregunte-precio-decoracion', 'Pregunté el precio de algo en una tienda y era decorativo', '🪴', 'verguenza', 'approved'),
  ('snapchat-historia-grupo', 'Publiqué una historia pensando que era un mensaje directo', '📱', 'verguenza', 'approved'),
  ('pague-propina-sin-querer', 'Pagué propina sin querer en un sitio de autoservicio', '💸', 'verguenza', 'approved'),
  ('conteste-mal-pregunta-facil', 'Fallé una pregunta facilísima en un concurso de bar', '🎯', 'verguenza', 'approved'),
  ('hable-con-muro', 'He hablado con alguien que no me escuchaba porque llevaba auriculares', '🎧', 'verguenza', 'approved'),
  ('mande-corazon-jefe', 'Mandé un corazón a mi jefe por error', '❤️', 'verguenza', 'approved'),
  ('resbale-hielo', 'Resbalé en el hielo y traté de hacerlo parecer intencional', '🧊', 'verguenza', 'approved'),
  ('snob-restaurante', 'Pedí algo en inglés en un restaurante español pensando que era más guay', '🍽️', 'verguenza', 'approved'),
  ('me-baje-tren-equivocado', 'Me bajé en la estación equivocada del metro y esperé el siguiente en silencio', '🚇', 'verguenza', 'approved'),
  ('pense-era-conocido', 'Saludé a alguien desde lejos haciéndolo gestos durante 30 segundos', '🙋', 'verguenza', 'approved'),
  ('presente-mal-apellido', 'Me presenté con el apellido de mi ex en una reunión de trabajo', '🗂️', 'verguenza', 'approved'),
  ('foto-fea-grupo', 'Soy el que sale mal en todas las fotos de grupo', '📷', 'verguenza', 'approved'),
  ('hice-silencio-cuento-chiste', 'Conté un chiste en una cena y no se rió nadie', '😐', 'verguenza', 'approved'),
  ('pregunte-hora-tengo-movil', 'Le pregunté la hora a alguien teniendo el móvil en la mano', '⌚', 'verguenza', 'approved'),
  ('me-quede-sin-papel-bano', 'Me quedé sin papel en el baño de casa de alguien que acababa de conocer', '🧻', 'verguenza', 'approved'),
  ('sali-aseo-con-papel', 'Salí del baño de un bar con papel de váter enganchado al zapato', '🚽', 'verguenza', 'approved'),
  ('volvi-buscar-algo-olvidado', 'Volví a casa a por algo y me olvidé de lo que había vuelto a buscar', '🔑', 'verguenza', 'approved'),
  ('cambie-sitio-mal', 'Me cambié de asiento en el tren y era el asiento de otro', '🪑', 'verguenza', 'approved'),
  ('no-reconoci-nuevo-corte', 'No reconocí a mi amigo con el pelo corto y lo ignoré en la calle', '💇', 'verguenza', 'approved'),
  ('me-mordi-lengua-comiendo', 'Me mordí la lengua comiendo delante de una primera cita', '😬', 'verguenza', 'approved'),
  ('dije-adios-dos-veces', 'Me despedí de alguien y fui en la misma dirección que él', '🚶', 'verguenza', 'approved'),
  ('olvide-nombre-recien-presentado', 'Olvidé el nombre de alguien nada más que me lo dijeron', '🙈', 'verguenza', 'approved'),
  ('me-pillo-mirando', 'Me pilló mirando fijamente a alguien en el metro', '👁️', 'verguenza', 'approved'),
  ('aplaudi-fin-presentacion', 'Aplaudí cuando terminó una presentación y era la diapositiva de preguntas', '👏', 'verguenza', 'approved'),
  ('me-cambie-pantalon-metro', 'Me di cuenta de que llevaba dos calcetines distintos ya en la oficina', '🧦', 'verguenza', 'approved'),
  ('olvide-apagar-micro-reunion', 'No apagué el micro en una reunión de Teams y me oyeron hablar solo', '💻', 'verguenza', 'approved'),
  ('cai-hamaca-playa', 'Me caí de la hamaca en la playa delante de todo el paseo', '🏖️', 'verguenza', 'approved'),
  ('respone-gracias-cuando-cumpleanos', 'Alguien me dijo "felicidades" y yo respondí "igualmente"', '🎉', 'verguenza', 'approved'),
  ('pregunte-cuanto-cuesta-algo-regalo', 'Pregunté el precio de un regalo que me habían hecho delante del que lo regaló', '🎁', 'verguenza', 'approved'),
  ('sone-en-clase', 'Me sonó el móvil en clase con el tono más vergonzoso posible', '📳', 'verguenza', 'approved'),
  ('confundi-hombre-mujer', 'Llamé "señor" a una señora desde detrás', '😳', 'verguenza', 'approved'),
  ('estornude-caro', 'Estornudé en pleno silencio de una reunión importante', '🤧', 'verguenza', 'approved'),
  ('me-gire-sin-motivo', 'Me giré convencido de que alguien me llamaba y no era nadie', '🫠', 'verguenza', 'approved'),
  ('cai-intentar-entrar-coche', 'Me caí al intentar entrar en el coche de alguien que acababa de conocer', '🚗', 'verguenza', 'approved'),
  ('dije-te-quiero-amigo-colgar', 'Le dije "te quiero" a un amigo al colgar el teléfono', '❤️', 'verguenza', 'approved'),
  ('llame-profe-nombre', 'Llamé al profesor por su nombre de pila en clase', '🎓', 'verguenza', 'approved'),
  ('equivoque-planta-hospital', 'Me perdí dentro del hospital y tuve que preguntar tres veces', '🏥', 'verguenza', 'approved'),
  ('no-reconoci-jefe-casual', 'No reconocí a mi jefe vestido de calle en el Lidl', '🛒', 'verguenza', 'approved'),
  ('me-quede-colgado-ascensor', 'Me quedé en el ascensor con un desconocido en silencio 8 minutos', '🛗', 'verguenza', 'approved'),
  ('me-sente-silla-rota', 'Me senté en una silla rota en una entrevista de trabajo', '🪑', 'verguenza', 'approved'),
  ('confundi-fila-supermercado', 'Me colé sin querer en la fila del supermercado y tardé en darme cuenta', '🛒', 'verguenza', 'approved'),
  ('me-pillaron-foto-museo', 'Me pillaron haciéndome una foto en un museo donde estaba prohibido', '🏛️', 'verguenza', 'approved'),
  ('pedi-la-cuenta-sin-querer', 'Pedí la cuenta en un restaurante y era la mitad de la comida', '🍝', 'verguenza', 'approved'),
  ('conteste-correo-todos', 'Di a "responder a todos" en un correo del trabajo sin querer', '📧', 'verguenza', 'approved'),
  ('me-equivoque-idioma', 'Le hablé en inglés a alguien español', '🇬🇧', 'verguenza', 'approved'),
  ('comi-comida-ajena', 'Me comí sin querer el bocadillo de un compañero de trabajo', '🥪', 'verguenza', 'approved'),
  ('me-pillo-cantando-coche', 'Me pillaron cantando a pleno pulmón en el semáforo', '🚗', 'verguenza', 'approved'),
  ('me-salte-saludo', 'Me olvidé de saludar a alguien cuando entré en una sala y lo ignoré todo el rato', '😶', 'verguenza', 'approved'),
  ('presumi-de-algo-falso', 'Presumí de saber hacer algo que no sabía hacer y tuve que demostrarlo', '😅', 'verguenza', 'approved'),
  ('busque-movil-con-linterna-movil', 'Busqué el móvil usando el móvil como linterna', '🔦', 'verguenza', 'approved'),
  ('finde-sin-dormir', '1 finde sin dormir', '😴', 'resaca', 'approved'),
  ('vomite-cabify', 'He vomitado en un Cabify', '🤢', 'resaca', 'approved'),
  ('desayune-kebab', 'He desayunado kebab', '🥙', 'resaca', 'approved'),
  ('llore-6am-amigos', 'Lloré por nada delante de mis amigos a las 6 AM', '😭', 'resaca', 'approved'),
  ('llame-ex-4am', 'Llamé a mi ex a las 4 AM para nada', '📞', 'resaca', 'approved'),
  ('desperte-ciudad-ajena', 'Me desperté en una ciudad que no era la mía', '🌆', 'resaca', 'approved'),
  ('pague-47-cabify', 'He pagado 47 € de Cabify a las 6 AM', '💸', 'resaca', 'approved'),
  ('llave-puerta-toda-noche', 'Dejé las llaves en la puerta toda la noche', '🔑', 'resaca', 'approved'),
  ('pasta-hidratante', 'He confundido pasta de dientes con crema hidratante', '🪥', 'resaca', 'approved'),
  ('beber-11am', 'He empezado a beber a las 11 AM', '🍻', 'resaca', 'approved'),
  ('perdi-cartera-fiesta', 'He perdido la cartera en una fiesta y la he encontrado en el congelador', '🧊', 'resaca', 'approved'),
  ('baile-mesa-bar', 'He bailado encima de una mesa de bar', '🕺', 'resaca', 'approved'),
  ('dormi-suelo', 'He dormido en el suelo de casa de un conocido', '🛌', 'resaca', 'approved'),
  ('pedi-comida-durmiendo', 'He pedido comida a domicilio dormido y no lo recordaba', '🍕', 'resaca', 'approved'),
  ('perdi-zapato-fiesta', 'He perdido un zapato en una fiesta y llegué a casa con uno', '👟', 'resaca', 'approved'),
  ('llame-madre-llorando', 'Llamé a mi madre llorando sin saber exactamente por qué', '📱', 'resaca', 'approved'),
  ('me-quede-dormido-taxi', 'Me quedé dormido en el taxi y el taxista me despertó tres paradas tarde', '🚕', 'resaca', 'approved'),
  ('me-desperte-sin-camiseta', 'Me desperté sin camiseta en casa y no recordaba haberla quitado', '👕', 'resaca', 'approved'),
  ('desayune-pizza-fria', 'He desayunado pizza fría del día anterior', '🍕', 'resaca', 'approved'),
  ('llegue-tarde-boda-resacoso', 'Llegué a una boda con resaca visible del día anterior', '💒', 'resaca', 'approved'),
  ('no-recorde-nada', 'No he recordado cómo llegué a casa', '🌀', 'resaca', 'approved'),
  ('me-quede-dormido-disco', 'Me quedé dormido en una discoteca', '🎵', 'resaca', 'approved'),
  ('mande-mensaje-equivocado-borracho', 'Mandé un mensaje borracho al contacto equivocado', '📩', 'resaca', 'approved'),
  ('beber-agua-caldo', 'He confundido agua con caldo en plena resaca', '🍶', 'resaca', 'approved'),
  ('perdi-movil-encontre-en-nevera', 'Encontré el móvil en la nevera al día siguiente de una fiesta', '📱', 'resaca', 'approved'),
  ('tostada-miel-con-tomate', 'He comido tostadas con lo primero que encontré a las 7 AM', '🍞', 'resaca', 'approved'),
  ('perdi-llaves-encontre-en-bolsillo', 'Busqué las llaves 20 minutos y estaban en el bolsillo', '🔑', 'resaca', 'approved'),
  ('foto-comprometida-historia', 'He subido una foto comprometida a stories sin darme cuenta', '📸', 'resaca', 'approved'),
  ('prometi-cosas-que-no-recuerdo', 'He prometido cosas borracho que no recuerdo haber prometido', '🤝', 'resaca', 'approved'),
  ('lie-en-boda', 'Me lié con alguien en la boda de un familiar', '💋', 'resaca', 'approved'),
  ('perdi-tren', 'Perdí el tren de vuelta por quedarme dormido en el bar', '🚆', 'resaca', 'approved'),
  ('confundi-dia-semana', 'Me desperté convencido de que era domingo y era lunes', '📅', 'resaca', 'approved'),
  ('cruce-ciudad-a-pie-resaca', 'He cruzado media ciudad a pie con resaca porque no había Cabify', '🚶', 'resaca', 'approved'),
  ('llegue-trabajo-mismo-ropa', 'Llegué al trabajo con la misma ropa del día anterior', '👔', 'resaca', 'approved'),
  ('vomite-ascensor', 'He vomitado en el ascensor de mi propio edificio', '🛗', 'resaca', 'approved'),
  ('me-gaste-todo-en-fiesta', 'Me gasté el presupuesto del mes en una sola noche', '💳', 'resaca', 'approved'),
  ('recupere-el-dia-siguiente', 'He necesitado dos días para recuperarme de una noche', '🛌', 'resaca', 'approved'),
  ('me-perdi-en-mi-ciudad', 'Me perdí en mi propia ciudad a las 5 AM', '🗺️', 'resaca', 'approved'),
  ('prometi-no-beber-mas', 'He prometido no volver a beber mientras vomitaba', '🚫', 'resaca', 'approved'),
  ('me-bebi-el-agua-de-los-hielos', 'Me bebí el agua de los cubitos fundidos del vaso del día anterior', '🧊', 'resaca', 'approved'),
  ('baile-sin-musica', 'He bailado en una zona sin música creyendo que había música', '🎶', 'resaca', 'approved'),
  ('me-fui-sin-despedirme', 'Me fui de una fiesta sin despedirme de nadie', '🌙', 'resaca', 'approved'),
  ('pague-ronda-sin-querer', 'Invité a una ronda entera sin querer al darle al botón de Bizum equivocado', '🍺', 'resaca', 'approved'),
  ('llegue-sol-a-casa', 'Llegué a casa cuando ya amanecía', '🌅', 'resaca', 'approved'),
  ('me-acoste-con-abrigo', 'Me acosté con el abrigo puesto sin darme cuenta', '🧥', 'resaca', 'approved'),
  ('dormi-con-lentillas', 'Dormí con las lentillas puestas y me desperté ciego', '👁️', 'resaca', 'approved'),
  ('me-cai-portal', 'Me caí en el portal de mi propio edificio al llegar de noche', '🏠', 'resaca', 'approved'),
  ('me-sente-bordillo', 'Me he sentado en un bordillo a las 4 AM a comer un bocadillo', '🌙', 'resaca', 'approved'),
  ('confundi-habitaciones-hotel', 'Intenté abrir la habitación de otra persona en el hotel a las 3 AM', '🏨', 'resaca', 'approved'),
  ('perdi-auriculares', 'He perdido los auriculares en una noche de fiesta', '🎧', 'resaca', 'approved'),
  ('me-pase-de-parada', 'Me pasé de parada durmiendo en el metro y llegué al final de la línea', '🚇', 'resaca', 'approved'),
  ('fotos-vergonzosas-stories', 'He tenido que borrar cinco stories al despertar', '📱', 'resaca', 'approved'),
  ('dicho-cosas-que-no-recorde', 'He dicho cosas que no recordaba haber dicho', '🗣️', 'resaca', 'approved'),
  ('compre-algo-online-dormido', 'Compré algo en Amazon durmiendo y no sé qué es', '📦', 'resaca', 'approved'),
  ('me-comi-lo-del-frigorifico', 'Me comí todo lo que había en la nevera a las 5 AM', '🌮', 'resaca', 'approved'),
  ('me-dormi-parada-bus', 'Me dormí en la parada del autobús esperando', '🚌', 'resaca', 'approved'),
  ('vomite-fuente', 'He vomitado en una fuente pública', '⛲', 'resaca', 'approved'),
  ('descubri-nuevo-amigo', 'He hecho un amigo eterno a las 3 AM que no recuerdo al día siguiente', '🤝', 'resaca', 'approved'),
  ('me-puse-mal-antes-de-empezar', 'Me puse malo antes de llegar a la fiesta', '🤢', 'resaca', 'approved'),
  ('fui-a-trabajar-sin-dormir', 'Fui a trabajar directamente desde la fiesta sin dormir', '☕', 'resaca', 'approved'),
  ('me-desperte-en-el-suelo', 'Me desperté en el suelo de mi salón con la puerta abierta', '🏠', 'resaca', 'approved'),
  ('pedi-pizza-sin-acordarme', 'Me llegó una pizza a las 10 AM que pedí sin recordarlo', '🍕', 'resaca', 'approved'),
  ('empece-fiesta-antes-de-cenar', 'Empecé a beber antes de cenar y no llegué a cenar', '🍾', 'resaca', 'approved'),
  ('perdi-a-mis-amigos', 'Perdí a todos mis amigos en una fiesta y llegué solo a casa', '🎉', 'resaca', 'approved'),
  ('fui-avion-resacoso', 'He cogido un avión con resaca', '✈️', 'resaca', 'approved'),
  ('cuernos-dos-veces', 'Me han puesto los cuernos +2 veces', '💔', 'amor', 'approved'),
  ('ex-stories-sin-like', 'Mi ex sigue viendo todos mis stories sin dar like', '👀', 'amor', 'approved'),
  ('declaracion-visto', 'Le declaré mi amor por WhatsApp y vi dos ticks azules', '✓✓', 'amor', 'approved'),
  ('sabanas-ruptura', 'Me quedé tres días sin lavar las sábanas tras una ruptura', '😶', 'amor', 'approved'),
  ('llore-ikea', 'Lloré con un anuncio de IKEA tras romper', '🪑', 'amor', 'approved'),
  ('volvi-ex', 'He vuelto con mi ex sabiendo que era una mala idea', '🔁', 'amor', 'approved'),
  ('stalk-novia-nueva', 'He caído en stalk profundo del Instagram de la novia nueva de mi ex', '🕵️', 'amor', 'approved'),
  ('mensaje-borracho-no-debi', 'He mandado mensaje borracho que no debí', '🍷', 'amor', 'approved'),
  ('dejaron-ok', 'Me dejaron por mensaje y le di OK', '👍', 'amor', 'approved'),
  ('enamorado-sin-saber', 'He estado años enamorado de alguien que ni sabía que existía', '🥀', 'amor', 'approved'),
  ('ghosting-despues-primera-cita', 'Me hicieron ghosting después de una primera cita perfecta', '👻', 'amor', 'approved'),
  ('escribi-borre-mensaje', 'He escrito y borrado el mismo mensaje diez veces sin enviarlo', '✏️', 'amor', 'approved'),
  ('match-tinder-sin-hablar', 'He tenido un match de Tinder sin hablarle nunca', '📱', 'amor', 'approved'),
  ('vi-ex-en-mercadona', 'Me crucé con mi ex en el Mercadona sin avisar', '🛒', 'amor', 'approved'),
  ('deje-por-texto', 'He dejado a alguien por WhatsApp', '💬', 'amor', 'approved'),
  ('me-dejaron-cumpleanos', 'Me dejaron el día de mi cumpleaños', '🎂', 'amor', 'approved'),
  ('mande-foto-equivocada', 'Mandé una foto íntima al grupo de amigos equivocado', '📲', 'amor', 'approved'),
  ('busque-senales', 'He buscado señales en los estados de WhatsApp de mi ex durante meses', '💭', 'amor', 'approved'),
  ('hice-like-foto-antigua', 'Le di like a una foto de 2016 stalkeando a alguien que me gusta', '📸', 'amor', 'approved'),
  ('ex-nueva-pareja-instagram', 'Vi que mi ex subía fotos con alguien nuevo en Instagram', '💔', 'amor', 'approved'),
  ('cita-hinge-horrorosa', 'He tenido la peor cita de mi vida', '😬', 'amor', 'approved'),
  ('me-enamore-de-un-amigo', 'Me enamoré de un amigo y lo arruiné todo', '😔', 'amor', 'approved'),
  ('plante-primera-cita', 'Planté a alguien en una primera cita', '🪴', 'amor', 'approved'),
  ('me-plantaron', 'Me plantaron en una primera cita', '🌵', 'amor', 'approved'),
  ('llore-cancion-que-era-nuestra', 'Lloré con una canción que era nuestra en el coche', '🎵', 'amor', 'approved'),
  ('texte-yo-siempre', 'Siempre he sido yo quien textea primero', '📲', 'amor', 'approved'),
  ('me-rechazaron-en-persona', 'Me rechazaron en persona delante de mis amigos', '😰', 'amor', 'approved'),
  ('guarde-conversaciones', 'He guardado conversaciones de WhatsApp con mi ex en capturas', '📁', 'amor', 'approved'),
  ('abri-cuaderno-de-penas', 'He escrito lo que sentía en un doc de Word durante una ruptura', '📝', 'amor', 'approved'),
  ('vi-perfil-tinder-ex', 'Vi el perfil de mi ex en Tinder mientras seguíamos juntos', '😐', 'amor', 'approved'),
  ('enamore-sin-posibilidad', 'Me enamoré de alguien que vivía en otra ciudad sabiendo que era imposible', '🚄', 'amor', 'approved'),
  ('estuve-en-zona-amiga', 'Estuve en la zona de amigos de alguien durante dos años', '🪤', 'amor', 'approved'),
  ('compre-regalos-para-nada', 'He comprado regalos para alguien que nunca llegó a ser mi pareja', '🎁', 'amor', 'approved'),
  ('cambie-planes-por-alguien', 'He cancelado planes con mis amigos para esperar un mensaje que no llegó', '📵', 'amor', 'approved'),
  ('vi-pelicula-triste-sola', 'He visto una película de amor sola llorando con helado', '🍦', 'amor', 'approved'),
  ('me-pusieron-cuernos-en-navidad', 'Me pusieron los cuernos en Navidad', '🎄', 'amor', 'approved'),
  ('quede-con-alguien-del-trabajo', 'Quedé con alguien del trabajo y fue raro el lunes siguiente', '🗂️', 'amor', 'approved')
on conflict (slug) do nothing;
